### ISSUE TITLE
`container_restart()` causes full rebuild on containerd

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt#1781]
Right now `live_update`s with a `container_restart` result in full image builds on clusters that use containerd.

We should figure out a way to support `container_restart` functionality on containerd, perhaps using a wrapper script that wraps the original entrypoint.

This problem can be reproduced on microk8s 1.14.

**Comment by maiamcc** [comment]
Update: we've got [a wrapper script](https://github.com/windmilleng/rerun-process-wrapper#rerunning-your-process-via-live_update) for working around this issue.

**Comment by nicks** [comment]
This is obsolete. We now handle container restart with the docker_build_with_restart extension
