### ISSUE TITLE
UI doesn't reflect multiple pods per resource

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt#2081]
Right now the Tilt UI only shows only pod ID per workload. This is confusing if you have a replica set. From Alton4 in #tilt:

> I’m testing out a handrolled statefulset and I’m more specifically trying to use tilt to validate behavior when my statefulset is deployed in HA mode, so having a way to see individual pod logs would be a great way to see how my app behaves when one of them goes down, for example

We should make sure that Tilt shows the logs for all the pods in a replica set and make sure that the UI indicates that we found all pods.

**Comment by maiamcc** [comment]
This issue is specifically about UI handling, so changing the title to reflect that.

Closing #3283 as a duplicate because this issue has more user interaction.

**Comment by maiamcc** [comment]
Not strictly related, but #2814 is thematically related, figured I'd link it here.

**Comment by nicks** [comment]
This might be easier to support now that PodLogStream is a separate API object - https://blog.tilt.dev/2021/05/24/real-programmers-log.html

@milas do you remember how you handled this with the KubernetesDiscovery API? Now that we keep track of all the pods, it's probably easier to support this than to NOT support it, and we probably have a bunch of code filtering logs that we don't need

**Comment by nicks** [comment]
wait, we do support this now! maybe we added support for this by accident when we switched to the new API

this can be closed. i'm going to file a separate issue for the UI handling to make sure there's a way to differentiate the different pods.

**Comment by milas** [comment]
> do you remember how you handled this with the KubernetesDiscovery API?

This actually didn't change: both pre + post API actually support multiple pods. It DOES prune out some*, but multiple pods can be tracked. In general, most places in code use `K8sRuntimeState::MostRecentPod()` to select a single one out of the map, but the others are there so can be used for metadata etc.

\* This actually happens in store, so you can still see them in the API in some cases (e.g. a `Succeeded` Pod that's not the "primary" Pod but still for the most recent deployment will be visible in API but not store)
