### ISSUE TITLE
Get logs from init containers

### ISSUE THREAD

**Issue by maiamcc** [tilt-dev/tilt#2292]
From @MattHodge:
> Would be great to be able to see the logs from the init containers

(This could potentially generate a lot of annoying noise -- would want to make it configurable in Tiltfile, or couple it with ability to turn logs on/off for specific containers.)

**Comment by dbentley** [comment]
This seems important in the case where you do need it.

Yeah, it's nice to be able to turn it off, but if that makes it take more effort to implement and thus it's harder for us to prioritize, I'd rather just turn it on always and see if people complain/want a way to turn it off.

If it's half a day to just add it always, I'd vote to just do it.

**Comment by victorwuky** [comment]
@andymartin-sch @MightySCollins @avdhoot @theothertomelliot @virta-jasonmay @bkcsfi : Init container logs are now in the newest release of Tilt. See https://github.com/tilt-dev/tilt/releases/tag/v0.14.2

**Comment by victorwuky** [comment]
@theothertomelliott : Init container logs are now in the newest release of Tilt. See https://github.com/tilt-dev/tilt/releases/tag/v0.14.2

cc @nicks
