### ISSUE TITLE
Allow Wildcard For allow_k8s_contexts Function

### ISSUE THREAD

**Issue by MattHodge** [tilt-dev/tilt#2357]
Hi There,

It would be great if we could pass a wildcard to the `allow_k8s_contexts` function, for example:

`allow_k8s_contexts("devenv-*")`

We create development namespaces on a shared development cluster, eg `devenv-nameA`, `devenv-nameB`, and it would be useful to have Tilt allow access to all `devenv-*` contexts without having to change it each time.

We could also use a `local` function if this bug was fixed: https://github.com/windmilleng/tilt/issues/2269, but allowing a wildcard could be a good  compromise of flexibility vs safety.

**Comment by maiamcc** [comment]
@dbentley unless I'm missing something, your solution won't work b/c of #2269, as Matt notes above.

**Comment by nicks** [comment]
we now have documentation that suggests:

```
allow_k8s_contexts(k8s_context())
```

https://docs.tilt.dev/api.html#api.allow_k8s_contexts
