### ISSUE TITLE
default_registry path building too opinionated for ECR

### ISSUE THREAD

**Issue by eaceaser** [tilt-dev/tilt#2419]
The path rewriting rule for `default_registry` path building:

> Prepend the value of registry and a /.

Has some issues with ECR, namely because ECR doesn't support arbitrary path nesting in repository names (unless you pre-create the repositories)

The current behavior only works if an ECR repository exists with the same name as the docker image ref, and if you pass the base ECR url to `default_registry` (e.g. `<account-id>.dkr.ecr.us-east-1.amazonaws.com`) 

One possible solution would be to allow for the docker image ref to be prepended to the image tag vs. appended to the image repo path. Not sure if this is the best solution though.

**Comment by maiamcc** [comment]
Thanks for the report @eaceaser, I didn't realize ECR had those restrictions. Is this currently blocking you, or do you have a workaround?

The first solution that comes to mind is an optional arg `transform_fn` to default registry, such that if the default prepending behavior doesn't work for you, you can define a custom func that takes the `original_image_name` and `registry` and decides how to stitch them together. Thoughts on that?

**Comment by eaceaser** [comment]
I can work around it for now -- the main issue is when using a ECR repo shared across projects for development.

I think taking a transform probably works. Even tho the image tags are fingerprinted and unique, it probably would be nice to have the ability to transform the tag as well to make it clearer what docker images correspond to which projects.

**Comment by nicks** [comment]
We were talking to a team today about this. I like the idea of building the image name into the tag.

Maybe something like:

default_registry(single_bucket="XXX")

to emphasize that it's a property of the registry
