### ISSUE TITLE
Organization Tools for Port Forwards

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt#2548]
Some resources will have many different port forwards:

* One for a HTTP endpoint
* One for a GRPC endpoint
* One for an admin server
* Another for a GraphQL explorer tool

With all of these port forwards listed sequentially in the resource information ribbon, it gets hard to know which port forward is for which thing.

There should be some sort of optional organization mechanism for port forwards. At the minimum you should be able to name them, but we also might want to be able to specify which port forwards speak HTTP and are thus clickable in the UI.

This was inspired by a discussion with @dotellie in the #tilt channel.

**Comment by nicks** [comment]
one thing i do really miss from the preview pane was "here's the map of all your services that have port-forwards" that was in ALL > Preview

**Comment by nicks** [comment]
I'm going to mark this as fixed, now that we have the links= argument for k8s_resource
