### ISSUE TITLE
Support --secret flag in `docker_build`

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt#2563]
The `--secret` flag is a flag that's [available to docker build in new versions of docker](https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information).

We should enable users to pass this flag in to `docker_build`, perhaps throw an error if we detect that the version of docker is too old?

[Originally discussed in #tilt](https://kubernetes.slack.com/archives/CESBL84MV/p1573737030263300)

**Comment by soulshake** [comment]
I believe this issue can be closed; [`docker_build` accepts a `secret` keyword argument now](https://docs.tilt.dev/api.html#api.docker_build) thanks to the linked PR above.

**Comment by nicks** [comment]
Thanks @soulshake !
