### ISSUE TITLE
feature request: load web assets from offline

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#2608]
Currently, Tilt loads its web assets from a publicly readable google cloud storage bucket at
https://storage.googleapis.com/tilt-static-assets/

This is much easier for us to manage operationally. But it means that if you're offline, or have a firewall that's blocking this site for some reason, the Tilt web UI will fail to load.

One or two people in the #tilt channel have asked how hard it would be to make this work offline. I'm not totally sure, and haven't spent much time looking into using something like Packr to do this

**Comment by nicks** [comment]
(Current workaround is to only use Tilt when offline, and unblock the above bucket in your firewall)

**Comment by victorwuky** [comment]
A workaround is installing and running Tilt from source, and setting `web-mode=local` to serve local assets from your local system. See https://github.com/windmilleng/tilt/blob/master/CONTRIBUTING.md#web-ui

**Comment by szucsitg** [comment]
We'd love this as well

**Comment by victorwuky** [comment]
@szucsitg feel free to upvote (👍 ) the issue. We use to track interest.

**Comment by CorentinWanteeed** [comment]
Hello ✋,

I am also interested about this feature. :)

**Comment by Tchoupinax** [comment]
Hello ✋,

I am also interested about this feature. :)

**Comment by nicks** [comment]
I think the Go team is working on a much more holistic solution to this problem https://github.com/golang/go/issues/35950, so I'm eagerly watching what happens there

**Comment by samkon** [comment]
It can be all about DNS configuration you're using as I use google dns. Reset your DNS configurations and try it again.
