### ISSUE TITLE
Feature: .env File Support

### ISSUE THREAD

**Issue by david-martyn-ford** [tilt-dev/tilt#2643]
It'd be great to use this pattern for setting application specific environment variables with the project. I have used it previously with docker-compose and NodeJS.

https://docs.docker.com/compose/env-file/
https://github.com/motdotla/dotenv#readme

**Comment by nicks** [comment]
Fwiw, I'm surprised this doesn't work out of the box, since it's supposed to be built in to docker compose?

**Comment by david-martyn-ford** [comment]
I'd imagine it would work if I was to use docker-compose, but I'm actually talking about using a `.env` file to populate values within the `Tiltfile`.

**.env**
```
AWS_ACCESS_KEY_ID=Test
AWS_SECRET_ACCESS_KEY=Test
```

**Titlefile**
```
docker_build('service1', './cmd/service1')

yaml = helm(
  './deployment/helm-charts/service',
  name='name',
  namespace='namespace',
  values=['./deployment/helm-charts/service/values.yaml'],
  set=[
    'service1.image=service1',

    'aws.accessKey=' + os.environ['AWS_ACCESS_KEY_ID'],
    'aws.secretKey=' + os.environ['AWS_SECRET_ACCESS_KEY'],
  ],
)

k8s_yaml(yaml)
```

**Comment by nicks** [comment]
ah! ok, that makes sense.

you can do this now with `local()`, with something like:

```
aws_access_key_id = str(local('source .env && echo $AWS_ACCESS_KEY_ID')).strip()
```

though we're working on better primitives for this. does that work?

**Comment by landism** [comment]
We've also been suggesting [`read_json()`](https://docs.tilt.dev/api.html#api.read_json) for this, e.g.

```
cfg = read_json('config.json')
yaml = helm(
  './deployment/helm-charts/service',
  name='name',
  namespace='namespace',
  values=['./deployment/helm-charts/service/values.yaml'],
  set=[
    'service1.image=service1',

    'aws.accessKey=' + cfg['AWS_ACCESS_KEY_ID'],
    'aws.secretKey=' + cfg['AWS_SECRET_ACCESS_KEY'],
  ],
)
```

**Comment by c0bra** [comment]
Tighter integration with .env files would be great

**Comment by afgarcia86** [comment]
I can't for the life of me figure out how to pass env vars into a `custom_build` :(

**Comment by nicksieger** [comment]
If there was a primitive like `read_env_file('.env')` that could read the env file and return a dictionary, would that help? Then you could apply the env file to the current process by doing `os.environ.update(read_env_file('.env'))`. The dictionary could be useful for passing to other functions too, for example to `docker_build(..., build_args=read_env_file('.env'))`.

**Comment by nicksieger** [comment]
See also [the dotenv tilt-extension](/tilt-dev/tilt-extensions/tree/master/dotenv).

**Comment by lizzthabet** [comment]
i think we can close this issue since the [dotenv](https://github.com/tilt-dev/tilt-extensions/tree/master/dotenv) tilt extension that @nicksieger mentioned provides this functionality.

**Comment by scalp42** [comment]
@nicksieger any chance to be able to load multiple env files so we can override (same as dotenv pretty much) values?

**Comment by nicksieger** [comment]
@scalp42 can you call `dotenv` from the dotenv extension multiple times with different filenames?

**Comment by IrfanAli17899** [comment]
Can dotenv return key value pairs of loaded envs?

My usecase is i have to pass env vars to helm and i don't want to write each var seperately, just simply pass dict and will automatically be parsed to yml.
