### ISSUE TITLE
Fatal Authorization Error: Tilt Watches Pods and Services In Wrong Namespace

### ISSUE THREAD

**Issue by armsnyder** [tilt-dev/tilt#2846]
We use a shared k8s cluster on our team for development, and we've found that users are getting `403 Forbidden` errors in Tilt after running `tilt up`.

>FATAL ERROR
Tilt has encountered a fatal error: Error watching pods. Are you connected to kubernetes? : WatchPods: makeInformer: unknown, Reason: Forbidden, Code: 403
Once you fix this issue you'll need to restart Tilt. In the meantime feel free to browse through the UI.

Our API audit logs show that Tilt is making k8s API requests to services and pods at the cluster-level and at the `default` namespace-level. Developers do not have access to these resources; their access is limited to certain namespaces only.

This is a problem for any cluster with users who have permissions to a restricted set of namespaces, like in clusters managed by Rancher2, for example.

Our Tiltfiles do not include any cluster-level or `default` namespace pods or services, so it is not clear why Tilt is making these requests nor why they should cause a fatal error for users.

**Repro steps:**
1. Create a namespace "foo" in k8s
1. Create a user in k8s
1. Give the user permissions to all verbs and all resources in the "foo" namespace
1. Create a KUBECONFIG file with the user's login credentials
1. Create a minimal Tiltfile which creates a k8s resource
   ```python
   k8s_yaml(blob('''
   apiVersion: v1
   kind: ServiceAccount
   metadata:
     name: foo
     namespace: foo
   '''))
   ```
1. Run `tilt up`
1. See an error in the console
   >FATAL ERROR
Tilt has encountered a fatal error: Error watching pods. Are you connected to kubernetes? : WatchPods: makeInformer: unknown, Reason: Forbidden, Code: 403
Once you fix this issue you'll need to restart Tilt. In the meantime feel free to browse through the UI.

Here are the API audit logs from Tilt:

```json
{
    "requestURI": "/api/v1/pods?labelSelector=app.kubernetes.io%2Fmanaged-by%3Dtilt&watch=true",
    "verb": "watch",
    "userAgent": "tilt/v0.0.0 (darwin/amd64) kubernetes/$Format",
    "objectRef": {
        "resource": "pods",
        "apiVersion": "v1"
    },
    "responseStatus": {
        "metadata": {},
        "status": "Failure",
        "reason": "Forbidden",
        "code": 403
    },
    "requestReceivedTimestamp": "2020-01-25T06:01:14.612754Z"
}
{
    "requestURI": "/api/v1/services?labelSelector=app.kubernetes.io%2Fmanaged-by%3Dtilt&watch=true",
    "verb": "watch",
    "userAgent": "tilt/v0.0.0 (darwin/amd64) kubernetes/$Format",
    "objectRef": {
        "resource": "services",
        "apiVersion": "v1"
    },
    "responseStatus": {
        "metadata": {},
        "status": "Failure",
        "reason": "Forbidden",
        "code": 403
    }
}
{
    "requestURI": "/api/v1/namespaces/default/services?labelSelector=app.kubernetes.io%2Fmanaged-by%3Dtilt&watch=true",
    "verb": "watch",
    "userAgent": "tilt/v0.0.0 (darwin/amd64) kubernetes/$Format",
    "objectRef": {
        "resource": "services",
        "namespace": "default",
        "apiVersion": "v1"
    },
    "responseStatus": {
        "metadata": {},
        "status": "Failure",
        "reason": "Forbidden",
        "code": 403
    }
}
{
    "requestURI": "/api/v1/namespaces/default/pods?labelSelector=app.kubernetes.io%2Fmanaged-by%3Dtilt&watch=true",
    "verb": "watch",
    "userAgent": "tilt/v0.0.0 (darwin/amd64) kubernetes/$Format",
    "objectRef": {
        "resource": "pods",
        "namespace": "default",
        "apiVersion": "v1"
    },
    "responseStatus": {
        "metadata": {},
        "status": "Failure",
        "reason": "Forbidden",
        "code": 403
    }
}
```

**Affects version**: `v0.11.1, built 2020-01-17`

**Known workaround**: Have the user change their k8s context to a namespace which they *do* have permission in, for example using `kubens`, before running `tilt up`. This stops the fatal error, but there may be unknown side-effects.

**Comment by armsnyder** [comment]
@nicks It looks like these calls originate from the `ServiceWatcher` and `PodWatcher` in the `k8swatch` package: https://github.com/windmilleng/tilt/tree/master/internal/engine/k8swatch

Do you think it's possible to change the watch calls to be scoped to only the namespaces of resources being managed by Tilt, or are the watches being set up before the namespaces are knowable?

**Comment by nicks** [comment]
Ya, let me jot down the background on this:
- Tilt tries to set up the watches as soon as it starts (before the Tiltfile gets executed)
- First, it tries to watch all resources with the managed-by: Tilt label applied.
- If it gets an access denied error, it checks to see if you have a default namespace in your kubeconfig. Then, it tries to restrict its watch to just that namespace instead.

It's an imperfect heuristic. Most users we see are either using a local cluster (where they have full access) or using a personal namespace in a shared cluster (where the default namespace in their kubeconfig is a good hint that this is what their personal namespace is). So this heuristic works pretty well in both places.

I think your idea of only watching namespaces that you're deploying resources to is a great one! +1 that we should do that.

But it's a pretty big change to the order of operations. Historically, changing the order of when things happen tends to have unforeseen side-effects. It might be easy or it might get tricky. Let me poke around at it and get back to you,

In the meantime, does the workaround of setting the namespace in the kubeconfig work for your team?

**Comment by armsnyder** [comment]
Thanks for the explanation! That helps to understand how it's meant to work, and in that case setting the namespace before running `tilt up` works for us.

I added this to our Tiltfile so that if the error occurs, it will succeed on a retry of `tilt up`, where "foo" is the shared dev namespace for the project:

```python
local('kubectl config set-context --current --namespace foo')
```

This issue arrises usually when there's a new team member who has never used kubectl. They download their kubeconfig, install kubectl and tilt, and want to be able to `tilt up` without additional setup.
