### ISSUE TITLE
custom_build doesn't seem to work with base images

### ISSUE THREAD

**Issue by gaetansnl** [tilt-dev/tilt#2856]
If I build multiple images based on a base image using custom_build, Obviously tilt does not understand that some images are based on other. It causes a lot of issues, and I can't build.

Use case: I'm trying to use buildctl to do in cluster builds.

**Comment by dbentley** [comment]
What does a Tiltfile look like for each?

It sounds like you want each `custom_build` to wait for its base image. Do you also need each `custom_build` to be able to get the fully qualified image that's already built?

Yes, I don't think we've thought of this, and probably should.

What happens if you don't tell Tilt about each image, but instead have each `custom_build` build the base image as well as the final image? Would that be slower? Incorrect?

**Comment by gaetansnl** [comment]
I need to build the base image then the other images, because the base image take 15 minutes to build on my 8 cores cpu (it does an npm install among other things). 

I currently use docker_build and it works fine (expect the issue I opened just before), I created functions like this
```
build_deps_image('temp-registry.dc1.*****/BASE', 'k8s/image/dev/deps.Dockerfile')
build_package('@*****.', 'temp-registry.dc1.*****', 'k8s/image/dev/server.Dockerfile')
build_package('@*****', 'temp-registry.dc1.*****', 'k8s/image/dev/*****.Dockerfile')
build_package('@*****', 'temp-registry.dc1.*****', 'k8s/image/dev/*****.Dockerfile')
build_package('@*****', 'temp-registry.dc1.*****', 'k8s/image/dev/******.Dockerfile')
build_package('@*****', 'temp-registry.dc1.*****', 'k8s/image/dev/*******.Dockerfile')

```
They end to call `docker_build`. Every image starts with `FROM temp-registry.dc1.*****/BASE`

But `docker_build` build images using docker and I would like to use buildctl to try to optimise my build. buildctl is way better than docker but also completely different API. So I tried to make it work with `custom_build`. But, as you saw, it can't currently support my base image. I tried to build in parallel without the base image, but it's too long and it uses too much space.

**Comment by dbentley** [comment]
Yes; I see.

I think we need a better story for dependencies between images. We're unlikely to get that in the next week, so I think my advice of a dummy resource with dependencies might help here, as well.

I'm happy to help implement that in the Tiltfile if you want to find some time to pair.

**Comment by gaetansnl** [comment]
I never used go, but I quickly looked at the source. I think dependencies between images is only one part of the problem. 
- Because with `custom_build`, tilt does not know about the dockerfiles... so it can't traverse the ast to replace the images...
- Even if tilt is aware of the dockerfile, tools like buildctl support more than the dockerfile syntax.

I think an idea can be to create a command like `custom_image_build` which takes same arguments as `custom_build`, plus a dockerfile path (and in the future a 'type' to support other formats). The command parse the dockerfile, analyze it and transform it, create a temporary file to use in the command like `$FILE`.

I just noticed that there is indeed no code to create the images DAG. But it was working for me because before last versions, the build was sequential and not parallel... 

If I have some time in the next weeks I'll try to look at it, but I think there is a non-negligible amount of works :/

**Comment by landism** [comment]
> But it was working for me because before last versions, the build was sequential and not parallel...

This is all a problem worth solving, but in the meantime, you can disable parallel builds with `update_settings(max_parallel_updates=1)` in your Tiltfile.

**Comment by maiamcc** [comment]
[I ran into something similar](https://cloud.tilt.dev/snapshot/Ab6TluwLkyKQOCfmfTw=) on a dummy project just now. Given Tiltfile:
```k8s_yaml('k8s.yaml')

custom_build(
  'parent',
  'docker build -f Dockerfile.parent -t $EXPECTED_REF .',
  ['.'],
)

custom_build(
  'child',
  'docker build -f Dockerfile.child -t $EXPECTED_REF .',
  ['.'],
)
```

Tilt doesn't build `parent` because "Image not used in any deploy config", and then when it attempts to build `child`, I get the error:
> Step 1/3 : FROM parent
> pull access denied for parent, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

If anyone's curious, [here's the repro case](https://gist.github.com/maiamcc/5708d39c7cfa63abb1a2d73d06be0315).

**Comment by computerquip-work** [comment]
I'm hit by this as well. Currently, I'm using buildah with some custom scripts. There's no way to describe to tilt that it needs to build my base image before the children images, so it just never does. To work around this, I'm rebuilding the base image every time which kinda sucks.
