### ISSUE TITLE
Tilt assumes local cluster if the cluster name is 'minikube'

### ISSUE THREAD

**Issue by queil** [tilt-dev/tilt#2895]
Hi, I am using tilt with a remote minikube and facing the following issue:

```
Tilt: v0.11.3, built 2020-01-24
System: linux-amd64
---
Docker
- Host: Error: ProvideDockerEnv: Could not read docker env from minikube: exec: "minikube": executable file not found in $PATH
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.17.0
---
```
Workaround: change cluster name to something else.

**Comment by maiamcc** [comment]
Oh huh, no, we didn't anticipate remote minikube when we built this system 😅 thanks for the report. I'm going to put this in our backlog for now, as it's a relatively uncommon case (thus far, anyway) and you have a workaround--but let me know if our minikube-is-local assumptions cause you any more trouble!

**Comment by queil** [comment]
@maiamcc thanks!
