### ISSUE TITLE
distinguish build logs from pod logs

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#2947]
In K8s slack, Pierre asks:

> Did you already consider to have a separate tab for "Build" (Build Log), a tab for "Run" (Pod Log) and maybe a tab "All" instead of a global one for each microservice ? Sometimes we just want to see "Run" or "Build" 

This is something we've heard a few times. The common bits of feedback we've heard in the past:

1) A pod is extremely chatty, which makes it impossible to make sense of the build logs
2) A build that takes a long time, so it's hard to track pending status

I could imagine different UI affordances for each use case (e.g., we notice that the build logs are getting broken up, and offer a quick-press-button to pin them to the bottom of the pane, or collapse them together)

**Comment by elemental-lf** [comment]
It would be really helpful to be able to differentiate pod and build logs and view them separately. The current situation where they are mixed together on a line-by-line basis is a little confusing at times and it is hard to find some information.

Apart from different tabs for build and pod logs I could also imagine a horizontal ruler to separate different steps from one another. This would structure the output and would make it easier to capture it visually. In addition, what about some kind of UI element to jump from one ruler to the next?

And for pod logs it would be helpful to prefix them with their pod name and color them. [stern](https://github.com/wercker/stern) is a good example for this. Apart from being able to distinguish the output of different pods the pod name is also useful to know if manual inspection of the pod via `kubectl` is required.

**Comment by rpocase** [comment]
I'm not sure if this is in scope of this issue, but it would be nice to be able to filter by container on a pod as well. E.g., most of my pods now end up with the primary application, tilt synclet, and other injected sidecar logs. Being able to select a primary application would be extremely helpful.

**Comment by nicks** [comment]
Just to update the issue - there's currently a lot of UX thinking / experimentation ongoing with this. 

I think it's genuinely a difficult UX problem -- the easy way out just adds more tabs to click through to find the error, and feels like going backwards to "now you have 5 terminal windows again". It solves the problem if you know what you're looking for, but makes it a lot harder to navigate when you don't know what you're looking for.

My current thinking is that Tilt needs some sort of Causality view, where clicking on a log takes you into a view where you can scroll up to see what came before it (causality-wise, like previous comments in a comment thread) and what came after it (causality-wise, like replies), with some lightweight UX to visualize direct vs indirect connections. Opentelemetry's notion of Spans / SpanLinks has a lot of good parallels here

I'm also thinking about ways to better focus in on and/or filter logs from different pods/containers, though I'm not sure how well that dovetails with the other problem

**Comment by sssilver** [comment]
Alternative approach -- maybe allow defining named filter regexes in Tiltfile per-service, to toggle these filters in the UI? Some services are verbose and when you're working on a particular feature a grep with a regex can be super helpful.

**Comment by zaro** [comment]
> I think it's genuinely a difficult UX problem -- the easy way out just adds more tabs to click through to find the error, and feels like going backwards to "now you have 5 terminal windows again". It solves the problem if you know what you're looking for, but makes it a lot harder to navigate when you don't know what you're looking for.

@nicks  isn't this more of a two separate problems actually ? One how to present meaningful logs, and then how to navigate these logs. The logs come from different places, some selection to see specific log only is going to be very useful.

I found about tilt, 3-4 days ago, I and I really love the concept. But combining all logs in a single window makes them extremely hard to navigate

**Comment by alanchrt** [comment]
This is one of our biggest pain points! My initial comment on Slack that led to seeing this issue:

> Some of our services output some pretty chatty logs, so these get printed in the tilt UI. However, whenever one of those services does a full rebuild, all the build logs get completely buried within the logs of the already-deployed pod, since it hasn't been terminated yet. Have you considered separating where build logs and pod logs stream in the UI? is there a workaround for this? i find myself completely killing tilt and doing tilt up again just to get clean log output... almost every time there's a rebuild.

Killing off tilt and restarting just so a single service can rebuild has been a big pain. I'd also be happy if there was even just a workaround way to view only build logs, even by cli.
