### ISSUE TITLE
Tilt tries to inject synclet into custom resource and fails

### ISSUE THREAD

**Issue by elemental-lf** [tilt-dev/tilt#2948]
I have a custom resource which contains a `Job` and a `CronJob` template. To update the image references inside of these templates I specified them in the `Tiltfile`:

```python
k8s_kind('OperatorConfig',
         image_json_path=[
             '{.spec.jobTemplate.spec.template.spec.containers[0].image}',
             '{.spec.cronJobTemplate.spec.jobTemplate.spec.template.spec.containers[0].image}'
         ])
```
This leads to the following error message:
```
Build Failed: Could not inject synclet: {0xc0008b2848}
```
This is with Tilt version `0.12.1` running with `--update-mode` `auto` which seems to result in an actual update mode of `synclet` as I'm using an external Kubernetes development cluster . If I set the `--update-mode` to `exec` the error doesn't occur but I also lose synclet functionality (like container restarts) for all other Kubernetes resources.

I think in a first step trying to inject synclet containers should be disabled (or unsuccessful injection should not be fatal) for custom resources even when the update mode is `synclet`. This would at least preserve the synclet feature for all other resources.

In a second step maybe another parameter (`pod_json_path`) could be added to `k8s_kind()` which allows to specify a list of JSON paths to pod specifications inside the custom resource which should have a synclet injected.

As one use case of custom resources is the implementation of alternative or additional workload controllers I think going the second step would be worthwhile. I've seen custom resources of other projects which also include pod specifications or templates.

**Comment by nicks** [comment]
Nice find! 

This might be hard to handle well. Currently synclet mode is all-or-nothing. Ya, I think you're diagnosis is exactly right:
step 1) allow tilt to fallback to exec-based updates if we can't inject a synclet
step 2) have some sort of pod_template_json_path for this use-case

How badly is this blocking you? For now, if you remove live_update from these images, Tilt shouldn't try to inject the synclet

**Comment by elemental-lf** [comment]
Thank you for asking. It's not really blocking and after all I'm not a paying customer here, so it's your call to prioritize things. The work-around you suggested is working.

**Comment by nicks** [comment]
I guess another option might be to make the synclet injector check if there are images adjacent to the container :thinking:

**Comment by elemental-lf** [comment]
Isn't the injector using reflection to find pod reference objects? This will always fail with CRs I think as they can't reference built-in complex types and are always build from the base types. For CRs the JSON path solution seems like the way to go as only the CRs user knows where a pod like structure can be found. 
As a reverse conclusion I think the synclet injection shouldn't try to inject anything into CRs by default (and `pod_template_json_path` could be implemented later). What will Tilt do in case of a live update when the user still associates pods with the CR via `k8s_resource()` and they have no synclet container?

**Comment by nicks** [comment]
ya, I basically agree with all of those things. There are multiple paths to fix the problem

**Comment by nicks** [comment]
This change had to be rolled back, so re-opening

**Comment by maiamcc** [comment]
As of #3563, the synclet is NOT enabled by default, and will soon be removed completely--closing this issue.
