### ISSUE TITLE
support manually triggering tiltfile executions

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#2957]
For the "(Tiltfile)" resource:
1. there is no retrigger button in the UI
2. `tilt trigger` doesn't work, and with a confusing error (since as far as the UI represents to the user, "(Tiltfile)" is a manifest that exists):
```
$ tilt trigger '(Tiltfile)'
Request to http://localhost:10350/api/trigger failed with status "400 Bad Request": no manifest found with name '(Tiltfile)'
```

This is workaroundable by:
`local_resource('rerun Tiltfile', 'touch Tiltfile', auto_init=False, trigger_mode=TRIGGER_MODE_MANUAL)`

**Comment by landism** [comment]
FWIW, I suspect many of the times this is wanted, it's due to unwatched dependencies in the Tiltfile rather than recovering from nondeterminism. Even so, when an unwatched dependency is getting in the way of your iteration, it's nice to be able to click a button to manually work around it without having to stop what you're doing and fix your dependencies.

**Comment by Raffo** [comment]
@landism I think the trick mentioned doesn't work. If  add this and run `tilt up`, I get the following in the output: 

```
auto_init=False incompatible with trigger_mode=TRIGGER_MODE_AUTO
```

**Comment by landism** [comment]
> @landism I think the trick mentioned doesn't work

Thanks! I've edited the original post to add `trigger_mode=TRIGGER_MODE_MANUAL` (and verified that it works this time 😬)

**Comment by nicks** [comment]
I filed https://github.com/windmilleng/tilt/issues/3046 to capture why people want a way to manually trigger Tiltfile executions. 

I feel like this feature is a good short-term stopgap if it's low-effort to implement. But if you've got a lot of local() calls in your Tiltfile that you need to manually re-trigger, then you're going to have bigger problems around stability / robustness.

**Comment by maiamcc** [comment]
IDK if this is helpful, but [here's an old WIP](https://github.com/tilt-dev/tilt/tree/maiamcc/can-trigger-tiltfile) for this issue that I pushed up in case it's useful to whoever tackles this.

**Comment by maiamcc** [comment]
This is live as of [v0.17.10](https://github.com/tilt-dev/tilt/releases/tag/v0.17.10)!
