### ISSUE TITLE
live_update synclet blocks Job from exiting

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3042]
Reported by Raffo in the tilt channel:

> I’m currently using [an] image in a job and the synclet is blocking the progress of the job as it never terminates :smile:

Tilt injects the synclet as a sidecar, which is why it's blocking the Job exit.

Work-arounds:
- Start tilt with `--update-mode exec`, which will use kubectl exec to do live updates instead of the synclet
- Don't use live_update for the image in the Job

Related issues:
- There's a long discussion of this problem here: https://github.com/kubernetes/kubernetes/issues/25908, with a proposal to add an API for non-blocking sidecars
- Tilt also has bugs when injecting the synclet sidecar into CRDs: https://github.com/windmilleng/tilt/issues/2948

**Comment by nicks** [comment]
Thanks makes me wonder if we should change Tilt to use the `kubectl exec` live_update strategy by default, unless there's a specific reason not to (like the user is using restart_container). I think it has much fewer problems in general.

**Comment by maiamcc** [comment]
As of #3563, the synclet is NOT enabled by default, and will soon be removed completely--closing this issue.
