### ISSUE TITLE
Add brew support for linux in install script

### ISSUE THREAD

**Issue by rmb938** [tilt-dev/tilt#3078]
Brew natively supports linux so the install script should check if it's installed and use it.

https://docs.brew.sh/Homebrew-on-Linux

Should just be able to do something like this from the osx block https://github.com/windmilleng/tilt/blob/master/scripts/install.sh#L31-L34

**Comment by nicks** [comment]
I like this idea! But as we add more branches in the installation flow, one concern I have is if it's possible to get "wedged" -- e.g., you have one Tilt binary at ~/.local/bin and another in homebrew, but the default one on your PATH is not the one getting updated each time.

**Comment by nicks** [comment]
Got another request for this today:
> Brew also is much easier to keep things up to date so I try to push users in that direction.
