### ISSUE TITLE
Ability to stop a local_resource

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt#3083]
Currently it's possible to:

1. Control whether a `local_resource` starts on `tilt up` (via `auto_init` flag)
2. Control whether a `local_resource is automatically updated when dependencies change (via `update_mode flag)

However, if you want to _stop_ a process after Tilt has started it there's currently no way to do that.

This is useful for "temporary" workflows, like React storybooks, that can be expensive to start but are useful to have on the "menu" of possible options. (I start Tilt, work on some stuff, spin up the storybook server to work on some story books, then stop it when I'm done)

**Comment by zkutasi** [comment]
I also would pop in and say this would be useful for us, as we start a gradle build container to warm it up and have very quick compilations (<10 seconds, without this, we have like 2-3 minutes with gradle)... and this gradle container cannot be deleted now by tilt down... not a big issue, but would be an easy addition I believe to also have a "down" command how to eradicate such a local_resource.

**Comment by maiamcc** [comment]
To add some more texture here: whatever we implement here can probably be equally applied to stopping a long-running Local Resource (running via `serve_cmd`) and tearing down/cleaning up after ANY Local Resource (long running or not -- e.g. your Local Resource runs `set-up-db.sh` and on `tilt down` you want to run `teardown-db.sh`).

Spitballing syntax: `local_resource('foo', cmd=xxx, teardown_cmd=yyy)`

**Comment by landism** [comment]
I think there are a couple different issues getting conflated here.

At the moment, Tilt triggers a "stop" of all local resources when Tilt is ctrl+C'd. Tilt down is not currently relevant.

I think Dan's OP is "I should be able to manually trigger a 'stop' of a local resource without killing Tilt".
I think Maia's comment is "I should be able to configure what 'stop' means for a given local resource."

**Comment by maiamcc** [comment]
Ugh you are correct, I'll open a new issue! 😅

**Comment by milas** [comment]
See also #3083 about pausing live updates specifically (but not tearing down the resource). Linking these because I think they fall under a similar umbrella of greater fine-grained resource control after `up`.

**Comment by milas** [comment]
See also #4314 about pausing live updates specifically (but not tearing down the resource). Linking these because I think they fall under a similar umbrella of greater fine-grained resource control after `up`.

**Comment by nicks** [comment]
We now have a Cancel button extension that adds a "Cancel" button to every local resource. You can use it to manually stop any builds or servers.

https://github.com/tilt-dev/tilt-extensions/tree/master/cancel

I'm going to consider this closed
