### ISSUE TITLE
Tilt File Watching Broken on WSL 9p/Windows filesystem

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt#3101]
Seems to work in some cases, but not others.

See https://github.com/microsoft/WSL/issues/4169

Originally reported in [#tilt channel](https://kubernetes.slack.com/archives/CESBL84MV/p1584737877252800?thread_ts=1584734274.236500&cid=CESBL84MV)

**Comment by nicks** [comment]
Reading this issue https://github.com/microsoft/WSL/issues/4739 (which has a cool shout-out to tilt.dev 🤗 🤗 🤗 ) makes me think this might not be possible to fix.

I wonder if we should add a thing to `tilt doctor` that writes a temp file to the current directory, and makes sure Tilt can see the change to it.

**Comment by nicks** [comment]
We talked a bit offline about this. As the attached WSL ticket points out, a good workaround is to move  your code to the Linux filesystem. This should be much faster anyway. The VSCode support for this has been getting better (https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)

**Comment by KOGI** [comment]
> The VSCode support for this has been getting better

Unfortunately no equivalent support for IntelliJ, yet 😞

**Comment by lizzthabet** [comment]
i think we can close this issue, since it isn't tilt-specific and there are workarounds mentioned above. others can chime in and re-open if they disagree!
