### ISSUE TITLE
feature request: readiness checks for local_resource(serve_cmd)

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3109]
Kubernetes has a notion of readiness checks: a signal that your server is up and ready to receive traffic
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

Tilt uses readiness in a few places: to determine whether to mark a service "green" in the UI, whether to build resources that depend on it, etc

Tilt also lets you run servers with local_resource(serve_cmd).

Users of local_resource(serve_cmd) would like some way to be able to also configure readiness checks to control the UI display. I like the Kubernetes API of letting you define both HTTP-based and shell-based readiness probes. You could also imagine other signals (like scanning logs)

**Comment by danyelf** [comment]
This would be great to help us monitor the multiple services we're tilting up on our laptop-microservice configs

**Comment by theothertomelliott** [comment]
One possible additional (if super hacky) probe that could be used in this case would be to wait for the "serve" process to be listening on any port.

This is useful in cases where you're automatically generating resources and don't have metadata available to know the port that they will listen on ahead of time.

**Comment by nicks** [comment]
work has begun on this! the api will look something like this: https://github.com/tilt-dev/tilt.specs/blob/master/readiness_probe.md#tiltfile-api

**Comment by milas** [comment]
This is available with Tilt [v0.18.5+](https://github.com/tilt-dev/tilt/releases/tag/v0.18.5) 🎉 

There's an example in the Local Resource docs in the `serve_cmd` section titled "custom environment": https://docs.tilt.dev/local_resource.html#serve_cmd.

Let us know if you encounter any issues!

**Comment by milas** [comment]
Oops - just closed this by accident. This is still underway but coming very soon!

**Comment by milas** [comment]
We just released readiness probes for local resources! You'll need to upgrade to Tilt [v0.18.6+][release-latest] for support.

Local resources with a readiness probe defined will not show as ready in the Tilt UI until the probe is successful and any other resources with a `resource_deps` dependency on one will wait to start until the local resource they're dependent upon passes the readiness probe check.

Similar to K8s, you can define an HTTP GET request, TCP socket connection, or arbitrary process/script to determine resource readiness. There are also several options for configuring the period, startup delay, and consecutive success/failure thresholds.

There's a complete example in the [local resource docs][docs-local-resource] and the [`probe` API reference][api-probe] shows the full range of possibilities.

If you run into any issues, don't hesitate to reach out!

[release-latest]: https://github.com/tilt-dev/tilt/releases/latest
[docs-local-resource]: https://docs.tilt.dev/local_resource.html#readiness_probe
[api-probe]: https://docs.tilt.dev/api.html#api.probe
