### ISSUE TITLE
Keyboard shortcut to move between tabs in Tilt web

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#3114]
Currently in Tilt web there are the tabs, Logs, Alerts, and Facets. 

There should be an easy way to tab through them with a discoverable keyboard shortcut. 

<img width="721" alt="Screen Shot 2020-03-25 at 9 30 29 AM" src="https://user-images.githubusercontent.com/10860550/77541686-5f78b380-6e7b-11ea-9e0b-07191b2c92d8.png">

**Comment by alanchrt** [comment]
Some ideas (vim-like patterns I've seen for tabs elsewhere):

- `h` and `l`
- `J` and `K`
- `gt` and `gT`

**Comment by victorwuky** [comment]
Thanks @alanchrt

**Comment by nicks** [comment]
This is currently implemented as 1, 2, 3

the next release should also have a help dialog to make the shortcuts more discoverable
