### ISSUE TITLE
default font size might be too large

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3115]
A lot of users have noted that the default font size of the web UI is large for their screens.

The easy work-around is to zoom out in your browser

I wonder if we should either:
- re-evaluate the default font-size, or
- offer some sort of Tilt Cloud -based way to set personal font size preferences

**Comment by victorwuky** [comment]
@nicks : Is there anyway to read the font size that is being used from the terminal that ran `tilt up` and use that to determine the font size of the web UI?

**Comment by victorwuky** [comment]
Closing this as now we have a smaller font size
