### ISSUE TITLE
`tilt log` CLI command for fetching the logs from a tilt resource

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3139]
For people who prefer to interact with Tilt from the commandline, it would be nice if there was a `tilt log [resource]` command that dumped the logs for a resource

Even better if it you could do `tilt log --follow [resource]` to make it streaming, like `kubectl log --follow`

Requested my tmc in the slack channel

**Comment by maiamcc** [comment]
Whipping up an MVP of this! Proposed behavior:
* `tilt logs resourceA` streams logs for resourceA from the beginning of the Tilt run
  * (presumably no "resourceA: asdfg" prefix is necessary in this case)
* `tilt logs resourceA resourceB` streams logs for resourceA and resourceB from the beginning of the Tilt run
  * logs will be prefixed by resource
* by default, streams logs from the Tilt running on port 10350 -- can change with the `--port` flag

Open questions:
* should there be a `--no-follow` option that just prints the current logs and exits? (should this be the default?)
* in "follow" mode (currently the default), should the command print logs from the beginning of the Tilt run or just START from any logs that arrive after the invocation of `tilt logs`?
* is a `tilt logs` cmd WITHOUT specific resources (i.e. tail all tilt logs starting from the beginning of the Tilt run) useful?

**Comment by maiamcc** [comment]
🚀  launched in [v0.17.1](https://github.com/tilt-dev/tilt/releases/tag/v0.17.1)! 🚀
