### ISSUE TITLE
Ensure that extensions continue to work across new versions of Tilt

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#3170]
## Problem

As raised by a user in Slack #tilt (https://kubernetes.slack.com/archives/CESBL84MV/p1585776134068700?thread_ts=1585768745.067700&cid=CESBL84MV)

> it would be nice to have tests in place validating that my extensions don't break between versions of tilt. Some cursory research shows starlark has some amount of support for this as is

## Description
Extensions are currently reviewed and approved by the Tilt team. But is there any additional work we can do to ensure that all extensions are working, across new versions of Tilt? See https://github.com/windmilleng/tilt-extensions

**Comment by milas** [comment]
We now run the extensions tests as part of the regular Tilt CI to ensure they are not broken by Tilt changes.
