### ISSUE TITLE
Development of extensions allows you test that it actually works before submitting a PR

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#3188]
As described in https://docs.tilt.dev/contribute_extension.html, the way to contribute an extension is not a very good development experience. You have to develop a function in a local file, test that it works, and then create a PR to the tilt-extensions repo by copying code over in another file structure. It's clumsy and a poor experience. And contributors cannot verify that it actually works before submitting a PR. This should be improved.

There can also be a CI test to validate that the extension follows the required format, such as having a README.md file. See https://github.com/tilt-dev/tilt-extensions/issues/20.

**Comment by esatterwhite** [comment]
The may not be the best place, But rather than just developing extensions, I want a way to load extensions from a repository other than tilt's. 

```python
load_extension("git://github.com/my-private-repo/fancy_things")
```

**Comment by nicks** [comment]
@esatterwhite ya, as you pointed out on https://github.com/tilt-dev/tilt-extensions/pull/25, i think you could implement this today as something like

```
git_checkout('https://github.com/my-private-repo/fancy_things')
load('./.git-sources/github.com/my-private-repo/fancy_things/Tiltfile', ...)
```

Given the `git_checkout` implementation in that PR. I feel like this is a case of "all extension systems can be implemented in terms of other extension systems :smile: ", though agree that there should be an off-the-shelf version of this

**Comment by esatterwhite** [comment]
And, if I'm not mistaken, you can't  use extensions in extensions, which also limits re-usability

**Comment by victorwuky** [comment]
Hi @esatterwhite : As of v0.15.0 of Tilt, you can use extensions in extensions. See release notes here: https://github.com/tilt-dev/tilt/releases/tag/v0.15.0. And also docs here: https://docs.tilt.dev/contribute_extension.html#create-and-test-a-function-in-your-tiltfile. Hope that helps!

**Comment by nicks** [comment]
there's now a guide on how to load extensions from the file system: https://docs.tilt.dev/extensions.html
