### ISSUE TITLE
 "Live Update failed with unexpected error"-type failures are not dismiss-able in the UI (even after the subsequent rebuild / deployment succeeds)

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#3213]
As reported in #tilt: https://kubernetes.slack.com/archives/CESBL84MV/p1586975751188500

> very minor potential bug - is it known/expected that "Live Update failed with unexpected error"-type failures are not dismiss-able in the UI (even after the subsequent rebuild / deployment succeeds)?
seems sort of similar to https://github.com/windmilleng/tilt/issues/2553 where the "dismiss" button is just missing

![Screen Shot 2020-04-15 at 1 41 45 PM](https://user-images.githubusercontent.com/10860550/79379595-21782800-7f2d-11ea-8a40-723a56dc3d2a.png)

**Comment by milas** [comment]
Closing this issue as stale - the Tilt UI has been redesigned since and this is no longer applicable.
