### ISSUE TITLE
knative support

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt#3232]
We should have a guide/docs around how to use Tilt with knative

**Comment by nicks** [comment]
created a branch in the example repo to play round with this:
https://github.com/tilt-dev/tilt-example-html/blob/nicks/knative/101-knative/Tiltfile

The most interesting thing I learned is that knative uses an operator to create immutable tags and inject them at runtime, whereas Tilt creates immutable tags at build-time and injects the tag into the YAML. See this discussion:

https://knative.dev/docs/serving/tag-resolution/

It's heartening to see someone else struggling with this same problem! Tilt's solution to this problem works really well with local dev, whereas knative's does not. See the part about local images here:

https://knative.dev/docs/serving/getting-started-knative-app/

You can resolve this in Tilt by setting default_registry('dev.local')

**Comment by nicks** [comment]
Note to self: the kind selector needs to be

```
k8s_kind('Service', api_version='serving.knative.dev/v1',
         image_json_path='{.spec.template.spec.containers[*].image}')
```

Note the "*", so that it matches all containers, not just the first one

**Comment by nicks** [comment]
We now have a knative extension!
https://github.com/tilt-dev/tilt-extensions/tree/master/knative

And docs on how to use it under:
https://docs.tilt.dev/custom_resource.html
