### ISSUE TITLE
Remove the synclet as default

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3245]
The Synclet is implemented as a privileged sidecar that talks directly to the Docker socket.

This is proving more and more difficult to make work, because it's inconsistent with the overall direction of the Kubernetes ecosystem:

- The privileged permission is generally discouraged and unexpected.
- The sidecar approach is not a good fit for this particular use-case, because it breaks a bunch of behavior. The Kubernetes community is hopeful for ephemeral containers (https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190212-ephemeral-containers.md)
- Modern Kubernetes clusters generally don't use Docker-shim at all, so don't even have a Docker socket.

We shouldn't drive new users to the synclet

**Comment by maiamcc** [comment]
Resolved by #3563
