### ISSUE TITLE
portforward errors creating error stream

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3266]
In the tilt channel, Andy reports that portforwarding is breaking with errors creating the error stream

```
E0430 14:41:35.590546   10139 portforward.go:340] error creating error stream for port 80 -> 80: Timeout occured
```

> as connections are attempted, but when we manually do kubectl port-forward  to bind to a different port and forward traffic in to the services, everything works fine over the other port.

what's particularly suspicious is that it's reproducible on one machine, but not on other machines

KIND 0.7.0 cluster on a Ubuntu desktop

**Comment by dotellie** [comment]
I'm also getting this in with Minikube for some reason. I'm gonna try restarting Tilt or something, but figured it might be worth putting this on here in case it helps with debugging this later.

```
E0522 15:57:24.276195   65096 portforward.go:340] error creating error stream for port 5000 -> 5000: Timeout occured
```

```
Tilt: v0.13.2, built 2020-04-16
System: linux-amd64
---
Docker (cluster)
- Host: tcp://192.168.39.173:2376
- Version: 1.40
- Builder: 2
---
Docker (local)
- Host: Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.18.0
```

Note: I don't have docker installed locally as I use podman, not that it should matter or anything. :sweat_smile:

**Comment by nicks** [comment]
For what it's worth, I've changed this error a bit in https://github.com/tilt-dev/tilt/pull/3367

In the next Tilt release, these logs will only show up if you start Tilt with `tilt up --debug`.

We were finding that in most cases, these logs weren't helpful for diagnosing what the underlying problem was, and often were actively misleading (e.g., they would spew spurious errors when you know that your pod is restarting)

We would still love repro cases for when portforwarding isn't working as expected, though I think this points to a need for more investigative tooling - like a way to ask Tilt "run sanity checks on my port-forward setup", or a health-check UX for port-forwards

**Comment by milas** [comment]
Closing this issue as stale - if you're encountering port forward issues, please create a new issue with the error you're seeing, `tilt doctor` output, and relevant Tiltfile snippet.

**Comment by girish2909** [comment]
tilt doctor
Tilt: v0.30.13, built 2022-12-05
System: windows-amd64
---
Docker (cluster)
- Host: tcp://172.21.220.123:2376
- Server Version: 20.10.20
- API Version: 1.41
- Builder: 2
---
Docker (local)
- Host: [default]
- Server Version:
- Version:
- Builder:
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.25.3
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: default
- Machine: c32ca0849e687c66faf46ad7970ac533
- Repo:
