### ISSUE TITLE
Add a way to set kubeconfig context from the command-line

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3296]
Most tools in the kubernetes ecosystem let you set the kubeconfig context from the command-line.

For example, kubectl has
--kubeconfig
--cluster
--context

It would be nice if Tilt supported similar flags (maybe kubecluster, kubecontext). It should be easy to add, since we already use the same client-go code as kubectl for configuring the context (and in fact it supports KUBECONFIG env variable out of the box)

(requested in the tilt slack channel)

**Comment by nicks** [comment]
good some additional context on this, this is useful when you have frequent staging clusters (e.g., a staging environment for each PR) and want to make tilt consistently point to the dev cluster without changing the active context

**Comment by dminella** [comment]
Hello,

This issue still relevant? Could I take it?

Cheers!

**Comment by nicks** [comment]
@dminella yes! you're welcome to take a crack at it. Abdullah had to go back to school. Here's where we got so far:

This line
https://github.com/tilt-dev/tilt/blob/master/internal/k8s/client.go#L485
is where overrides are typically set by the --context flag in kubectl (we were trying to integrate as well as we could with the kubectl code for instantiating the go k8s client)

This line
https://github.com/tilt-dev/tilt/blob/master/internal/k8s/env.go#L51
is wrong, since GetStartingConfig() removes those overrides

**Comment by maiamcc** [comment]
@dminella are you picking this up because of the "Good first issue" tag? We probably should have removed that when Abdullah first tried this, it turned out to be more complicated than we anticipated. You're definitely welcome to take the issue if you're still interested though!

**Comment by dminella** [comment]
Yes @maiamcc , I picked up because the tag. I think that is better I looking for another one that matchs with good first issue, thank you for advise me! 

@nicks I appreciate the introdution, but I'll take a good first issue at this moment, who knows if in the future I came back here!

**Comment by nicks** [comment]
This flag should be available in tilt v0.17.4 !
