### ISSUE TITLE
Enforce minimum kubernetes version

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3297]
A user had an issue where everyone on their team was using Kubernetes 1.16, but one person was using Kubernetes 1.13, and it led to weird issues. How can surface this and support this better?

A simple feature would be to have an extension or API for enforcing a minimum Kubernetes version. Prior art:
https://github.com/windmilleng/tilt-extensions/tree/master/min_tilt_version
https://github.com/windmilleng/tilt/issues/3293#issue-613605521

But it's kind of a "horse that left the barn" problem - if you're enforcing it in the Tiltfile, you have to know you even have that problem. I wonder if there's a bigger TiltCloud feature to surface the distribution of kubernetes version across the team, and that this is closer to the "Jess only has two CPUs allocated" problem described here: https://github.com/windmilleng/tilt/issues/3117#issuecomment-621267400. But that might be out of scope for this

**Comment by abdullahzameek** [comment]
A new extension `min_k8s_version` solves this issue! Can be found here : https://github.com/tilt-dev/tilt-extensions/tree/master/min_k8s_version
