### ISSUE TITLE
Improvements on the Java live update method

### ISSUE THREAD

**Issue by zkutasi** [tilt-dev/tilt#3312]
Hi,

I am fiddling with the live update method descibed here:
https://docs.tilt.dev/example_java.html

I stumbled upon some issues:

1. If I add a new file to my source-code, this new file is sync-ed into the container, but not picked up by entr... This is because entr manual suggests to implement it in another way: http://eradman.com/entrproject/ ... So watch directories for changes, and put the whole thing in a loop... it seems it works... what do you think?

2. If I rename a file, for example refactor it... the old file is not removed... This is especially problematic in Spring, as it dynamically injects Beans all around via their interface-implementation, or if I rename my controller, I will get "ambiguous mapping" error. And the only solution is to restart Tilt? So is there any way to tell Tilt sync() to do a full sync, so remove files existing only on the remote side?

Apart from this, I think it works pretty good... will try to use it, and see if I come up with any new issue... many thanks for the guide, was really helpful.

**Comment by landism** [comment]
Thanks for the report!

These are both now fixed.

**Comment by zkutasi** [comment]
Huge thanks for these, I will try them out soon! When I thought this tool cannot get any better, you guys prove otherwise :). Keep up the good work.
