### ISSUE TITLE
Allow arbitrary additional key/value pairs in tilt_config.json

### ISSUE THREAD

**Issue by andymartin-sch** [tilt-dev/tilt#3334]
In our use of [Tiltfile Configs](https://docs.tilt.dev/tiltfile_config.html), we define our service groups in the Tiltfile like how it's done in the documentation.

After we rolled this out to developers, some mentioned that it would be nice if the groups could be defined directly in the tilt_config.json file like:
```
{
  "to-edit": [],
  "to-run": [],
  "service_groups": {
    "svc_a": ["x", "y", "z", ...etc...],
    "svc_b": [ ...etc...]
    ...etc...
  }
}
```

This would let developers customize the set of service groups (a) in a file that's not tracked in version control and (b) in-line with where they choose which groups to run and edit.

The problem is that using a tilt_config.json file that's structured like the above is not currently supported -- the end result is:
```
Traceback (most recent call last):
  /home/martin/....snip..../Tiltfile:43:19: in <toplevel>
  <builtin>: in config.parse
Error: /home/martin/....snip..../tilt_config.json specified unknown setting name 'service_groups'
```
This seems to be because a [config.define_string_list](https://docs.tilt.dev/api.html#modules.config.define_string_list) call has to be made in the Tiltfile to tell Tilt about the new `service_groups` field but there is no "define_string_dict"-like method that would let us pass in a dict instead of a list.

Would it be possible to just turn off this validation entirely and allow arbitrary key/value pairs to be present in tilt_config.json without throwing an error?

**Comment by landism** [comment]
How about a `config.define_object("service_groups")` (unsettable via the command-line) that'd indicate that something can exist with that name and any value, while still allowing validation to happen?

**Comment by andymartin-sch** [comment]
Yeah, that sounds like it would work for our use case 👍
