### ISSUE TITLE
Add kate swp files to ignore patterns

### ISSUE THREAD

**Issue by iggy** [tilt-dev/tilt#3378]
Kate (the default kde text editor) uses a variation of Vim's `.swp` files called `.*.kate-swp`. While it has the ability to change where the .kate-swp files are created, it's not on by default and actually a little tricky to find even if you are looking for it. I think for ootb experience, it might be nice to add `.*.kate-swp` to the ignore list in `tilt`.

I looked at the code for the editor and don't see anything like is mentioned in the `tilt` code about vim "incrementing" the extension (so, no `.kate.swo` files, etc).

**Comment by nicks** [comment]
That sounds reasonable to me! Since you've already dug in a bit to the code, want to send a PR?
