### ISSUE TITLE
Facet tab organization

### ISSUE THREAD

**Issue by theothertomelliott** [tilt-dev/tilt#3403]
I've been finding the Facets tab really useful for inspecting generated k8s yaml. But when I open it, I usually find the content scrolled to the bottom, so I need to scroll up until I hit upon the start of the applied yaml section, which can be fiddly for larger resources.

It's a minor annoyance, but it would be great to have a means of going straight to the top of the yaml section, or collapsing the different sections.

**Comment by victorwuky** [comment]
Thanks for logging this @theothertomelliott . cc @maiamcc
