### ISSUE TITLE
Ability to dynamically ignore files at runtime.

### ISSUE THREAD

**Issue by KOGI** [tilt-dev/tilt#3404]
A few functions accept an `ignore=[]` flag to prevent triggers on certain files, but most functions don't. In many cases, these ignores can be achieved with the `.tiltignore` file, but in some cases, these filenames aren't known until runtime.

We have the ability to dynamically _watch_ files with `watch_file()`, but there is no counterpart `ignore_file()` or `unwatch_file()`. Adding this method would allow run-time ignore rules.

This may even be a potential solution for #1930 and #2602 

In my particular case, I'm using `local('helm pull ...')` and `k8s_yaml(helm('path/to/pulled/chart'))`. To ensure we always have a fresh copy of said chart, I'm also doing a `local('rm -rf path/to/pulled/chart')` immediately before the pull. If tilt is already running, then that chart is being watched. If I update my tiltfile, it gets re-run, which deletes that directory, which triggers a re-run, which successfully pulls the chart, and the newly created files, in turn, trigger another re-run, which again deletes the dir, ad nauseum.

See https://github.com/tilt-dev/tilt-extensions/pull/19

Since `helm()` doesn't have an `ignore=[]` flag, there seems to be no way around this. The ability to dynamically un-watch this directory prior to deleting it would solve the problem.

**Comment by jazzdan** [comment]
Hey @KOGI,

Thanks for opening this. I think that makes a lot of sense. This could be pretty easily hacked together by making a Tiltfile function that appends patterns as strings to the in-memory version of the `.tiltignore` file and letting the engine reload it as if the `.tiltignore` had changed.

**Comment by nicks** [comment]
fwiw, this has bitten me a lot too

**Comment by KOGI** [comment]
Any updates/plans/roadmap for this, yet?

**Comment by nicks** [comment]
not yet! though there are some changes underway to change the internal data model for the ignores, to make it easier to make/debug changes like this

**Comment by KOGI** [comment]
❤️
