### ISSUE TITLE
custom_build not watching '.'

### ISSUE THREAD

**Issue by benjamin-wright** [tilt-dev/tilt#3418]
First off, thanks for the awesome tool, am a recent adopter and absolutely loving it!

In trying to fit the tool into one of our repos, I'm having an issue with the `custom_build` function, applied using the code below (with sensitive bits redacted)

```
custom_build(
    '***',
    'DEV_BUILD_IMAGE=$EXPECTED_REF make dev',
    [ '.' ],
    live_update=[
        sync('./src', '/usr/src/app/src'),
        sync('./test', '/usr/src/app/test'),
        sync('server.js', '/usr/src/app/server.js')
    ]
)
```

This mostly works fine, image builds and is available in my local cluster, live update works and is awesome. However, if I make updates to the Dockerfile (in the project root, so `./Dockerfile`) used to create the image, a fresh build is not triggered. The `docker_build` version of this command works as expected, so I expected the `[ '.' ]` deps definition would pick up the change outside of the live_update sync sources and just work.

Am I missing something, or is this a bug in the watch implementation for custom_build?

FYI: Running tilt 0.14.2 on OSX Catalina

**Comment by jazzdan** [comment]
Hi @benjamin-wright! I wasn't able to reproduce this in [this example repo](https://github.com/jazzdan/custom-build-depend-dot).

If I had to guess there's something in either your `.gitignore`, your `.dockerignore` or your `.tiltignore` files in that root directory that is causing the problem. Tilt respects these files and doesn't watch them, you can learn more about that [in this doc](https://docs.tilt.dev/file_changes.html).

Any chance you can paste the output of any of those files that live in the root of the project directory?

**Comment by benjamin-wright** [comment]
Ah, I didn't realise the .dockerignore ignoring applied to custom_build too! The .dockerignore has `**` at the top, putting `!Dockerfile` in too seems to have resolved it.

Does that make sense for a `custom_build`? We're using a Makefile to wrap our docker build statements, so that our automation uses the same build commands as local dev. But for a .dockerignore that uses `**` and only includes source dirs, that means that watch will ignore Dockerfile, Makefile, etc., which we wouldn't want to send in the context but absolutely do want to watch.

I've had a look through the docs and couldn't find a way of ignoring an element of the .dockerignore...?

**Comment by nicks** [comment]
One workaround might be to have a `watch_file('Dockerfile')` in your Tiltfile. That will reload the whole Tiltfile, but Tilt should be pretty smart about not updating resources that haven't changed

It's interesting that you're using custom_build to wrap docker build, so you probably want *most* of the .dockerignore behavior, just not this bit.

At the very least, we should add some notes in the documentation that `custom_build` respects .dockerignore.

I understand the desire to have a way of "ignoring an element of the .dockerignore". My experience with these sorts of systems is that it's very easy to keep adding overlapping "keep / ignore / keep / ignore" knobs, and that adding more layers of ignores makes them even more difficult to engineer and organize. Not saying we shouldn't add this, just that we want to be thoughtful about how we do it.

**Comment by benjamin-wright** [comment]
Hi @nicks 

Yeah, I can see how it could get messy, and the note in the documentation would help a lot to clarify the behaviour, which was most of the problem. It might be nice to be able to expand the watch capability of the custom build, but on reflection we're abusing .dockerignore at the moment anyway. If we refactored a bit to separate the code and Dockerfile from the CI scripts etc. we'd have a much more simple .dockerignore file and this would cease to be a problem.

Thanks for the pointer on `watch_file`, will give that a go when I get a chance, hopefully that'll get us a short term patch until we can get the longer term refactor in. 😄

**Comment by benjamin-wright** [comment]
Will close this as I don't think there was anything to do beyond the documentation tweak.
