### ISSUE TITLE
Nit: Weird highlighting of `Your Tilt Cloud status` text in Tilt UI 

### ISSUE THREAD

**Issue by andymartin-sch** [tilt-dev/tilt#3420]
Very minor issue, but there is some weird highlighting behavior around the text in the upper-right hand corner of the Tilt UI with the text `Your Tilt Cloud status`.

One example:
![pic](https://i.imgur.com/KNlyfFL.png)

I think this is a longstanding thing, not related to any recent Tilt release.

**Comment by victorwuky** [comment]
Thanks for logging this @andymartin-sch . cc @hyu .

**Comment by victorwuky** [comment]
I can only reproduce this on Chrome. Weird!
