### ISSUE TITLE
Versioning of extensions

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#3426]
Right now there is no way to version extensions. This issue serves to gather feedback and interest.

**Comment by MikeSouza** [comment]
Support for specifying a version or even a commit hash would very much have saved us hours of dev time troubleshooting.

https://github.com/tilt-dev/tilt-extensions/issues/135

**Comment by TimothyLoyer** [comment]
I'm working on bringing Tilt to my team. A recent update to an extension has broken it's functionality for me, and without a way to pin to the last working version I'll just need to rely on it getting fixed soon or develop my own extension in order to ensure that it won't interrupt our workflow.

**Comment by grrttedwards** [comment]
The `git_resource` extension already supports many "versioning" type features, like using specific commit hashes or branch names to check out. It may be an easy win to enable the `ext://` family to do the same until a complete versioning scheme has been developed for extensions.

**Comment by nicks** [comment]
the extension guide now has instructions on how to pin the extension repository to a specific version: https://docs.tilt.dev/extensions.html

We add a tag for each tilt release, if you want to pin to the tilt release.
