### ISSUE TITLE
CRD image injection when repo and tag are expressed differently

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3427]
Most CRDs expect an image field where an image is injected. Tilt has an API for injecting the image:

```
  image: frontend:latest
```

But sometimes, Helm charts express the image repo and the image tag separately

```
image:
  repo: frontend
  tag: latest
```

Unfortunately, Tilt's API for discovering images in CRDs assumes one field (see https://docs.tilt.dev/api.html#api.k8s_kind and image_json_path)

We'd probably need something like
image_repo_json_path, image_tag_json_path

(requested by bkpandey in the tilt channel)

**Comment by pandeybk** [comment]
Thank you @nicks, adding helmrelease manifest example for reference, https://github.com/fluxcd/flux-get-started/blob/master/releases/ghost.yaml#L18-L19

**Comment by nicks** [comment]
I think the tricky part of this is handling it in the case where the "tag" field is omitted in the yaml, but tilt needs to inject it.

Currently thinking about an api like

```
k8s_kind(kind, image_object={'json_path': ..., 'repo_field': 'repo', 'tag_field': 'tag'}
```

the api is a bit awkward, but i think will unblock you without leading to too many weird api edge cases.

**Comment by nicks** [comment]
@pandeybk Tilt v0.15.2 supports the above syntax! let us know if you have any issues with it
