### ISSUE TITLE
distribute tilt with conda-forge

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3431]
conda-forge is a community package registry for the conda package manager

https://conda-forge.org/

Although it's most well-known in the python & data science communities, it's a general-purpose package manager. We're starting to see more teams that use Tilt for their big-data workflows, so it might make sense to distribute Tilt there too.

**Comment by joseph-zhong** [comment]
Hey @nicks FYI I've submitted a PR to conda-forge (https://github.com/conda-forge/staged-recipes/pull/11935/) and am awaiting feedback, I was able to test locally on both a MacOS and Windows machine and it seemed to work as expected, let me know if you have any suggestions :)

```
(base) $ conda-build tilt
...
(base) $ which tilt
/Users/josephz/miniconda3/bin/tilt
(base) $ tilt version
v0.14.3, built 2020-06-12
```

**Comment by joseph-zhong** [comment]
Update: this is currently blocked by a missing go v1.14 version in conda-forge: https://github.com/conda-forge/go-feedstock/pull/87 -- Will follow up in the [gitter chat](https://gitter.im/conda-forge/conda-forge.github.io) to try and unblock and will update accordingly

**Comment by joseph-zhong** [comment]
https://github.com/conda-forge/staged-recipes/pull/11935/ is now merged and this should now be resolved, `tilt` should now be installable via 

```bash
$ conda install tilt -c conda-forge
...
$ which tilt
/Users/josephz/miniconda3/envs/ctrldev/bin/tilt
$ tilt version
v0.16.0-dev, built 2020-07-28
```

**Comment by majidaldo** [comment]
issue should be closed.

**Comment by nicks** [comment]
https://github.com/conda-forge/tilt-feedstock
