### ISSUE TITLE
include() should be able to load symbols

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3433]
We currently have two mechanisms for loading Tiltfiles

```load()``` - which can load symbols from other Tiltfiles, but requires static strings
```include()``` - which can only execute other Tiltfiles (not load symbols), but allows dynamic strings

Unfortunately, this breaks down if you want to load symbols from a dynamically-determined file, e.g.,

```
for dir in get_list_of_dirs():
  include(dir + '/Tiltfile', 'some_data')
```

which we've seen in a few places. For example, cluster API does something like this for providers, and we've heard another user do this with helm values.

**Comment by KOGI** [comment]
Another upvote for this. Currently trying and failing to do something like this:
`load('{root}/some/child/dir/foobar.tilt'.format(root=config.main_dir), 'my_symbol')`

**Comment by nicks** [comment]
This is now implemented as `load_dynamic`: https://docs.tilt.dev/api.html#api.load_dynamic
