### ISSUE TITLE
k8s_yaml should error on empty YAML

### ISSUE THREAD

**Issue by maiamcc** [tilt-dev/tilt#3439]
Expected: When `k8s_yaml` is passed an empty YAML string (i.e. `blob('')`) or `None`, it should error (presumably when this happens, it's b/c something went wrong when the user read/generated the YAML) -- or at least surface a warning?

Observed: the following calls are both legal and raise no error/warning--
* `k8s_yaml(blob(''))`
* `k8s_yaml(None)`

**Comment by abdullahzameek** [comment]
Solved with PR #3461
