### ISSUE TITLE
local_resource prints dumb command

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3441]
https://cloud.tilt.dev/snapshot/Afjxke4L3Pi6CYW1Deg=

When I run a local_resource(serve_cmd) with no build command, it prints:
Running command: [sh -c true] 

this is silly

**Comment by jazzdan** [comment]
@nicks I wasn't able to reproduce that with this Tiltfile:

```python
local_resource(
    'should clean up lock file on ctrl+c of tilt',
    '',
    serve_cmd='sleep 500',
)
```

snapshot: https://cloud.tilt.dev/snapshot/AZDJku4LxwySRS-ugv0=

I think you got this from my honeycomb example repo where I, erroneously, passed in 'true' as the build command explicitly: https://github.com/jazzdan/honeycomb-example/blob/master/Tiltfile#L3

Does that seem right?

**Comment by nicks** [comment]
ah you're right!
