### ISSUE TITLE
Customize the tag naming convention tilt uses internally to extend/override the tilt-<GUID> convention

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#3445]
From Slack: https://kubernetes.slack.com/archives/CESBL84MV/p1591903994336000

> Question about docker_build. Is there a way to customize the tag naming convention tilt uses internally to extend/override the tilt-<GUID> convention?

**Comment by nicks** [comment]
This is a misunderstanding of the problem that Cameron was trying to solve, we dug a bit more and narrowed it down to this: https://github.com/tilt-dev/tilt/issues/3448
