### ISSUE TITLE
Allow `include`d/`load`'d files to use tilt extensions

### ISSUE THREAD

**Issue by KOGI** [tilt-dev/tilt#3452]
It's very helpful to be able to organize your tiltfile by separating sections out into smaller files that can be included into the main Tiltfile. However, those sub-files are unable to make use of tilt extensions. There are 2 ways we can fail at this:

#### Main Tiltfile
```python
include('otherfile.tilt')  # this is just more tiltfile, NOT an extension, and NOT defining shared functions
```

#### Other Tiltfile
```python
load('ext://someExtension', 'someFunction')
someFunction('doAThing')
```

This fails with: **``Error: cannot load ext://git_resource: extensions cannot be loaded from `load`ed Tiltfiles``** which is confusing, since this file was `include`d, not `load`ed.

Ok, so let's load the extension first, and _then_ include our sub-file...

#### Main Tiltfile
```python
load('ext://someExtension', 'someFunction')  # load this first, so our included file can make use of it
include('otherfile.tilt')  # this is just more tiltfile, NOT an extension, and NOT defining shared functions
```

#### Other Tiltfile
```python
someFunction('doAThing')
```

This one fails with: ``Error: /path/to/otherfile.tilt:1:1: undefined: someFunction`` which suggests the included file doesn't share global context with the main tiltfile.

***If included files aren't capable of using extensions, it creates a _major_ limitation to organizing our scripts in this fashion.**

**Comment by KOGI** [comment]
@victorwuky is this relatively simple enough that it might land soon, or is it more likely a ways down the line?

**Comment by KOGI** [comment]
@victorwuky for what it's worth, while it would be nice for extensions to also load files, it seems to me like that's less important than the ability for non-extension, local includes to be able to make use of existing extensions.

**Comment by victorwuky** [comment]
Thanks @KOGI for the comment. Right now we don't have a clear timeline of when we'd pick up this feature in particular.

**Comment by maiamcc** [comment]
@KOGI to give a little more context, it turns out this feature isn't actually that simple because (among other things) we'd need to do a lot of work around handling working directories and all the inevitable edge cases. So--we'll keep you posted!

**Comment by nicks** [comment]
@maiamcc can you elaborate a bit more on why this is difficult to solve?

Ya, it seems like this should be much higher priority if it blocks the ability to use the restart_process extension

**Comment by nicks** [comment]
@maiamcc Your comment on https://github.com/tilt-dev/tilt-extensions/issues/37 makes me think you're might be confusing two different issues:

1) load()-ing extensions from other extensions raises questions about how we version extensions, and handle diamond dependencies
2) load()-ing extensions from other sub-included files in the "normal" repo doesn't raise any versioning concerns, and is much easier to resolve

**Comment by KOGI** [comment]
#1 would be nice
#2 is what this issue is asking for

**Comment by nicks** [comment]
@maiamcc how do you feel about removing the restart_process deprecation warning until this issue is resolved? seems like this issue is a blocker to adoption of restart_process.

**Comment by maiamcc** [comment]
Ugh yeah I was hoping it wouldn't be that hard to fix this issue, but since it's almost 3, I guess I'll revert the deprecation warning for today's release :-/

**Comment by maiamcc** [comment]
This should be fixed in [the latest release](https://github.com/tilt-dev/tilt/releases/tag/v0.15.0) -- let us know if you run into any trouble!

**Comment by KOGI** [comment]
Woo! Works like a charm! Thank you all!
