### ISSUE TITLE
extensions should be able to load other extensions

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3472]
Currently extensions are prohibited from loading other extensions

A user noticed this problem in this PR
https://github.com/tilt-dev/tilt-extensions/pull/19
where they were trying to use the namespace extension from the helm_remote extension

This severely limits the usability of extensions

**Comment by nicks** [comment]
The main blocker here is how we deal with extension versioning, and diamond dependencies between extensions

**Comment by maiamcc** [comment]
Allowed as of [v0.15.0](https://github.com/tilt-dev/tilt/releases/tag/v0.15.0). Our diamond dependency solution is to enforce that all modules are loaded from the `tilt_modules` directory of the root Tiltfile, even if they're invoked from a Tiltfile at a different location/deeper in the call stack.
