### ISSUE TITLE
auto_init=False makes tilt ci hang

### ISSUE THREAD

**Issue by damoon** [tilt-dev/tilt#3478]
Using auto_init=False for local_resource makes tilt ci hang.

**Comment by damoon** [comment]
i believe tasks with disabled auto start should be ignored during "tilt ci"

**Comment by maiamcc** [comment]
Good catch, ty!

**Comment by maiamcc** [comment]
This should be fixed in [the latest release](https://github.com/tilt-dev/tilt/releases/tag/v0.15.0) -- let us know if you run into any trouble!

**Comment by damoon** [comment]
work for me :D
thanks for the fix
