### ISSUE TITLE
Extension fetcher should grab the whole directory, not just the Tiltfile

### ISSUE THREAD

**Issue by maiamcc** [tilt-dev/tilt#3482]
As seen in https://github.com/tilt-dev/tilt-extensions/pull/35, sometimes an extension relies on more files than just the Tiltfile (e.g. supplementary scripts). It would be useful if the Tilt extension fetcher grabbed the whole directory of an extension, not just the Tiltfile. (Though: would there be security risks here?)

**Comment by nicks** [comment]
fixed in v0.17.5
