### ISSUE TITLE
Cannot build resource_deps on renamed/grouped k8s_resources

### ISSUE THREAD

**Issue by zkutasi** [tilt-dev/tilt#3497]
Hi,

Version is 0.15.0.

I'm trying to separate bootstrap-like objects like CRDs and make all of the other k8s resources depend on them, but I have stumbled upon a weird issue, maybe it is intentional, but maybe it is a bug: If I select at least one "uncategorized" object Kind and create a new resource from these with k8s_resource function (see below), then make the workloads or anything else depend on that, I see that Tilt keeps the dependent resources forever in Pending state for some reason I cannot understand... The one I depend on reaches OK status just fine

I have tried to reproduce it, and here is what I came up with as minimal:

Tiltfile:
```
load('ext://namespace', 'namespace_create')
namespace = 'tilt-test'
update_settings(max_parallel_updates=1)
namespace_create(namespace)

proj = 'microservice-ci-demo'
h = helm('helm/' + proj,
    name=proj,
    namespace=namespace
)
k8s_yaml(h)

k8s_resource(
    objects=['microservice-ci-demo:serviceaccount'],
    new_name='cluster-bootstrap'
)

k8s_resource(
    workload='microservice-ci-demo',
    resource_deps=['cluster-bootstrap']
)
```

Helm charts:
just a simple helm3-generated helm chart with a simple Deployment, a Service and a ServiceAccount... the ServiceAccount is used to make the new resource to depend on just for simplicity.

The one that works:
```
load('ext://namespace', 'namespace_create')
namespace = 'tilt-test'
update_settings(max_parallel_updates=1)
namespace_create(namespace)

proj = 'microservice-ci-demo'
h = helm('helm/' + proj,
    name=proj,
    namespace=namespace,
)
k8s_yaml(h)

k8s_resource(
    workload='microservice-ci-demo',
    new_name='one'
)

k8s_resource(
    workload='microservice-ci-demo-two',
    new_name='two'
)

k8s_resource(
    workload='two',
    resource_deps=['one']
)
```

I simply made a copy of the deployment, and added a hardcoded "-two" as suffix to its name in the YAML file. 

Is this supposed to work like this or is this a limitation/bug or am I missing something important? The documentation does not state this is something that should not work: https://docs.tilt.dev/api.html#api.k8s_resource

I'm thinking the issue might be this statement: https://docs.tilt.dev/resource_dependencies.html
```
A resource is “ready” when:
    For K8s resources: the pod is running and K8s considers all of its containers ready
```
As this is not a K8s object that has a Pod attached to it... maybe this use-case is not covered, and the resource never signals success?

Thanks!

**Comment by landism** [comment]
> As this is not a K8s object that has a Pod attached to it... maybe this use-case is not covered, and the resource never signals success?

Yep, you're right. It looks like this intersection of features hadn't been considered and this is a bug in Tilt. Thanks for the detailed report!

**Comment by zkutasi** [comment]
Cool, thanks for the feedback!

In the meantime I opted as a workaround to use a job to wait for the CRDs (can be done with kubectl but our component already has such a job so I just wired that in as dependency)... and this works fine it seems.

**Comment by nicks** [comment]
AFAIR, @jazzdan did some work to think thru how to handle workload vs non-workload manifests when he added the k8s_objects stuff
https://github.com/tilt-dev/tilt/pull/3361

@jazzdan does this look familiar to you at all?

**Comment by jazzdan** [comment]
It all looks familiar but I can't say for sure if I thought threw this. Looking at [the tests](https://github.com/tilt-dev/tilt/blob/master/internal/tiltfile/tiltfile_test.go#L4543:L5049) I don't see any that test this behavior, so it's probable that it wasn't considered.

I think it should be addressed, and I might be able to look at it this week.

**Comment by nicks** [comment]
looking into it
repro case: https://github.com/tilt-dev/tilt-example-html/blob/nicks/ch8127/2-recommended/Tiltfile
