### ISSUE TITLE
Changes to Tiltfile Config do not stop previously started services

### ISSUE THREAD

**Issue by andymartin-sch** [tilt-dev/tilt#3499]
I'm not sure if this should be considered a Tilt bug or not, but we use `set_enabled_resources` from https://docs.tilt.dev/tiltfile_config.html to selectively enable services from our helm charts. The problem is that when we try to _stop_ services that were previously enabled, Tilt doesn't actually stop those services (pods stay `Running`, etc).

This sort of intuitively makes sense, since changes to the Tiltfile Config trigger a Tiltfile re-execution and on that secondary execution Tilt has no way of really knowing that it should stop previously-launched pods/services, but it seems to go against the "user story" of https://docs.tilt.dev/tiltfile_config.html where people can select arbitrary sets of services to run without stopping everything and restarting.

In Slack, someone else mentioned:
> I've had similar issues with tilt_options.json . My guess is this really feeds back into the need for lifecycle hooks, but I think removing a service should (by default) destroy related resources. There is something to be said about unexpected side effects of doing such a thing, though

Potentially related: https://github.com/tilt-dev/tilt/issues/1699

This is not a critical/major issue, but it does come up as a developer QoL thing and it makes us more likely to come up with our own custom workflow down the road if more developers find this annoying.

**Comment by nicks** [comment]
also related to https://github.com/tilt-dev/tilt/issues/3137. I've always wanted a garbage collector so that when you remove resources from a tiltfile during a run, Tilt deletes any resources it deployed during that session.

**Comment by nicks** [comment]
I'm pretty sure this will get fixed in https://github.com/tilt-dev/tilt/pull/4700 in the next release

**Comment by andymartin-sch** [comment]
Yep thanks! This seems to be fixed in 0.21.1 - nice :)

**Comment by nicks** [comment]
:tada: :tada: :tada:
