### ISSUE TITLE
Specify path relative to (root) Tiltfile directory

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#3501]
Often times users will specify relative paths in API calls such as https://docs.tilt.dev/api.html#api.load and https://docs.tilt.dev/api.html#api.include. When these are called in files that are in deeply nested subdirectories, it will be messy to reference files, such as the Tiltfile, when it's in a different node of the subdirectory tree.

You might end up with scenarios such as: `../../../../../frontend/Tiltfile`.

There should be a way to specify the directory of the Tiltfile where Tilt was originally run. For example, Bazel uses `//`. We can use `//` to represent the directory of the Tiltfile.

**Comment by victorwuky** [comment]
@theothertomelliott: Is this what you are looking for?

**Comment by theothertomelliott** [comment]
That covers it nicely, thanks!

**Comment by landism** [comment]
[`config.main_dir`](https://docs.tilt.dev/api.html#modules.config.main_dir) is in the latest build and simplifies this situation

**Comment by theothertomelliott** [comment]
Great! This is a nice step forward for api.include, but unfortunately doesn't help with api.load (which would be our main use case). Due to this error:

```
first operand of load statement must be a string literal
```

I think this is something from the Starlark spec, so not sure if there would be a reasonable workaround.

**Comment by landism** [comment]
drats, sorry

**Comment by nicks** [comment]
I'm going to close this, given that 
1) we now have `config.main_dir` for determining the root Tiltfile directory
2) dynamic load paths are already covered by https://github.com/tilt-dev/tilt/issues/3433, so you can follow along there for when that gets fixed

yay!

**Comment by anuj-kosambi** [comment]
I don't know the current way to do this but I archived via extension repo 
```
v1alpha1.extension_repo(name = "name", url = "file://" + os.path.abspath(".") + "/relativepath")
v1alpha1.extension(name = "extname", repo_name = "repo_name", repo_path = "repo_path")
```

and
```
load("ext://extname", "...")
```
