### ISSUE TITLE
No resources found error

### ISSUE THREAD

**Issue by dealancer** [tilt-dev/tilt#3503]
Following error happens when  my script updates `.k8s.local.yml` file:

```
Successfully loaded Tiltfile (2.343401ms)
No resources found. Check out https://docs.tilt.dev/tutorial.html to get started!
```

My Tiltfile looks like this:

```
k8s_yaml('./.k8s.local.yml')

...
```

When I run `ahoy up` again everything works as expected.

Any ideas?

**Comment by landism** [comment]
Let me try giving my understanding of the problem to make sure we're on the same page:
1. you run `ahoy up` and it reads .k8s.local.yml and creates some non-zero number of resources, as expected
2. you run some script that edits .k8s.local.yml
3. tilt notices you changed .k8s.local.yml, reloads it, and decides that it no longer knows about any resources
4. you kill tilt
5. you run `ahoy up` again, without changing anything, and tilt is back to showing the expected resources

Is that accurate?

Hm, this isn't a lot to go on! I haven't heard of any bugs like this. A couple of ideas that come to mind:

1. What does `ahoy` do? Does the issue reproduce if you run `tilt up` directly?
2. I'd put a `local('cat .k8s.local.yml')` in the Tiltfile and compare check what gets output in the two cases

**Comment by dealancer** [comment]
@landism , correct, `ahoy up` is simply alias for `tilt up`.  `local('cat .k8s.local.yml')` did not help, showing the same error.

**Comment by landism** [comment]
> local('cat .k8s.local.yml') did not help, showing the same error.

Sorry, I didn't mean to imply it'd fix the error. I was suggesting checking to make sure it output the same text in both the case where things work and the case where they don't.

Would you mind sharing a Tilt [snapshot](https://docs.tilt.dev/snapshots.html)?

**Comment by dealancer** [comment]
@landism ,

It looks like I can not create a snapshot. I am seeing the following error message:

```
Error creating snapshot: posting snapshot failed. status: 500 Internal Server Error, response: error creating snapshot
```

**Comment by dealancer** [comment]
I noticed that when I use raw customize files everything works as expected:

```
k8s_yaml(kustomize('./manifests/kustomize.build/overlays/local'))
```

**Comment by landism** [comment]
can you add a `local('cat ./.k8s.local.yaml')` to your Tiltfile and share a log where Tilt prints .k8s.local.yaml and then says no resources found?

**Comment by dealancer** [comment]
I can not longer reproduce this issue, so I am closing it.
