### ISSUE TITLE
Tilt Cloud: Consider allowing the "time last seen" information to be turned off

### ISSUE THREAD

**Issue by andymartin-sch** [tilt-dev/tilt#3520]
One thing that came up in our team's discussion was that surfacing granular data around when each developer was last seen working can make people feel a little uneasy/creeped out/self conscious, even when the best intentions are presumed. This is particularly true in cases like ours where this is the first time we've ever used a "connected" tool like Tilt as a core part of our development workflow.

I don't think this is a huge deal and (so far) no one has objected to a degree where they'd prefer to not use Tilt at all because of it, but our team could not determine specific use cases for the "Last Tilt Check-In" functionality that outweighed the perceived costs.

We are definitely interesting in tracking analytics around the rollout of Tilt (ex: how the number of daily/weekly active Tilt users changes over time), but it seems like the "Last Tilt Check-In" dates are not the best way to look at & analyze this information anyway.

If opinions vary and other users *do* find this information useful, would it be possible to add a configuration option to not show it in the Tilt Cloud UI?

Note: Sorting based on "time last seen" would still be totally fine from our perspective.

**Comment by victorwuky** [comment]
@andymartin-sch : Thanks for the feedback. One of the purposes of this page (and Tilt Cloud broadly), is to allow DevEx engineers to triage problems that individuals are facing. Along with private team snapshots which allows the team owner to peak into a user's state, the idea here is to equip the team owner more context.

What would think about showing this type of information after a click, or even possibly in a separate flow? I.e. if someone sends you a snapshot, you could retrieve this type of information on demand. I'm not sure if you should "get permission" from the user. But that way it would be less creepy?

> We are definitely interesting in tracking analytics around the rollout of Tilt (ex: how the number of daily/weekly active Tilt users changes over time), but it seems like the "Last Tilt Check-In" dates are not the best way to look at & analyze this information anyway.

This makes sense to me, and perhaps aggregated statistics over time makes more sense.

**Comment by andymartin-sch** [comment]
> @andymartin-sch : Thanks for the feedback. One of the purposes of this page (and Tilt Cloud broadly), is to allow DevEx engineers to triage problems that individuals are facing. Along with private team snapshots which allows the team owner to peak into a user's state, the idea here is to equip the team owner more context.

Yeah I think we're in total agreement that this is a great goal. The issue is just that we couldn't really think of a specific type of problem that a developer might run into that could be solved (or significantly helped) by us knowing when a developer last ran Tilt.

(Attaching a timestamp to snapshots, noting users' Tilt Versions in the Tilt Cloud UI, etc - agree, there are tons of possibilities to surface really useful information.)

> What would think about showing this type of information after a click, or even possibly in a separate flow? I.e. if someone sends you a snapshot, you could retrieve this type of information on demand. I'm not sure if you should "get permission" from the user. But that way it would be less creepy?

Maybe it could just not be scaled up to be more granular than `today`/`yesterday`/`N days ago` or `this week`/`last week`/`N weeks ago`?

**Comment by victorwuky** [comment]
Hi @andymartin-sch . We changed this earlier to be less granular. Not sure if @jazzdan already let you know. He made the change. Thanks Dan! I'll go ahead and close this issue. Let us know if we can improve this further.

**Comment by andymartin-sch** [comment]
Thanks @victorwuky + @jazzdan ! 

Just to be clear, if you get many other users/customers asking for this or if someone thinks of specific scenarios where having more granularity would help with debugging, rolling this back is not a "deal breaker" for our use of Tilt.
