### ISSUE TITLE
Dont show local() commands

### ISSUE THREAD

**Issue by Co0ker** [tilt-dev/tilt#3528]
I am trying to display the beautiful output of the execution process (Tiltfile) and I really lack the ability to disable command execution logging in the local() function

**Comment by nicks** [comment]
Have you tried `local(cmd, quiet=True)`? or are you looking for something different?
https://docs.tilt.dev/api.html#api.local

**Comment by Co0ker** [comment]
Hi, @nicks 
quiet = True - removes the output of the command, but tilt still shows which command it executes. I would like tilt not to show the command that it executes

**Comment by nicks** [comment]
ah, gotcha, thanks!
