### ISSUE TITLE
[feature request] Resource Icons

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#3530]
Would be really nice to be able to specify a set of icons in the resource collapsed view, pulling from `@material-ui/icons` or the like.

**Comment by nicks** [comment]
Oooh, what do you mean? Like different icons to indicate that the resource is OK, Pending, Error? Or icons to indicate a "short" name for the resource? Something else?

**Comment by kevin-lindsay-1** [comment]
I was referring to the latter, but it would be neat to be able to define statuses as well, and assign icons to them.

Hard part would likely be the API for triggering specific statuses.

**Comment by nicks** [comment]
@hyu what do you think of this? I really love this idea, and even wonder if we could even auto-assign icons to resources based on intelligent guesses, similar to how vscode has extensions that do this:
https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme

This would help a lot for places like the left hand side of the logs pane, where names can be long and there's not a lot of screen real-estate.

**Comment by hyu** [comment]
@kevin-lindsay-1 and @nicks — I think this is a great idea! I'll add it to our design backlog so we can think through how to integrate these icons with our current Sidebar design.

**Comment by kevin-lindsay-1** [comment]
@hyu while that's being thought through, I'd like to [possibly tangentially] raise up a consideration for showing `deps` as well, possibly by inferring a rough order from which resources have dependencies.

I recognize that the current view might not be ideal for such a request, because you're basically trying to represent a Directed Acyclic Graph via one-dimensional set of points. My gut says a design accomodation could be to create collapsible groups for referenced `Tiltfile`s and possibly incorporate a light border between dependencies (A and B require C, order would be `C ; A, B`, and more complex orderings could be inferred from the dependency graph, allowing manual override for the picky). 

`Garden`'s attempt to make the dependency graph a literal graph is nice, but IMO it uses up a lot of screen real estate where you could introduce a visual design pattern to convey similar meaning. For example, perhaps if you highlight a particular resource, you could have two different highlighted colors on the other resources; one color for the selected resource's dependencies, another color for resources that depend said resource. This combined with an inferred order/grouping on dependencies would make it very clear _when_ in the deployment process things broke.
