### ISSUE TITLE
UI: Times in right hand bar are off by 1 minute

### ISSUE THREAD

**Issue by evanj** [tilt-dev/tilt#3533]
Somewhere it seems like the UI is displaying times `% 60` or maybe `- 60` (I'll bet somewhere it might be trying to show 1min x seconds but is only showing the seconds?). Here is a screenshot of a step that reported `DONE IN: 108.23s` but the side bar shows `48.2 s`. Attaching a screen shot.

Tilt version: `v0.15.1, built 2020-06-24`

<img width="1018" alt="Screen Shot 2020-07-01 at 11 10 59 AM" src="https://user-images.githubusercontent.com/675151/86261807-052f7300-bb8d-11ea-8c39-6776505090ba.png">

**Comment by nicks** [comment]
!

that's weird, lemme see if i can repro, hang on

**Comment by nicks** [comment]
ya, i can repro this

**Comment by evanj** [comment]
I am jealous that your builds are fast enough that you've never noticed this :)
