### ISSUE TITLE
Waits and rebuild if one image is used in several deployment

### ISSUE THREAD

**Issue by Co0ker** [tilt-dev/tilt#3538]
I have one image in several deployments (in one helm chart). Tilt waits for the completion of the assembly and deployment in the first deployment, and then instead of using the finished image, begins to reassemble it.

Used `custom_build` with `cloudbuild`
Version: `v0.15.1, built 2020-06-24`

I'm building a large system based on tilt (40+ microservices) and apparently this is the last problem that will help complete the project. Really looking forward to the answer)

**Comment by nicks** [comment]
@Co0ker Thanks for the report! This is basically the same as https://github.com/tilt-dev/tilt/issues/2992, can you :+1: that / follow up there?
