### ISSUE TITLE
add Homebrew as install option (if it's available)

### ISSUE THREAD

**Issue by zachvalenta** [tilt-dev/tilt#3539]
The README and the docs site recommend using curl to grab the `tilt` binary

* https://github.com/tilt-dev/tilt#install-tilt
* https://docs.tilt.dev/install.html#macos

But based on a few previous issues it seems like `tilt` is(was?) available via Homebrew.

* https://github.com/tilt-dev/tilt/issues/3078
* https://github.com/tilt-dev/tilt/issues/1155
* https://github.com/Homebrew/homebrew-core/pull/36309

When I search for it, however, it doesn't seem available:

```sh
$ brew search tilt

No formula or cask found for "tilt".

Closed pull requests:
tilt: add formula, v0.5.1 (https://github.com/Homebrew/homebrew-core/pull/36309)
Bump skylight from 1.7.0 to 2.0.0 (https://github.com/Homebrew/braumeister/pull/125)
Bump skylight from 1.6.1 to 1.7.0 (https://github.com/Homebrew/braumeister/pull/124)
doxygen: use Qt 5 (https://github.com/Homebrew/homebrew-core/pull/2861)
Added formula for libmonome (https://github.com/Homebrew/legacy-homebrew/pull/9273)
OSXey 1.2 (new formula) (https://github.com/Homebrew/legacy-homebrew/pull/29364)

```

Seems like, if brew is an option, it should be surfaced in the docs. And maybe an explanation for why not if it isn't.

Project looks great, btw.

**Comment by nicks** [comment]
Hi @zachvalenta ! I think you just need to scroll a little bit further down the page, it's here:
https://docs.tilt.dev/install.html#homebrew-macos

but don't worry! the install script checks to see if homebrew is available and uses it if it is:
https://github.com/tilt-dev/tilt/blob/master/scripts/install.sh#L31

**Comment by zachvalenta** [comment]
Aha! Gotcha. The script checking for Homebrew is very neat.

I don't think I've ever seen a project do it this way i.e. have multiple, non-colocated sections for the same os installation process. Not to say that approach is wrong, just unintuitive IMO.

Either way, great project and look forward to using it :)

**Comment by nicks** [comment]
:100:
