### ISSUE TITLE
Frequently getting "short read in readEvents()" on Windows

### ISSUE THREAD

**Issue by mnpenner** [tilt-dev/tilt#3556]
I'm getting this error a lot:

![](https://mpen.xyz/share/2020/07/phpstorm64_2020-07-06_23-35-12.png)

> Tilt has encountered a fatal error: short read in readEvents()  
> Once you fix this issue you'll need to restart Tilt. In the meantime feel free to browse through the UI.

I'm running Windows 10 Version 10.0.19042 Build 19042.  
Tilt v0.15.2, built 2020-07-02

I'm using PhpStorm as my IDE and Hg for version control. I thought maybe one of those was writing excessive files so I tried adding some of the temp files I'm aware of to `.tiltignore`:

```
**/*___jb_*___
**/hg-*
.hg
```

But that doesn't seem to help. 

Please let me know what else I can provide to help diagnose the issue.

**Comment by YoeriVD** [comment]
I get this consistently during startup (only on windows, running from powershell/cmd), but I haven't figured out why yet.

**Comment by nicks** [comment]
ok, i think i have a repro case for this. 

1) Go to https://github.com/tilt-dev/tilt-example-java/tree/master/4-recommended/src/main/resources/static with a unix terminal and run `touch file{1..1000}.txt`
2) Run `tilt up` under https://github.com/tilt-dev/tilt-example-java/tree/master/4-recommended

**Comment by nicks** [comment]
i think i have a fix but it takes some real Go/Windows syscall kungfu

**Comment by nicks** [comment]
This should be out in Tilt v0.17.0 :tada:
