### ISSUE TITLE
Ability to associate arbitrary URLs with a resource

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#3571]
Presumably, the user would pass an arg to `k8s_resource` to associate a URL with that resource.

Presumably that URL would show up on the top of the web UI where URLs show up today, though conceivably it could be somewhere else (e.g. as a free text field: #6157 -- the downside of this approach is that we have no good way of knowing whether the annotation is a link or not).

Depending on implementation, this may be more generic version of the behavior specified in https://github.com/tilt-dev/tilt/issues/2983.

**Comment by victorwuky** [comment]
cc @maiamcc 

@theothertomelliott: Feel free to thumbs this up if you want.

**Comment by theothertomelliott** [comment]
One possible complication is that a lot of our "landing page" endpoints for individual services include account ids or other variable elements. For most of our resources, we wouldn't be able to provide a hard-coded URL.

**Comment by nicks** [comment]
This is implemented as `k8s_resource(links=)`! https://docs.tilt.dev/accessing_resource_endpoints.html#arbitrary-links
