### ISSUE TITLE
Tilt Cloud: Override 404 error page to look like a Tilt Cloud page

### ISSUE THREAD

**Issue by andymartin-sch** [tilt-dev/tilt#3580]
(This is a minor, "nice to have" issue)

It would be nice if Tilt Cloud's "Snapshot" UI overrode the default 404 response to something that displayed a HTML-based webpage instead of returning a 404 response code with no content

For example, requesting [a snapshot link that's been deleted](https://cloud.tilt.dev/snapshot/AfynqO8Lv2Z86bYQqQ4=) leads to:
![img](https://i.imgur.com/ZTFjkNL.png)

Our users are technical enough to where they know what's going on, but it would be a more pleasing UX experience if the response were more Tilt Cloud-y

For example, https://github.com/asdfasdf-does-not-exist

**Comment by maiamcc** [comment]
Ooh good call, thanks for the report!
