### ISSUE TITLE
Tilt Lets You Configure Duplicate Resources

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt#3588]
The problem is neatly illustrated by this hypothetical unit test:

```golang
func TestK8sResourceSameNames(t *testing.T) {
	f := newFixture(t)
	defer f.TearDown()

	f.dockerfile("foo1/Dockerfile")
	f.yaml("foo1.yaml", deployment("foo", image("gcr.io/foo1"), namespace("ns1")))

	f.file("Tiltfile", `

k8s_yaml(['foo1.yaml', 'foo1.yaml'])
k8s_resource('foo:deployment:ns1', new_name='foo')
`)
	f.load()
}
```

Which results in:

```
--- FAIL: TestK8sResourceSameNames (0.01s)
    tiltfile_test.go:5329: k8s_resource at /tmp/TestK8sResourceSameNames097492016/Tiltfile:4:13 specified unknown resource "foo:deployment:ns2". known resources: foo:deployment:ns1:apps:0, foo:deployment:ns1:apps:1
```

It seems wrong that Tilt gives you a suggestion to help you configure a resource that is invalid in the first place. I'm not sure under which circumstances you'd want to do this, for example

```golang
func TestK8sResourceSameNames(t *testing.T) {
	f := newFixture(t)
	defer f.TearDown()

	f.dockerfile("foo1/Dockerfile")
	f.yaml("foo1.yaml", deployment("foo", image("gcr.io/foo1"), namespace("ns1")))

	f.file("Tiltfile", `

k8s_yaml(['foo1.yaml', 'foo1.yaml'])
k8s_resource('foo:deployment:ns1:apps:0', new_name='foo')
`)
	f.load()
}
```

This doesn't error.

If you were to actually apply this to a cluster there's no guarantee which of the duplicate resources would get applied, and as of recently duplicate resources is a warning anyways.

As a result I think specifying a k8s_resource for which there are multiple duplicate, matching selectors, should be an error and the above test should fail.

**Comment by nicks** [comment]
hmmmm...i thought @abdullahzameek just fixed this recently? https://github.com/tilt-dev/tilt/issues/1852
or is this issue different in some way?

**Comment by andymartin-sch** [comment]
We are still on v0.15.2 if that explains it?

**Comment by jazzdan** [comment]
I ran this test on master, so it might be different in some way. Let me dig in to it.

**Comment by jazzdan** [comment]
Yeah so @abdullahzameek @nicks both of these tests pass for me on master which seems wrong, or am I setting something up incorrectly?

```golang
func TestK8sResourceSameNames(t *testing.T) {
	f := newFixture(t)
	defer f.TearDown()

	f.dockerfile("foo1/Dockerfile")
	f.yaml("foo1.yaml", deployment("foo", image("gcr.io/foo1"), namespace("ns1")))

	f.file("Tiltfile", `

k8s_yaml(['foo1.yaml', 'foo1.yaml'])
`)
	f.load()
}

func TestK8sResourceSameNames2(t *testing.T) {
	f := newFixture(t)
	defer f.TearDown()

	f.dockerfile("foo1/Dockerfile")
	f.yaml("foo1.yaml", deployment("foo", image("gcr.io/foo1"), namespace("ns1")), deployment("foo", image("gcr.io/foo1"), namespace("ns1")))

	f.file("Tiltfile", `

k8s_yaml(['foo1.yaml'])
`)
	f.load()
}
```

**Comment by landism** [comment]
#1852 works by checking if the [k8s target's display name](https://github.com/tilt-dev/tilt/blob/8a9c4a42be82bcf003b60f068a0b25443c234e6b/internal/tiltfile/tiltfile_state.go#L1497) has more than 4 components (e.g., a :0 or :1 at the end)

The target's display name only computes a unique name within objects [attached to that k8s target](https://github.com/tilt-dev/tilt/blob/ccf6ca32aa9b15ee9233b919c8d652537ed24af0/internal/k8s/target.go#L49).

The unit test in #1852 puts all the duplicate yaml in a single resource, so the new warning triggers. Dan's unit test puts the duplicate yaml in different resource, so it doesn't.

**Comment by jazzdan** [comment]
@landism doesn't the second unit test there put the duplicate YAML in one resource?

**Comment by landism** [comment]
Nope! It defines two duplicate objects in one yaml file. Resource assembly doesn't care which file the objects are defined in. It just looks for any object with a workload and makes a resource out of it. You could throw a `f.assertNumManifests(1)` at the end of your test.

The only ways that come to mind to get duplicate objects *within* a resource are:
1. duplicate non-workload objects, so they end up in "uncategorized"
2. k8s_resource's objects arg (actually not sure if you can put workloads in this way)

**Comment by maiamcc** [comment]
Yeah just chiming in here as someone who reviewed @abdullahzameek's PR, I'm not aware of a reason we decided to make this case (duplicate k8s entities on the same resource) a warning rather than error, except "we don't think it's hurting anyone and we don't want to break anyone" -- @nicks is there context there I'm missing?

Given the case that @jazzdan brings up here (i.e. we probably shouldn't let users CONFIGURE a duplicate resource, given that we have no way to predict which one gets applied to the cluster), on top of the fact that it seems questionable to arbitrarily apply only one of a duplicate entity to the cluster, I think we should make the case of "user tried to apply more than one entity with the same name" an error (and check across _all_ entities, not just those in the same resource). Any objections?
