### ISSUE TITLE
local_resource 'cmd' and 'serve_cmd' run in different working directories when 'include()'-ed

### ISSUE THREAD

**Issue by NAlexPear** [tilt-dev/tilt#3602]
## The Bug:

When working with a `local_resource`, I'd expect `cmd` and `serve_cmd` to have the same working directory. Right now, `cmd`'s working directory is the directory in which its `Tiltfile` resides, and `serve_cmd`'s working directory is the directory where `tilt up` was called. I ran into this inconsistency while using a `Tiltfile` that `include`s a child `Tiltfile` that runs a `serve_cmd`-based `local_resource`.

[Here's a repro repo to see this behavior in action](https://github.com/NAlexPear/tilt-serve-cmd-repo). 

## Requested Solution:

It's not clear whether `cmd` or `serve_cmd` has the intended behavior, but they should almost certainly be the _same_ behavior. And it would be really nice for the purposes of `Tiltfile` composition if `serve_cmd` mirrored `cmd`'s current behavior of running in the same directory as its `Tiltfile`.

**Comment by landism** [comment]
Nice find. Thanks for the clear repro.

You're right that they should have the same behavior.

I'll change `serve_cmd` to match `cmd`, since `cmd`'s behavior is consistent with how other Tiltfile functions behave (e.g., `local`).

**Comment by landism** [comment]
A fix has been merged and will be in the next Tilt release. Thanks again!
