### ISSUE TITLE
[Feature Request] Debounce/Timing on watches

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#3606]
Sometimes I update my code while `tilt up` is running, and this triggers local resources to re-run. It would be nice to be able to configure an optional debounce period, so that the job is only executed after the files are not altered for an amount of time.

This would alleviate resources on queued re-runs, and potentially alleviate weird UI edge cases, wherein a resource's status is not correctly marked because it's been updated so much in such a short period of time that it seems to not know what state it's in anymore (I mainly see this occur with local resources).

Possible syntax for simplistic timing:
```
resource(
  'name',
  debounce=10000 # ms
)
```

---

Or a more complex syntax for keeping any timing-related features grouped, mainly in case other observables such as a `throttle` are requested:
```
resource(
  'name',
  timing={
   type: 'debounce', # rather than a "debounce" key, because operators such as 'debounce' and 'throttle' are likely mutually exclusive
   duration: 10000 # ms; maybe rename `value`?
  }
)
```

---

(Spitballing here) Depending on how far an observable-like pattern would be useful, you could perhaps just expose up an array of `operators` that are chained:
```
resource(
  'name',
  operators=[
  {
     type: 'debounce',
     value: 10000
  },
  {
    type: 'filter', # maybe a use-case?
    value: ...
  },
  ...
  ]
)
```
Personally, I think that if such a complex case as implementing a slew of observables is required, then it would likely be easier to find/create a utility library and offer up an API (if it doesn't already exist) for simply providing information on the state of the current job and allowing the user to define their own function that returns a boolean/enum for whether or not to re-run the job/resource.

**Comment by landism** [comment]
Thanks for the thoughtful write-up.

This is a problem we've tried to mitigate, both by having some built-in debouncing on all file watches, and by making local_resource builds mutually exclusive with all other builds. The latter can cost a lot of time in some cases, though, and it'd be nice to have another approach.

Debouncing sounds like a good way to provide users greater control to avoid some of these annoying rebuilds.

Might I ask what kind of process is generating file changes that need to be debounced? In some cases it's possible to move those into tilt local_resources so that nothing else builds while they're running, but there are obviously cases where that doesn't make sense.

**Comment by kevin-lindsay-1** [comment]
In my case I have local dependency install, some codegen, and then a build, while at the same time I have in the container `live_update` definitions in place which happens to duplicate a fair amount of that work, which in and of itself is not a big deal, but I've noticed that when a local build happens the docker build/live update can sometimes lag behind the local build, and if too many changes happen locally it ends up queueing inside the `k8s_resource`, placing things into a somewhat unknown state during that point.

It may be because `local`, `k8s`, and `live_update` resources/jobs are not treated the same from a debounce standpoint, and as a result can create weird timings.

My immediate thought when this desync would occur was "In my case, i'm only using tilt against a local k8s cluster, so speed is the primary concern; it would be nice if I could tell Tilt to not 'queue' resources and instead **cancel** running jobs if a new update shows up"

**Comment by Jackbennett** [comment]
Further to this it would be useful to have tilt terminate in-progress builds if it's growing a queue. 

as an example;

* node-update-check writes to package.json -> tilt starts building
* npm install --package-lock-only to update package-lock.json -> tilt queues a build immediately after the previous run. Just kill the previous image build.

It would be nice to avoid having to specify configs about what file should update when and why. A debounce, while useful in some context doesn't account for this behaviour unless it's debouncing as long as image build times. Which is too much.

Perhaps this could be default and docker_build could have `queue_builds=true` to return the build queue behaviour similar to gitlab https://docs.gitlab.com/ee/ci/yaml/#interruptible
