### ISSUE TITLE
install script incorrectly assumes amd64

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#3616]
A user reported the install script was broken for them on arm64.

```
if [[ "$OSTYPE" == "linux-gnu" ]]; then
      set -x
      curl -fsSL https://github.com/tilt-dev/tilt/releases/download/v$VERSION/tilt.$VERSION.linux.x86_64.tar.gz | tar -xzv tilt
```

This will install the x86_64 binary even if the host is arm64.

1. We should check arch as well. Maybe `uname -m`?
2. To support arm64, we need to add it to the [release config](https://github.com/tilt-dev/tilt/blob/master/.goreleaser.yml#L16)

**Comment by landism** [comment]
I spent a bit trying to test an arm64 build but the only test environment I could scrounge up was a docker container running arm64 via qemu.

I don't have a lot of faith in this as a test environment for validating arm64 builds:
1. It apparently happily executes both arm64 and amd64 binaries.
2. /proc/cpuinfo says "Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz"
3. When I try to run the arm64 binary with simply "./tilt", to get the help, I get this:
```
ERRO[0000] failure getting variant                       error="getCPUInfo for pattern: Cpu architecture: not found"
```
(though the help otherwise successfully renders)

**Comment by nicks** [comment]
have you considered adding arm64 to the release config with the _alpha suffix (like we did for Windows support) and see if anyone tries to download it?

**Comment by milas** [comment]
The install script was made arch-aware in #5050.
