### ISSUE TITLE
Use .dockerignore with prepended custom name when using custom named Dockerfile

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#3617]
From [Slack #tilt](https://kubernetes.slack.com/archives/CESBL84MV/p1595805784300600) 

> buildkit has a feature where if you use a custom-named Dockerfile it will look for a .dockerignore that is prepended with the name of the Dockerfile before falling back on the normal .dockerignore (so Dockerfile.test will cause it to look for Dockerfile.test.dockerignore). When I run a build manually with DOCKER_BUILDKIT=1 the build is successful, but the same build done by tilt seems to always use the .dockerignore with no prepended name.

**Comment by salim-runsafe** [comment]
I am the person who found the issue and put the message in slack. Just let me know what I can do to help.

**Comment by nicks** [comment]
i think this is a duplicate of https://github.com/tilt-dev/tilt/issues/3231 ?

**Comment by nicks** [comment]
ya, i just copied this comment there to make this easier to find. thanks for reporting! marking as dupe
