### ISSUE TITLE
[TILTFILE + BACKEND] Resource Grouping (MVP)

### ISSUE THREAD

**Issue by maiamcc** [tilt-dev/tilt#3643]
Offshoot of #3203 to discuss the Tiltfile + backend considerations of resource grouping in the sidebar and to track work. See the original ticket for some possible future consideration, but for the purposes of an MVP we're scoping work down to explicitly assigning resources to groups via the Tiltfile.

Team Tilt doesn't have bandwidth to implement this right now but we'd be excited to help a contributor(s) do it--comment here if you're interested!

This issue spans the implementation of Tiltfile syntax, piping that information through the engine, and making it available in the specified format in [the frontend state](https://github.com/tilt-dev/tilt/blob/022b45ca268da13c50d5dbc2c25755b6649e4331/web/src/HUD.tsx#L81). To discuss design/frontend considerations, see #3644, but @hyu and @smombartz will do the actual implementation.

### In scope:
1. Implement Tiltfile syntax for specifying resource group. Proposed syntax (via @KOGI):
    ```python
    resource_group(group_name: str, resource_names...: str)
    ```
2. Surface group information in [the frontend state](https://github.com/tilt-dev/tilt/blob/022b45ca268da13c50d5dbc2c25755b6649e4331/web/src/HUD.tsx#L81) in format (TODO: @hyu):
    ```
    TBD
    ```
    a. take group information set in Tiltfile and store in [`EngineState`](https://github.com/tilt-dev/tilt/blob/f9d466c5b4ed1517d1abdec9939918ad57306558/internal/store/engine_state.go#L25)
    b. update [webview proto schema](https://github.com/tilt-dev/tilt/blob/3a61a3feeff6f5da5828ad22557b7a6f4af8a0ed/pkg/webview/view.proto) with fields for group information requested above (use `make proto` to generate protobufs)
    c. [send group information from backend to frontend](https://github.com/tilt-dev/tilt/blob/8442eab153d73d56f49d173f88dd428abe84611c/internal/hud/webview/convert.go#L19)

### Out of scope:
1. Passing a group as a `resource_dep`
2. Nested groups
3. Passing a group as an arg to `resource_group`
4. Place remote Tiltfile in group a la `include('./services/A/Tiltfile', group='A')`
5. Override remote/imported Tiltfile groups (in the case of a shared dependency or a different slice of the architecture)

**Comment by landism** [comment]
This just shipped! docs here: https://docs.tilt.dev/tiltfile_concepts.html#resource-groups
