### ISSUE TITLE
[FRONTEND/DESIGN] Resource Grouping

### ISSUE THREAD

**Issue by maiamcc** [tilt-dev/tilt#3644]
Offshoot of #3203 to discuss frontend/design considerations of resource grouping in the sidebar. Feel free to discuss, kick around ideas, etc. -- @hyu and @smombartz will do the actual implementation.

**Comment by landism** [comment]
this just shipped! docs here: https://docs.tilt.dev/tiltfile_concepts.html#resource-groups
