### ISSUE TITLE
[Bug] Helm chart with pre-install, pre-upgrade hooks

### ISSUE THREAD

**Issue by apolegoshko** [tilt-dev/tilt#3651]
Hi there!

I've found a bug, but, please correct me if I'm wrong. 🐛 

I have made a very basic helm-chart which contains two resources: **Deployment** and **Job**. Object of a kind **job** have annotations `pre-install, pre-upgarde`. When I'm installing this helm chart via `helm install test-helm-chart . --namespace test` I see that job has created pod, which run some command (In my example it sleeps for 60 seconds) and after that, when job/pod completed, the deployment starting rolling out.

When I'm using the same helm chart in scope of Tiltfile with the same annotations, I see that job and deployment start together at the same time, while I'm expecting the same behaviour, that I described above. Interesting thing, that logs from deployment appears in tilt output after job been completed, but the behavior in cluster exactly not as expected. It creates job,deployment together, but from my perspective, it should work the same way, as I was ran `helm install ...` 

Output of a `tilt doctor`:

```bash
Tilt: v0.17.0, built 2020-07-31
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.40
- Builder: 2
---
Kubernetes
- Env: unknown
- Context: <hidden-context>
- Cluster Name: <hidden-context>
- Namespace: default
- Container Runtime: docker
- Version: v1.15.11-eks-af3caf
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: [redacted]
- Repo: [redacted]
```

Tiltfile itself:

```bash
# allow access to the elastic kubernetse services
allow_k8s_contexts('<hidden-context>')

k8s_yaml(helm('helm-chart', values='helm-chart/values.yaml', namespace='test'))
```

I've attached this very-very basic helm chart, which contains only 2 objects.

[helm-chart.tar.gz](https://github.com/tilt-dev/tilt/files/5011943/helm-chart.tar.gz)

Thanks in advance.

P.s. this is an example, but in real example this job should make useful work, f.e. run database migrations..

**Comment by jazzdan** [comment]
Expanding on what I said to @apolegoshko in k8s slack:

The `helm` built in in Tilt doesn’t run `helm install`, it runs `helm template`. I think you have two options moving forward:

1. Use `local` to run `helm install`. Downside here is then Tilt won’t know what was deployed, and you won’t be able to live update anything or see logs.
2. Tell Tilt that one resource (the deployment) depends on another resource (the job) with  the resource_deps parameter on k8s_resource . Then Tilt won’t try to deploy your deployment until the job has finished.

#2 definitely works and is the path I'd recommend for now.

However it _would_ be cool if the `helm` built in could parse your chart and configure those dependencies automatically.

**Comment by nicks** [comment]
as an aside, i wonder if we should bite the bullet and make the helm() built-in an extension, so that we can fix things like this without having to release a full version of tilt. e.g., a helm_local() extension.

I think the way I would implement this is something like:
1. run local('helm template ...') to get the yaml
2. parse the yaml with decode_yaml_stream
3. read the yaml annotations to figure out what the hook stages are
4. partition resources by hook stages with k8s_resource and resource_deps, to enforce order of resources

**Comment by apolegoshko** [comment]
The second option works for me. If you think this issue can be closed, feel free to do that.

**Comment by jazzdan** [comment]
I think we should leave this open until all of the problems that you've surfaced have their own issues. I'll try to do that later today. But in the meantime I'm glad we were able to get you unblocked!

**Comment by jazzdan** [comment]
I'm going to close this in favor of #3658 actually
