### ISSUE TITLE
parallel local resources

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3657]
Tilt generally doesn't parallelize local_resource builds, because they often read/write files and may not be able to be parallelized safely.

But many local resource jobs are read-only (e.g., a resource that runs `npm lint`, and can be safely parallelized). How do we support this?

A couple options I can think of:
- You can mark local_resource as read_only or safe_parallel, and it can be parallelized with anything
- Alternatively, make everything parallelizable, and have primitives in Tilt for reducing parallelization (like Airflow's pool API https://airflow.apache.org/docs/stable/concepts.html?highlight=pool#pools)
- a mix of the two? e.g., a parallelizable_with="all" or parallizable_with=["a", "b"]?

**Comment by landism** [comment]
I think we could safely reclaim most of the lost local_resource parallelization by reducing the current restriction to:
"file changes that occur while a local_resource is building will not cause any builds to start until that local_resource finishes".

Though, that's going further down the rabbit hole of it being hard to understand why something is/isn't building.

**Comment by nicks** [comment]
Hmmm...I'm not sure I follow? how would that address the problem where local resources fail cryptically because the artifact files they read are changing while they're building?

I feel like there's a lot of prior art here, both with the history of Makefile parallelization efforts, and the history of Blaze/Bazel/Buck/Pants genrules. Seems like where most projects land is on either (a) something very simple and easy to reason about, or (b) a more holistic sandboxing solution.

**Comment by landism** [comment]
> how would that address the problem where local resources fail cryptically because the artifact files they read are changing while they're building?

whoops, yeah, I was incorrectly focusing on protecting against a different issue. It doesn't.

**Comment by nicks** [comment]
One idea I was playing with is having an `output_files=...` where we let you list the output files that this rule is expected to write.

Then over time, we'd be able to add:
1) more intelligence to parallelize and order things
2) more intelligence to help you write the output_files rule correctly
which is similar to the evolution of genrule (which also tightened up over time)

**Comment by benjamin-wright** [comment]
Could you do something with the `depends_on` notation? Seems like there's potentially a bit of overlap, or at least that's where I first started looking.

**Comment by tmc** [comment]
I'd love to see some solution here even if kind of a hammer like safe_parallel -- for my use cases that would suffice.

**Comment by nicks** [comment]
i'm going to take a crack at a safe_parallel - which i think is a big hammer, but i think is what you want in most cases - and we'll see where that gets us
