### ISSUE TITLE
Provide a way to trigger/reload the main Tiltfile from the browser

### ISSUE THREAD

**Issue by KOGI** [tilt-dev/tilt#3662]
All other resources in the browser can be manually re-run with the ![image](https://user-images.githubusercontent.com/1231996/89341475-3bfa1c80-d656-11ea-804c-60459038c517.png) icon

It would be very helpful if we could do the same for the main Tiltfile, too

**Comment by nicks** [comment]
I think this is a duplicate of https://github.com/tilt-dev/tilt/issues/2957 ?

**Comment by jazzdan** [comment]
Yup, good call @nicks
