### ISSUE TITLE
Allow resource_deps to be used with helm_remote

### ISSUE THREAD

**Issue by CorentinWanteeed** [tilt-dev/tilt#3671]
Hello :)

I would like to use `resource_deps` with the `helm_remote` command like `k8s_resource`.

It is possible ? :)

Thank you for your work !

**Comment by jazzdan** [comment]
Hey @CorentinWanteeed, you could use `k8s_resource` to configure a resource that was created by `helm_remote` just as you would a resource that was created by, say, `k8s_yaml`. It would look something like this:

```starlark
load('ext://helm_remote', 'helm_remote')
helm_remote('myChartName')
# Assuming this creates a resource in the sidebar named 'myChartName', then we can configure it like so:
k8s_resource('myChartName', resource_deps=['myOtherResource'])
```

Does that work for you?

**Comment by CorentinWanteeed** [comment]
Amazing !

It works exactly as expected. Thank you.
Maybe a little advice : I went to https://docs.tilt.dev/resource_dependencies.html to search documentation about that (and using search bar with `dependancies`. Maybe a little paragraph on this page with your explanation will be very cool !

Thank a lot and have a nice day :)
