### ISSUE TITLE
[Bug] local_resource and docker_build.live_update.run commands do not respect dependency order

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#3676]
### Context

I'm using both `local_resource`s and `docker_build`s with `live_update`s, and I have the following steps defined:
```
...

# Generate k8s outputs
k8s_yaml(
  helmfile('k8s/helmfile.yaml')
)

# Build our docker container
docker_build(
  PROJECT_NAME,
  '.',
  dockerfile='docker/dockerfile',
  build_args={
    'node_env': 'development',
    'directory': '.'
  },
  entrypoint='yarn tilt:nodemon',
  live_update=[
    sync(
      './package.json',
      '/app/package.json'
    ),
    sync(
      './src',
      '/app/src'
    ),
    run(
      'yarn install',
      trigger=[
        './package.json'
      ]
    ),
    run(
      'yarn tilt:codegen',
      trigger=[
        './src/typeDefs'
      ]
    ),
    run(
      'yarn tilt:build',
      trigger=[
        './src'
      ]
    )
  ],
  ignore=[
    ...
  ]
)

###
# RESOURCES
###
# Install dependencies
YARN_DEPENDENCIES = create_namespaced_name('yarn_dependencies')
local_resource(
  YARN_DEPENDENCIES,
  cmd='yarn install',
  deps=[
    'package.json'
  ]
)

# Generate type definitions
CODEGEN = create_namespaced_name('codegen')
local_resource(
  CODEGEN,
  cmd='yarn tilt:codegen',
  deps=[
    './src/typeDefs'
  ],
  resource_deps=[
    YARN_DEPENDENCIES
  ]
)

# Run a build
BUILD = create_namespaced_name('build')
local_resource(
  BUILD,
  cmd='yarn tilt:build',
  deps=[
    './src'
  ],
  resource_deps=[
    CODEGEN
  ]
)

# Create k8s resource
k8s_resource(
  PROJECT_NAME,
  resource_deps=[
    YARN_DEPENDENCIES,
    BUILD
  ],
  objects=[
    ...
  ]
)
```

Note that the `k8s_resource` has dependencies on the `local_resource`.

### Expected behavior
I expect that when I update source code tilt will do the following:
1. run code generation _locally_ on my type definitions (graphql schema)
2. build _locally_
3. perform the defined live update commands on the docker container
4. if I alter code again before 3 is finished, either **cancel** the current steps, or postpend them to the current **queue**

### Actual behavior
When I update source code, it does not appear that the implied dependency between `live_update`s and `k8s_resource` dependencies are respected. In other words, it appears that the `k8s_resource` **initially** respects the dependency order, but the `live_update` doesn't.

They then become further and further out of sync as I update code (likely due to having separate queues), at a glance appearing that they might have some kind of implied (and incorrect) order between them, but that's hard to judge. Safest to assume from my perspective that `live_update` and `resource_deps` are not actually linked from a dependency ordering standpoint, and just sometimes appear that way.

I can think of use cases where I might want to ignore the dependency order implied via `k8s_resource`, but for the sake of DX I would think that respecting the implied order would be a reasonable default, which is why I labeled this as a bug, not a feature request.

**Comment by kevin-lindsay-1** [comment]
For the record, I've noticed this issue for a few weeks now, and it was pretty hard to even notice that it was happening, as it appears to be reliant upon the two separate job queues (local vs live update) to become out of sync.

It's certainly possible that something is happening under the hood that I'm not catching, so if the implied dependency is _supposed_ to work, then I can dig in and make sure it's not user error on my end.

**Comment by nicks** [comment]
Ya, that's correct, resource_deps only affect initialization order, and has no effect at all on live_update order. see:
https://docs.tilt.dev/resource_dependencies.html
https://github.com/tilt-dev/tilt/issues/3667

I think there's a couple interesting feature requests in here, most notably the ability to cancel an active live_update if there are other changes queued up in the dependencies.
