### ISSUE TITLE
too many resources in uncategorized

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3689]
When the uncategorized bucket has too many resources, the kubectl timeout will kick in and cancel the kubectl apply. There are a couple ways we could fix this:

1) Break up the kubectl apply calls to some max number of resources (say, 5 or even 1)
2) Move the kubectl apply stuff into tilt itself rather than shelling out
3) Make the timeout a function of the number of resources we're kubectl applying (i.e., more resources gives a longer timeout)

**Comment by maiamcc** [comment]
(In case anyone's not aware, there's currently an escape hatch for this: you can set the timeout via `[update_settings](https://tilt-dev.slack.com/archives/C014SMLKJN6/p1597246175006500?thread_ts=1597181931.003000&cid=C014SMLKJN6)` in your Tiltfile!)

**Comment by milas** [comment]
I think #3739 probably addressed this, as AFAICT all K8s resources are applied serially, one-at-a-time. Safe to close?

**Comment by lizzthabet** [comment]
since we haven't received any more reports on this issue in the past year, i'd say safe to close!
