### ISSUE TITLE
Image dependency cycle error when using custom base image

### ISSUE THREAD

**Issue by Tchoupinax** [tilt-dev/tilt#3713]
Hello,

It appears that Tilt does not love very much when my Dockerfile is based from a personal customized image.

In my Tiltfile, i use `docker_build_with_restart` command to reload the service when i save my files. This command targets a Dockerfile which starts like this:

```docker
FROM docker.registry.my-domain.com/my-project-base
```
Note: `docker.registry.my-domain.com/my-project-base` is an image i made and upload on my private docker registry.

When i launch tilt, it ends with these lines:

```
Successfully loaded Tiltfile (4.245542058s)
getting image build info for builder-api: Image dependency cycle: docker.registry.my-domain.com/my-project-base
```

(Normaly, my cluster has the correct right to access my registry. When i download directly the image with removing `docker_build_with_restart` paragraph, it works)

However, if i replace `FROM docker.registry.my-domain.com/my-project-base` with `FROM debian` image is built. I am wondering what is the issue with customized image.

Thank you for reading my issue and do not hesitate to ask me more details :)

**Comment by Tchoupinax** [comment]
It seems to work when i add the option `base_suffix`. I think the `-base` in my image comes into conflict with the default suffix which also equals `-base`.

Someone can confirm ? ^^

**Comment by maiamcc** [comment]
@Tchoupinax yep, that sounds right -- that's why we provide the `base_suffix` option, so you can change image naming if Tilt's image naming conflicts with your image naming.

It looks like your problem is resolved, is that right? Lmk if you're still having problems.

**Comment by Tchoupinax** [comment]
Yeah it is resolved :) I just wanted to have an overview.
Thank you for your answer :)

I close this issue.
