### ISSUE TITLE
Can I develop using remote k8s but building with remote Docker, like when using minikube?

### ISSUE THREAD

**Issue by lghamie** [tilt-dev/tilt#3728]
Hey there, I'm using a remote k8s cluster, and would like to be able to build the docker image in the cluster itself.

Is there any possibility to do that? What should I configure?

One of the reasons for this is that some of the layers generated when building are very large, because of npm, and since the cluster is remote, uploading them takes super long. 

Being able to just ship all the code and building the docker image remotely, like when using minikube, would allow me to do all the npm install related stuff on the same server.

Thanks!

**Comment by landism** [comment]
Yep, this is possible! It can be a bit tricky in practice.

[These docs](https://docs.tilt.dev/local_vs_remote.html#remote-builds) describe the current status.

**Comment by landism** [comment]
I'm going to close this as answered, and if you want to dig into specific approaches, we can do that here, in a new issue, in a meeting ("schedule a meeting link" in the docs linked above) or on [Slack](https://tilt.dev/contact).
