### ISSUE TITLE
Tilt rebuilds docker image when file in 'sync' path is touched, rather than live_updating.

### ISSUE THREAD

**Issue by boyd-bit-io** [tilt-dev/tilt#3730]
Having issues with live_update rebuilding instead of syncing a file change; I've read the relevant docs a few times and can't figure out what I'm doing wrong.

I change the file services/webapp/foo/bar.py and expect a live update, but instead there's a full docker rebuild.
```
1 File Changed: [/Users/mdb/src/REPO/services/webapp/foo/bar.py] • q-django-core-chart
Will not perform Live Update because:
	Found file(s) not matching any sync (files: /Users/mdb/src/REPO/services/webapp/foo/bar.py)
Falling back to a full image build + deploy
```

Tiltfile location: /Users/mdb/src/REPO/Tiltfile

Tiltfile snippet:
```
docker_build(
  'django-core',
  'services/webapp',
  dockerfile='services/webapp/Dockerfile',
  live_update=[
    fall_back_on(['services/webapp/run.sh','services/webapp/django_services/settings.py']),
    sync('./services/webapp', '/src/'),
  ])
```

My understanding is that the docker_build context path is relative to the Tiltfile directory, and the first argument to 'sync' is also relative to the Tiltfile directory.

I tried modifying the docker build context to also be at the root of the repository, instead of 'services/webapp', but then nothing would happen if I changed the same file (`services/webapp/foo/bar.py`).
I've tried a few other path permutations but haven't gotten anything to work.

Tilt doctor:
```
Tilt: v0.15.1, built 2020-06-24
System: darwin-amd64
---
Docker (cluster)
- Host: tcp://192.168.64.14:2376
- Version: 1.40
- Builder: 2
---
Docker (local)
- Host: [default]
- Version: 1.40
- Builder: 2
---
Kubernetes
- Env: minikube
- Context: minikube-dev-mdb-Madelaines-MBP.localdomain
- Cluster Name: minikube-dev-mdb-Madelaines-MBP.localdomain
- Namespace: default
- Container Runtime: docker
- Version: v1.18.3
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗
The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
- User Mode: opt-in
- Machine: d98b64728a82a66c0ac94b7062ecbc2d
- Repo: BIU2Fsug9j4BXswD0uPV1g==
```

Any tips?

**Comment by boyd-bit-io** [comment]
I've also tried changing the build context to the repository root, using 'ignore' to narrow down to a subfolder.

However, now the container doesn't update at *all* when a file within that subfolder changes. 

```
docker_build(
  'django-core',
  '.',
  dockerfile='services/webapp/Dockerfile',
  ignore=['*', '!services/webapp/**/*'],
  live_update=[
    # Relative to tiltfile location.
    sync('services/webapp', '/src/'),
  ])
```
I'm assuming this is due to improper 'ignore' paths (since `['*', '!*']` will reload the container when any file is touched), but no path/glob format I've tried works as I want it to.
```
'!services/webapp/**/*'
'!services/webapp/*'
'!services/webapp'
```

**Comment by boyd-bit-io** [comment]
Downgrading to Tilt 17.0 fixes this issue.

**Comment by boyd-bit-io** [comment]
Going back to 0.17.2, the bug no longer reproduces, which makes me think this was related to bad minikube state (if `minikube delete` is what actually fixed it)

Closing issue for now; will reopen if this recurs and I can get a reliable repro.

**Comment by landism** [comment]
I'm glad you're no longer seeing the problem!

> makes me think this was related to bad minikube state

I think this is Tilt's fault rather than minikube's.

From the log snippets, it looks like Tilt wasn't recognizing `/Users/mdb/src/REPO` as a base dir for the django-core image. When Tilt logs changed file paths, it makes them relative to the base dir if possible, rather than any absolute path, e.g.:

```
      fortune │ 1 File Changed: [webapp/foo.yaml] • webapp
      fortune │ Will not perform Live Update because:
      fortune │       Found file(s) not matching any sync for webapp (files: foo.yaml)
      fortune │ Falling back to a full image build + deploy
```

If you run into this again, would you mind grabbing the output of this?
`tilt dump engine | jq '.ManifestTargets["q-django-core-chart"].Manifest.ImageTargets[].BuildDetails.BuildPath'`

**Comment by boyd-bit-io** [comment]
Hitting it again.
```
ℳ   tilt dump engine | jq '.ManifestTargets["q-django-core-chart"].Manifest.ImageTargets[].BuildDetails.BuildPath'


"/Users/mdb/src/REPO"
"/Users/mdb/src/REPO"
"/Users/mdb/src/REPO/services/webapp"
"/Users/mdb/src/REPO/services/webapp"
```

**Comment by nicks** [comment]
from Matt's comment above, it looks there's some sort of confusion between REPO/webapp/foo.yaml and REPO/services/webapp/foo.yaml ?

would it be possible to mail the full tilt engine dump to nick@tilt.dev ?

**Comment by nicks** [comment]
(i think the key here is going to be trying to narrow down an isolated repro case, since we have not been able to repro this issue independently)

**Comment by boyd-bit-io** [comment]
The issue seemed to be introducing an intermediate docker container. The intermediate dockerfile contained the 'COPY . .', and the final dockerfile, which was based on the intermediate dockerfile, didn't copy files, instead running some intermediate scripts. Removing the intermediate dockerfile and putting hte 'copy . .' logic back in the final dockerfile appears to have fixed the issue for us, for now.

**Comment by boyd-bit-io** [comment]
Update: the issue is recurring for me even after removing the intermediate dockerfile.

Myself and a colleague have the same Tiltfile, minikube version, docker version, and tilt version, and my colleague is not seeing the issue. 

I will email a tilt engine dump.

**Comment by boyd-bit-io** [comment]
One potentially interesting difference:

For my containers, which fully rebuilt, it said
```
Build finished:
  Reason: Changed Files | Dependency Updated
```
whereas for my colleague, for whom live_update was working, it said
```
Build finished:
  Reason: Changed Files
```

**Comment by nicks** [comment]
Thanks for the engine dump! Ya, I suspect this might have to do with the way the base image context overlaps with the image context that you're trying to live-update, and wonder if there's something weird and non-deterministic happening

**Comment by boyd-bit-io** [comment]
Do you have any recommendations for workarounds? Make all image contexts start from the same root path?

**Comment by nicks** [comment]
I don't think we have any recommendations yet. 

Just calling out a detail that might be a necessary condition to come up with a repro case. 

I tried a couple different things and haven't been able to reduce a repro case. : \

Do you have any idea what might be different between your colleague's machine and yours? OS?

**Comment by nicks** [comment]
I'm like 75% sure that I know what the problem is!

On MacOS, filesystems are case-insensitive, and there's some arcane logic to decide which casing of the path it gives you. So  "/Users/mdb/src/REPO" and "/Users/mdb/src/repo" are the same directory. The engine dump you sent me has different capitalizations, and I suspect something is treating them as different directories

**Comment by boyd-bit-io** [comment]
I think you're right.

```
mdb at Madelaines-MBP in ~/src/repo 
ℳ   tilt up
Tilt started on http://localhost:10350/
v0.17.4, built 2020-09-03

(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
```
live_update doesn't work.

```
mdb at Madelaines-MBP in ~/src/repo
ℳ   cd ../REPO

mdb at Madelaines-MBP in ~/src/REPO
ℳ   tilt up
Tilt started on http://localhost:10350/
v0.17.4, built 2020-09-03

(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
```
Live_update works now.

**Comment by boyd-bit-io** [comment]
Can confirm issue does not reproduce on tilt 1.17.7
