### ISSUE TITLE
make resource settings editable in the Tiltfile

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#3738]
### Problem

If my Tiltfile loads another Tiltfile (or extension), and the loaded Tiltfile declares a resource, I can't change that resource's options (e.g., add objects to it or rename it or make it manually triggered). The only recourse is to change the loaded Tiltfile (or extension) to be more parameterized and plumb through whatever settings I want to configure.

The concrete use case that inspired this issue is that KOGI wants to [add more objects to a k8s_resource created by an extension](https://github.com/tilt-dev/tilt/issues/3714#issuecomment-677941174)

### Proposal

Make it possible to edit resource's options. This would allow me to load an extension that defines a resource and then change that resource's options, without having to edit the extension and get a PR merged.

### Implementations

The main options that come to my mind are:

* Make all `*_resource` parameters optional
* Expose resource settings as starlark values
* Do something like the golang [functional options pattern](https://www.sohamkamani.com/golang/options-pattern/) and have builtins for resource options and a builtin for adding options to a resource

#### Make all `*_resource` arguments optional

i.e., change their type to `Union[T, None]`.
When a `_resource` function is called, if there are existing settings, merge any non-`None` args with those existing settings.

Cons:
* This feels like it'd make the API pretty messy and complicated.

#### Expose resource settings as starlark values

e.g., `resource_options['servantes'].objects.append('foobar')`

Cons:
* We don't currently have a way to track usage of starlark values, so we'd lose visibility into which options are being used.

#### Functional Options Pattern

e.g., `resource_options['servantes'].options.append(resource_objects('foobar'))

Cons:
* feels verbose. might be fixable.

Note: As written, of the three only the "starlark values" one allows modifying the values of existing options (e.g., add to the list of objects in a k8s resource or mutate a local_resource's cmd, rather than replace)

**Comment by KOGI** [comment]
Personally, (without knowing what affects it would have on the backend), I like option #1 the best. From the user's perspective, it definitely feels the cleanest and most understandable.

If you're worried about it blowing out the complexity of the API, maybe there could be a separate function for amending resources after they're created:
```python
k8s_resource('foo')
amend_resource('foo', objects=[...], new_name='bar', ...)
```

**Comment by KOGI** [comment]
Any movement on this at all? Thoughts about path forward?

**Comment by nicks** [comment]
I don't see any good reason why k8s_resource can't be additive

k8s_resource('foo', objects=['object1'])
k8s_resource('foo', objects=['object2'])

Similar to how k8s_yaml and most of our settings calls work, where you can call them multiple times.

I don't think it's a good idea to allow the ability to read the options from previous k8s_resource calls, since i think that gets us further away from declarative programming and weird order of operations bugs

**Comment by landism** [comment]
> I don't see any good reason why k8s_resource can't be additive
> Similar to how k8s_yaml and most of our settings calls work, where you can call them multiple times.

I don't think I did a good job of explaining my issue with additive k8s_resource in the first post, so just to ensure we've distinguish between "you understand the reason and it isn't good enough to block" and "the reason in my head isn't in your head" - my main hesitations (which isn't to say blockers, but, rather, the things keeping me from saying "yes this is obviously the path forward") are:
1. Documenting this using python conventions feels awkward. It's true that our existing settings calls have been following this pattern in implementation, but the behavior is not in our docs at all! It seems like we'd need to change all default arg values to 'None', all arg types to `Union[T,None]` and wrap all arg with like "if not None, updates the setting to...default setting is..."? Or give up on python doc conventions (like, don't change the documented types or default values and just add a note saying you can re-call the function and set args you don't want to update to `None`), or leave the behavior undocumented.
2. This pattern leaves the user able to append to the list of objects, but not clear or replace. Ditto for port forwards, resource deps, pod selectors. Our settings calls don't have list types, so this hasn't come up. Maybe we just accept that limitation and hope it isn't a thing people want to do often.

**Comment by KOGI** [comment]
A couple other options:
1. introduce new args like `additional_objects` and `additional_port_forwards` when you want to add to the list
2. allow a special char/symbol for adding (and possibly removing values):
    `objects=['+', 'anotherA', 'anotherB']`
    or
    `objects=['+anotherA', '+anotherB', '-originalX']`
3. introduce a new function (in the same spirit as `sync()`, `run()`, and `fall_back_on()`) to the effect of `append_config()`:
    `objects=append_config('anotherA', 'anotherB')`
    or
    `objects=remove_config('originalX')`
    The above allows addition and removal while still satisfying @nicks (valid) opinion that reading of existing values shouldn't be allowed.
