### ISSUE TITLE
Separation of service logs, status, search and filter logs

### ISSUE THREAD

**Issue by jerrythomas** [tilt-dev/tilt#3744]
I was trying to set up a cluster which includes a Cassandra backend cluster and the logs from the Cassandra cluster filled up the log screen. I was wondering if some of the following can be considered as feature requests?

- [ ] Additional tab for cluster components (pods services etc) 
- [ ] It would be great if the Tilt/Kubernetes execution logs can be separated from the container logs. A list of services and the logs from each it would help in finding some runtime issues v/s issues with `Tilt/Kubernetes` related issues.
- [ ] Support for search and filter on the logs would also be helpful. For example, the streamed logs are sometimes JSON objects and filtering by `"level"="error"` could be helpful.

**Comment by victorwuky** [comment]
Great thanks for the issue @jerrythomas . These all seem like great ideas. Do you mind separating them into three separate issues. That'll especially help other folks be able to dig in further, chat about specifics, and hopefully popular ideas will be implemented sooner. 😄

**Comment by milas** [comment]
Closing this issue - the new Tilt UI has a separate `(Tiltfile)` resource where Tilt logs go, and each resource has its own section for its container logs. Additionally, it supports searching and filtering, including regex support. Thanks for the suggestions, feedback like this helped drive the redesign!
