### ISSUE TITLE
[Feature request] Declare resource as optional, allow skipping in UI

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#3756]
So I typically have `local_resource`s for things like yarn installation, codegen and builds, but I also have pretty much the exact same jobs running in `live_update`, so after the first initial run, it would be nice to be able to skip those jobs automatically on updates, but optionally.

For example, let's say I update the `local_resource` `build`'s `deps`, the `./src` directory.

I would like to be able to do the following:

1. Define that job as `run once`
2. Define that job as `optional` after the first job
3. On demand in the UI (no declarative changes in code), click a check box or something for that resource, and have it run on successive changes to that directory

This would mainly be useful for flexibility in workflow, as right now I can do most of those, but it requires me to update config (or worse, the tiltfile), rather than simply being part of the workflow in the UI.

**Comment by victorwuky** [comment]
Thanks @kevin-lindsay-1. So essentially turn on/off resources in the UI, but the Tiltfile sets the default?

**Comment by kevin-lindsay-1** [comment]
Yes, via declaring a resource as optional, as well as being able to declare that a job should be ran once and watched, but only watched once specifically enabled.
