### ISSUE TITLE
live updates fail when container isn't ready

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3759]
1) Take any app with live-update. Here's a good example:
https://github.com/tilt-dev/tilt-example-html/tree/nicks/liveupdatepending/2-recommended

2) Insert a runtime delay to container readiness. Any delay is fine. This commit adds an init container that sleeps for 10 sec
https://github.com/tilt-dev/tilt-example-html/commit/108c6ad23e392d24d6299f34698396c71f19aa01

3) Try to live update

Expected result:
The live update should wait for the container to be ready, then live-update it

Actual result:
The live update fails, and we fall back to a full image deploy

This is a particularly awful experience for teams on remote clusters where e.g., they have to provision a new node at runtime. The user has to remember not to run live update during this period, or the whole runtime process will start over

**Comment by nicks** [comment]
here's a snapshot of what this looks like:
https://cloud.tilt.dev/snapshot/Aaqfv_ULmsgTAzqABg0=

**Comment by victorwuky** [comment]
cc @joseph-zhong

**Comment by nicks** [comment]
should be fixed in v0.17.5
