### ISSUE TITLE
Tilt kubernetes object selector should allow escaping for ':' in resource name

### ISSUE THREAD

**Issue by detiber** [tilt-dev/tilt#3761]
Currently it is not possible to reference a resource using the tilt-specific kubernetes object selector if that resource has a name with a ':' in it.

For example, if using the helm_remote extension to deploy cert-manager, it is not possible to group a subset of the created roles and clusterroles created as part of a k8s_resource.

Example of the created roles/clusterroles that exhibit this behavior:
```
     → cert-manager-cainjector:leaderelection:role
     → cert-manager:leaderelection:role
     → cert-manager-webhook:dynamic-serving:role
     → cert-manager-cainjector:leaderelection:rolebinding
     → cert-manager:leaderelection:rolebinding
     → cert-manager-webhook:dynamic-serving:rolebinding
```

**Comment by nicks** [comment]
should be fixed in v0.17.5
