### ISSUE TITLE
"What we have in store" on tlit.dev fades too early

### ISSUE THREAD

**Issue by mpokryva** [tilt-dev/tilt#3778]
Hi there, small UX bug to report. On tilt.dev, when I scroll to the limit in the "What we have in store" section, the last item is still quite faded and difficult to read. Thanks for building a great tool!

![image](https://user-images.githubusercontent.com/14366106/93221867-40792100-f73c-11ea-9930-bd4c9585d15f.png)

**Comment by victorwuky** [comment]
Thanks @mpokryva for the report. See https://github.com/tilt-dev/tilt.build/pull/740.
