### ISSUE TITLE
docker_build_with_restart fails for multi-container kubernetes deployment

### ISSUE THREAD

**Issue by viharm91** [tilt-dev/tilt#3790]
Use Case: Kubernetes Deployment has multiple containers in it, and also has different entrypoints. 
docker_build_with_restart entrypoint doesn't have any functionality to specify entrypoint for each relevant container. Tilt assumes all containers has a single entrypoint.
It works fine with single container kubernetes deployment.

**Comment by nicks** [comment]
thanks for filing!

ya, we had some discussion on this in the slack channel. docker_build_with_restart is intended to be a generic solution for the  simple use case.

If you have more complex needs (like running multiple containers of the same image with different entrypoints), your best bet is to use a more full-featured yaml templating tool to inject restart entrypoints into the containers you need them for, and not use docker_build_with_restart at all.

I've thought about adding a system like

```
docker_build(..., entrypoint=(switch(condition(x, 'x-entrypoint'), condition(y, 'y-entrypoint'), default('z-entrypoint')))
```

but that starts to get into the realm of trying to design a bespoke yaml templating sytem within Tilt, which seems bad for the ecosystem overall. if possible, we'd rather encourage people to use Helm, and make sure Tilt interoperates well with helm.

**Comment by maiamcc** [comment]
Just jumping in here to say that we DO support different _args_ per container -- that is, by default, the `entrypoint` value only overrides the `command` specified in Kubernetes YAML and NOT the `args`. If you want to call two completely different commands, we don't support that well, but say you have Kubernetes YAML that looks like this:
```
spec:
  containers:
  - name: container1
    command: ["/path/to/bin", "--flag1"]
  - name: container2
    command: ["/path/to/bin", "--flag2"]
```
The `entrypoint` arg in the Tiltfile will override the contents of `command`, making both of these containers run the same thing. However, you can fix the problem like so:
```
```
spec:
  containers:
  - name: container1
    command: ["/path/to/bin"]
    args: ["--flag1"]
  - name: container2
    command: ["/path/to/bin"]
    args: ["--flag2"]
```
since the `entrypoint` Tiltfile param leaves the `args` field untouched.

Does that solve your problem? Or are you running two different _commands_ (rather than the same command with different args)?

**Comment by viharm91** [comment]
We merged both containers and made it a single container, so we don't need that use case any more.
Thanks for checking the issue and providing additional information.

Closing it based on comments from @nicks @maiamcc .
