### ISSUE TITLE
clusterctl for local dev clusters

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3794]
Background:
We (tilt-team) spend a lot of time spinning up different configurations of local dev clusters. In particular:

- Making sure an app works on different cluster types (kind, minikube, k3d, docker-for-desktop, microk8s)
- Making sure the cluster has the right resource allocation (CPU, memory)
- Setting up a local registry to push/pull images from, such that the registry doesn't require special creds, and keeps the images cached when you reset the cluster
- Setting up persistent storage, so that the storage sticks around when you reset the cluster. Or you can even commit the storage data into source control
- Iterating on ingresses and other networking configurations, and testing them locally.

We already have a bunch of docs on this, and are working on more:
https://github.com/tilt-dev/kind-local
https://github.com/tilt-dev/minikube-local
https://github.com/tilt-dev/k3d-local
https://docs.tilt.dev/choosing_clusters.html

I would like to move towards a world where we have a single CLI for encoding this knowledge, and making it easier for other dev teams to leverage. 

A good start would just be something that lists all the local clusters (since I often forget I'm running one :joy:)

I don't think this necessarily needs to be part of Tilt itself (yet), but it might be eventually

**Comment by jaredallard** [comment]
:wave:

Not sure if this makes sense, but for cluster configurations I've noticed that all the recommended options (excluding the not cross-platform Docker for X option) are running a local docker registry. Has it been considered trying to use something like [k3s using host docker](https://github.com/jaredallard/k3s-docker-for-mac) for image cache sharing? Of course there is overhead and some stitching needed to get it working, but it's pretty powerful having those be shared.

Sorta off-topic, so feel free to move or something else, but seemed tangentially related 😆

**Comment by nicks** [comment]
:wave: 

Ya, this is something we've been talking about a lot lately! @ellenkorbes is making a video on it :grin: 

We've found that with the one-piece clusters (where you run K8s and build Docker images with the same Docker daemon), the clusters have lots of stability issues, and need to be reset frequently.

We generally recommend a separate registry because it's a lot more robust. You can use different builders if you need them. If you do need to reset your cluster, the image cache persists. I think the trick is getting the ergonomics right, so you don't necessarily need to think about the way that those are separate pieces interact all the time. (which I'm hoping this tool would help with)

**Comment by nicks** [comment]
This is now implemented! https://ctlptl.dev/
