### ISSUE TITLE
tilt logs -n to specify number of lines

### ISSUE THREAD

**Issue by maiamcc** [tilt-dev/tilt#3797]
From a user in #tilt:
> one thing that might be nice is a `-n` option. so you could print a certain number of lines back. eg. `tilt logs -n 1000 web-frontend | grep foo`

**Comment by maiamcc** [comment]
Probably won't do this anytime soon: as a workaround `tilt logs | tail -n 50`

**Comment by alanchrt** [comment]
@maiamcc I think the main issue with piping to `tail` is that you still can't get _more_ than the default number of lines. Cutting to a shorter number isn't my primary use case, personally.
