### ISSUE TITLE
Port forward links missing in 0.17.7

### ISSUE THREAD

**Issue by theothertomelliott** [tilt-dev/tilt#3832]
After upgrading to 0.17.7, I'm seeing that port forward links for my k8s_resources have disappeared.

Our port forwards are defined using the `port_forwards=["local_port:k8s_port"]` format.

**Comment by maiamcc** [comment]
Investigating!

**Comment by maiamcc** [comment]
Can't repro, seems to have been an issue with switching versions and the browser catching up/accessing the correct version of the JS. Closing this!
