### ISSUE TITLE
tilt does not delete resources when deployed to a remote cluster

### ISSUE THREAD

**Issue by abatilo** [tilt-dev/tilt#3841]
When using an alternative `default_registry()` and a remote Kubernetes context, running `tilt down` doesn't actually delete any resources. Using a local `kind` cluster works as expected.

Tilt version:
```
v0.17.7, built 2020-10-05
```

EKS version:
```
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by victorwuky** [comment]
Thanks @abatilo . I've marked this as a bug issue.

**Comment by nicks** [comment]
Thanks for reporting! That's alarming!

We have many users who use a remote cluster (including EKS), and this is the first I've ever heard of this.

When you run `tilt down`, what do you see? does it print something like:

Deleting via kubectl:
→ Deployment/my-deployment-1
→ Deployment/my-deployment-2

does deleting those resources manually with `kubectl delete` work?

(trying to think of what could be different about your environment that would cause this issue :thinking: )

**Comment by abatilo** [comment]
I'm a fool. My deepest apologies @victorwuky and @nicks .

I didn't set `tilt down --context $CONTEXT` correctly when I was doing things on the remote cluster.

Again, very sorry. Closing this issue.

**Comment by victorwuky** [comment]
Not a problem @abatilo . Thanks for using Tilt and engaging the community here. Do continue raising issues as you see fit.
