### ISSUE TITLE
Predictable tag names

### ISSUE THREAD

**Issue by Richard87** [tilt-dev/tilt#3849]
Hi!

Im running the development environment on GKE, and am pushing all images there immediately. 

But it would be lovely and help with deployment to product ion if the tag names used during development where predictable. Then I could speed up building the produxtion image with the latest image in cache... 

Skaffolds default way of doing it is great, tag it with the latest git commit, and includes -dirty if any of the files have been changed. 

For eksample image:xyz123 and image:xyz123-dirty

**Comment by victorwuky** [comment]
Hey there. Would `extra_tag` in https://docs.tilt.dev/api.html#api.docker_build or `tag` in https://docs.tilt.dev/custom_build.html help with your use case?

**Comment by Richard87** [comment]
I'm not sure, I read another issue that the extra tag was not pushed to the repo, but that might be fixed.

Anyhow, I didn't figure out how to get information from the local git repo?

**Comment by nicks** [comment]
You can get the information from the local git repo by adding this to your tilfile:

```
commit = str(local('git rev-list -1 HEAD --abbrev-commit').strip()
```

I've definitely worked with teams who use this approach + extra_tags + local_resource to wire together a solution for pushing images for cache re-use. I see this feature request as a possible implementation of https://github.com/tilt-dev/tilt/issues/3629, though I think we want a solution that requires less manual wiring

**Comment by Richard87** [comment]
Thanks! That solves my issue :D
