### ISSUE TITLE
Tilt does not work over https

### ISSUE THREAD

**Issue by ZacxDev** [tilt-dev/tilt#3863]
Loading tilt over https will cause tilt to attempt to connect to an insecure websocket which will be blocked by the browser due to mixed content.  I've been monkey-patching this by putting in a breakpoint before the websocket connection happens and changing the url, but that is obviously not ideal.

The websocket url is created here:

https://github.com/tilt-dev/tilt/blob/c1c2def7433fb7884f219684f698beeec21dff4e/web/src/PathBuilder.tsx#L17

This is likely a super easy fix, but I don't have a tilt environment setup so I won't get to this until I can find some time to set everything up correctly.  If someone could take a look before then, it would be much appreciated!

**Comment by nicks** [comment]
out of curiosity...how/why are you running tilt over https?

ya, it should be as easy as changing ws:// to wss://

**Comment by ZacxDev** [comment]
> out of curiosity...how/why are you running tilt over https?
> 
> ya, it should be as easy as changing ws:// to wss://

Our cluster has gotten very large/resource-intensive so running it locally is no longer a nice experience, our batteries die super fast, and switching between projects can take upwards of 20 minutes for all the images to rebuild and pods to spin up.  Part of my solution to this has been moving to cloud-based dev environments, in which we use Cloudflare's argo and access products to securely connect to which have https by default.

If you're curious to learn more, here is where I first learned about this sort of workflow when I was researching potential solutions to my problems: https://blog.cloudflare.com/how-replicated-secured-our-remote-dev-environment-with-cloudflare-access/
