### ISSUE TITLE
Tilt Cloud: Signing in directly from team page leads to "invalid callback redirect path" error

### ISSUE THREAD

**Issue by andymartin-sch** [tilt-dev/tilt#3872]
This is extremely minor, just logging so you all are aware.

Steps to reproduce:
1. Navigate to team page (ex: `https://cloud.tilt.dev/team/$TEAM_UUID/page`)
2. Click the "Sign Out" button to manually force your session token to be invalid (this seems to happen to me automatically every once in a while when a token goes stale - clicking the log out button isn't necessary to see this error from time to time)
3. As a part of 2, you probably got redirected to https://cloud.tilt.dev/ -- logging in from here does work correctly, so to reproduce the issue, go back to the team page from 1
4. Directly from this team page, click the Sign In button

Expected behavior:
Login completes the same way as it does when signing in from the main cloud.tilt.dev page

Actual behavior:
URL gets stuck at `https://cloud.tilt.dev/auth/github/callback/team/$TEAM_UUID/page?code=~~snip~~&state=~~snip~~`
 and a white page with the text `invalid callback redirect path: "/team/$TEAM_UUID/page"` is shown

As mentioned in 2, I see this from time to time (maybe roughly once per week for each computer I use to access Tilt Cloud?) despite never explicitly clicking the Sign Out button. This happens because I have my team page bookmarked, which is likely pretty common among other Tilt Cloud users.

**Comment by maiamcc** [comment]
Thanks for reporting @andymartin-sch -- I can repro, alas.

@landism got 15 mins to look into this?
