### ISSUE TITLE
Click to copy pod ID in Web UI

### ISSUE THREAD

**Issue by maiamcc** [tilt-dev/tilt#3882]
From a user in Slack:
> it would be handy to have a copy button next to the [pod] name at the top of the Tilt UI when a service is selected.

Click-to-copy Pod ID in the web UI is a cheap way we can make it easier for users to interact with/script against their pods (this makes an incremental bit of progress towards what #2060 is trying to achieve).

**Comment by maiamcc** [comment]
There's lots of discussion to be done on how/whether to signal copy-ability with iconography etc., but I think that even without icons, if you click the pod ID and it gets copied and you see a tooltip saying "Pod ID copied!" that would be strictly better than the current behavior. On these grounds I'm marking this "good first issue" (even though there may be more involved design work later). @hyu @SurbhiSGupta lmk if you disagree!

**Comment by nicks** [comment]
fixed in https://github.com/tilt-dev/tilt/pull/3982
