### ISSUE TITLE
Tilt installer doesn't work on Alpine Linux

### ISSUE THREAD

**Issue by jpetazzo** [tilt-dev/tilt#3883]
On Alpine, `$OSTYPE` is `linux-musl`, and the installer script only looks for `linux-gnu` and `darwin`, so the install script fails:

```
/ # curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash -x
+ VERSION=0.17.9
++ command -v brew
+ BREW=
+ set -e
+ [[ -z '' ]]
+ install_tilt
+ [[ linux-musl == \l\i\n\u\x\-\g\n\u ]]
+ [[ linux-musl == \d\a\r\w\i\n* ]]
+ set +x
The Tilt installer does not work for your platform: 
Please file an issue at https://github.com/tilt-dev/tilt/issues/new
```

Since the `tilt` binary is currently statically linked, it works fine on Alpine anyway:
```
bash-5.0# file tilt 
tilt: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=nMePJCSaJbBKq9Y44r6d/c-EfWPM0UtRXslRgxayq/-ZifGfxUWg3pEmCeRrf0/Y9a5MW6aMwBnN23Sjrn3, stripped
bash-5.0# ./tilt version
v0.17.9, built 2020-10-19
```

Would it make sense to add a check for `linux-musl` so that the installer works on Alpine?
Or do you foresee that you might want to switch to dynamic linking in the future, which would break Alpine?

Would it make sense to add a link to the manual install process in the output of the install script?

I'm happy to send PRs either way that you'll deem useful.

Thank you! ♥

**Comment by jpetazzo** [comment]
![Why not both?](https://user-images.githubusercontent.com/171481/97374228-25abd780-18b8-11eb-8334-dbd70cbda5de.png)

**Comment by nicks** [comment]
closing this since it sounds like it works now!
