### ISSUE TITLE
Live Update

### ISSUE THREAD

**Issue by kawther18** [tilt-dev/tilt#3890]
Hello Tilt team,

I'm working with tilt and I had some issues with the Live Update feature, that I hope you can help me with: So I'm using tilt with an application with Angular code that has "npm build" and "npm run" in its Dockerfile. Whenever I change something in my code, it will require me to build and run the app all over again, meaning rebuilding a new docker image, push and redeploy the entire application. The second app is an angular app served behind nginx web-server, also the live update didn't work.So I wanted to ask if there is any possible way to use live update feature in a similar conditions.
Regards,

Kawther

**Comment by maiamcc** [comment]
Hi there, glad to hear you're trying Tilt and happy to help with your Live Update issues. I don't understand exactly what problem you're seeing. Will you please share as much information as you're able about what exactly is going on? I don't understand a. your current configuration, b. what you're doing that you expect to trigger a live update, and c. what happens instead.

Could you post:
1. the output of `tilt doctor`
2. the contents of your Tiltfile
3. Tilt logs when you make a file change that you expect to result in a live update (the easiest way to share these is to generate a snapshot with the button at the upper right)

If you'd rather, you can send this to me directly at maia@tilt.dev

**Comment by maiamcc** [comment]
We are discussing this via email, going to close this issue.
