### ISSUE TITLE
Snapshot is not loading

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#3902]
### Expected Behavior
Snapshot should load

### Current Behavior
It gets stuck on the loading screen. For both public and private team snapshots.

<img width="1665" alt="Screen Shot 2020-11-05 at 1 30 41 PM" src="https://user-images.githubusercontent.com/10860550/98281768-2bb25000-1f6b-11eb-90a9-ead853f978c9.png">
<img width="1677" alt="Screen Shot 2020-11-05 at 1 30 49 PM" src="https://user-images.githubusercontent.com/10860550/98281770-2ce37d00-1f6b-11eb-946e-e0b3f2c0b20f.png">

### Steps to Reproduce
1. Start Tilt
2. Create a snapshot.
3. Access the snapshot.

#### `tilt doctor` Output

```
Tilt: v0.17.10, built 2020-10-30
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.40
- Builder: 2
---
Kubernetes
- Env: docker-for-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.18.8
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗
```

#### About Your Use Case

First reported from a private partner slack channel: https://tilt-dev.slack.com/archives/CLW854H9A/p1604600786021400

**Comment by victorwuky** [comment]
@landism : Can you please take a look? Thanks.

**Comment by landism** [comment]
I've deployed a fix to cloud.tilt.dev. Unfortunately, snapshots created by 0.17.10 prior to this deploy will still be broken.
