### ISSUE TITLE
Rename 'Favorites' to 'Pinned'

### ISSUE THREAD

**Issue by taylorcoffelt** [tilt-dev/tilt#3905]
## Describe the Feature You Want
Rename 'Favorites' to 'Pinned' or 'Pinned Resources'

### Current Behavior
All references and Icons in tilt currently relating to 'Pinning' a resource have consistent language, with the exception of the actual list where those 'Pinned' resources are shown. 

The list itself is labelled "Favorites", while the icons, tooltips, etc show 'Pin/Unpin'. To continue the consistency with the rest of the application, I feel the list title should reflect the naming from the rest of the application.

An exception to this would be if you are intending to add additional 'Sections' that a resource could be 'Pinned' to, in which case, keeping 'Favorites' and changing the action description to 'Pin to Favorites' / 'Pin to X' would make more sense.

### Why Do You Want This?
UX/UI Consistency in naming application features

**Additional context**

**Comment by victorwuky** [comment]
@SurbhiSGupta : What do you think about this?

**Comment by victorwuky** [comment]
@taylorcoffelt : In the latest release, we call it "Pinned". Thanks for the feedback!

<img width="459" alt="Screen Shot 2020-12-18 at 4 52 12 PM" src="https://user-images.githubusercontent.com/10860550/102664725-6229e000-4151-11eb-95a5-926195dc9cb9.png">
