### ISSUE TITLE
etcd Statefulset PodManagementPolicy by OrderedReady vs Parallel

### ISSUE THREAD

**Issue by zkutasi** [tilt-dev/tilt#3906]
### Expected Behavior
etcd in our deployments have 3 replicas, and it is expected to be rolling-started, otherwise I see sporadic random cluster failures... I traced down that it is around 30-50% of the time the cluster cannot be formed due to "member count unequal" errors. And the Helm variant always installs, issue is only with Tilt. I have found this ticket https://github.com/tilt-dev/tilt/issues/1962, where it is stated that this PodManagementPolicy is rewritten by Tilt to Parallel, which seems to be the issue...

### Current Behavior
etcd cluster randomly cannot form a cluster with Tilt, with Helm it is always OK.

### Steps to Reproduce
Take I guess an etcd helm chart, take 3 replicas and try to use Tilt to deploy. Unfortunately our Helm Charts are proprietary and I cannot share them.

#### `tilt doctor` Output
vagrant@vagrant:[17:58:01]~/tmp/ci> tilt doctor
Tilt: v0.17.10, built 2020-10-30
System: linux-amd64
---
Docker
- Host: [default]
- Version: 1.40
- Builder: 2
---
Kubernetes
- Env: unknown
- Context: kubernetes-admin@kubernetes
- Cluster Name: kubernetes
- Namespace: default
- Container Runtime: docker
- Version: v1.16.2
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: e1517ad59ac720d252693580f2cc35e9
- Repo: 
vagrant@vagrant:[18:15:35]~/tmp/ci>

#### About Your Use Case
This hinders our efforts to test with Tilt the perfect exact chart-content... it would not be a big issue but etcd seems to rely on this too much on our side.
A possible approach would be to make this PodManagementPolicy switchable... make it default to on, but make if switchable for scenarios like this at least. It would be a good idea to document every such change you make on YAML descriptors to follow up on these as well.

**Comment by nicks** [comment]
ugh, ya, as the related issues explain:
https://github.com/tilt-dev/tilt/issues/1962
https://github.com/kubernetes/kubernetes/issues/60164

the StatefulSet controller doesn't handle failure well...which is really bad for a tool like Tilt where we expect that StatefulSets will fail sometimes.

but now that Tilt has a way to kill pods from the UI, maybe that's OK and we should revert to not setting the PodManagementPolicy...

**Comment by nicks** [comment]
question: you're not building etcd from scratch right?

maybe the solution here is to only change the PodMangementPolicy for images that you're building yourself, since those are the ones we expect to change frequently

**Comment by zkutasi** [comment]
Hello Nick,

Thanks for looking into this!

Our Microservice uses several dependencies, etcd is one of them, so in order to deploy our full environment we deploy the dependencies in one helm chart (we call this one CI chart) and then deploy our MS' helm chart, in this way we separate the product from its dependencies, as we develop in dozens of Teams all across the globe.

I've checked, and we build our own Helm charts, but we download the official binary and Dockerize in-company. We have enormous amount of Design Rules to follow, none of the public-domain charts or docker images are able to fulfill. I have checked and the helm chart content I was able to find online does not resemble ours... I'm sure people over that other Team developed their own flavor of the charts. I also checked, and an init-container mounts a custom shell script called AddMember, I'm sure that implements how the official guide suggests to add members... and this also support scalability I think. SO it has a quite complex featureset.

I'm not sure the proposed solution is good for all people out there... for example the etcd developers cannot use Tilt then, or possibly anyone who relies on this parameter to be a rolling behavior (although also not sure if this is something officially relied on or it is just us). In our case, the mentioned solution would be perfect, as we just use this as a dependency... and we want two things: 1) pull up the whole stack of microservices reliably and 2) live update our microservice that does not rely on this. But (2) may change in the future. It is best to have control if needed.

**Comment by zkutasi** [comment]
FYI, I think we hit this issue:
https://etcd.io/docs/v3.3.12/op-guide/runtime-configuration/

"If adding multiple members the best practice is to configure a single member at a time and verify it starts correctly before adding more new members. If adding a new member to a 1-node cluster, the cluster cannot make progress before the new member starts because it needs two members as majority to agree on the consensus. This behavior only happens between the time etcdctl member add informs the cluster about the new member and the new member successfully establishing a connection to the existing one."

I suspect at starting 3 instances, there will be a random race-condition on this initial cluster-addition.
