### ISSUE TITLE
Helm support for Capabilities.APIVersions missing

### ISSUE THREAD

**Issue by zkutasi** [tilt-dev/tilt#3907]
### Expected Behavior
Tilt shall properly use helm template, possibly giving the user the absolute flexible freedom to give any command line parameters into the Tiltfile's helm() function, besides values, as Helm has some tricky use-cases still, like this one: https://github.com/helm/helm/pull/5392

I issued a bug, because this makes it impossible for us now to deploy this helm chart of ours that has this functionality inside... maybe other helm chart functionalities also missing, making Tilt deploy the wrong things.

### Current Behavior
Tilt does not support for example the built-in **Capabilities** functionality: the https://helm.sh/docs/chart_template_guide/builtin_objects/, this means that if a helm chart is built on top of such functionalities, it is impossible to render the helm charts properly. We have a helm chart that has an if-else clause on this Capability (on an API object) and we could easily lie to helm template, but we cannot now as the helm() function does not support giving extra parameters like the above.

As a Workaround I know we could re-implement helm-template (explained on the Wiki here: https://docs.tilt.dev/helm.html) and add our own functionality to it, but this kind of makes the helm() function obsolete and we could miss some neat tricks you guys do in the process.

### Steps to Reproduce
Simply create a Helm chart where you check for the **Capabilities** a Cluster has via helm... it will always be rendered the same way, if the Cluster does not have that capability

### Context
vagrant@vagrant:[23:38:11]~/tmp/ci> tilt doctor
Tilt: v0.17.10, built 2020-10-30
System: linux-amd64
---
Docker
- Host: [default]
- Version: 1.40
- Builder: 2
---
Kubernetes
- Env: unknown
- Context: kubernetes-admin@kubernetes
- Cluster Name: kubernetes
- Namespace: default
- Container Runtime: docker
- Version: v1.16.2
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: e1517ad59ac720d252693580f2cc35e9
- Repo: 
vagrant@vagrant:[23:39:40]~/tmp/ci>

#### About Your Use Case
Ability to fully use "helm template" with all functionalities, and utilize every kind of helm chart.
My take on this would be to extend the helm() function with a very flexible extra argument that in a dict/string I can give anything to it, parameterizing helm template directly. So for example in this use-case, I simply would pass in something like "--api-versions "MY_EXTRA_API_CAPABILITY_STRING" as a simple string, or a dict, does not matter as long as it is flexible and future-proof. If it is as fexible as it gets, it is future-proof

**Comment by nicks** [comment]
thanks for the report! If you need a work-around, this doc:
https://docs.tilt.dev/helm.html#re-implementing-the-helm-built-in
shows you how to pass arbitrary flags to helm with `local()`, but I agree that it would be nice if the built-in had this.

**Comment by zkutasi** [comment]
Yes, that WA I think is fine for us for now. Thanks, just wanted to get it out :), I have spent half a day to debug this :).

**Comment by Pobek** [comment]
Hey,
We've also encountered this and just wanted to know if there is any progress on fixing it :)

**Comment by lizzthabet** [comment]
hi @Pobek, this isn't work that's scheduled for the tilt team right now, but your comments and +1s help us prioritize issues for future planning! happy to talk through any questions about the workaround nick that posted above.

**Comment by nicks** [comment]
`helm_resource` should support this because it uses `helm install` directly: https://github.com/tilt-dev/tilt-extensions/tree/master/helm_resource

I'm going to close this issue. We can re-open if someone REALLY wants to add an `--api-versions` arg to the old helm() function, but I suspect they'd be happier using `helm_resource`.
