### ISSUE TITLE
spacing artifacts on tilt v0.17.11

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3927]
Just got this report of spacing issues on v0.17.11:
<img width="313" alt="Screen Shot 2020-11-16 at 10 04 53 AM" src="https://user-images.githubusercontent.com/278641/99273264-c6761e80-27f6-11eb-9994-52342b14e220.png">

Might have been broken by the fix to https://github.com/tilt-dev/tilt/issues/3903

Need to get repro steps

**Comment by victorwuky** [comment]
I'm able to reproduce this with `Always` selected in v0.17.11

<img width="593" alt="Screen Shot 2020-11-16 at 10 53 44 AM" src="https://user-images.githubusercontent.com/10860550/99275883-08549400-27fa-11eb-9454-9b31c3a57dcf.png">

<img width="658" alt="Screen Shot 2020-11-16 at 10 55 03 AM" src="https://user-images.githubusercontent.com/10860550/99276016-33d77e80-27fa-11eb-841e-7f30195ef00f.png">


Which #3903 fixes. 

@andymartin-sch : Are you using mac and have `Always` selected?

**Comment by andymartin-sch** [comment]
I'm on Mac but have "Automatically based on mouse or trackpad" selected

**Comment by andymartin-sch** [comment]
@victorwuky  when I flip it to "When scrolling" the problem goes away immediately

**Comment by victorwuky** [comment]
Thanks @andymartin-sch . That's strange. I'm not able to reproduce the `Automatically` scenario. Are you okay to use `When scrolling` for now? We plan to release a new version of Tilt later this week and hopefully that should resolve this problem.

Oh, and would you happen to be using the brand new mac OS? (I am not currently.)

**Comment by andymartin-sch** [comment]
Yeah that's a fine workaround for now. I'm on macOS Catalina 10.15.7.

**Comment by victorwuky** [comment]
Ok thanks @andymartin-sch

**Comment by nicks** [comment]
oh wait, i'm goofed. Tilt v0.17.11 doesn't have the fix for https://github.com/tilt-dev/tilt/issues/3903, so this is just the same issue as that one.

**Comment by victorwuky** [comment]
I'm not able to reproduce what Andy indicated in https://github.com/tilt-dev/tilt/issues/3927#issuecomment-728152711, for v0.17.11.

But I just tested what's on master now and I get good behavior for all three selections of the scroll bars from https://github.com/tilt-dev/tilt/issues/3927#issuecomment-728151383.

**Comment by victorwuky** [comment]
@andymartin-sch : Feel free to upgrade to latest Tilt. Just released. https://docs.tilt.dev/upgrade.html.

I'm unable to reproduce this bug on the latest Tilt. Let me know if you still can. (Make sure to refresh your browser too.)

**Comment by andymartin-sch** [comment]
yeah this is resolved for me on v0.17.12 - thanks!
