### ISSUE TITLE
Tilt lifecycle without push

### ISSUE THREAD

**Issue by BobyMCbobs** [tilt-dev/tilt#3930]
## Describe the Feature You Want
Build using local Docker socket / env without pushing using `docker_build`.

### Current Behavior
`custom_build` is required for this behavior and some extra logic to make the Tiltfile dynamic, such as:
```python
if not os.getenv('SHARINGIO_PAIR_NAME'):
    docker_build('myimage', '.', dockerfile="build/dev.Dockerfile")
else:
    custom_build('myimage', 'docker build -f build/dev.Dockerfile -t $EXPECTED_REF .', ['.'], disable_push=True)
```

### Why Do You Want This?
It will help with Continuous-Development™ in Pairing environments (such as [pair](https://github.com/sharingio/pair)), meaning providing there's a Docker socket and an API service it manage the development lifecycle.

**Additional context**
I work inside a Pod in my Kubernetes cluster on a single node with Docker socket access, such as in:
- Minikube
- Baremetal
- anything with Docker socket and a _kubeconfig_

**Comment by victorwuky** [comment]
Great. Thanks for the request.

**Comment by nicks** [comment]
Thanks @BobyMCbobs ! 

One of the things I was talking a bunch with sig-cluster-lifecycle earlier this year was to have a common standard for clusters to advertise "my docker socket is available at XXX" 

https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/generic/1755-communicating-a-local-registry#support-for-other-local-image-loaders

the syntax we were playing around with was something like:

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-docker-socket
  namespace: kube-public
data:
  localDockerSocket.v1: |
    host: "tcp://172.17.0.5:2376"
    certPath: "/home/nick/.minikube/certs"
    tlsVerify: "1"
EOF

Note that Tilt will generally already auto-detect Minikube, but has to call `minikube docker-env` to get it, and it would be good if there was a non-minikube-specific way for tilt to fetch this configuration

**Comment by BobyMCbobs** [comment]
> Thanks @BobyMCbobs !
> 
> One of the things I was talking a bunch with sig-cluster-lifecycle earlier this year was to have a common standard for clusters to advertise "my docker socket is available at XXX"
> 
> https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/generic/1755-communicating-a-local-registry#support-for-other-local-image-loaders
> 
> the syntax we were playing around with was something like:
> 
> ```
> cat <<EOF | kubectl apply -f -
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: local-docker-socket
>   namespace: kube-public
> data:
>   localDockerSocket.v1: |
>     host: "tcp://172.17.0.5:2376"
>     certPath: "/home/nick/.minikube/certs"
>     tlsVerify: "1"
> EOF
> ```

This would be quite useful to have!
This would mean for no client _Tiltfile_ configuration, right?

> Note that Tilt will generally already auto-detect Minikube, but has to call `minikube docker-env` to get it, and it would be good if there was a non-minikube-specific way for tilt to fetch this configuration

I think this only works on the host machine, not inside of the cluster (in a Pod)
