### ISSUE TITLE
Select resources when calling Tilt commands in CLI

### ISSUE THREAD

**Issue by victorwuky** [tilt-dev/tilt#3931]
## Describe the Feature You Want
From: https://kubernetes.slack.com/archives/CESBL84MV/p1605641951433000: 

it'd be nice is you could send some selectors into tilt to get things out of the engine state

example: it migth be nice to run "tilt trigger $(the set of targets that have not succeeded)"

currently I'm at:
tilt dump engine |gron | grep 'HasSucceededAtLeastOnce = false' |gron --ungron |jq -r '.ManifestTargets | keys[]'

### Why Do You Want This?

**Additional context**

**Comment by lizzthabet** [comment]
since this issue hasn't received more 👍🏻s or comments, i think it's okay to close.
