### ISSUE TITLE
Distance between resources doubles

### ISSUE THREAD

**Issue by damoon** [tilt-dev/tilt#3932]
### Expected Behavior
With a lot of resources listed in the UI, the elements are all listed with the same distance.

### Current Behavior
Once the list becomes longer then the height (i believe) the distance between elements doubles.

### Steps to Reproduce
1. Create a list long enough or increase the page zoom until the list gets longer then the page is high.
2. Decrease the zoom until the list with doubled distances fits on screen. The list will shrink to less then half of the page height. 

bad: https://www.dropbox.com/s/3z9fpupfr3fdnfv/Screenshot%20from%202020-11-17%2022-28-33.png?dl=0
good: https://www.dropbox.com/s/l1mdk9mthucx650/Screenshot%20from%202020-11-17%2022-29-38.png?dl=0

#### `tilt doctor` Output
```
$ tilt doctor
...
Tilt: v0.17.11, built 2020-11-12
System: linux-amd64
---
Docker
- Host: [default]
- Version: 1.40
- Builder: 2
---
Kubernetes
- Env: unknown
- Context: test
- Cluster Name: My
- Namespace: development
- Container Runtime: docker
- Version: v1.18.10
- Cluster Local Registry: {Host:registry.My.de hostFromCluster:registry.registry.svc:5000 SingleName:}
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 
- Repo: 

```

#### About Your Use Case
Setting up a project with a lot of service dependencies make the UI hard to use.
A by default hidden group for dependencies would be nice. (Next to fixing the CSS)

**Comment by victorwuky** [comment]
This should be fixed with this week's release (Thursday or Friday). 

See https://github.com/tilt-dev/tilt/issues/3927

**Comment by damoon** [comment]
thanks :D

**Comment by victorwuky** [comment]
@damoon : Feel free to upgrade to latest Tilt. Just released. https://docs.tilt.dev/upgrade.html.

I'm unable to reproduce this bug on the latest Tilt. Let me know if you still can. (Make sure to refresh your browser too.)
