### ISSUE TITLE
ergonomics of running concurrent Tilt instances

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3948]
SB in the Tilt channel writes:

> we are adding tilt to a few different projects that one developer could be running concurrently. We are moving from a bunch of Makefile and docker-compose.yml files that the developers need to understand to a simple tilt up that is managed by one ops team, but now we need some way to orchestrate parallel tilt instances and we're heading backwards a little bit. We plan on using tilt dump engine to get the pod ID for a given resource so we can shell into it with a simple script

> each use of tilt is for a separate product, each of which is a collection of microservices that are not in any way related to the other products

> so we'd like a developer to be able to jump into a project and know that they can tilt up . Right now we're looking at the next step being that they source a file that will always be in the same place in each project, containing a few bash functions. One of those functions would be something like cli-helper, which would use tilt dump engine to get the pod ID for a resource when it is provided as an argument for cli-helper and then kubectl exec into it

I feel like this touches on a pain that I've personally felt, and that has been touched on in a few tickets:
https://github.com/tilt-dev/tilt/issues/3434
https://github.com/tilt-dev/tilt/issues/2235

if you have multiple independent repos with separate Tiltfiles, but sometimes you need to run them together, orchestrating the different tilt instances as hard.

I've often wondered if Tilt should operate more like Docker, where running a Tiltfile is like running a container under a single supervisor, and you have one unified interface over them (rather than a separate server for each env)

**Comment by nicks** [comment]
the current workaround i recommended was to wrap it in a Makefile, though that doesn't feel great

SB suggested a `.tiltconfig`, though there already is a tilt_config.json with semantics that wouldn't work for this, and I'm a little nervous about a proliferation of config files :grimacing:

**Comment by salim-runsafe** [comment]
@nicks I'm SB from Slack. What about setting environment variables like `TILT_HOST` and `TILT_PORT` that would be used by `tilt` when present?

**Comment by nicks** [comment]
@salim-runsafe Oooh I like that idea!
