### ISSUE TITLE
Closing the terminal should shutdown any local processes

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3962]
### Expected Behavior
Closing the terminal should shutdown any local processes

### Current Behavior
It does not

### Steps to Reproduce
1. Run tilt up under https://github.com/tilt-dev/opentelemetry-collector
2. close the terminal
3. sudo ps aux | grep otelcol

**Comment by scottwlyft** [comment]
Confirmed it works as expected on 0.18.0
