### ISSUE TITLE
Provide a way to see (visually or programatically) a dependency graph

### ISSUE THREAD

**Issue by KOGI** [tilt-dev/tilt#3979]
We have a relatively large stack of services that Tilt is running and there is a lot of interdependency between resources.
Tilt does an awesome job of sorting it all out and running things in the proper order, but sometimes _we_ aren't so good at specifying the appropriate dependencies. Sometimes we think we should be depending on one thing, when we probably should have depended on something else either further up or further down the line.

Most of the time we just run tilt up with everything, but sometimes we need to run `tilt up -- --with-just-some-subset`. If we haven't got our dependencies set up quite right, launching just that subset can sometimes cause a much larger portion of the stack to deploy than we realized and, tracing through the code, it can be difficult to figure out that service `X` got launched because `A` depended on `B` which depended on `K` which itself depended on `C` and finally roped in service `X`. So even though we intended to only launch `A` (and `B` which it depends on), we're now unexpectedly getting `K`, `C` and `X`, too.

It would be really helpful to be able to somehow see (or programmatically access vars containing this info) what resources depend on what other resources. A visual representation would be excellent, but it might be more feasible (and still helpful) if we could simply do something like (quick pseudo-code):

```
allQueued = getAllQueuedResources() # everything tilt is planning to launch
foreach(name, item in allQueued) {
    if name == 'theOneImInterestedIn':
       print(item.dependentResources) 
```

With something like that, we could inspect `unexpectedlyLauncedService.dependentResources` and see a list of things that depend on this one (aka, "this was launched because someOtherResource needed it"). We could even the recurse into `someOtherResource.dependentResources` and follow the chain all the way up.

**Comment by omh1280** [comment]
We'd also love to see this added

**Comment by landism** [comment]
We should add something like this to the product, but in the meantime, in case it saves someone some time my bash history had a quick-and-dirty one-liner to generate an image of the dependency graph:
`(echo 'digraph deps {' && tilt alpha tiltfile-result | jq -r '.Manifests[] | "  \(.Name) -> \(.ResourceDependencies[]?);"' && echo '}') | dot -Tpng | open -a Preview.app -f`

notes:
* requires `jq` and `dot`
* if not on macos, you'll want to redirect the output of `dot` (e.g., `dot -Tpng > deps.png`) instead of piping it to Preview

**Comment by KOGI** [comment]
Just a note that the `dot` command comes from the `graphviz` lib

**Comment by KOGI** [comment]
Also, I wonder if there's a filter in there to ignore ETCD (kubernetes system)? My stack includes our own, separate instance of ETCD, and while I've confirmed it definitely starts up with a normal `tilt up`, the generated dependency graph doesn't show it anywhere.

**Comment by landism** [comment]
> I wonder if there's a filter in there to ignore ETCD (kubernetes system)?

Oh, I'm guessing that's because it's only showing resources that have incoming or outgoing edges (deps). This will add edgeless nodes:
```
(echo 'digraph deps {' && tilt alpha tiltfile-result -f infra.tilt | jq -r '.Manifests[] | if .ResourceDependencies != null then " \"\(.Name)\" -> \"\(.ResourceDependencies[]?)\";" else .Name end' && echo '}') | dot -Tpng > deps.png
```

**Comment by KOGI** [comment]
That does the trick!!

**Comment by pnovotnak** [comment]
"Why is tilt stuck" or "what is tilt doing" are the most common questions I get (for an admittedly pretty big config). Having a visualization ought to eliminate this class of questions.

**Comment by nicks** [comment]
as of tilt 0.22.15, the tilt api publishes some information about why resources are waiting. Here's a little shell script you can use to get them:

```
tilt get uiresource -o=jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.status.waiting}{"\n"}{end}' | sort
```

**Comment by omh1280** [comment]
This has been mostly solved in v0.23.0:
> Displays why a resource is pending

This has been a very helpful upgrade and IMO may justify closing this issue.

**Comment by pnovotnak** [comment]
Also solves for me. I support closing the issue

**Comment by bcsgh** [comment]
Has any progress been made on the original thing that was asked for?

The actual dependency graph is likely a lot more generally useful than the special case that was cited when this was closed. In my case I'm more interested in things like missing dependencies so the hackery above using `jq` and `dot` is a bare minimum for having a working solution.
