### ISSUE TITLE
Customizing Tilt with a Tilt API server

### ISSUE THREAD

**Issue by wu-victor** [tilt-dev/tilt#4013]
## Background
We're considering ways to make it easier for folks to add more functionality to Tilt on their own, and more quickly. We think it might be interesting for _you_, as a user of Tilt, to extend and customize Tilt for your team's specific workflows and needs. It shouldn't take you months. Not weeks. But at most, days.

- We already have https://github.com/tilt-dev/tilt-extensions. But that's constrained to packaging up your custom functionality, and sending it to the Tilt team to approve. Maybe you can't do that, or don't want to do that.
- You can use multiple Tiltfiles and have shared functionality invoked with https://docs.tilt.dev/api.html#api.load. But that's limited to Starlark, the Tiltfile, and what Tilt exposes via the API. https://docs.tilt.dev/api.html

## Proposal
What if we exposed even _more_ of the guts of Tilt? ([See Tilt's control loop.](https://blog.tilt.dev/2020/11/13/demystified.html)) Just like you can use `kubectl` and various tools to interact with a Kubernetes cluster's internal state via the [Kubernetes API](https://kubernetes.io/docs/reference/using-api/), what if you could talk to Tilt's internal state via a Tilt API Server? In particular, you would be able to:

- Create, Update, Get, and Watch objects in Tilt's internal state

You would be able to access this deeper API (compared with the [existing API](https://docs.tilt.dev/api.html)), from a Tiltfile, allowing you more possibilities. But you could also build whole new UI paradigms! (Anyone want to contribute a VS Code extension?) You could create entirely new features and workflows if you had that deep access to Tilt's internal state. You wouldn't be limited to the existing web UI of Tilt, and even using a Tiltfile itself.

**Comment by nicks** [comment]
this exists now https://api.tilt.dev/
