### ISSUE TITLE
When a resource name has a slash in it, clicking on it in the webui sidebar doesn't work

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#4026]
### Steps to Reproduce
Make a resource with a slash in the name, e.g.:
```
local_resource('a/b', 'echo hi')
```
`tilt up`, open the web ui, and click on the "a/b" resource in the sidebar.

### Expected Behavior
Tilt shows me the logs for the "a/b" resource.

### Current Behavior
Tilt shows me "No match for /r/a/b"

This is presumably a matter of uri-encoding the resource name in the sidebar link, and the link should be to `/r/a%2Fb` instead of `/r/a/b/`

**Comment by nicks** [comment]
It's worth pointing out that Kubernetes objects don't allow names with slashes on them (https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names), and there might be value in following the k8s conventions here.

But I haven't thought too hard about the trade-offs here and could probably be convinced it's worth supporting this too

**Comment by landism** [comment]
That sounds a lot simpler than making sure we have proper encoding/unencoding everywhere!

**Comment by VeryStrongFingers** [comment]
Just on the topic of encoding and for posterity, regardless of supported characters in Kubernetes objects - to avoid XSS and HTML injection vulnerabilities it's still desirable to encode these values 🦺
