### ISSUE TITLE
detect when cluster has been deleted

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4037]
Bjorn Tipling in the slack channel asks:

> tilt can't tell when I've deleted the cluster and just tries to reconnect to deployments on a cluster that doesn't exist anymore.  I would have expected tilt to just quit?

I'm not totally sure that quitting is the right behavior, but I do agree that Tilt should have better detection for when you cluster is dead

**Comment by lizzthabet** [comment]
with the cluster status information that's available in the tilt ui and api (via `tilt describe cluster`) as of [v0.27.2](https://github.com/tilt-dev/tilt/releases), i think we can consider this issue closed. when you launch tilt and your cluster is in a healthy state, tilt will poll to check that it's still healthy and update the cluster status information if there's an error.
