### ISSUE TITLE
make it easy to edit the set of enabled resources

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#4039]
## Describe the Feature You Want
When starting or stopping working on a service, I'd like to be able to easily add/remove it from Tilt's set of enabled resources.

### Current Behavior
This is currently achieved via `tilt args`, but that:
1) is in the CLI, not the web UI
2) only allows *replacing* the list of enabled resources, not editing (e.g., if I'm running resources foo bar baz, I can't just `tilt stop baz` or `tilt start quu`, I have to re-type all the other resources I still want, e.g. `tilt args foo bar baz quu`)

**Additional context**
Maybe `tilt start` / `tilt stop` would suffice for many users, but also many users don't want to have to go back to the CLI to do Tilt stuff.

**Comment by landism** [comment]
We've changed `tilt args` so that if you run it without any arguments, it opens `$EDITOR` to allow you to edit the current set of args.

We're also working on building enable/disabling resources into the web ui, and have shipped the first part of that: https://docs.tilt.dev/disable_resources.html. We have a few more features we want to add (described on that page) before considering this issue closed.

**Comment by dvdapp** [comment]
Nice that's helpful. Appreciate all the work you guys are putting into Tilt! 🙏

**Comment by nicks** [comment]
we recently shipped the `tilt enable` and `tilt disable` cli commands!

https://docs.tilt.dev/cli/tilt_enable.html
https://docs.tilt.dev/cli/tilt_disable.html

marking this as done
