### ISSUE TITLE
UI: It'd be nice to show the name of the resource/service we are "Pending" on

### ISSUE THREAD

**Issue by adamf** [tilt-dev/tilt#4054]
## Describe the Feature You Want
I'd like the UI to show me _what_ a resource is pending on:

<img width="292" alt="Screen Shot 2021-01-07 at 12 14 43 PM" src="https://user-images.githubusercontent.com/188338/103940361-09ab8a00-50e2-11eb-8d76-af449e8a3cd7.png">

If the text said "Pending on <resource name>" that would be very useful.

### Current Behavior
The resource chip just says "Pending" without saying on what (see screenshot above).

### Why Do You Want This?
It'd be useful to see at a glance which resources is currently blocking other resources. We have 30+ resources so not all fit on the screen at a time, so the resource that is blocking the other resources may not be obvious.

Thanks!

**Additional context**

**Comment by victorwuky** [comment]
Thanks @adamf . This makes sense!

**Comment by milas** [comment]
This was added in #5086.
