### ISSUE TITLE
custom_build: unexpected keyword argument "command_bat"

### ISSUE THREAD

**Issue by Hellysonrp** [tilt-dev/tilt#4061]
### Expected Behavior
As stated in [the docs](https://docs.tilt.dev/api.html#api.custom_build), `command_bat` might be used to set a Windows-specific command.

### Current Behavior
Error: custom_build: unexpected keyword argument "command_bat"

### Steps to Reproduce

1. Add some `custom_build` in Tiltfile with a `command_bat` argument, like this:
```python
custom_build('some_resource', 'do_something && docker build -t $EXPECTED_REF .', ['.'], command_bat='do_something && docker build -t %EXPECTED_REF% .')
```

#### `tilt doctor` Output

```
Tilt: v0.18.3, built 2021-01-05
System: windows-amd64
---
Docker
- Host: [default]
- Version: 1.40
- Builder: 2
---
Kubernetes
- Env: docker-for-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.19.3
- Cluster Local Registry: none
---
```

#### About Your Use Case

I mainly use Windows for development, so this would be useful to me.
As you can see in the example in the Steps to Reproduce, the main difference of the Windows command is the way in which an environment variable value is obtained.

### Cause

https://github.com/tilt-dev/tilt/blob/dd0e5498cad3630c96b1db5e34554c0763d357ce/internal/tiltfile/docker.go#L289

Compared to the docs, in the code, there is an extra `_val` in the argument name.

**Comment by nicks** [comment]
thanks for the report! ya, this is just a bug. you can workaround it for now by using command_bat_val=... but we should fix this
