### ISSUE TITLE
Tilt Helm --set arguments escaping fails if value string includes dots

### ISSUE THREAD

**Issue by nikohaap** [tilt-dev/tilt#4095]
### Expected Behavior
Don't escape Helm --set arguments if those includes escapes

### Current Behavior
If Helm --set arguments haven't been escaped those values won't be escaped
If Helm --set arguments have been escaped those escapes will be escaped so Helm --set arguments will be invalid from the Helm point of view.a

<pre>
 ✖ (Tiltfile) ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ N/A             •  <5s ago
    HISTORY: EDITED FILES Tiltfile                                                                                                                                                        Error    (0.0s) •  <5s ago
             FIRST BUILD                                                                                                                                                                  Error    (0.0s) • <15s ago
    ERROR:
       1 File Changed: [Tiltfile] • (Tiltfile)
       Beginning Tiltfile execution
       Successfully loaded Tiltfile (1.192623ms)
       /Users/dude/tilt-issue/Tiltfile:11:2: invalid escape sequence \.
</pre>

### Steps to Reproduce
1. $ helm create nginx
2. [Tiltfile.txt](https://github.com/tilt-dev/tilt/files/5841129/Tiltfile.txt)

#### `tilt doctor` Output
<pre>
tilt doctor
Tilt: v0.18.4, built 2021-01-13
System: darwin-amd64
---
Docker (cluster)
- Host: tcp://172.16.152.16:2376
- Version: 1.41
- Builder: 2
---
Docker (local)
- Host: Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.19.2
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: fb995098cbbad0847d48aebb30f3824a
- Repo:
</pre>
```

#### About Your Use Case
I can't set dynamic ingress.annotations which includes dots since all escapes which I try to use will be escaped by the Tilt helm template command.

**Comment by nicks** [comment]
I think this error is actually a new starlark/python3 thing. 

```
$ python -W error
Python 3.6.0 (default, Aug 14 2020, 13:07:49) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> x = "\."
  File "<stdin>", line 1
SyntaxError: invalid escape sequence \.
```

`"\."` is not valid in a python string. You need to do `"\\."` to make sure it gets passed through

**Comment by maiamcc** [comment]
@nikohaap did you get a chance to try to above?

**Comment by nikohaap** [comment]
I got it work

```
 tilt doctor
Tilt: v0.18.8, built 2021-02-03
System: darwin-amd64
---
Docker (cluster)
- Host: tcp://172.16.152.14:2376
- Version: 1.41
- Builder: 2
---
Docker (local)
- Host: Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.19.2
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: fb995098cbbad0847d48aebb30f3824a
- Repo:
```

````
$ cat Tiltfile

yaml = helm(
  './nginx',
  # The release name, equivalent to helm --name
  name='nginx',
  # The namespace to install in, equivalent to helm --namespace
  namespace='default',
  # The values file to substitute into the chart.
  # Values to set from the command-line
  set=[
	'podAnnotations.app\\.gitlab\\.com/app=testing'
  ]
  )
k8s_yaml(yaml)

```

```
Initial Build • (Tiltfile)
Beginning Tiltfile execution
Running: [helm template nginx /Users/nikohaap/tilt-issue/nginx --include-crds --namespace default --set
podAnnotations.app\.gitlab\.com/app=testing]
Successfully loaded Tiltfile (132.92047ms)

```

Deployment
```
$ kubectl get deployment 
....
  template:
    metadata:
      annotations:
        app.gitlab.com/app: testing
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: nginx
....
```

**Comment by nicks** [comment]
nice! Thanks for posting the working case!
