### ISSUE TITLE
No alerts tab in new UI

### ISSUE THREAD

**Issue by SupremeTechnopriest** [tilt-dev/tilt#4123]
## Describe the Feature You Want

The alerts tab disappeared in the new UI. Also cant figure out how to switch back to the old UI.  The old UI is better IMO.

**Comment by landism** [comment]
Thanks for the report!

> The alerts tab disappeared in the new UI.

Yep, we're still in the process of fleshing out the new UI. We just added this yesterday, and it will be in the next Tilt release:
![image](https://user-images.githubusercontent.com/7453991/105872891-ea10ce80-5fc8-11eb-8038-e2c9c30a640c.png)

> Also cant figure out how to switch back to the old UI

Yeah, it's unfortunately not super discoverable. I'll see if we can do something about that. In the meantime, you can find it here:
![image](https://user-images.githubusercontent.com/7453991/105871107-f98f1800-5fc6-11eb-8fef-a37cd7785b5d.png)

> The old UI is better IMO.

We're working on changing that. We're interested in concrete examples of things that are worse about the new UI.

Thanks!

**Comment by SupremeTechnopriest** [comment]
Thanks!  FWIW I love tilt and it makes my life way easier.  The main reason I love it is when I deploy, I can see all my logs easily while things are coming up. Saves me a ton of `kubectl logs` commands.  With the new UI, that dashboard view puts a few clicks in between me and the logs.  Another thing I like to do is go to ALL and monitor the alerts and dismiss them as they are resolved (making my pods all green).  When everything is all green I know my deployment is ready and at that point I generally close tilt.  I wouldn't want to accidentally update a template and have it deployed to my production environment. The dashboard view would be nice for an ops wall or something, but I generally don't use tilt for that.  More used for development and initial deployment of my helm charts.  Glad to see that the alerts are coming back.  Feel free to close this issue.

**Comment by landism** [comment]
Great, thanks for the feedback!
