### ISSUE TITLE
Tilt trying to send local image to docker.io

### ISSUE THREAD

**Issue by sirdawidd** [tilt-dev/tilt#4145]
Windows 10 enterprise (17763.1697)
Docker Desktop version: 2.5.0.1
Kubernetes 1.19.3 

New Windows users following the first example guide will encounter issues requiring some troubleshooting:

If the user opted for the curl method of installing Tilt in the Tilt installation guide (https://docs.tilt.dev/example_csharp.html), the "tilt up" command on the first example guide throws an error:

```
STEP 2/3 — Pushing appname
     Pushing with Docker client
     Authenticating to image repo: docker.io
     Sending image data

Build Failed: pushing image "docker.io/library/appname": denied: requested access to the resource is denied
```

kubectl config current-context
`docker-desktop`

Expected behavior, deploy image to local k8s not to docker.io

**Comment by nicks** [comment]
Thanks for the report @sirdawidd ! Can you post the output of `tilt doctor`?

fwiw, I just tried that example with my windows machine and it worked ok...and we have a few partner teams that use Windows. So I doubt it's quite as simple as "new windows users" but not sure what's going on. Usually Tilt should detect that docker-desktop is local and doesn't need pushing.

**Comment by sirdawidd** [comment]
Thanks for help,
The output of the command is as follows 
PS P:\> tilt doctor
Tilt: v0.18.6, built 2021-01-29
System: windows-amd64
---
Docker
- Host: Error: Cannot connect to the Docker daemon at npipe:////./pipe/docker_engine. Is the docker daemon running?
--

Which is strange because everything works fine on docker.
I'm using it on Hyper-v, and I have option enabled  Expose daemon on tcp://localhost:2375 without TLS

I can try on WSL

**Comment by nicks** [comment]
hmmmm...that usually means Docker isn't running when you ran Tilt doctor...in the logs above in the initial report, it looks like it was connecting to docker just fine?

**Comment by sirdawidd** [comment]
It means that tilt cant connect via npipe to docker, however docker on my pc working fine, how otherwise I can build the docker image? When I run tilt it build docker image step 3 is, as mentioned in initial task , checking via npipe if docker is alive, when it getting false its trying to send to docker.io (which is weird, rather should print error). 
I haven't enable wsl2 on docker and using hyper-v as this option require  ( Win 10 build 18362.1040+)
But I will try to run docker directly on wsl, instead of windows.

**Comment by sirdawidd** [comment]
Ok, what I did was install wsl on windows, reinstall docker desktop, and everything is working fine.

**Comment by nicks** [comment]
ok. i wonder if it got into a weird state. glad it works now, will keep an eye out for this in the future
