### ISSUE TITLE
Disabling local metrics via UI does not remove the resources from the K8s cluster

### ISSUE THREAD

**Issue by milas** [tilt-dev/tilt#4152]
### Expected Behavior
Disabling metrics should remove any K8s resources Tilt added to the local cluster.

### Current Behavior
Disabling metrics simply hides the graphs in the UI but does not remove the resources.

### Steps to Reproduce
1. Enable metrics from UI
2. Disable metrics from UI
3. Run `kubectl get all -l "app.kubernetes.io/part-of=tilt-local-metrics"` and see that resources are still present

(NOTE: We might want a way to disable _without_ removing resources, but IMO we should certainly offer an ability to clean up easily.)

### Additional Context
This came up in Slack because the metrics pods were preventing other pods from being scheduled due to a resource-constrained node:
> (pods are competing for some limited cpu on the nodes, making other pods not schedule)

**Comment by milas** [comment]
Do you think it makes more sense to keep this as a separate open issue or close in favor of #3137?

**Comment by nicks** [comment]
the local metrics UI has been removed!
