### ISSUE TITLE
M1 (darwin/arm64) builds

### ISSUE THREAD

**Issue by milas** [tilt-dev/tilt#4154]
## Describe the Feature You Want
* Native builds for Macs with M1 chips

### Current Behavior
* Tilt runs under Rosetta 2 emulation

**Additional context**
Support for `darwin/arm64` is part of Go 1.16, which should be stable in Feb 2021

**Comment by nicks** [comment]
as reported in https://github.com/tilt-dev/tilt/issues/4352, the Brew error message for this is pretty bad:

Error: Invalid formula: /opt/homebrew/Library/Taps/tilt-dev/homebrew-tap/ctlptl.rb
formulae require at least a URL
Error: Cannot tap tilt-dev/tap: invalid syntax in tap!

I also think we'll need to have ctlptl binaries on M1 too (though i think that will be much less work, just cutting binaries with Go 1.16)

**Comment by nicks** [comment]
v0.19.1 now has MacOS ARM binaries in alpha
