### ISSUE TITLE
determine tilt path

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4167]
## Describe the Feature You Want
A portable way to use `tilt` in local commands

### Why Do You Want This?
Some local commands need to re-invoke Tilt. But the user might not have tilt on PATH, or may have renamed the tilt binary to something else. For an example of this, see:

https://github.com/tilt-dev/tilt-extensions/pull/128

**Additional context**
Possible solutions:
sys.argv like in python, so you can use sys.argv[0]
os.Executable like in Golang https://golang.org/pkg/os/#Executable

**Comment by milas** [comment]
This is available with `sys.executable` as of 0.19.6+ (#4436)
