### ISSUE TITLE
tilt webserver 404s

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4185]
Bob in the #tilt channel writes:

> localhost:10351 404'd at first. After a restart, everything comes up, but after a few minutes a refresh will fail. At that point the root path loads, but then the console shows failing (404) XHR responses for /ws/view 

As far as I know, we haven't had any other reports about this, and I can't think of anything that would cause a problem like this. But I'm filing this to keep an eye out for it!

**Comment by KOGI** [comment]
![image](https://user-images.githubusercontent.com/1231996/107433248-efe4d480-6add-11eb-845d-a6eac88a482b.png)

**Comment by KOGI** [comment]
If it makes any difference, I'm running tilt v0.18.8 inside of WSL (Ubuntu 16.04), and didn't seem to be a problem until upgrading Tilt from 0.18.3 to 0.18.8. A minikube delete, docker restart, and full system reboot didn't seem to help.

**Comment by nicks** [comment]
does downgrading to 0.18.3 fix it? i looked through all the changes between 0.18.3 and 0.18.8 and didn't see anything that could plausibly cause this...

**Comment by KOGI** [comment]
@nicks about to try that... searching for docs about how to downgrade...

**Comment by nicks** [comment]
simplest way is unzip https://github.com/tilt-dev/tilt/releases/download/v0.18.3/tilt.0.18.3.windows.x86_64.zip and use the binary inside

**Comment by KOGI** [comment]
> simplest way is unzip https://github.com/tilt-dev/tilt/releases/download/v0.18.3/tilt.0.18.3.windows.x86_64.zip and use the binary inside

I ended up just changing the url for the "upgrade" script... `https://raw.githubusercontent.com/tilt-dev/tilt/v0.18.3/scripts/install.sh`

**Comment by KOGI** [comment]
After running `curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/v0.18.3/scripts/install.sh | bash`, Tilt actually reports its version now as v0.18.2 (looks like every tag actually lists the _previous_ version in its install script rather than the version for which the tag is named)

I am no longer seeing 404 errors.

Now bisecting to tag v0.18.5 (which tilt runtime reports as v0.18.4)...

**Comment by nicks** [comment]
ya, curling the install script will give you the previous release (since we can't update the install script until after we've done the release)

v0.18.2 was a botched release (somebody had their git client open to an ancient branch of tilt with some random edits on it when they tagged it) so isn't good for bisecting.

playing around with this on WSL...how long does it take for the 404s to start appearing?

**Comment by KOGI** [comment]
It seems inconsistent. Sometimes as quick as 30 seconds, other times it takes 2-3 minutes. However, 18.2 is still running strong even now.

**Comment by KOGI** [comment]
> ya, curling the install script will give you the previous release (since we can't update the install script until after we've done the release)

Just curious: why not just postpone tag creation until after the version is bumped?

**Comment by nicks** [comment]
goreleaser needs the release tag to exist before it will compile assets and attach them to the release page

if we bumped the version first, then there'd be a period where the install script didn't work because the release version didn't exist

there are ways around this, but doing it this way is pretty common in other Go projects I've looked at

**Comment by nicks** [comment]
are you able to repro the problem in any of the example repos? e.g. , https://github.com/tilt-dev/tilt-example-html ?

Trying to narrow down what might be different between your machine and my machine

**Comment by KOGI** [comment]
I apologize for not getting back to you on this. Things got busy. The good news is that now, with latest minkube, and latest Tilt (0.18.11) this seems to no longer be an issue!

**Comment by nicks** [comment]
wooo thanks Bob. Still curious what caused this, but maybe we fixed it accidentally :grimacing:
