### ISSUE TITLE
Web page is very unresponsive when there are a lot of logs coming from pods (Chrome)

### ISSUE THREAD

**Issue by mar-kolya** [tilt-dev/tilt#4196]
### Expected Behavior

There should not be slow down when there are pods that write a lot of logs 

### Current Behavior

When there are a lot of log events UI becomes very unresponsive and I often get 'Browser Tab is too slow' message.
This may be cause by jus large rate of events - I see `toCheckpoint` value in 100s of thousands after ~half a hour run.

Tilt version: v0.18.8, built 2021-02-03

### Steps to Reproduce

1.
2.
3.
4.

#### `tilt doctor` Output

```
$ tilt doctor
...
```

#### About Your Use Case
I do not think there is anything too special about the setup, but I do have a dosen services that actively writing logs and this seems to cause slowdown - especially if I leave tilt run for a while - this leads to UI being very-very slow.
Maybe as a stop-gap measure it would be possible to add an option to just disable k8s logs collection? We have other means to look at the logs and logs seem to prevent us form using other features.

**Comment by nicks** [comment]
good news! Tilt v0.18.9 just launched today - it has a "Clear Logs" button to clear the logs. 

I think we should also add some logic that auto-clears the logs when it gets too long

There's a separate request to disable log collection on a container-by-container basis https://github.com/tilt-dev/tilt/issues/3814

**Comment by mar-kolya** [comment]
Thanks! This may help  - how ever I often get into a state when browser cannot 'rerender' the tab when I switch to it - button is unlikely to help :(

**Comment by nicks** [comment]
this should be a lot better in v0.18.10!
