### ISSUE TITLE
quay.io auth errors

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4197]
We've received reports from one partner team of quay.io registry pulls failing with auth errors while Tilt is up. The error looks like this:

```
ImageBuild: failed to create LLB definition: unexpected status code [manifests 4.3.0]: 401 UNAUTHORIZED
```

But we've gotten mixed messages on why this happens and how to resolve it: They write:

> `docker login quay.io` sometimes fixes it but not always 

It's not clear if this is a Tilt issue or a Docker issue or a Quay.io issue. One hypothesis is that something about the Quay.io auth connection is expiring and for some reason Docker isn't refreshing the connection, but something on the Tilt side might re-initiate the auth handsshake

Related issues:
https://github.com/tilt-dev/tilt/issues/4043

**Comment by lizzthabet** [comment]
since we don't have a repro case and there haven't been additional comments, i'm going to close this issue.
