### ISSUE TITLE
Live Update Permission Denied

### ISSUE THREAD

**Issue by markgarrigan** [tilt-dev/tilt#4200]
### Expected Behavior

Live update should work.

### Current Behavior

Live update does not work and triggers a new build

Dockerfile
```
FROM docker.repo1.uhc.com/node:14-alpine

# Default value; will be overridden by build_args, if passed
ARG node_env=production

ENV NODE_ENV $node_env

WORKDIR /usr/app

ADD package.json .
ADD yarn.lock .
RUN yarn install

EXPOSE 4000 9229

ADD . .

ENTRYPOINT [ "node", "/usr/app/server.js" ]
```

Tiltfile
```
load('../dss-common/tilt/Config', 'dss_namespace')

k8s_yaml(helm('helm/dss-ez-api', set=['image=dss-ez-api-container'], namespace=dss_namespace))

docker_build('dss-ez-api-container', '.',
    build_args={'node_env': 'development'},
    entrypoint='npm run dev',
    live_update=[
        sync('.', '/usr/app'),
        run('cd /usr/app && yarn install', trigger=['./package.json', './yarn.lock']),
])
```

Error received in Tilt logs...
```
STEP 1/1 — updating image docker.repo1.uhc.com/optumiq_dsw/tilt/dss-ez-api-container
     Updating container: be1f86a5a2
Will copy 1 file(s) to container: be1f86a5a2
- '/Users/mgarriga/Development/dss/dss-ez-api/routes/index.js' --> '/usr/app/routes/index.js'
tar: can't remove old file usr/app/routes/index.js: Permission denied

Live Update failed with unexpected error:
	command terminated with exit code 1
Falling back to a full image build + deploy
```

### Steps to Reproduce

Use the dockerfile and tiltfile from the official Tilt.dev nodejs example then deploy it on our cluster. That last part will be rather difficult for you so you'll have to take my word for it. :)

#### `tilt doctor` Output
```
Tilt: v0.18.9, built 2021-02-12
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: unknown
- Context: oea-dev
- Cluster Name: oea-dev-cluster
- Namespace: dss-mark
- Container Runtime: docker
- Version: v1.18.3
- Cluster Local Registry: none
---
```

#### About Your Use Case

Just trying to get live update working with a nodejs app.

**Comment by nicks** [comment]
oof, sorry to hear about this.

We've seen some reports of this. It tends to happen when you've set permissions in the container to deny access to live_update. There is some related discussion on these issues: https://github.com/tilt-dev/tilt/issues/3060, https://github.com/tilt-dev/tilt/issues/3708. 

Tilt has somewhat limited ability to fix the permissions for you, though maybe there's something we can do here or have some better checks to inform you what's happening.

If you add 

```
USER root
```

to the dockerfile, does that fit the issue?

**Comment by markgarrigan** [comment]
@nicks That does not fix the issue. :(

**Comment by markgarrigan** [comment]
What's interesting is I have another service using these files and it works fine...

Dockerfile
```
FROM docker.repo1.uhc.com/node:15
WORKDIR /usr/app
COPY ./src ./src
COPY .npmrc package.json package-lock.json riot.config.js ./

RUN npm i
CMD npm start
```

Tiltfile
```
load('../dss-common/tilt/Config', 'dss_namespace')

docker_build('dss-ez-app-container', '.', dockerfile='Dockerfile.dev',
  live_update=[
    sync('.', '/usr/app'),
    run('cd /usr/app && npm run build'),
    run('cd /usr/app && npm install', trigger=['./package.json', './package-lock.json'])
])

k8s_yaml(helm('helm/dss-ez-app', set=['image=dss-ez-app-container'], namespace=dss_namespace))
```

One difference in the one that works is the COPY vs. ADD

**Comment by nicks** [comment]
Are you able to 'kubectl cp' files into the pod at that path? (Tilt is essentially doing a fancier 'kubectl cp')

Alternatively, you could 'kubectl exec -it bash' into the pod and look at the file permissions to see if there's anything unusual?

**Comment by markgarrigan** [comment]
I think I found the issue...

This was in the helm chart...
```
      securityContext:
        runAsUser: 2000
        fsGroup: 1001
```

changed that to...
```
      {{- if (default .Values.secure true) }}
      securityContext:
        runAsUser: 2000
        fsGroup: 1001
      {{- end }}
```

then in the Tiltfile set secure to false
```
k8s_yaml(helm('helm/dss-ez-api', set=['image=dss-ez-api-container','node=development','secure=false'], namespace=dss_namespace))
```

**Comment by victorwuky** [comment]
Thanks @markgarrigan. Any other problems? If not we’ll close out this issue.

**Comment by markgarrigan** [comment]
I think that solves it for this. Thanks @victorwuky and @nicks

**Comment by nicks** [comment]
thanks for letting us know! I also filed https://github.com/tilt-dev/tilt/issues/4206 to improve the error messaging here
