### ISSUE TITLE
Filter Resources

### ISSUE THREAD

**Issue by pusewicz** [tilt-dev/tilt#4203]
## Describe the Feature You Want

When running various services in a multi-service environment, it is difficult to find the resource in the list.

### Current Behavior
No way to quickly filter the resources in order to jump to it.

### Why Do You Want This?
It is difficult to find a resource, especially when some local or syncback resources are defined in a multi-service Tiltfile. Having the ability to fuzzy-match filtering of the names would greatly improve the experience.

**Comment by victorwuky** [comment]
Thanks for the feedback @pusewicz. Which version of Tilt are you using? Just wanted to see if you’re using a newer version with the newer UI.

**Comment by pusewicz** [comment]
I'm on 0.18.10 currently.

**Comment by pusewicz** [comment]
This has been implemented in https://github.com/tilt-dev/tilt/pull/4379
