### ISSUE TITLE
Update k8s_resource documentation and provide helm example

### ISSUE THREAD

**Issue by markgarrigan** [tilt-dev/tilt#4204]
## Describe the Feature You Want

The documentation should match the API reference.

### Current Behavior

The docs here https://docs.tilt.dev/resource_dependencies.html don't match https://docs.tilt.dev/api.html#api.k8s_resource

It's also unclear how to use k8s_resource with k8s_yaml(helm('path/to/chart/dir')). I "think" I "might" know but, I'd just be throwing darts.

### Why Do You Want This?

I want it to be a little easier to get started using helm with k8s_resources

**Comment by nicks** [comment]
Re: "The documentation should match the API reference"

Can you be more specific about what you expect to see, and how that differs from what you actually see? I looked at it a few times and didn't see the difference.

Re: how to use k8s_resource with helm() - ya, it's the name of the Kubernetes object. Will add this to the helm demo

**Comment by markgarrigan** [comment]
The method definition from the API reference
```
k8s_resource ( workload='' , new_name='' , port_forwards=[] , extra_pod_selectors=[] , trigger_mode=TRIGGER_MODE_AUTO , resource_deps=[] , objects=[] , auto_init=True , pod_readiness='' , links=[] )
```
The usage that the docs show
```
k8s_resource('frontend', resource_deps=['database'])
```
The string 'frontend' is not listed as a parameter in the docs.

The docs here https://docs.tilt.dev/accessing_resource_endpoints.html show the correct usage according to the API reference.

**Comment by nicks** [comment]
is the report that `k8s_resource(workload='frontend')` is different from `k8s_resource('frontend')`?

This is a starlark/Python language thing. From https://github.com/bazelbuild/starlark/blob/master/spec.md#functions:

> A call may provide arguments to function parameters either by position, as in the example above, or by name, as in first two calls below, or by a mixture of the two forms, as in the third call below. All the positional arguments must precede all the named arguments. Named arguments may improve clarity, especially in functions of several parameters.

```
idiv(x=6, y=3)		# 2
idiv(y=3, x=6)		# 2

idiv(6, y=3)		# 2
```

does that help?

**Comment by markgarrigan** [comment]
Thanks for the starklark/python lesson! I have zero clues about Python. This makes it understandable.

**Comment by nicks** [comment]
:+1: 

I've been writing python too long, my brain totally skipped over the difference between those two calls haha. Though I agree we should have a Helm example that demonstrates how it interacts with k8s_resource, posted one here: https://github.com/tilt-dev/tilt-helm-demo/pull/4

**Comment by markgarrigan** [comment]
👍 
Thanks @nicks! That'll work.

**Comment by nicks** [comment]
just closing the loom, tilt-helm-demo updates to use k8s_resource have been merged: https://github.com/tilt-dev/tilt-helm-demo/blob/master/Tiltfile
