### ISSUE TITLE
Tilt somehow groups multiple Services under the same workload that should go under their own

### ISSUE THREAD

**Issue by zkutasi** [tilt-dev/tilt#4233]
I have an App and I have a postgresql with Patroni making it HA and managing the Endpoints object of it.
Now I issue on the GUI a full reload of the App, and I observed that the Endpoints were deleted from the PGSQL Helm chart from my cluster, they simply have gone... which is caused by deleting the corresponding PGSQL service objects themselves (endpoints in this case cease to exist)... but those service objects "belong" to another workload, which has a workload resource in TIlt already (postgresql)... so I do not get why they were removed... but this causes that the Endpoint never gets re-deployed by Tilt from this point onward, and the App's connection to the service is forever broken, until I CTRL+C out and issue "tilt up" again.

### Expected Behavior
Tilt shall match workload service objects properly into workloads or provide a way to control the behaviour

### Current Behavior
After GUI-force-update on the APp, I see the following
Web Trigger • myapp:Deployment
STEP 1/6 — Force update
     Deleting kubernetes objects:
     → Deployment/myapp
     → Service/postgresql-replica
     → Service/postgresql
     → Service/myapp

As you can see triggering ONLY the App, the postgresql services get deleted as well, making the whole stack unusable. There is absolutely no connection name-wise between them.

### Steps to Reproduce
I think this is something to do with our Postgresql having a headless service, using Patroni and Endpoint objects are pushed onto the cluster in the Helm Chart itself.

#### `tilt doctor` Output

Tilt: v0.18.4, built 2021-01-13
System: linux-amd64
---
Docker
- Host: [default]
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: unknown
- Context: eea-esxi-871
- Cluster Name: kubernetes
- Namespace: default
- Container Runtime: docker
- Version: v1.16.2
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: e1517ad59ac720d252693580f2cc35e9
- Repo: yo/mTy2Z1+o8bs9QaT4BsQ==

#### About Your Use Case

Live update works properly it seems... but issuing a full tilt reload shall not be worse. This causes minor inconvenience now, because the workaround is there: use live update or re-tilt-up again.

I have a very custom Tiltfile already... and also I shall not disclose about our code... but could you tell me what determines how the services get "attached" to the workloads by Tilt and is there a way I can control this somehow? I have no idea why my App workload has multiple service objects attached, while those services have matching Workloads already... so maybe Tilt incorrectly matches them up? I feel the issue seems to be with the way postgresql works with patroni and a headless service... maybe Tilt in this case just guesses which workload the Service belongs to... wrongly in this case.

**Comment by zkutasi** [comment]
I have found I think the assembly code, here: https://github.com/tilt-dev/tilt/blob/6ea5b466a0ad0f5bd530e90fa81c09b22f2aef38/internal/tiltfile/tiltfile_state.go#L645
But to me it is way more complex that I could read...

**Comment by maiamcc** [comment]
Sorry to hear that Tilt is attaching services to the wrong deploys! If you're curious, [the relevant code is here](https://github.com/tilt-dev/tilt/blob/69c9019a9575d06671658a2d6b4816799d4034c6/internal/k8s/entity.go#L393) -- basically, if your Deployment has `metadata.labels` foo=bar and baz=quux, we will group in a Service if it has those same labels in `spec.selector`. 

I don't know why your services are being grouped wrong--could you send me a minimal repro case? All I need is some YAML that reproduces the problem.

**Comment by zkutasi** [comment]
Hi, sure, I will try to pack together some minimal repro case for you (currently it is a pretty big helm project)... my two "attaching" service objects have no selectors at all in them, they look like this (cleaned up private stuff a bit like annotations and naming):

```apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
  labels:
    app: postgresql
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/managed-by: tilt
    app.kubernetes.io/name: postgresql
    cluster-name: postgresql
  name: postgresql
  namespace: ns
spec:
  clusterIP: 10.108.19.165
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  - name: metrics
    port: 9187
    protocol: TCP
    targetPort: 9187
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
eea-esxi-871:~ #```

So we use Endpoints... and Patroni sets these endpoints, but not using selectors on this postgresql. I think this is because Patroni selects which postgresql is master, and this helm chart defines one service for master and one for replica... and so Patroni can set these dynamically, even if in case of mastership change.

I wonder in this case how Tilt behaves... where these Services will end up... as according to the above code and your explanation, they should not be selected. Something else selects them maybe.

Tomorrow I will try to create a very-very minimal test, even without patroni, just to see how this works (selectorless service + two Workloads)

**Comment by maiamcc** [comment]
Oh! No need for a test case, I know what's going on--Tilt says that your service "matches" the pod spec because the service has no selectors and therefore trivially matches any pod spec. I will push a fix.

**Comment by zkutasi** [comment]
Thanks very much Maia, very appreciated!
