### ISSUE TITLE
Helm/Go/Javascript Example?

### ISSUE THREAD

**Issue by kickthemooon** [tilt-dev/tilt#4238]
I have a project with a helm chart, a golang app and javscript app (webpack).

Using tilt I would like to be:
 - deploying the helm chart to my local minikube cluster 
 - updating the go app
 - updating the javascript app

I also have multi-stage dockerfiles for both applications

**Comment by maiamcc** [comment]
We unfortunately don't have anything that ties all three of those together, but you can check out our [example Go project](https://docs.tilt.dev/example_go.html), [example Node project](https://docs.tilt.dev/example_nodejs.html), and [Helm cookbook](https://docs.tilt.dev/helm.html). Let me know if you have any specific questions!

**Comment by kickthemooon** [comment]
ok, thanks.
