### ISSUE TITLE
Error/ Warning filters show that there are entries, but the log view is empty.

### ISSUE THREAD

**Issue by SupremeTechnopriest** [tilt-dev/tilt#4258]
### Expected Behavior

When the filters say there are errors or warnings selecting on the filter should display them.

### Current Behavior

The log area only shows headers of all the resources.  I think these are a little misleading and you can probably do without the headers. Especially when there are no errors or warnings to report for that resource.

![image](https://user-images.githubusercontent.com/2261598/109542351-cd5d3000-7a79-11eb-9b64-952ab46d7113.png)

### Steps to Reproduce

1. Deploy some resources that will throw warnings or errors.
2. Switch to the new UI .
3. Click the filter for warning/ error.
4. Observe the log area.

#### `tilt doctor` Output

```
$ tilt doctor

Tilt: v0.18.9, built 2021-02-12
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: docker-for-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.19.3
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: b07ff31bcc0852cb4ed113aa80c93207
- Repo: trjiT0Rdv7yICO5gwAvx0g==
```

#### About Your Use Case

Discussed with Han over a zoom call.

**Comment by nicks** [comment]
ooh thanks for the detailed report! @markgarrigan pointed this out to me this morning...i wonder if this is a recent regression

**Comment by nicks** [comment]
fixed by https://github.com/tilt-dev/tilt/pull/4285
