### ISSUE TITLE
Automatically join multiple projects together in the UI

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#4278]
## Describe the Feature You Want

Right now, `tilt up` has the behavior of accepting a `port` argument, which lets you have multiple instances of tilt running at the same time.

However, it looks like recent updates of tilt have become slightly greedier with ports. Previously I could run `tilt up --port 10350` and `tilt up --port 10351` and they would run simultaneously without issue.

Now what appears to happen is that `tilt up --port 10350` will use up port `10350`, but also a few additional as necessary, making me have to kind of guess which port to select.

I know that I could simply figure out the port behavior and call it good, but I'd prefer that if running `tilt up` on multiple folders talked to the current "main" session, and merged the two sessions together in the UI. That way I don't need multiple tabs for each of these sessions, when really I'm trying to use all of them at once, and being split out into multiple tabs is really not the ideal experience, rather it's just kind of the default expectation when running local services.

Not saying it would be easy, but if I could just `tilt up` everything I want and have each individual session communicate with a "main" session (and be broken down in the UI accordingly), that would be a really great UX, especially for those of us that spin up many projects at once, condensing everything down into one tab.

It would also be fairly nice to be able to `tilt down` a session/list of resources via a button in the UI once this is exposed, because the session itself becomes an entity in the UI. The only question of this bit is if the first `tilt up` is the "main" session, what happens if you run `tilt down` on it?

### Why Do You Want This?

- No fussing with ports
- `tilt` effectively becomes an "always there" service (at least, in the user's head); a single tab that is almost always open, rather than feeling like one of many local servers.
- No rummaging through folders in the CLI to spin up commonly-used projects

### Doors/cans of worms this could open
- `tilt up/down` previous sessions/projects in the UI via history/Least Recently Used
- tilt automatically starts as a service, runs local scripts, spins up projects at boot
- Project-level dependencies?

**Comment by landism** [comment]
Making tilt more daemon-y and giving the user more control over adding and removing things is a thing we've discussed and are interested in but haven't yet prioritized.

> Now what appears to happen is that tilt up --port 10350 will use up port 10350, but also a few additional as necessary, making me have to kind of guess which port to select.

This sounds really annoying and I think is worth sorting out sooner rather than later as a bug/separate issue.

Also, even without the recent behavior change you describe, fussing with even just the one port is annoying and we should fix that. Linking #3434 as related issue.

**Comment by nicks** [comment]
> However, it looks like recent updates of tilt have become slightly greedier with ports. Previously I could run tilt up --port 10350 and tilt up --port 10351 and they would run simultaneously without issue.
> Now what appears to happen is that tilt up --port 10350 will use up port 10350, but also a few additional as necessary, making me have to kind of guess which port to select.

Hmmmm...can you be more specific about what you're seeing? I was not able to reproduce this issue.

doing an `lsof -p [PID] | grep LISTEN` seemed to show it only listening on one port when I tried it with Tilt v0.18.11

**Comment by kevin-lindsay-1** [comment]
@nicks https://github.com/tilt-dev/tilt/issues/4282

**Comment by nicks** [comment]
@kevin-lindsay-1 also, for what it's worth, we're currently working towards a tilt architecture that's more a general-purpose apiserver (https://github.com/tilt-dev/tilt/issues/4013). I'm pretty sure will enable the exact ergonomics you're looking for here (i.e., merging two sessions together in the UI). But it's a big technial lift. I think this feature request is independently super useful as a description of a workflow that we want to enable.

**Comment by kevin-lindsay-1** [comment]
@nicks I agree. It's less a true feature request and more a raising an entire road in the roadmap for discovery
