### ISSUE TITLE
expose process info of tilt via api

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4283]
A dev flow that a few teams have tried to build is something that looks like this:

```
up:
  // run tilt in the background

down:
  // stop tilt process in the background
```

currently, the best way to do this is with some combination of `tilt up &` and `pkill tilt`

I think my ideal api here would be for the new apiserver (https://github.com/tilt-dev/tilt/issues/4013) to expose a PID of the running tilt server and give people tools to script that but i can also imagine other apis

**Comment by nicks** [comment]
As of Tilt v0.19.6, you can do this with the session API like so:

```
pid=$(tilt get session Tiltfile -o jsonpath --template '{.status.pid}')
kill $pid
```

**Comment by milas** [comment]
Closing this as the PID is available from the `Session` API for use in scripting. See the example above from Nick.
