### ISSUE TITLE
apiserver compliant resource naming validation

### ISSUE THREAD

**Issue by milas** [tilt-dev/tilt#4309]
As we migrate to apiserver internally for Tilt entities, we need to ensure that they pass validation,
i.e. they have acceptable names + label values based on the rules.

Currently, only `Cmd` + `FileWatch` are in the process of being written to apiserver, but we don't
want to have a constant stream of "breaking" changes as validation gets stricter on an entity-by-entity
basis, so it's probably best to enforce this consistently upfront with additional validation even for
entities not being stored in apiserver (yet).

#### Names
> must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character

*Regex*
```
([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]
```

(See [validation.go](https://github.com/kubernetes/apimachinery/blob/2456ebdaba229616fab2161a615148884b46644b/pkg/util/validation/validation.go#L33-L34) from `k8s.io/apimachinery`)

#### Labels
> a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character

*Regex*
```
(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?
```

(See [validation.go](https://github.com/kubernetes/apimachinery/blob/2456ebdaba229616fab2161a615148884b46644b/pkg/util/validation/validation.go#L155-L159) from `k8s.io/apimachinery`)

### Tiltfile: User Controlled Names (e.g. "resource" names)
We can make a one-time breaking change to make the validation stricter across all of these using the apiserver name regex. This is probably unlikely to affect too many users - the most likely offending character that might exist is `/`.

### Tiltfile: External Names (e.g. image refs)
Unfortunately, any image refs with a registry (e.g. `gcr.io/foo`) or tag (e.g. `bar:latest`) won't be valid, and we'll want to both use these as a labels (e.g. for `FileWatch` to indicate the target that it belongs to) as well as entity names in the future as images are migrated to apiserver.

Annotations do NOT have any constraints on character set for their value, so we can also use annotations where appropriate. For example, a sanitized label value might be appropriate for use as an opaque handle/reference, but the annotation value could be suitable for display or actual business logic. 

We'll probably need to apply a sanitization here, replacing any non-valid characters with `_`, for example.

**Comment by nicks** [comment]
I wonder if we can sanitize cmd + filewatch names for now, and punt this down the field a bit...

**Comment by nicks** [comment]
on the other hand, most existing Manifest names are inferred from kubernetes resources / docker-compose service names, so probably already obey this rule. the big exceptions are:
- local_resource names
- resources that have been manually renamed (with new_name)
- The special `(Tiltfile)` resource

**Comment by nicks** [comment]
for reference:

As far as I can tell, API server doesn't do any validation of names, but we could add some here:
https://github.com/tilt-dev/tilt-apiserver/blob/main/pkg/server/builder/rest/strategy.go#L98
or in the type-specific validators

Here's the validator that Kubernetes currently uses for CRDs:
https://github.com/kubernetes/kubernetes/blob/0cba30d891cb77e813d7f19dcc5ae422076fcfe3/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/validator.go#L44

At HEAD, if you try to create a local_resource with a slash in it, the client code will complain here:
https://github.com/kubernetes/kubernetes/blob/40a411a61af315f955f11ee97397beecf432ff4f/staging/src/k8s.io/client-go/rest/request.go#L272

since the underlying architecture doesn't know how to construct a well-formed request to the API server

**Comment by nicks** [comment]
@milas where did you find the rules above on apiserver contstraints/validation?

One of the interesting exceptions is underscores, which some things allow and some do not.

I checked docker-compose, which doesn't have anything about valid names in the spec, but does give me an error if I try to specify a service name with spaces:
> Invalid service name '_ _' - only [a-zA-Z0-9\._\-] characters are allowed

**Comment by milas** [comment]
Updated orig issue with links, but it's in [validation.go](https://github.com/kubernetes/apimachinery/blob/2456ebdaba229616fab2161a615148884b46644b/pkg/util/validation/validation.go#L30-L34) in `k8s.io/apimachinery`.

And yep, some things follow "DNS" rules and are stricter - no `_` and 63 char max:
* https://kubernetes.io/docs/concepts/overview/working-with-objects/names/ 
* https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

**Comment by milas** [comment]
Agreed!

What are your thoughts on making this a breaking change right now vs adding some temporary sanitization logic?

I think we'll always have some resource types that Tilt will need to handle automatic sanitization for, e.g. images, since there's no way to give a valid ref that will conform to apiserver constraints. Given that, I don't think it's the worst thing to apply it more broadly for the moment if we want to hold off on a breaking change around manifest names for a bit.

**Comment by nicks** [comment]
I'm going to send out a proposed pr in a bit with some validation; just want to have end-to-end testing for it with a real apiserver

**Comment by nicks** [comment]
i misunderstood something, here's where the validation happens now - https://github.com/kubernetes/apiserver/blob/master/pkg/registry/rest/create.go#L112

just need to do this validation earlier, during initial resource creation

**Comment by milas** [comment]
Do you think we should publish a blog post alerting to the change or just post a notice in the GitHub release notes? The error message is pretty self-explanatory and tweaking names is hopefully fairly quick for users.

**Comment by nicks** [comment]
ya, let's throw it in the release notes. I want to write a blog post on why we're moving to an API server, which i think should also explain why the api is changing
