### ISSUE TITLE
Pause updates for a particular resource

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#4314]
Currently, when working on a service, live updates are a godsend, but sometimes you want to make changes to multiple files, and doing that causes an "update queue" to happen, where each change causes a successive update.

To get around this, the best way I currently know how is to stop tilt, but then my local scripts that only run once all need to run again, which isn't ideal.

Cancelling live updates, condensing their file output, and then re-running would probably be ideal, but in the immediate, a "pause" button on a particular resource to prevent further updates would be nice.

**Comment by maiamcc** [comment]
We currently have the ability to toggle auto updates on/off for tests -- would be pretty easy to extend that to all resources!

**Comment by nicks** [comment]
The new table view has a column called Trigger Mode that does this! Setting it to "Manual" will pause updates into you trigger them manually.
