### ISSUE TITLE
[Question] How to categorize duplicates?

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#4317]
When using `k8s_resource`, you can associate a particular uncategorized resource with another resource.

You can also specify `allow_duplicates` when creating things with `k8s_yaml`, which is what (as of the other day) `namespace_create` does, as well.

In my particular case, using nested tiltfiles, this causes the namespace to be an uncategorized resource, and it creates duplicates as expected, but I can't make a selector that can categorize them because they're duplicates.

What's the best approach here? Having a tiltfile create a namespace is really nice, but not being able to select them isn't ideal.

To me, a namespace isn't necessarily a resource itself but more of a background thing, so maybe they could just be ignored rather than associated to a resource. Maybe adding a function like `ignore_uncategorized(objects: string[] = [])`.

That, or maybe they could be made part of the UI in a way that shows that they were created, but aren't really "foreground" things.

**Comment by milas** [comment]
See #3993 for issue around selectors being problematic in scenarios like this.

I'll keep this open as I think there's at least a couple _other_ possible feature requests/avenues in here:
* Combine _true_ duplicates, i.e. same selector + identical YAML (I'm not sure if this is feasible)
* Deeper/more explicit namespace support directly within Tilt beyond `k8s_yaml` + `namespace` extension
* Allow filtering/hiding certain objects/object types from UI as suggested in this issue
