### ISSUE TITLE
[Feature Request] Cross-platform/shell local scripts

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#4330]
## Describe the Feature You Want

Tilt is a great workflow tool, and it works really well when everyone is working in the same general style.

It would be really nice to have an updated `local`/`local_resource` or variant them which detects which OS/shell you have, and issue a command for each variant.

Something along the lines of:

```starlark
local(mac='cp ...', windows='copy ...')
```
or if you base it on shell,
```starlark
local(bash='cp ...', cmd='copy ...')
```

You might be able to have both via something like `local(detect='os')` `local(detect='shell')`, or just separate functions that wrap `local` and `local_resource`. Maybe shell detection would be more reliable than OS detection.

### Current Behavior

As far as I've seen, right now you'd have to implement this logic yourself, which would make things a little more logically complex, when you're pretty much trying to do one specific thing but different environments might require slightly different commands and/or syntax.

### Why Do You Want This?

So that in a multi-OS environment, like an open-source team, it's really easy to pitch and have very little speedbumps.

**Additional context**

**Comment by nicks** [comment]
Hmmmm...all our built-ins have a shell and Windows batch command option. For local(), it looks like: local(command='...', command_bat='...'). See:

https://blog.tilt.dev/2020/05/20/windows-support.html
https://docs.tilt.dev/api.html#api.local

We borrowed the convention from other cross-platform tools like Bazel. Does that work for your needs?

**Comment by kevin-lindsay-1** [comment]
That looks like it will work for my purposes, I'll test it out and re-open this if it not. Thanks!

**Comment by majidaldo** [comment]
I don't think cross-platform tools ia a problem for tilt to solve. You could just do everything in a cross-platform language like Python but that requires an extra step for simple one-liners. What Tilt could do is have some kind of default shell config. if you have something like git for windows then 'sh -c' for the shell can work.

I'd like this for custom_build. Most times the only difference b/w the two platform commands is just $VAR vs %VAR%! So I was wondering if the Tilt team can just implement this as a convenience!
