### ISSUE TITLE
run(trigger) support glob syntax or equivalent

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#4347]
## Describe the Feature You Want

It would be really nice to use glob syntax for `live_update(run(trigger))`, because based on my testing and reading the docs there is no way to watch a pattern rather than a specific file or entire directory.

### Current Behavior

If I specify a common glob path like `./src/**/*.js`, it does not run that specific step for that specific trigger.

Instead, I have to do everything against the entire `src` directory, running all of my rebuild operations that can differ based on file type.

For example, I use graphql files to specify a schema, and there's a simple build step for copying files into the build directory. When I update a typescript file, it copies the graphql files even though there was no `.{gql,graphql}` change.

### Why Do You Want This?

Right now live updates are actually slower for me than doing a full rebuild, because certain tools like `nodemon` take a little longer to initially spin up. This isn't much of a problem when watching works correctly, but right now it's running every single type of live update command even when a file would not be updated.

**Comment by nicks** [comment]
thanks for the report! I'm going to de-dupe this against https://github.com/tilt-dev/tilt/issues/1818, please throw your thumbs-up there!
