### ISSUE TITLE
Invalid formula thrown by the installation script on Apple M1 chip

### ISSUE THREAD

**Issue by bedeabza** [tilt-dev/tilt#4352]
### Expected Behavior
I am trying to install Tilt via the official installer with:
```curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash```

### Current Behavior
```Cloning into '/opt/homebrew/Library/Taps/tilt-dev/homebrew-tap'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 428 (delta 38), reused 0 (delta 0), pack-reused 365
Receiving objects: 100% (428/428), 59.64 KiB | 1.19 MiB/s, done.
Resolving deltas: 100% (273/273), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/tilt-dev/homebrew-tap/ctlptl.rb
formulae require at least a URL
Error: Cannot tap tilt-dev/tap: invalid syntax in tap!
```

### Context
OS X 11.2.3 on MacBook Air M1 2021 (arm64)

**Comment by nicks** [comment]
thanks for the report! Ya, i think this is simply reporting that there are no M1 binaries yet. Brew's error message for that case is not great. I'm going to de-dupe this under https://github.com/tilt-dev/tilt/issues/4154, please thumbs-up that issue!

**Comment by nicks** [comment]
v0.19.1 now has MacOS ARM binaries in alpha
