### ISSUE TITLE
Way to load built images directly into cluster, without pushing/pulling them?

### ISSUE THREAD

**Issue by fgielow** [tilt-dev/tilt#4356]
Hello,

Currently in Tilt, all the images defined on my docker_build cycle need to be pushed to the remote registry so they can be pulled into my clusters nodes.  In order to save bandwidth and speed up things (some developers might have poor connection speeds), I've been trying to build the image locally and load that into my cluster directly through a custom_build, without needing to push that to our registry first.

```
custom_build ('ghcr.io/arbncoltd/renew_angular_web',
    "docker build ./renew_frontend -t $EXPECTED_REF --target angular_app_base && " +
    "k3d image import --cluster renewcl $EXPECTED_REF",
    ["./renew_frontend"],
    disable_push=True,
    live_update=[
        sync('./renew_frontend/','/usr/src/app/'),
        run('cd /usr/src/app/ && npm install', 
            trigger=["./renew_frontend/package.json", "./renew_frontend/package-lock.json"]
        )
    ]
)
```

But that of course does not work because the EXPECTED_REF is local to my host only, while the tag used inside the cluster is different, as it is content-aware.

Nevertheless - is there any way for such content-aware tag to be built and loaded to my cluster locally? If I built the image locally and my cluster is also local on dev environment, it does not make much sense to need to push that so it's pulled again. 

I am diving head first into Tilt but I did some research, so I am sorry if I have missed any obvious solutions.
Thanks in advance!

**Comment by nicks** [comment]
Have you tried k3d's local registry feature?

https://k3d.io/usage/guides/registries/#using-a-local-registry
https://docs.tilt.dev/choosing_clusters.html

We've worked with k3d team to make sure tilt aito-detects it. It's the best way to get images into the cluster

**Comment by fgielow** [comment]
> Have you tried k3d's local registry feature?
> 
> https://k3d.io/usage/guides/registries/#using-a-local-registry
> https://docs.tilt.dev/choosing_clusters.html
> 
> We've worked with k3d team to make sure tilt auto-detects it. It's the best way to get images into the cluster

This worked flawlessly! Thanks very much.
