### ISSUE TITLE
support kustomize with plugins

### ISSUE THREAD

**Issue by ssetti** [tilt-dev/tilt#4361]
## Describe the Feature You Want

Currently if I have kustomize installed with plugins, the kustomize built-in command should work with plugins (e.g. if I have a kustomize-sops plugin).

### Current Behavior

Currently if I have kustomize installed with plugins, the kustomize built-in command does not invoke those plugins.

### Why Do You Want This?

This will enable for us to use mostly the same artifacts through from dev to prod

**Additional context**

**Comment by nicks** [comment]
Can you try replace thing `kustomize()` call with `local('kustomize build --enable_alpha_plugins .')` and see if that works?

Background: Tilt's kustomize() built-in is mostly a wrapper around `local('kustomize build ...')`, with some small ease-of-use improvements. 

Looks like `kustomize build` doesn't run plugins by default unless you use the --enable_alpha_plugins flag (see: https://kubectl.docs.kubernetes.io/guides/extending_kustomize/#no-security). 

But it'd be good to double-check that  sure this works for you so you don't have to wait on the next Tilt release to find out - I'm not super familiar with kustomize plugins and there might be other gotchas

**Comment by ssetti** [comment]
Thanks @nicks for the suggestion.  I have already used this approach and its working fine.  I am going to close the the request.
