### ISSUE TITLE
live updates triggered on .git/index.lock

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4370]
I'm seeing lots of spurious live updates triggered when .git/index.lock changes, which is not right. Think we broke something here.

**Comment by nicks** [comment]
fixed in v0.19.1!

**Comment by kinan66** [comment]
I am using v0.33.6, and I suddenly started having this problem. any suggestions on what can I do?

**Comment by nicks** [comment]
@kinan66 sad to hear that! can you file an issue with a repro case?
