### ISSUE TITLE
Parallel `helm` and `kustomize` rendering.

### ISSUE THREAD

**Issue by omh1280** [tilt-dev/tilt#4378]
## Describe the Feature You Want
In a monorepo with many microservices, helm/kustomize rendering takes some time (10+s with our usecase). If Tilt could do this work in parallel I think there would be a noticeable performance improvement.

### Current Behavior
When Tilt reloads Tiltfiles, it must render out all Helm/kustomize charts and it does so in serial. This scales linearly with the number of Helm/kustomize calls, which can be large for a monorepo with microservices.

### Why Do You Want This?
Monorepo with microservices use case. Not all microservices are launched, but this doesn't matter because Tilt must load all of their Kubernetes YAMLs to be aware of them.

**Comment by nicks** [comment]
Hi @omh1280 ! Thanks for reporting. Ya, this makes sense.

Short version: Tilt doesn't have great APIs for this right now. Currently, Tilt has a two-step architecture: read in all the image specs / YAML, then parallelize the build/deploy. This doc explain it in more depth: https://docs.tilt.dev/controlloop.html

The downside of this architecture is that we can't easily parallelize things that generate YAML. There's some good discussion on this issue: https://github.com/tilt-dev/tilt/issues/3046

We're working on a richer API that should make it a lot easier to parallelize these kinds of things. If you need a short-term solution, your best bet is probably to have a local() call that parallelizes it outside of Tilt and dumps the yaml somewhere that tilt can read in.

**Comment by omh1280** [comment]
Thanks for the explanation @nicks ! That temporary solution suffices for now. We look forward to the richer API :)

**Comment by nicks** [comment]
we have some new primitives for generating k8s resources async!

here's a post on how to do it for arbitrary scripts: https://blog.tilt.dev/2021/12/03/k8s-custom-deploy.html

and here's a post on how we do it to parallelize helm_resource - https://blog.tilt.dev/2022/01/26/helm-improvements.html

(sent to @omh1280 on another thread and re-posted here)
