### ISSUE TITLE
`tilt down` doesn't account for resource_deps

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#4431]
### Steps to Reproduce
1. define a Tiltfile with two resources. "m2", which has a resource_dep on "m1", and "m1".
2. `tilt down`

### Expected Behavior
`tilt down` deletes m2's k8s entities before m1's

### Current Behavior
`tilt down` deletes m1's k8s entities before m2's (at least, it can--depends on declaration order)

#### About Your Use Case
`tilt down`'s current behavior is basically to delete resources in the order of `reverse(k8ssort(allManifests.flatMap(m => m.entities)))`, where k8ssort is a function that simply orders entities [by kinds](https://github.com/tilt-dev/tilt/blob/334baabc141cfe72b2f49a35de5d46230d090991/internal/kustomize/ordering.go#L32), where, e.g. deployments always come after namespaces and configmaps. This is because we want to ensure we, e.g., delete namespaces after the deployments that contain them, or configmaps after the deployments that depend on them.
If there is a dependency not covered by that entity order (e.g., the argo crd EventBus and its controller), then Tilt might try to delete them in the wrong order, leading to a failed deletion.

**Comment by landism** [comment]
When I wrote this, I thought it'd be a cheap fix of deleting entities in reverse topo order of manifests (e.g., `reverse(topo(allManifests)).flatMap(m => k8sSort(m.entities))`, but that has its own problem:
Currently, by default, lots of k8s objects end up in 'uncategorized', including namespaces and configmaps. If we don't do a global sort by k8s kind, then we need some other way to ensure that uncategorized's namespaces and configmaps get deleted after some resource's deployment. We could add logic to put uncategorized first, but there might be other rules to follow and we don't want to reimplement the build control rules as part of `down`.
It seems like we should look into refactoring the build controller so that `down` can reuse its logic, but in reverse. Unfortunately, the build controller doesn't simply generate a build order, but rather just picks the next available thing to build, one at a time. I suspect making it reversible is sufficiently non-trivial that this bug needs more evidence to justify prioritizing.

**Comment by landism** [comment]
Users should be able to work around this by ensuring that affected k8s objects get deleted first on `tilt down`, e.g.:
```
if config.tilt_subcommand == 'down':
  local('kubectl delete EventBus MyEventBus')
```

**Comment by adamf** [comment]
We see this, especially with PersistentVolumes and PersistentVolumeClaims that end up with finalizers.
