### ISSUE TITLE
clear logs does not clear warnings

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4472]
### Steps to Reproduce
1. Check out https://github.com/tilt-dev/tilt.build
2. Run tilt up
3. Kill one of the pods so it restarts
4. Observe that the resource status turns yellow
5. Click clear logs

### Expected Behavior
The resource status should be green

### Current Behavior
The resource status remains yellow

#### About Your Use Case
I feel like this used to be something we handled well, but dropped it on the move to the new UI

**Comment by andymartin-sch** [comment]
just want to bump this issue once :)

the combination of this + https://github.com/tilt-dev/tilt/issues/3483 means that "normal"/successful use of Tilt results in a few warning/yellow colored services in the left sidebar and there's nothing that the user can do to get the color back to green once the warnings are resolved / no longer an issue

**Comment by nicks** [comment]
thanks @andymartin-sch ! let me poke at this a bit. we've done some major revamps to how the tilt ui works that might make this easier
