### ISSUE TITLE
Tilt (post 19) truncates useful logs

### ISSUE THREAD

**Issue by adamf** [tilt-dev/tilt#4476]
### Expected Behavior
A process' full logs should be available.

### Current Behavior
A process logs a lot of data - a few thousand lines, say - and while scrolling thru these logs to find the issue the logs suddenly truncate and jump to the last log lines, leaving only a page or two of logs left. This means we can't find important data - stack traces, failures in test suites, etc.

### Steps to Reproduce
1. Run a process that generates a lot of logs
2. Scroll around
3. The logs get cut off

#### `tilt doctor` Output
OS X latest, tile 0.19.1-6, hyperkit driver. 

#### About Your Use Case
We've had to roll back to 0.18.x. We can't use tilt if the logs don't work. This is particularly impactful in the test suite cases, where, say, 200 tests run and 4 fail early and log their traceback early in the run. Those tracebacks get lost with 0.19.x

That said, the logs do take up a bunch of browser memory over time. Perhaps the logs could truncate after x resource restarts, but always keep the full logs of a resource run?

**Comment by adamf** [comment]
Also see https://kubernetes.slack.com/archives/CESBL84MV/p1617637043068000

**Comment by nicks** [comment]
hmmm....thanks for reporting. For what it's worth, Tilt has always truncated logs. Otherwise it would grind to a halt. We can't realistically keep all logs. For an example, see: https://github.com/tilt-dev/tilt/issues/3936

I think the algorithm for truncation changed a bit in v0.19, so it would be helpful to have an example of a server configuration where tilt was discarding useful logs...

**Comment by adamf** [comment]
@nicks for us it's the test case example - we have something like 200 unit tests for one of our applications and when you run the full test suite the log truncation in 19+ removes most of the logs a short time after the tests finish, which means you can't go back and see why some tests failed. This doesn't happen in 18 (it does truncate, but it leaves plenty for research).

**Comment by nicks** [comment]
how long are the logs for the tests? i think the current cap is about 1MB. The test server I usually use logs about once every 10ms, and it goes awhile before Tilt truncates anything. I think the main thing that changed is what we decide to truncate first.

**Comment by nicks** [comment]
(we could just bump it to 2MB, but i'm worried that something else is happening that's particular to your setup that we need to be able to repro to fix)

**Comment by adamf** [comment]
We have 32 resources in our tilt config, about 15 of them actual services that are logging something (typically health check responses) every few seconds, then logging a lot of requests when using the local tilt instance. The test runs go for around 14 minutes and log near-constantly that whole time. 

Nothings changed about that since we upgraded to 0.19.x. How did the picker for what to truncate change?

**Comment by adamf** [comment]
(I'm actually shocked we don't hit 1MB of logs in like.. 10 minutes even on an idle cluster - even our health check logs are like 120 bytes each, so only takes something like 8500 log lines to hit 1MB)

**Comment by nicks** [comment]
ah, that's interesting. 

It used to truncate purely based on recency, but that disfavored servers that weren't chatty but logged important info.

Now it truncates the most chatty service first.

I wonder if what's happening here is that, because you have a lot of services, they're filling up the log buffer, but the test has MORE logs, so it's truncating the tests before the services.

So maybe the answer here is that we should weight by both how chatty the services is and by recency. hmmm...

**Comment by nicks** [comment]
let me test it at 2MB and with an algorithm that rates recency more

**Comment by nicks** [comment]
ah wait the reason we capped it at 1MB is to keep initial page load fast as well, as per this comment https://github.com/tilt-dev/tilt/issues/3359#issuecomment-632139740

I think weighting by recency will still help here though

**Comment by jmo-qap** [comment]
@adamf this bug appears to be different bug than another we're experiencing which is no new logs being shown after a few service rebuilds and restarts

**Comment by nicks** [comment]
Try out tilt v0.20 and see if that helps! I think it should work a lot better in this case - the log limit is much higher and truncates more by recency
