### ISSUE TITLE
trigger_mode=TRIGGER_MODE_MANUAL, auto_init=False doesn't work for serve_cmd-only resources

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4548]
```
local_resource('serve-cmd',
               serve_cmd='echo 🤐; sleep 100000',
               trigger_mode=TRIGGER_MODE_MANUAL, auto_init=False)
```

basically, neither of these commands ought to run without user intervention. the former (an update cmd only) behaves as expected; the latter (a serve_cmd) runs even tho it shouldn’t

You can work around it by adding an update cmd

**Comment by milas** [comment]
This is fixed in [v0.20.4](https://github.com/tilt-dev/tilt/releases/latest).
