### ISSUE TITLE
Running Python scripts with `local_resource` doesn't log output until after the process exits

### ISSUE THREAD

**Issue by theothertomelliott** [tilt-dev/tilt#4558]
### Expected Behavior

When running in a `local_resource`, stdout and stderr output from Python scripts is shown in the Tilt UI as soon as it is output.

### Current Behavior

The output does not appear until the script exits, both for `cmd` and `serve_cmd` commands. In the case of `serve_cmd`, this means that you only see output if the process fails.

### Steps to Reproduce

We're using Python 2.7.17 (upgrading could be an option).

1. Create a Python script called `test.py` with the content:

```
import time

print("Printed immediately.")
for i in range(10):
    time.sleep(1)
    print("Tick.")
```

2. Create a Tiltfile to use this script:

```
local_resource("python", cmd="python test.py")
```

3. Run `tilt up` and open the UI for the resource (e.g.: http://localhost:10350/r/python/overview)

#### `tilt doctor` Output

```
Tilt: v0.20.3, built 2021-05-14
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: docker-for-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.19.7
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: e604148f7c70ace56491ba47f54be49c
- Repo: 
```

#### About Your Use Case

We're seeing some of our local resources failing when run with Tilt, but not when run directly from the Terminal. The delayed output may be related, but even if not, it's making it difficult to diagnose the root cause.

**Comment by nicks** [comment]
Oh boy I know this issue. This has given me nightmares.

pre-Python 3.7, Python would try to "intelligently" buffer output, but sometimes makes the wrong decision.
https://docs.python.org/3/using/cmdline.html#cmdoption-u

You can fix it with either `python -u`, or PYTHONUNBUFFERED=true

I would personally be fine with making Tilt run all local scripts with PYTHONUNBUFFERED set by default

**Comment by theothertomelliott** [comment]
That did the trick, thanks! And gave us some extra output we'd somehow missed entirely.
