### ISSUE TITLE
Where do I send my money?

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#4601]
I use this project a bunch for free right now.

Not super interested in the paid version for my usage, but I'd still like to support the project. I didn't see any kind of donation or GH sponsorship links.

How can I make you take my money?

**Comment by nicks** [comment]
Hehe, thanks @kevin-lindsay-1 . 

We're not accepting donations right now. The best way to support the project right now is by coming to Tilt office hours when you have feedback (https://github.com/tilt-dev/tilt#community--contributions), or to schedule some time with the Tilt Liftoff program if you've got a major service or team you want to get set up with Tilt (https://tilt.dev/liftoff)

(I know you've been coming to office hours :), just wanted to note it for anyone who stumbles on this issue)
