### ISSUE TITLE
DOCKER_HOST using ssh protocol makes tilt up fail

### ISSUE THREAD

**Issue by temal-** [tilt-dev/tilt#4603]
### Expected Behavior

`tilt up` works when using SSH protocol in `DOCKER_HOST` environment variable

### Current Behavior

tilt up fails with

```
Beginning Tiltfile execution
Successfully loaded Tiltfile (10.47725ms)
Failed to connect to Docker: error during connect: Get "http://user%40host/v1.24/version": dial tcp: lookup user@host: no such host
```

when using `DOCKER_HOST=ssh://user@host`.

### Steps to Reproduce

1. set `DOCKER_HOST` to use ssh protocol (e.g. `export DOCKER_HOST=ssh://user@host`)
2. create Tiltfile containing `docker_build` function
3. run `tilt up`

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.20.4, built 2021-05-24
System: darwin-arm64
---
Docker
- Host: Error: error during connect: Get "http://user%40host/v1.24/version": dial tcp: lookup user@host: no such host
---
Kubernetes
- Env: k3d
- Context: k3d-clamav-rest
- Cluster Name: k3d-clamav-rest
- Namespace: default
- Container Runtime: containerd
- Version: v1.20.4+k3s1
- Cluster Local Registry: none
---
```

#### About Your Use Case

I want to make use of a remote docker host via SSH.

**Comment by temal-** [comment]
Same behaviour with `v0.20.5`.

**Comment by milas** [comment]
The next release of Tilt (tentatively v0.20.6) will be able to connect using `ssh://` Docker connection strings.

I was able to do some basic testing and verify that this works, but as a heads up, it's worth mentioning that this is a fairly uncommon setup (vs. local Docker or tcp/http(s) remote Docker) so you might encounter some issues.
