### ISSUE TITLE
Sticky loading popover in v0.20.5

### ISSUE THREAD

**Issue by ebenoist** [tilt-dev/tilt#4604]
### Expected Behavior
The loading popover screen in the Web UI should go away after connecting to the local tilt daemon.

### Current Behavior
`Loading...` appears until most (all?) of the containers are booted.

#### `tilt doctor` Output

```
$ tilt doctor
[erik/exclude-health+][~/dev/reverb]❥  tilt doctor
Tilt: v0.20.5, built 2021-05-28
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: kind-0.6+
- Context: kind-kind
- Cluster Name: kind-kind
- Namespace: default
- Container Runtime: read-failure
- Version: Error: Get "https://127.0.0.1:60700/version?timeout=32s": dial tcp 127.0.0.1:60700: connect: connection refused
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: 9dba14d67dd4c502e594a05aa1a0e5ec
- Repo: HqkW338Dth3PB3xaNOmm8Q==
```

**Comment by ebenoist** [comment]
![image](https://user-images.githubusercontent.com/1656713/120341118-3bed9c00-c2bc-11eb-8ee6-f23633bff92b.png)

**Comment by hyu** [comment]
Hi @ebenoist, thanks for reporting this issue! 

I tried to repro this issue with v0.20.5 by opening both Tilt Web UI and also the legacy terminal UI during startup, but I wasn't able to reproduce the issue you described. The Loading screen quickly disappears and I can see resources loading.

Can you tell me a bit more about what you observed? Does this happen very frequently? Do you have a sense of what repro steps might be?

**Comment by ebenoist** [comment]
Happens on every boot up and sticks around until the last few resources are loading. All of these services either run in docker or on the local host. I took a screen cap if that helps.

![loading](https://user-images.githubusercontent.com/1656713/120654060-ee516a80-c446-11eb-8153-da3852d9f804.gif)

**Comment by nkuik** [comment]
Our team is also experiencing this issue; we are using docker-compose for running all our services. When all tasks/resources are started up, the `Loading...` doesn't seem to reappear, but when tasks are running and containers are starting up, one must refresh the page to see the service statuses before it switches back to `Loading...`.

**Comment by landism** [comment]
I've hit this in the past but haven't managed to repro this exact issue.

I was able to repro a related recent unintended change that might have the same root cause:
In [servantes](https://github.com/tilt-dev/servantes/), `tilt down` then `tilt up`. In older versions of Tilt, all resources would show up as soon as the Tiltfile finished executing. In v0.20.5, resources show up over time (I haven't yet tracked down the exact condition that causes them to eventually show up). Given the "Loading..." dialog shows up [when the frontend doesn't know about any resources](https://github.com/tilt-dev/tilt/blob/c7a500bbeae4807e796b9dd7064f0112bc59b3ec/web/src/HUD.tsx#L217), it's possible this stems from just an even larger delay on the FE learning about resources.

**Comment by landism** [comment]
I got a repro on the "Loading..." with a dev build by:
1. commenting out the [frontend refresh code](https://github.com/tilt-dev/tilt/blob/c7a500bbeae4807e796b9dd7064f0112bc59b3ec/web/src/HUD.tsx#L362-L369)
2. making a dev build
3. launching tilt on servantes, opening the web ui
4. repeating: wait for most of the startup logs to finish, kill tilt, restart tilt. The issue would usually happen within 5 or so runs.
