### ISSUE TITLE
infinite loop in sidebar filter

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4618]
We received a report of an infinite loop when typing into the Sidebar resource filter

> when I typed “initdb” into the filter for tilt resources, it is now infinitely cycling between “i” “in” “ini” “init” all the way out to “initdb” in random orders and it won’t stop even if I totally reload the tab or go to a different page.

We persist the sidebar filter in local storage. The library we use has had infinite loops in the past
https://github.com/soyguijarro/react-storage-hooks/issues/5

and this behavior, to me, definitely looks like the behavior that would happen if it was encountering localstorage errors and retrying continuously.

We have not been able to reproduce this issue

**Comment by nicks** [comment]
(This would likely require a fix in the upstream library if we could figure out how to repro)

**Comment by nicks** [comment]
i was able to repro some hanging behavior with

```
window.localStorage.setItem = () => {
  throw new Error('my error ' + Date.now())
}
```

I don't think their error backoff behavior is quite right

**Comment by landism** [comment]
I was able to repro this pretty consistently by having multiple tabs open to the Tilt UI on the resource view and quickly typing characters into the resource filter box. It didn't seem to repro when typing slowly.

This fits the hypothesis that each tab is:
1) getting notified the value updated
2) reading the value
3) writing the value back

I have not dug into this - #3 above is a bit surprising to me - we're only calling the function to update the value in the TextField's onChange - if #3 is happening, presumably it's inside the useStorageState call itself or onChange is invoked when we pass in the new value we get from localStorage.

**Comment by landism** [comment]
FWIW it seems much easier to repro in the table view (#4965)

**Comment by lizzthabet** [comment]
to reproduce this the way @landism described, i had to open more than two browser tabs with tilt and type quickly in the field. interestingly enough, i wasn't able to reproduce with only two tabs open.
