### ISSUE TITLE
Support for Docker Buildx?

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt#4622]
## Describe the Feature You Want

We've got multi-arch builds where I work. When I need to test this, I add a node to my k8s cluster that uses a different chipset.

Does Tilt support building to multi-arch? A use case I could have when developing locally would be to change `nodeSelectors` to place the proper image on each node based on chipset.

After local dev is done, this is useful because it can give parity with multi-chipset clusters, such as AWS EKS.

### Current Behavior

As far as I know, there's no way to specify chipset.

### Why Do You Want This?

Parity between local and prod, _speed_.

**Comment by nicks** [comment]
hi @kevin-lindsay-1 ! 

Good news! Tilt already supports buildx. The terminology is a bit confusing here. Tilt's docker_build talks to the Docker API directly (and does not go through the CLI), so it supports both features of docker build and docker buildx (docker buildx is mainly a CLI layer).

It sounds like you mainly need support for buildx's `--platform` flag?

We also see people use custom_build to invoke docker buildx, as in this comment: https://github.com/tilt-dev/tilt/issues/3398#issuecomment-637686468

**Comment by kevin-lindsay-1** [comment]
Hey @nicks 

Sorry, I saw this comment but didn't really have a response worth writing until now.

> Tilt's docker_build talks to the Docker API directly

I've never used Docker's API directly, so as a user of both it's hard to say what the I feel like Tilt's API should be in regards to this.

Assuming that Tilt is using `docker_build` as a stand-in for docker's CLI, then my initial instinct would be to "just make a `docker_buildx_build`" command so that you can have different commands with different flavors of the API.

However, upon a little further thought I wonder if that's even necessary for rough parity, because `buildx build` was intentionally designed by the docker team to change as little as possible.

Since Tilt doesn't actually even use `build` or `buildx build` under the hood directly, I guess it's a question of API design philosophy and abstraction. Should Tilt try to make rough parity with the design of the docker CLI, or should it break away and have its own function that can "do it all" at the expense of being harder to point back towards docker's documentation for how everything works?

> It sounds like you mainly need support for buildx's --platform flag?

Yes. I'll be describing my use case below, it's a bit off the beaten track.

---

Normally, I use Tilt to simply build an image for my host's `TARGET`, that being `mac/darwin-amd64`, and using in Kubernetes via docker desktop's built-in kubernetes. I bootstrap the cluster with a few charts that we use in production via `helmfile` for the sake of high-level parity with our production and pre-production cluster.

However, sometimes I'm specifically building an image as the tool itself, such as a CI deployment helper image, tool runner, etc. The user in question won't be using Kubernetes, rather they'll be using the image directly, and for their use case running an interactive (dev) or programmable (prod) shell as the `CMD` is the intended purpose.

In cases like this, Tilt acts as a very nice way to simultaneously `watch` a dockerfile for rebuilds and then use in kubernetes for the sake of being able to use it as it will be used internally (we use gitlab's runner framework).

So when working like this, actually running on different `TARGET` nodes is the goal, because we have a design goal to support both `amd64` and `arm64`, per AWS' EKS managed node groups' supported set of targets.

For this purpose, it's easy enough to have a chart deploy multiple deployments with a list of `nodeSelectors` that simply duplicate the deployment.

---

When working in that flow, I think that the only thing Tilt's UI is missing is a way to `exec` directly into a pod in a deployment.

I think the simplest way to support this use-case would be to offer a small button for exec, which then exposes a "floating" `select` which displays a list of pods, and then when you click one, it opens up your default terminal with an entrypoint of `sh` or `bash` or the like.

Ideally I guess the experience would be to enable a user to effectively feel like they could just click into the log window and start issuing commands, but I doubt anyone would be upset if Tilt simply copied the `kubectl exec` command onto their clipboard.

**Comment by nicks** [comment]
Here are some docs that use `kubectl build` to startup a docker server on a remote cluster:
https://blog.tilt.dev/2021/11/12/docker-build-alternatives.html
https://github.com/tilt-dev/tilt-example-builders#kubectl-build

We've found it's a bit easier to use and configure than `docker buildx` (but still want to add some docs on buildx)

**Comment by nicks** [comment]
(deleted an earlier comment because i misread the above ticket)

We added support for the --platform flag a while back, which should let you do multi-arch images.

We also have support for building in-cluster with `kubectl build` (which we've found a bit easier to configure than buildx) https://blog.tilt.dev/2021/11/12/docker-build-alternatives.html

The other comments about easier UIs to exec into a container are covered here:
https://github.com/tilt-dev/tilt/issues/2060

so i think that covers everything in this ticket!
