### ISSUE TITLE
Error when trying to pull an image from a local insecure registry

### ISSUE THREAD

**Issue by nicoga97** [tilt-dev/tilt#4663]
### Expected Behavior
When running the docker file it should pull the base image successfully of a local docker insecure registry.

### Current Behavior
When running the tilt file Im gettin the following error:
```
Step 1/12 : ARG IMAGE_REGISTRY
Step 2/12 : FROM $IMAGE_REGISTRY/myRegistry/java12:latest
Get https://ip-of-machine-running-registry(local):5000/v2/: http: server gave HTTP response to HTTPS client
```

I had already added the insecure registry to daemon docker config file 
```
"insecure-registries": [
    "local.registry:5000",
    "localhost:5000",
    "127.0.0.1:5000",
    "ip-of-machine-running-registry(local):5000"
```

I had also config kubernetes in order like this:
```
kubectl patch configmap/config-deployment \
   --namespace knative-serving \
   --type merge \
   --patch '{"data":{"registriesSkippingTagResolving":"<<ip-of-machine-running-registry(local)>>:5000"}}'
```

When I try to build the image of the dockerfile without using tilt it pulls the image successfully.

#### `tilt doctor` Output

```
Tilt: v0.20.7, built 2021-06-10
System: darwin-amd64
---
Docker (cluster)
- Host: tcp://127.0.0.1:62957
- Version: 1.41
- Builder: 2
---
Docker (local)
- Host: [default]
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.20.2
- Cluster Local Registry: none
```

**Comment by nicks** [comment]
@nicoga97 Thanks for reporting!

This is a misconfiguration! Here's what's happening. Tilt is building directly on your Minikube cluster's Docker daemon, not on your local Docker daemon. You're setting the insecure registry setting on the wrong Docker daemon!

If you start minikube with the --insecure-registry flag, I think that will fix your issue:
https://minikube.sigs.k8s.io/docs/handbook/registry/#enabling-insecure-registries

try that and let us know how it goes.

**Comment by nicoga97** [comment]
@nicks Thanks for your answer!
I forgot to mention that  at the moment of starting minikube I set the insecure registry as shown below:
```
minikube start --cpus=2 --memory=‘8g’ --insecure-registry=ip-of-machine-running-registry(local):5000

```

**Comment by nicks** [comment]
Hmmm...that's interesting :thinking: . 

The minikube docs say " Ensure the cluster is deleted using minikube delete before starting with the --insecure-registry flag.", so i wonder if there are conditions where it doesn't take effect properly.

Tilt doesn't really have much control over whether Docker is properly using an insecure registry, but we do give you tools to help you diagnose the problem. Here are some things to try.

The `tilt docker` command will talk to the same Docker daemon that Tilt is talking to. https://docs.tilt.dev/debug_faq.html#why-does-my-image-build-fail-in-tilt-when-it-succeeds-with-docker-build

So I would probably run:

```
tilt docker info
```

to view the insecure registries that it think it has. Also, you can run:

```
tilt docker -- build # your normal docker build flags
```

to better replicate the `docker build` command Tilt is running.

As an aside, we tend to get a lot of bug reports from people who have configured minikube incorrectly, so we do maintain some tools for configuring minikube. See:

https://github.com/tilt-dev/minikube-local
https://github.com/tilt-dev/ctlptl#minikube-with-a-built-in-registry-at-kubernetes-v1188

In particular, we recommend setting it up with containerd and a local insecure registry, which is less likely to have weird problems.

**Comment by nicoga97** [comment]
@nicks You were totally right! I didn't read the part of minikube docs were says " Ensure the cluster is deleted using minikube delete before starting with the --insecure-registry flag.", it was a misconfiguration, nothing related to Tilt, sorry for wasting your time.
Thanks!

**Comment by nicks** [comment]
@nicoga97 not a waste of time at all, it's helpful to us to know that people are running into this kind of problem so we can have better tooling to diagnose it.
