### ISSUE TITLE
It reporting: ERROR: Build Failed: ImageBuild: Error parsing reference: "golang:1.13.0 as tilt-helper" is not a valid repository/tag: invalid reference format

### ISSUE THREAD

**Issue by huchen2021** [tilt-dev/tilt#4678]
### Steps to Reproduce

1.
2.
3.
4.

#### `tilt doctor` Output

```
$ tilt doctor
...
```

#### About Your Use Case

```
When I run "tilt up" under project(https://github.com/kubernetes-sigs/cluster-api), the Tiltfile is https://github.com/kubernetes-sigs/cluster-api/blob/release-0.3/Tiltfile
It reporting the following error:
```
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/85480625/123023348-d3e92c00-d409-11eb-82d7-e87015600f7b.png">

**Comment by landism** [comment]
Thanks for the report!

I didn't have any luck reproducing this using the latest Tilt and cluster-api. Some more information might help us track this down, if you don't mind:

1. Can you share the output of `tilt doctor`? It'd be helpful to know the version of Tilt and Docker you're using.
2. At what git SHA are you running cluster-api?
3. Do you get this error every time you `tilt up`?
4. Has this Tiltifle worked for you in the past? If so, about when did it start producing this error?
5. Do you know if anyone else working on cluster-api has encountered this?

**Comment by landism** [comment]
The output of this could also be useful:
`tilt dump engine | jq '.ManifestTargets["capd-controller-manager"].Manifest.ImageTargets'`

**Comment by huchen2021** [comment]
> Thanks for the report!
> 
> I didn't have any luck reproducing this using the latest Tilt and cluster-api. Some more information might help us track this down, if you don't mind:
> 
>     1. Can you share the output of `tilt doctor`? It'd be helpful to know the version of Tilt and Docker you're using.
```
# tilt doctor
Tilt: v0.20.8, built 2021-06-18
System: linux-amd64
---
Docker
- Host: [default]
- Version: 1.26
- Builder: 1
---
Kubernetes
- Env: kind-0.6+
- Context: kind-kind
- Cluster Name: kind-kind
- Namespace: default
- Container Runtime: containerd
- Version: v1.21.1
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: default
- Machine: 2a56958d041940a6e3affc156d5d1b2d
- Repo:
- 
```
>     2. At what git SHA are you running cluster-api?
> 
```
# git status
# On branch release-0.3
```

>     3. Do you get this error every time you `tilt up`?
> 
```
yes
```
>     4. Has this Tiltifle worked for you in the past? If so, about when did it start producing this error?
> 
```
no
```
>     5. Do you know if anyone else working on cluster-api has encountered this?

```
not yet
```

**Comment by huchen2021** [comment]
> tilt dump engine | jq '.ManifestTargets["capd-controller-manager"].Manifest.ImageTargets'
```
# tilt dump engine | jq '.ManifestTargets["capd-controller-manager"].Manifest.ImageTargets'
[
  {
    "BuildDetails": {
      "BuildArgs": null,
      "BuildPath": "/root/go/src/cluster-api/test/infrastructure/docker/.tiltbuild",
      "CacheFrom": null,
      "Dockerfile": "\n# Tilt image\nFROM golang:1.13.0 as tilt-helper\n# Support live reloading with Tilt\nRUN wget --output-document /restart.sh --quiet https://raw.githubusercontent.com/windmilleng/rerun-process-wrapper/master/restart.sh  &&     wget --output-document /start.sh --quiet https://raw.githubusercontent.com/windmilleng/rerun-process-wrapper/master/start.sh &&     chmod +x /start.sh && chmod +x /restart.sh\n\n\nRUN wget -qO- https://dl.k8s.io/v1.14.4/kubernetes-client-linux-amd64.tar.gz | tar xvz\nRUN wget -qO- https://get.docker.com | sh\n\n\nFROM gcr.io/distroless/base:debug as tilt\nWORKDIR /\nCOPY --from=tilt-helper /start.sh .\nCOPY --from=tilt-helper /restart.sh .\nCOPY manager .\n\n\nCOPY --from=tilt-helper /usr/bin/docker /usr/bin/docker\nCOPY --from=tilt-helper /go/kubernetes/client/bin/kubectl /usr/bin/kubectl\n",
      "ExtraTags": null,
      "LiveUpdate": {
        "BaseDir": "/root/go/src/cluster-api",
        "Steps": [
          {
            "Dest": "/manager",
            "Source": "/root/go/src/cluster-api/test/infrastructure/docker/.tiltbuild/manager"
          },
          {
            "Command": {
              "Argv": [
                "sh",
                "-c",
                "sh /restart.sh"
              ],
              "Dir": "/root/go/src/cluster-api",
              "Env": null
            },
            "Triggers": {
              "BaseDirectory": "/root/go/src/cluster-api",
              "Paths": null
            }
          }
        ]
      },
      "Network": "",
      "PullParent": false,
      "SSHSpecs": null,
      "SecretSpecs": null,
      "TargetStage": "tilt"
    },
    "Refs": {
      "ConfigurationRef": {
        "matchType": 0,
        "ref": {
          "domain": "gcr.io",
          "path": "k8s-staging-cluster-api/capd-manager"
        }
      },
      "registry": {
        "Host": "gcr.io/k8s-staging-cluster-api",
        "SingleName": "",
        "hostFromCluster": ""
      }
    },
    "dependencyIDs": [],
    "dockerignores": [
      {
        "LocalPath": "/root/go/src/cluster-api/test/infrastructure/docker/.tiltbuild",
        "Patterns": [
          "**",
          "!manager"
        ],
        "Source": "docker_build(\"gcr.io/k8s-staging-cluster-api/capd-manager\") only="
      }
    ],
    "overrideCommand": {
      "command": [
        "sh",
        "/start.sh",
        "/manager"
      ]
    },
    "repos": [],
    "selector": "gcr.io/k8s-staging-cluster-api/capd-manager",
    "tiltFilename": "/root/go/src/cluster-api/Tiltfile"
  }
]
```

**Comment by landism** [comment]
It looks like you are using an old version of Docker that predates the support for "FROM image AS name" syntax. Unfortunately, `tilt doctor` grabs the docker API version but not the docker engine version. You can check `docker version` to get your docker engine version. If it predates Docker 17.05, that will confirm this is the problem and you'll need to get on a newer version of the docker engine.

(this may seem like a stretch since this feature was added to Docker in 2017, but the behavior and reported API versions match this, and there are distros like RHEL that lag way behind)

**Comment by nicks** [comment]
Ya, this just means that you're on an old version of Docker, and the version of Docker you're using doesn't support some features in the cluster-api Dockerfile.
