### ISSUE TITLE
VS Code Tiltfile editor support

### ISSUE THREAD

**Issue by tiangolo** [tilt-dev/tilt#4734]
## Describe the Feature You Want

I would like to get editor support with autocompletion including the API documentation and type checks for the available Tiltfile API.

I'm actually writing this issue mainly to share my findings, there's already a trick/hack that can help a lot.

### Current Behavior

There's no (static) editor support with completion or type checks available.

Interpreting `Tiltfile` as plain text:

<img width="352" alt="Screenshot 2021-07-07 at 12 53 16" src="https://user-images.githubusercontent.com/1326112/124748291-34588d00-df23-11eb-8de2-ebf76105cac4.png">

Interpreting `Tiltfile` as Python:

<img width="352" alt="Screenshot 2021-07-07 at 13 00 23" src="https://user-images.githubusercontent.com/1326112/124748376-53efb580-df23-11eb-8054-35f25ef6b2df.png">

### Why Do You Want This?

I depend a lot on editor support, for programming languages, config files, etc. I've even built open source [frameworks](https://github.com/tiangolo/fastapi) and [libraries](https://github.com/tiangolo/typer) to get better editor support. 😅 

I could easily write erroneous code if I don't get help from the editor. I like the confidence, speed, and particularly the **developer experience** I get when I have good editor support.

### Hack / Workaround

There's a quick hack that can be used right now and sort-of-almost works:

* On the same project directory, create a subdirectory `typings`:

```bash
mkdir typings
```

* download the Tilt `api.py` file under `typings/tiltapi.pyi`:

```bash
curl https://raw.githubusercontent.com/tilt-dev/tilt.build/master/api/api.py -o typings/tiltapi.pyi
```

* In the top of the `Tiltfile`, add the following import:

```Python
from tiltapi import *
```

🚨 That import is a syntax error because `import` is a Starlark [reserved keyword](https://github.com/bazelbuild/starlark/blob/master/spec.md#lexical-elements). And it will break Tilt. It will have to be commented out before running Tilt.

But during development, while editing the `Tiltfile` it will help with editor support:

<img width="959" alt="Screenshot 2021-07-07 at 13 11 35" src="https://user-images.githubusercontent.com/1326112/124749734-e6448900-df24-11eb-8c51-5e92d46da64f.png">

<img width="553" alt="Screenshot 2021-07-07 at 13 13 51" src="https://user-images.githubusercontent.com/1326112/124750005-391e4080-df25-11eb-9589-1c0fadcbd93b.png">

<img width="718" alt="Screenshot 2021-07-07 at 13 14 57" src="https://user-images.githubusercontent.com/1326112/124750105-5b17c300-df25-11eb-88e0-fb700ccb0414.png">

### How that hack works

As the docs are created with Sphinx from that `api.py` file, all that can be reused as type stubs.

There are some things missing, like `TRIGGER_MODE_MANUAL`, nevertheless, that trick above can already improve a lot the experience of writing a `Tiltfile` for newcomers like myself.

It works because by default Pylance and Pyright (the stuff doing Python static analysis in VS Code) will look for additional Python stub files in the `typings` directory by default. Stub files are mainly plain Python files with a `.pyi` extension to provide all that static information (type annotations, docs, etc).

So, by downloading `api.py` exactly in that path in the project and importing it like that VS Code can provide editor support.

### Alternative 1

Alternatively, it would be possible to modify the type stubs used by Pylance and add the builtins defined by the `Tiltfile` API, but that would modify them for all Python in that project, affecting projects using Python (providing non-existent builtins, etc).

One way to do it is to modify the local stubs from Pylance, the exact file depends on the latest release, you can get there by writing a builtin like `locals()` and using the "Go to Definition" functionality, which will take you to the Pylance-specific stub file used.

### Alternative 2

Another alternative would be to manually clone the official Python typeshed stubs and modify the builtins in there. More or less the same as **Alternative 1** but with extra steps and without modifying Pylance's internal files.

There's a config for that, `python.analysis.typeshedPaths`, but I understand that right now it only supports a single path (that has to include all the Python stdlib, including builtins, etc).

**Note**: any of these 2 alternatives would break editor support for normal Python by polluting non-existent built-in global functions and variables.

### Improving that

That workaround could be improved a lot by declaring any missing *symbols* in `api.py`, like `TRIGGER_MODE_MANUAL`.

And I guess something similar could be done for extensions.

---

A more structured and "professional" approach (consuming much more effort) would be to write a VS Code extension that in some way plugs into Pylance and adds the custom builtins provided by Tilt.

Another option is to request the Pylance team to accept more than one path for that `python.analysis.typeshedPaths` config and put the `Tilefile` API in a custom location locally, etc.

Anyway, I ended up researching this a bunch to improve my own developer experience, so I decided to share my findings in case it's useful for others later.

**Comment by hyu** [comment]
Thank you so much for this detailed write-up of a workaround for Tilt API editor support, @tiangolo!

We definitely want to improve the developer experience for Tilt API. Although we're not yet at the point of investing effort in a dedicated VS Code extension, it's really helpful to see what you set up for your own use case.

**Comment by lizzthabet** [comment]
with tilt v0.26.0, you can now use the [official tilt vscode extension](https://marketplace.visualstudio.com/items?itemName=tilt-dev.Tiltfile)! i'm going to close this issue, and any additional feedback / issues can be filed in under tilt's [vscode extensions repo](https://github.com/tilt-dev/vscode-tilt/issues). 🎉
