### ISSUE TITLE
Regression in dc_resource link support 

### ISSUE THREAD

**Issue by ebenoist** [tilt-dev/tilt#4736]
### Expected Behavior
Docker compose resource links should be present in the UI as per: https://github.com/tilt-dev/tilt/pull/4175

### Current Behavior
Links declared in `dc_resource` calls are no longer present (open ports declared in the docker-compose.yml still provide links)

### Steps to Reproduce
1. Download latest tilt
2. Add a link to an existing dc_resource
3. Inspect the UI
```
dc_resource(
    'foozles',
    links=[
      link('https://foozles.devo.test')
      ],
    )
```

#### `tilt doctor` Output

```
Tilt: v0.21.2, built 2021-07-06
System: darwin-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.7
- API Version: 1.41
- Builder: 2
---
Kubernetes
- Env: docker-for-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.21.2
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: default
- Machine: 9dba14d67dd4c502e594a05aa1a0e5ec
- Repo: HqkW338Dth3PB3xaNOmm8Q==
```

**Comment by hyu** [comment]
Hi @ebenoist, I just did a quick test using the latest release ([v0.21.2](https://github.com/tilt-dev/tilt/releases/tag/v0.21.2)), and I do see the specified link in the main overview UI:

<img width="1457" alt="Screen Shot 2021-07-08 at 4 24 21 PM" src="https://user-images.githubusercontent.com/20349/124986053-2da44580-e009-11eb-85bc-9f6c68ddc372.png">

Is that the UI you were referring to, or did you mean something else?

**Comment by ebenoist** [comment]
This is the UI I'm talking about, but I'm not seeing the custom links like you have listed. I wish I did! It does look like you're on v0.21.1 based on your screenshot though?

![image](https://user-images.githubusercontent.com/1656713/125000662-7f070180-e016-11eb-9ce9-f6637be3ea8c.png)

```
dc_resource(
    'rql',
    links=[
      link('https://rql.devo.test')
      ],
    )
```

**Comment by ebenoist** [comment]
I can confirm that the issue is still present in v0.21.3. I'll start combing through commits to see if there was an obvious change that caused the issue.

**Comment by nicks** [comment]
Hmmm...is it reliably reproducible, or is it intermittent that the link doesn't appear? I'm kind of stumped, I can't reproduce it either.

**Comment by nicks** [comment]
ooh, one thing I've noticed! If I have two dc_resource calls:

```
dc_resource(
  'redis',
  links=[
    link('https://redis.devo.test')
  ],
)
dc_resource(
  'redis',
  links=[
    link('https://redis2.devo.test')
  ],
)
```

Tilt only uses the last one. And I have

```
dc_resource(
  'redis',
  links=[
    link('https://redis.devo.test')
  ],
)
dc_resource('redis')
```

Then the first link gets wiped out. Could that be what's happening here?

**Comment by ebenoist** [comment]
@nicks You found it! Thats absolutely what is going on. We have a section of our Tiltfile that loads all the services via the yaml. This is now inadvertently clearing the links. I can avoid the issue completely by changing the order of operations in our Tiltfile. Thank you.
