### ISSUE TITLE
services cleaned up on tiltfile error

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4745]
report:
> tilt up -> wait for everything to deploy successfully -> edit Tiltfile and make a breaking change (Tiltfile resource goes red in Tilt UI) -> all services suddenly stop :disappointed:

This is probably related to the new Kubernetes resource garbage collection. I don't think it's supposed to behave this way.

**Comment by andymartin-sch** [comment]
thank you! can confirm this is resolved in 0.21.3
