### ISSUE TITLE
support DOCKER_CONTEXT env variable

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4769]
## Describe the Feature You Want
The DOCKER_CONTEXT env variable lets you connect to different docker daemons.

Tilt should respect the DOCKER_CONTEXT env variable

https://docs.docker.com/engine/context/working-with-contexts/

### Current Behavior
Tilt does not appear to support the DOCKER_CONTEXT env variable

**Additional context**
I think this might be a bug in the underlying Docker client library. 

Here's the Docker client library documentation: https://pkg.go.dev/github.com/docker/docker@v20.10.7+incompatible/client#hdr-Usage

Here's where the Docker CLI uses this variable: https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/cli/command/cli.go#L514

It might make sense to talk to Docker upstream about shipping a client library that properly respects DOCKER_CONTEXT, so that each client library doesn't have to implement this themselves.

**Comment by nicks** [comment]
filed upstream as https://github.com/moby/moby/issues/42650

**Comment by milas** [comment]
FWIW I had to manually pull over support for `DOCKER_HOST=ssh://...` in #4607 for similar reasons - seems kinda arbitrary what ends up in CLI vs library, unfortunately :(

**Comment by nicksieger** [comment]
Looks like the way to support this might have to be to call `docker context inspect ...` to get the information, and even then it's probably best to want and address this after the docker client can be configured from the Tiltfile.
