### ISSUE TITLE
table ui: toggle trigger mode - easy to wrongly expect persistence

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#4798]
The web UI's table view has a "trigger mode" column that allows the user to switch between auto and manual:
![image](https://user-images.githubusercontent.com/7453991/127181688-a0efe151-0552-4173-b10d-41015814de1a.png)

If a user toggles these to suit their preferences and then restarts Tilt, any changes they made are forgotten.
1. This might be annoying/surprising on its own.
2. This might be especially surprising since our other UI elements (sidebar toggles, stars) do persist across runs.

It might be nicer to:
1. Adjust the users' expectations (perhaps by changing the text on the button or providing some kind of brief note when they click)
2. Make these settings persist

**Comment by ellenkorbes** [comment]
> (sidebar toggles, stars) do persist across runs

Wait toggles and stars persist? I thought they were all ephemeral. You're right that this is super inconsistent. I'll raise this issue elsewhere.
