### ISSUE TITLE
local_resource with "dir" param errors

### ISSUE THREAD

**Issue by razzmadaz** [tilt-dev/tilt#4805]
### Expected Behavior

Calling 
```
local_resource('postgres-init',
                cmd='./init.sh',
                dir='./temporal/setup',
                deps=['./temporal/setup'],
                resource_deps=['postgres', 'postgres-create'],
)
```
Should work. (Works on other machines, albeit macs)

### Current Behavior

`tilt up` yields this error in the web UI:
```
Traceback (most recent call last):
  /home/daz/programming/workflow-engine/Tiltfile:107:15: in <toplevel>
  <builtin>: in local_resource
Error: local_resource: unexpected keyword argument "dir"
```

#### `tilt doctor` Output
```
daz@desdemona:~/tmp$ tilt doctor
Tilt: v0.22.1, built 2021-07-23
System: linux-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.7
- API Version: 1.41
- Builder: 2
---
Kubernetes
- Env: kind-0.6+
- Context: kind-temporal1
- Cluster Name: kind-temporal1
- Namespace: default
- Container Runtime: containerd
- Version: v1.21.1
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: 5749265cf4ed96cef95abb533fddd439
- Repo: 
```

**Comment by landism** [comment]
Thanks for the report!

The 'dir' parameter was added relatively recently. My best guess is something like you upgraded tilt but your tilt process was spawned from an older tilt binary.

Some things to check/try:
* What version of Tilt does the web ui display in the upper right?
![image](https://user-images.githubusercontent.com/7453991/127505647-2aea6b85-c8b9-4b9b-9646-40176e0cea5c.png)
* If you kill Tilt and restart it from the terminal where `tilt doctor` reports 0.22.1, does the issue repro? (using the same terminal avoids issues with, e.g., changed .bashrcs or bash path resolution caching)

**Comment by razzmadaz** [comment]
I *think* killing the running tilt -> tilt down -> tilt up in a new shell worked. 
Not quite sure I get why though since the old tilt binary was clobbered when upgrading.
Thanks for the help and great tool! :rocket:
