### ISSUE TITLE
close the loop on `tilt ci --output-snapshot-on-exit`

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#4811]
A user coming across `tilt ci --output-snapshot-on-exit` would be reasonable to think that its goal is to create a snapshot that they could view in their browser using the Tilt UI, as they could any other Tilt snapshot, but it ends up being kind of just confusing.

This is currently kind of a half-finished feature (introduced in #3049).

Workflows currently enabled by this argument (unclear whether people are using them):
* inspect the JSON directly to see what Tilt's state was
* grab your tilt token from your browser and run a curl command to upload the snapshot to tilt cloud

Possible next steps:
* add a little note saying it's currently mostly just useful as a state dump to save people the confusion
* kill this argument or mark it hidden / unsupported
* replace it with something that dumps all of the api objects or engine state
* add a subcommand to view a snapshot from a file
* add a subcommand to upload a snapshot from a file to tilt cloud

**Comment by gorilych** [comment]
> kill this argument or mark it hidden / unsupported

no-no-no :) I'm using it to save snapshots in CI, and it's the only way to have tilt snapshot here.

**Comment by nicks** [comment]
AFAIK, this is in use today. People use to generate jenkins artifacts, then dig through the results manually. We talked about writing a viewer, but has never been high priority. See discussion here: https://github.com/tilt-dev/tilt/issues/2513

**Comment by andymartin-sch** [comment]
we're users of the current `--output-snapshot-on-exit` flag and would be happy to beta test or give feedback for enhancement ideas

**Comment by sgreene570** [comment]
Friendly bump on this. We've recently started using the `--output-snapshot-on-exit` flag and were surprised to see that you essentially have to scroll through the state dump file (60K lines) manually to find what you're looking for. 

A local CLI option to render the snapshot in your browser, or some capability to upload the snapshot file to tilt cloud would be awesome and would save us lots of time debugging failed CI runs.

**Comment by leoluk** [comment]
We'd gladly pay for this.

**Comment by adamf** [comment]
We'd love this - +1

**Comment by gorilych** [comment]
Tilt snapshot can be uploaded to https://cloud.tilt.dev/snapshot/ with

```bash
curl -X POST --data @tilt.snapshot \
    -HX-Tilt-Token:1234567-xxxxxx-xxxx-xxx \
    -HX-Tilt-TeamID:e6abebcb-xxxx-xxxx-xxxx-xxxxxxxx \
    https://cloud.tilt.dev/api/snapshot/new
```

Value for `X-Tilt-Token` can be found in browser dev tools when you logged in in tilt console (don't remember where exactly, mb cookies?).

Value for `X-Tilt-TeamID` is team id from cloud.tilt.dev url, this header is optional.

**Comment by steve-bitdotio** [comment]
@gorilych thanks for providing a workaround!

However, I am unable to find any `X-Tilt-Token` in my browser, all that I can find is an encrypted `current-session` cookie.
Am I missing something? TIA!

**Comment by sgreene570** [comment]
@gorilych thanks for providing a workaround!

However, I am unable to find any X-Tilt-Token in my browser, all that I can find is an encrypted current-session cookie.
Am I missing something? TIA!

**Comment by sgreene570** [comment]
Aha! I found my tilt `token` file in `~/.tilt-dev` after reading https://github.com/tilt-dev/tilt/blob/master/vendor/github.com/tilt-dev/wmclient/pkg/dirs/dirs.go

**Comment by sgreene570** [comment]
Unfortunately, the manual curl workaround mentioned above has a hard size limit of 4 Mb (xref https://github.com/tilt-dev/tilt/issues/3687), so being able to view snapshots in your browser locally (or having some way to upload > 4 Mb snapshots) would be awesome.

**Comment by damoon** [comment]
looking at the 4Mb limit and data protection in general, i would prefer to not upload snapshots to a any kind of cloud.

I would enjoy solutions like
- a local command like to open tilt with the static content from the snapshot or
- a local command to transform snapshots to a self contained html+js+css file

Both UIs would only needs to support switching between the service tabs, seeing the state of a service and scrolling through its logs.

Anything i can do to support this?
