### ISSUE TITLE
`write_file` Tiltfile api

### ISSUE THREAD

**Issue by milas** [tilt-dev/tilt#4827]
a `write_file` api like:

```
write_file(contents, filename, append=False)
```

_Originally posted by @nicks in https://github.com/tilt-dev/tilt/issues/2664#issuecomment-887714959_

This would be complimentary to `read_file` - it could even have a `watch=True` param to let you set up automatic file watching on it.

## Context
Currently, a reasonable workaround to create a file is doing something like:
~`local('echo {} > {}'.format(shlex.quote(contents), output_path), echo_off=True, quiet=True)`~
```python
local('echo "$CONTENTS" > {}.format(output_path),
      env={'CONTENTS': str(contents)},
      echo_off=True,
      quiet=True)
```
It could be followed by a `watch_file()` call if you also wanted to react to further changes.

**Comment by milas** [comment]
I'm doing some Tiltfile logic where I'm generating resources I want to write to disk.

I actually hit an issue where between Starlark string / shell escaping, things were getting broken. Being able to stream a `blob` straight to disk would be helpful to avoid this.

It's also conceivable you could hit `ARG_MAX` at some point when trying to use a shell/`echo` to write a big generated file.

**Comment by nicks** [comment]
would it work to do something like this?

```
local('echo "$CONTENTS" > {}'.format( utput_path), env={'CONTENTS': str(contents)}, echo_off=True, quiet=True)
```

**Comment by milas** [comment]
Ha yep, I realized I was being foolish and switched to use `env` right after making this issue which does make it way more robust.

**Comment by psigen** [comment]
FYI: as written, this seems to be limited by the `MAX_ARG_STRLEN` of the shell or similar:
```
Error: command "echo \"$CONTENTS\" > ./my_cool_path.yml" failed.
error: fork/exec /bin/sh: argument list too long
```

**Comment by nicksieger** [comment]
Also note that `local` now has a `stdin` parameter that can be used to work around the "argument list too long" issue.
