### ISSUE TITLE
Remote cluster - rebuild image and redeploy with k8s_yaml(helm(...))

### ISSUE THREAD

**Issue by archletekke** [tilt-dev/tilt#4865]
## Describe the Feature You Want
We would like to be able to easily redeploy via k8s_yaml or similar on a remote cluster after an image has been rebuilt locally. For the local env we are using `docker_build` and `restart_container`, but I've failed to find a solution doing the same for a remote one.

The setup we have figured out so far does build the image and deploys it initially, but not later on when the image is rebuilt.

```
allow_k8s_contexts('ekke-local-dev')

load('ext://helm_remote', 'helm_remote')

docker_build('docker.io/archlet-x',
             'python/.',
             dockerfile='python/x/Dockerfile',
             live_update=[x,y,z]
             ])
k8s_yaml(helm('k8s/x', values=['./k8s/x/x.yaml'], set=['version=local']))
```

### Current Behavior
Not sure if this is even possible. Didn't find any relevant commands which I would act as a callback once a rebuild has been done.

### Why Do You Want This?
We would like to provide personal remote development clusters for our developers so that they can run the whole setup (large and very coupled at the moment, so hybrid is not very straightforward) on older macbooks. The local tilt-based current setup overwhelms the laptop and makes development experience too slow.

**Comment by nicks** [comment]
hi @archletekke !

I'm not totally sure I understand your bug report. Most of our example projects should work fine on a remote cluster. (and in fact we have many teams who use them with a remote cluster)

Your comment:
| The setup we have figured out so far does build the image and deploys it initially, but not later on when the image is rebuilt.

makes it sound like your live update isn't working? is that right? Does it work ok for you with the example projects? (e.g., https://docs.tilt.dev/example_static_html.html)

(There's a separate guide to how to set up Tilt with remote Docker builds, but that will still be much slower than Live Update if it's working correctly)

**Comment by archletekke** [comment]
Hi @nicks,

Thanks for the quick reply! I dug a bit deeper now and it seems like JS-based containers are working as they should. However, python based ones do not seem to restart again. And all of this by just using the regular `docker_build` command.

Should I provide the command in the Dockerfile as one of the arguments and still use `docker_build_with_restart`?

**Comment by archletekke** [comment]
Seems as if it might have been an issue with a previous version of Tilt? We tried this setup a few months ago and it didn't work.

I now just tested the docker_build_with_restart and also docker_build versions and everything worked very easily. Thanks for the help.

**Comment by nicks** [comment]
oh ya! Different frameworks handle the live-reload differently - i think some Python frameworks (like Flask debug mode) will restart the process themselves. If your framework doesn't handle restarting, you can use docker_build_with_restart to do it.
