### ISSUE TITLE
UIButton rendering order is nondeterministic

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#4868]
### Steps to Reproduce
Add multiple buttons to a resource, e.g.:
```
local_resource('hi', 'echo hi')
load('ext://uibutton', 'cmd_button', 'location', 'text_input')
for i in range(1, 20):
  cmd_button('test' + str(i), resource='hi', argv=['echo', 'foo', '$str'], text='Hi! ' + str(i), inputs=[text_input('str')]) #, icon_name='travel_explore')
```

### Current Behavior
Every time you refresh the tilt ui, the buttons are in a different / seemingly random order.

### Expected Behavior
The buttons appear in a consistent order.

### Context
We had a similar problem with UIResource: #4756
We can't cheaply use that solution for UIButton since they're not all generated in one place at one time. We could get part of the way there with the global_vars extension or by, on button creation, querying all buttons and setting order to the max order plus 1.
For now it's probably fine to just sort by alpha and worry about this if/when users have enough buttons that they want to control their order.

**Comment by milas** [comment]
> For now it's probably fine to just sort by alpha 

Creation time could also be a good candidate - that'd give you reasonable control most of the time by ordering your `cmd_button` calls

**Comment by landism** [comment]
> Creation time could also be a good candidate

I like that idea! I just did the alpha thing and was getting the ol' (1 10 11 12 ... 2 20 21) sorting.

Unfortunately, I just tried creation timestamp and the results weren't great. `Metadata.CreationTimestamp` is `Time`, not `MicroTime`, so a bunch of buttons have identical creation timestamps and we're back to randomish ordering.

**Comment by milas** [comment]
> `Metadata.CreationTimestamp` is `Time`, not `MicroTime`

😭 

Too bad K8s UIDs are also totally random and not using one of the cool kid UUID schemes that are time-sortable
