### ISSUE TITLE
`tilt up` without a Kubernetes cluster takes 20 seconds to start

### ISSUE THREAD

**Issue by robertmarsal** [tilt-dev/tilt#4882]
### Expected Behavior
When doing `tilt up` and only using docker-compose resources tilt starts straight away

### Current Behavior
At the moment `tilt` is trying to reach a Kubernetes cluster and waiting for a timeout delaying the startup time

### Steps to Reproduce

1.  Use a machine where there is no Kubernetes cluster
2. Use a Tiltfile that only imports a docker-compose file
3. Run `tilt up` and notice how it takes 20 seconds to process the tiltfile and then bring up the services

**Comment by nicks** [comment]
thanks for filing @robertmarsal !

we haven't seen this before. is it possible that you have a ~/.kube/config that's pointing at a dead cluster? i wonder if tilt sees you have a valid config, tries to connect to it, and times out.

(it's still a bug that tilt blocks 20 seconds trying to connect to it...but i'm curious if deleting the config fixes your problem for now).

**Comment by robertmarsal** [comment]
Hi @nicks you are correct! I still had a config file pointing to a dead cluster. Removing that file fixes the problem. Thanks

**Comment by hookenz** [comment]
@nicks I just had this problem when roaming with my laptop running a local microk8s cluster.
It still seems to be happening with a recent version of Tilt.

v0.33.22, built 2025-01-03
