### ISSUE TITLE
error creating self-signed certificates on tilt dump openapi

### ISSUE THREAD

**Issue by robert-elles** [tilt-dev/tilt#4982]
Running the command`tilt dump openapi` results in

Error: error creating self-signed certificates: unable to generate self signed cert: failed to write cert fixture to /root/project/vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/testdata/localhost_127.0.0.1-127.0.0.1_.crt: open /root/project/vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/testdata/localhost_127.0.0.1-127.0.0.1_.crt: permission denied

**Comment by nicks** [comment]
ha, thanks for reporting! ya, i think there's an issue with dev build vs release build, lemme poke around at it.

**Comment by nicks** [comment]
we just released v0.22.10, which should fix this problem
