### ISSUE TITLE
docker compose v2 support

### ISSUE THREAD

**Issue by tachiniererin** [tilt-dev/tilt#4993]
## Describe the Feature You Want
when running `tilt up` it should check if the `docker-compose` binary exists, and if not check if the [compose plugin](https://docs.docker.com/compose/cli-command/) is installed and run that instead.

### Current Behavior
tilt can't find the the docker-compose binary in the path and fails with `Error: Subscribing to docker-compose events [...] exec: "docker-compose": executable file not found in $PATH`

### Why Do You Want This?
i hit this change today morning because the package was updated in arch linux, it's only a question of when this change will also hit other distributions.

**Comment by tachiniererin** [comment]
The only way i found as to how to detect if `docker compose` is available is unfortunately is by running it. `docker plugin ls` doesn't list it on my machine, it probably only does when it's installed manually?

What i did as a quick fix is this:
```diff
diff --git a/internal/dockercompose/client.go b/internal/dockercompose/client.go
index 9b07f0232..d804cbc83 100644
--- a/internal/dockercompose/client.go
+++ b/internal/dockercompose/client.go
@@ -46,6 +46,7 @@ type cmdDCClient struct {
 	env         docker.Env
 	mu          *sync.Mutex
 	composePath string
+	isV2        bool
 }
 
 // TODO(dmiller): we might want to make this take a path to the docker-compose config so we don't
@@ -55,6 +56,7 @@ func NewDockerComposeClient(env docker.LocalEnv) DockerComposeClient {
 		env:         docker.Env(env),
 		mu:          &sync.Mutex{},
 		composePath: dcExecutablePath(),
+		isV2:        dcIsV2(docker.Env(env).AsEnviron()),
 	}
 }
 
@@ -290,11 +292,36 @@ func dcExecutablePath() string {
 	composePath, err := exec.LookPath(v1Name)
 	if err != nil {
 		composePath = "docker-compose"
+	} else {
+		return composePath
 	}
+
+	genericName := composePath
+	if runtime.GOOS == "windows" {
+		genericName += ".exe"
+	}
+	_, err = exec.LookPath(genericName)
+	if err != nil {
+		composePath = "docker"
+	}
+
 	return composePath
 }
 
+func dcIsV2(env []string) bool {
+	cmd := exec.Command("docker", "compose")
+	cmd.Env = append(os.Environ(), env...)
+	output, _ := cmd.Output()
+	if strings.Contains(string(output), "is not a docker command") {
+		return false
+	}
+	return true
+}
+
 func (c *cmdDCClient) dcCommand(ctx context.Context, args []string) *exec.Cmd {
+	if c.isV2 {
+		args = append([]string{"compose"}, args...)
+	}
 	cmd := exec.CommandContext(ctx, c.composePath, args...)
 	cmd.Env = append(os.Environ(), c.env.AsEnviron()...)
 	return cmd
```

Unfortunately i'm not familiar enough with tilt internals to do this properly for a PR...

**Comment by milas** [comment]
As a temporary workaround, you might be interested in `compose-switch`: https://github.com/docker/compose-switch.

But also as a heads up, there are some known issues with v2 currently (in particular #4890). Recent versions of Tilt will warn you at startup.

**Comment by tachiniererin** [comment]
It seems to be working again since https://github.com/docker/compose/releases/tag/v2.2.0. I'm currently testing it and after a few live-reload cycles it still seems to work. I guess as soon as these compose changes make it into a proper release this can be closed.

**Comment by tachiniererin** [comment]
Works fine with https://github.com/docker/compose/releases/tag/v2.2.2

**Comment by nicks** [comment]
thanks for the update!
