### ISSUE TITLE
Support docker_compose(blob)

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#4999]
Currently, `k8s_yaml` accepts either a filename or a Blob of dynamically constructed YAML
https://docs.tilt.dev/api.html#api.k8s_yaml

`docker_compose` only accepts a filename.
https://docs.tilt.dev/api.html#api.docker_compose

It would be useful for `docker_compose to also accept a blob, for teams that dynamically generate docker-compose YAML from a template.

AFAIR, Maia mostly implemented dynamically-generated docker-compose YAML in this PR:
https://github.com/tilt-dev/tilt/pull/3200
as part of an unrelated effort to add injected entrypoints for Docker Compose. But we ended up not needing injected entrypoints, and scrapped the PR. I don't think it would be too hard to revive the part that handled dynamic YAML.

**Comment by nicksieger** [comment]
@nicks are you working on anything related to this currently? Looks like some recent work you did has us closer to being ble to do this, and I'm looking for issues to pick up.

**Comment by nicks** [comment]
ya, the engine supports it now. the tiltfile bindings just need to be added.
