### ISSUE TITLE
A way to limit the number of concurrent build processes

### ISSUE THREAD

**Issue by fgielow** [tilt-dev/tilt#5005]
## Describe the Feature You Want
Determine how many images can be built simultaneously. 

### Current Behavior
All different images are built simultaneously.

### Why Do You Want This?
This would be useful to run tilt in machines that are not so powerful or with stacks that are complex and depend on too many different images.

**Additional context**
Maybe there are ways to achieve this writting code in the Tiltfile without native directives, if this is possible through any other means I'd be grateful if someone should show an example.

**Comment by lizzthabet** [comment]
@fgielow, thanks for the request! have you checked out [`update_settings`](https://docs.tilt.dev/api.html#api.update_settings) in the tilt docs? i'm wondering if setting a `max_parallel_updates` might meet your use-case.

**Comment by fgielow** [comment]
> @fgielow, thanks for the request! have you checked out [`update_settings`](https://docs.tilt.dev/api.html#api.update_settings) in the tilt docs? i'm wondering if setting a `max_parallel_updates` might meet your use-case.

Yeap, this has solved my issues. 

Thanks for the quick reply!
