### ISSUE TITLE
undefined: kustomzie

### ISSUE THREAD

**Issue by exocode** [tilt-dev/tilt#5131]
### Expected Behavior

`k8s_yaml(kustomzie("../metashop-backend/k8s/overlays/dev"))` or
`k8s_yaml(kustomzie("../metashop-backend/k8s/overlays/dev/kustomize.yaml"))` should start

### Current Behavior​
This line 
`k8s_yaml(kustomzie("../metashop-backend/k8s/overlays/dev"))`

in `Tiltfile` raises: 

```
Filter resource logs by text or /regexp/
1 File Changed: [Tiltfile] • (Tiltfile)
Loading Tiltfile at:...../development/Tiltfile
.../development/Tiltfile:26:10: undefined: kustomzie
```
### Steps to Reproduce

`brew install socat tilt-dev/tap/tilt`

place that `k8s_yaml(kustomzie("some_kustomize.yml"))` into your Tiltfile

`tilt up`

#### `tilt doctor` Output

```
❯ tilt doctor
Tilt: v0.22.15, built 2021-10-29
System: darwin-amd64
---
Docker
- Host: tcp://192.168.99.122:2376
- Server Version: 20.10.8
- API Version: 1.41
- Builder: 2
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.21.6
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: d2fc64a42b4f7a8bf742649db4356d70
- Repo:
...
```

#### About Your Use Case

What can I do?

**Comment by lizzthabet** [comment]
hi @exocode, thanks for the report! is it possible that you misspelled `kustomize` as `kustomzie`? based on the output you shared, i think this could be the case.

**Comment by exocode** [comment]
thank you, sorry! 🙈
