### ISSUE TITLE
You specified some resources that could not be found

### ISSUE THREAD

**Issue by qelan** [tilt-dev/tilt#5138]
I am pretty sure this is related to the Helm deploy name not matching the actual Helm chart name, but I don't know because the error is too vague!  When I run "tilt up" with my Tiltfile, I get the following error in the browser window:

You specified some resources that could not be found: "engine"

But, it does not tell me in which file it thinks that the resource was defined.  I also don't see any way to make things more verbose so that I could scan the output to try to determine where the problem might be.  I do think it might be because you are looking at the "app.kubernetes.io/name" label to find the name of my pod, but it is really differentiated by "app.kubernetes.io/instance" because I run multiple services based on the same Helm template.  When you look at the selector labels below you will see that both "app.kubernetes.io/name" and "app.kubernetes.io/instance" are used to find things.

Output from tilt doctor:
Tilt: v0.22.15, built 2021-10-29
System: windows-amd64
---
Docker
- Host: Error: Could not read docker env from minikube.
Did you forget to run `minikube start`?

---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: read-failure
- Version: v1.21.4
- Cluster Local Registry: none
---

Here is my Helm template when I run it from the command line using "helm template":
---
# Source: engine/templates/secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "engine-1"
  labels:
    helm.sh/chart: engine-2021.3.0
    app.kubernetes.io/name: "engine"
    app.kubernetes.io/instance: "engine-1"
    app.kubernetes.io/version: "2021-3"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "astute-knowledge"
data:
  rd-admin.username: <redacted>
  rd-admin.password: <redacted>
  rd-auth.username: <redacted>
  rd-auth.password: <redacted>
---
# Source: engine/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "engine-1"
  labels:
    helm.sh/chart: engine-2021.3.0
    app.kubernetes.io/name: "engine"
    app.kubernetes.io/instance: "engine-1"
    app.kubernetes.io/version: "2021-3"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "astute-knowledge"
data:
  action.end-point: "http://action-service"
  download-server.url: "https://content.astuteknowledge.test/d/"
  dynamo-db.dynamo-end-point: "http://dynamodb.ak-main-system:8000"
  engine.name: "RealDialog1"
  es.elastic-search-endpoint: "http://elasticsearch.ak-main-system:9200"
  kinesis.region: "us-east-1"
  kinesis.stream: "ak_runtime_mschwickerath"
  logging.level.root: "INFO"
  mart.end-point: "http://mart-api.ak-mart:3000"
  rd-admin.server: "mssql.ak-main-system"
  rd-admin.port: "1433"
  rd-admin.database: "MOCK_ADMIN"
  rd-auth.server: "mssql.ak-main-system"
  rd-auth.port: "1433"
  rd-auth.database: "MOCK_AUTH"
  spring.profiles.active: "local"
---
# Source: engine/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: engine-1
  labels:
    helm.sh/chart: engine-2021.3.0
    app.kubernetes.io/name: "engine"
    app.kubernetes.io/instance: "engine-1"
    app.kubernetes.io/version: "2021-3"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "astute-knowledge"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "engine"
    app.kubernetes.io/instance: "engine-1"
---
# Source: engine/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-1
  labels:
    helm.sh/chart: engine-2021.3.0
    app.kubernetes.io/name: "engine"
    app.kubernetes.io/instance: "engine-1"
    app.kubernetes.io/version: "2021-3"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "astute-knowledge"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: "engine"
      app.kubernetes.io/instance: "engine-1"
  template:
    metadata:
      annotations:
        checksum/config: e5cbdb53277efe1441cf1f34f731e48fe7317593ee46ae446eab85d8388a4c2d
        checksum/secrets: e6031913b7a4fd9631d70bb3c9be2c5d43ac31d6b75cde45520087054995c52b
      labels:
        app.kubernetes.io/name: "engine"
        app.kubernetes.io/instance: "engine-1"
    spec:
      serviceAccountName: ak-service-reader
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 120
      containers:
        - name: engine
          securityContext:
            {}
          image: "engine:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            httpGet:
              path: /RDWeb/actuator/health/liveness
              port: http
          readinessProbe:
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            httpGet:
              path: /RDWeb/actuator/health/readiness
              port: http
          startupProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 15
            httpGet:
              path: /RDWeb/actuator/health/liveness
              port: http
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: "AWS_DEFAULT_REGION"
              value: "us-east-1"
            - name: "AWS_REGION"
              value: "us-east-1"
            - name: "SPRING_PROFILES_ACTIVE"
              valueFrom:
                configMapKeyRef:
                  key: "spring.profiles.active"
                  name: engine-1
            - name: "SPRING_CLOUD_KUBERNETES_CONFIG_NAME"
              value: engine-1
            - name: BPL_DEBUG_ENABLED
              value: "true"
            - name: BPL_JVM_THREAD_COUNT
              value: "20"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:-OmitStackTraceInFastThrow -XX:ReservedCodeCacheSize=100M"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 60"]
          volumeMounts:
            - mountPath: "/etc/secrets"
              name: "engine-1-secrets"
            - mountPath: "/home/cnb/.aws"
              name: "engine-1-aws-credentials"
              readOnly: true
      volumes:
        - name: "engine-1-secrets"
          secret:
            secretName: "engine-1"
        - name: "engine-1-aws-credentials"
          secret:
            secretName: "aws-credentials"
---
# Source: engine/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: engine-1
  labels:
    helm.sh/chart: engine-2021.3.0
    app.kubernetes.io/name: "engine"
    app.kubernetes.io/instance: "engine-1"
    app.kubernetes.io/version: "2021-3"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "astute-knowledge"
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/RDWeb/actuator/health/liveness"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "10"
spec:
  ingressClassName: "nginx"
  rules:
    - host: "engine1.astuteknowledge.test"
      http:
        paths:
          - path: /RDWeb
            pathType: Prefix
            backend:
              service:
                name: engine-1
                port:
                  number: 80
---
# Source: engine/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "engine-1-test-connection"
  labels:
    helm.sh/chart: engine-2021.3.0
    app.kubernetes.io/name: "engine"
    app.kubernetes.io/instance: "engine-1"
    app.kubernetes.io/version: "2021-3"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "astute-knowledge"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['engine-1:80/RDWeb/actuator/health/liveness']
  restartPolicy: Never

**Comment by Chimney42** [comment]
Hi @qelan,
thanks for filing this issue! Could you also share the content of your Tiltfile?

Thanks!

**Comment by Chimney42** [comment]
Thanks!
If I understand correctly, you are building one docker image here
```
build_java_image('engine', 'Web-7.0.jar', '../Server/Web',
                 ['parent-pom', 'core', 'RealDialogSOAPforJava', 'server', 'weblib', 'webobjects'])
```
and then deploying multiple resources with this image like this
```
for i in range(len(engine_names)):
    engine_index = i + 1
    engine_host_name = 'engine{0}.astuteknowledge.test'.format(engine_index)
    engine_deploy_name = 'engine-{0}'.format(engine_index)
    deploy_java_service(
                        deploy_name=engine_deploy_name,
                        name='engine',...
    )
```
You are probably receiving the error because you are trying to run `tilt up engine`, but the resources  are named `engine-1`, `engine-2`, etc.
Could you try running `tilt up engine-1` to see if that works?

**Comment by qelan** [comment]
I am not adding anything after "tilt up", so that can't be the problem.  I am trying to run the entire stack.

**Comment by Chimney42** [comment]
When you receive the error message it should say something like

```
You specified some resources that could not be found: "asdfasfklasj"
Is this a typo? Existing resources in Tiltfile: "api", "web"
```
Could you share which existing resources are listed for you?

**Comment by Chimney42** [comment]
In your Tiltfile you are setting the enabled_services 
```
config.define_string_list('enabled_services')
```
which is equivalent to running `tilt up <service>`
Did you specify anything in that list in your config?

**Comment by qelan** [comment]
Yes, I did have a list of services to run, and that included 'engine' rather than 'engine-1'.

Is there a way to make the error message more informative, so I could have known to look there rather than filing this meaningless bug report?

**Comment by Chimney42** [comment]
It's definitely worth thinking about!

Do you have a suggestion how that error message could have been more informative or a workflow that would have made it easier for you to track down the issue?

**Comment by qelan** [comment]
Since it was related to enabled_services, if it could have said something like:

Your enabled_services includes XXXX, but that resource was not found.  The resources that are defined are: XXX, YYY, ZZZ

**Comment by Chimney42** [comment]
I have opened a feature request for this: https://github.com/tilt-dev/tilt/issues/5144
You can add more details and context in there if you'd like.

If this solves your issue for now, let me know, or you can also close this issue yourself :)

**Comment by qelan** [comment]
Thanks for your help.
