### ISSUE TITLE
custom_build auto_init = False

### ISSUE THREAD

**Issue by majidaldo** [tilt-dev/tilt#5146]
## Describe the Feature You Want
I don't want Tilt to invoke custom_build on startup. Trying to combine local_resouce for this feature and custom_build was getting ugly.

### Why Do You Want This?
I build everything remotely (I think tilt should abstract out building images).

**Comment by landism** [comment]
Tilt doesn't invoke `custom_build` as an independent thing, but in order to build an image used by a resource. To prevent it from running on startup, you can specify `auto_init=False` on the resource(s) consuming the image generated by the `custom_build`. Let me know if that helps!
