### ISSUE TITLE
dependency graph

### ISSUE THREAD

**Issue by majidaldo** [tilt-dev/tilt#5147]
Just a general comment: I've been soaking up Tilt for the past few days. Just like build systems in general, I think Tilt should generate a dep graph so that a user can see at a high level what's going on. As I'm going through the docs I see things like 'deps' and 'resource_deps'. They should just be one thing: deps.

Is this possible?

**Comment by landism** [comment]
Thanks for filing! I think this is covered by #3979. Feel free to reopen if it's different.
