### ISSUE TITLE
`helm` builtin doesn't give accurate `Capabilities.ApiVersions`

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#5149]
### Expected Behavior
When loading a helm chart via `helm` in a Tiltfile, the helm chart can run with an accurate value for `Capabilities.ApiVersions`.

### Current Behavior
The `helm` builtin runs `helm template`, which does not talk to the k8s cluster and `Capabilities.ApiVersions` is populated with hard-coded values from k8s 1.16.

### Steps to Reproduce
1. add this to an object's metadata in a helm chart:
```
  annotations:
    capabilities: "{{- join "," .Capabilities.APIVersions }}"
```
(you can also try `{{Capabilities.APIVersions.has("mygroup/v1")}}` for some group in your cluster)
2. Load that chart with a `helm` call in a Tiltfile (or just run `helm template` on it and skip Tilt, if you trust Tilt is just running `helm template`)
3. Observe that it reflects some hardcoded values rather than what's actually in your cluster.

### Notes
1. Users can work around this with `local('helm template blah --validate')` or the same with `--api-versions`
2. Googling "Capabilities.APIVersions.Has" brings up some useful related bugs - this has confused a lot of helm users
3. Calling `helm template --validate` causes helm to talk to the api server and properly populate `Capabilities.APIVersions`, but introduces another problem: https://github.com/helm/helm/issues/6663
4. `helm template` supports an `--api-versions` arg, which allows one to populate `Capabilities.APIVersions` without talking to the API server, but then either the user would need to list api versions in the Tiltfile or we'd need to grab API versions from the API server.
  a. Grabbing API versions from the server could be trouble because we'd run this as part of Tiltfile execution before actually creating any CRDs. We could have Tilt also grab API versions from yaml that has been passed to `k8s_yaml`, as long as those calls precede the `helm`.
5. Maybe we can just do `--validate` and `--is-upgrade`? This was [re-added to helm to address this case](https://github.com/helm/helm/pull/7054), but I haven't fully understood whether we can just always use it or if we'd need to only use it on invocations after the first.

**Comment by nicks** [comment]
`helm_resource` should support this: https://github.com/tilt-dev/tilt-extensions/tree/master/helm_resource

I'm going to close this issue. We can re-open if someone REALLY wants to add an `--api-versions` arg to the old helm() function, but I suspect they'd be happier using `helm_resource`.
