### ISSUE TITLE
allow use of Tiltfile functions defined in v1alpha1.extensions

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#5171]
## Describe the Feature You Want
* The ability to write shared Tiltfile code that doesn't need to be published to tilt-extensions (perhaps to allow a lower quality level, avoid bottlenecking on a Tilt reviewer, or for security/privacy reasons)
* v1alpha1.extension could allow this, but since it's loaded asynchronously, the Tiltfile can't read from a Tiltfile loaded by it.

### Current Behavior
* v1alpha1.extensions are loaded asynchronously, so a Tiltfile cannot load their code
* extensions can be published to the tilt-extensions repo, but there are many potential extensions for which that is not appropriate
* extensions can be just put in any old repo and loaded via the git_resource extension

### Why Do You Want This?
* presumably v1alpha1.extension is the future, and it'd be nice to reduce the number of ways in which we're pulling in Tiltfile code (and the number of things we're calling "extension"
* alternatively, we could decide we're not going to support this and documenting this on v1alpha1.extension to help users avoid going down a rabbit hole

**Comment by nicksieger** [comment]
I'd love to see better first-class support for loading extensions from multiple possible sources, similar to [how you can do this in Terraform](https://www.terraform.io/docs/language/modules/sources.html). I think `git_resource` isn't named well enough that it's obvious that you'd use it to load shared Tiltfile code.

**Comment by nicks** [comment]
i have a branch that does this

basically the plan was to have a syntax like:

```
extension_repo(name='default', ...)
extension(name='kubefwd', repo='default', ...)

load('ext://kubefwd', 'some_symbol')
```

To change `load()` so that it
- writes any pending extension_repo/extension objects to the apiserver
- wait on them to finish executing
- memoize the symbols in-memory (this is how starlark is designed to work in practice - and why it's so aggressive about making things immutable)
- load('ext://kubefwd') loads symbols registered by the extension named 'kubefwd'

but i ran out of time and decided to deprioritize it in favor of other things (there's some gotchas around making this work well with 'tilt down', etc)

**Comment by tachiniererin** [comment]
i'm currently running into the issue that i would need exactly this feature. i'm building a bunch of custom functions for defining internal services (e.g. generalized live update and so on) which will be shared across 10+ repos and services.
it's quite useless as a public tilt extension, so the feature i'd really need is loading extensions from private repos.

for now a hack with git_resource will do, but this would be really great to have in the future.

**Comment by nicks** [comment]
As of v0.25, we now let you load functions from extensions loaded with v1alpha1.extension. Guide is here: https://docs.tilt.dev/extensions.html
