### ISSUE TITLE
dc_resource(auto_init=False)

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#5176]
`dc_resource` should have an `auto_init=False` argument, to match the argument for k8s_resource and local_resource

**Comment by Chimney42** [comment]
@nicks for `k8s_resource` and `local_resource` autoInit defaults to True. What's the reasoning behind defaulting it to False for `dc_resource`?

**Comment by nicks** [comment]
it should default to True for dc_resource too, but you should be able to set it to False

**Comment by Chimney42** [comment]
As a side note: When I spin up a resource with `auto_init=False` in the UI, it behaves like a disabled service with no manual trigger. I would expect a resource where auto_init is disabled to always have the trigger mode set to `TRIGGER_MODE_MANUAL`.
Is this worth a separate issue?

**Comment by nicks** [comment]
afair, there was a fair amount of discussion about this at the time, but i don't remember what the content of the discussion was - @milas might remember, cf https://github.com/tilt-dev/tilt.build/pull/868

i believe this mode is intended for tests where you don't want the test to run at startup, but you do want the test to run when you change a file.

**Comment by milas** [comment]
Yeah, I think the context is right (don't run this test on startup, but run it if I change a relevant file), but I also feel like the UI should _probably_ still provide a manual trigger in that case, so might be worth an issue still.

**Comment by nicks** [comment]
filed as https://github.com/tilt-dev/tilt/issues/5252
