### ISSUE TITLE
Local resource task incorrectly displays as failing

### ISSUE THREAD

**Issue by heycait** [tilt-dev/tilt#5177]
### Expected Behavior
Tilt is running a `local_resource` task with a make command that runs `go test`. When all tests have passed, it returns a zero exit code and should show up as passing in both the task logs and the sidebar.

### Current Behavior
Tilt shows the task as failed.

While I have previously seen Tilt show this task to have succeeded, when it does incorrectly show up as failed, it consistently does so even upon task re-runs. 

```
.
.
.
=== RUN   TestUpdateSkipsUpdatedPods
--- PASS: TestUpdateSkipsUpdatedPods (20.08s)
=== RUN   TestUpdateRollback
    update_test.go:290: Skipping rollback tests
--- SKIP: TestUpdateRollback (0.00s)
PASS
ok  	.../test/e2e	150.955s
[RED] Server exited with exit code 0
```

### Steps to Reproduce

1. Make a Tiltfile with a `local_resource` running `go test` with the final test skipped OR possibly any bash script that returns exit code 0.
2. `tilt up` see task fail

I'm not sure 100% how to reproduce this as I have seen it work but now it's stuck in the failed state. Once it gets to the failed state, it seems to stay that way even on a fresh minikube cluster (I have yet to see it succeed again).

#### `tilt doctor` Output
```
$ tilt doctor
Tilt: v0.23.0, built 2021-11-12
System: darwin-amd64
---
Docker (cluster)
- Host: tcp://127.0.0.1:53567
- Server Version: 20.10.8
- API Version: 1.41
- Builder: 2
---
Docker (local)
- Host: [default]
- Server Version: 20.10.8
- Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.22.2
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: 3b722dd486b9a926fc9947beba57d241
- Repo: BN+SQX4S10y+S8cBM9muRA==
```

**Comment by nicks** [comment]
Can you provide the snippet of your tiltfile that runs the test?

The error message "Server exited with exit code 0" looks suspicious to me, because that usually means you have a `local_resource(serve_cmd="./run-some-server.sh")`, where the server is not expected to ever exit (and even exit code 0 is a problem)

**Comment by nicks** [comment]
fwiw, I tried to repro with this Tiltfile:

```
local_resource(
  'custom-cmd',
  cmd='exit 0')
```

which seemed to work ok for me...I'm hoping a snippet will help add detail important to finding a repro case.

**Comment by heycait** [comment]
Here's the snippet of the Tiltfile:

```
local_resource(
    "e2e-tests",
    serve_cmd="make test-e2e-minikube",
    deps=[
        "ts/cmd/",
        "ts/internal/",
        "ts/pkg/",
    ],
    resource_deps=["run-controller"],
)
```

The make command definition:
```
test-e2e-minikube:
	E2E_NAMESPACE=default E2E_IMAGE=nginx:1.15 STORAGE_CLASS=standard go test ./test/e2e/... \
		-kubeconfig=${HOME}/.kube/config -kubeconfig-context=minikube -v -tags=e2e
```

**Comment by heycait** [comment]
I realize now it should be `cmd` instead of `serve_cmd`. I'm not sure if I had that before when it was succeeding and it somehow got changed.
