### ISSUE TITLE
docker image status

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#5185]
We currently have KubernetesApply, which depends on image builds

We don't currently model those image builds in the API server

We're going to start simple: writing data about docker_build to the API server.

We'll add a new object DockerImage

Which contains:

- How the image was built
- When the build started/ended
- Detailed performance data from the buildkit API

The initial idea is to have just enough data that you can write a little extension that reports build stats to honeycomb / datadog / etc

**Comment by milas** [comment]
* API schema: https://github.com/tilt-dev/tilt/pull/5175
* Docker build perf tracking: https://github.com/tilt-dev/tilt/pull/5183
* Docker Compose build perf tracking: https://github.com/tilt-dev/tilt/pull/5195

**Comment by nicks** [comment]
launched! https://api.tilt.dev/kubernetes/docker-image-v1alpha1.html
