### ISSUE TITLE
Live Sync Sporadically Does Full Rebuild

### ISSUE THREAD

**Issue by rwoll** [tilt-dev/tilt#5196]
### Expected Behavior

Several `touch`es or edits to a `live_update` `sync`'d file should only use existing container and not trigger a build or recreate.

### Current Behavior

Sporadically, and seemingly non-deterministically, Tilt will decide to do a full build/recreate of a container even though we expect it to simply be doing a `live_update`+`sync`.  This is true with a very aggressive `.dockerignore`, too. These even happens for trivial changes like simply saving the same file repeatedly. It'll be fine the first few saves (i.e. get live sync'd), but then sporadically when you go to save, Tilt decides to recreate the whole container. This is even while all working on the same file without switching between files.

### Steps to Reproduce

```
$ git clone https://github.com/rwoll/tilt-live-sync-triggers-full-rebuild-repro.git
$ cd tilt-live-sync-triggers-full-rebuild-repro
$ tilt up
```

Once Tilt is up and the `ui` resource is green, start editing `src/App.tsx` a bunch (saving every couple of edits). You can also simply try running: 

```
$ for i in `seq 1 100`; do echo $i; touch src/App.tsx; sleep 10; done
```

In the Tilt UI, most of the time  you'll see it live sync but ever couple of saves it will do a full re-rcreate:

![repro-example-tilt](https://user-images.githubusercontent.com/11915034/142335032-f8035c96-8410-4a56-af09-36c4029230df.jpg)

The above happened when I simply did a touch on `src/App.tsx` 3 times in a row waiting a bit in between. The first two times it did what you'd expect, but the 3rd time it decided to do a full build+recreate.

### Context

Some things to note:

1. The linked repro was created via Create React App:

    ```
    $ npx create-react-app my-app --template typescript --use-npm
    ```
2. We're using Docker Compose, not k8s.
3. We're using a specifically named container in our DC config
4. This was repo'able on 3 different macOS machines (2 of which are M1s)
5. `tilt describe filewatches docker-compose:ui` didn't output anything unexpected. It just lists the `src/App.tsx` changes.

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.23.0, built 2021-11-12
System: darwin-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.8
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
---
Kubernetes
- Env: docker-for-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.21.5
- Cluster Local Registry: none
---
```

#### About Your Use Case

We can't use Tilt with our UI dev for now so it has a more involved setup than the rest of our Tilt workflow (which is basically just `tilt up` since Tilt is generally so awesome! <3 ) We gave UI dev in Tilt a shot, but the sporadic slower updates when we hit this case made us decide to switch back to running the UI in a different way.

Overall, we're loving Tilt so we'd appreciate any help debugging this! Thanks so much for your work! 😄

**Comment by hyu** [comment]
Hi @rwoll, thanks for this detailed description of the issue. Live Update definitely should be using the existing container in the cases you outlined! We'll look into this issue and see what's causing this odd behavior.

**Comment by nicks** [comment]
This is definitely a tilt bug. 

But there's also something odd going on with your docker-compose file:

```
version: '3.8'
services:
  ui:
    container_name: ui
    image: rwoll/tilt-repro:offline
    build:
      context: .
 ```

In docker-compose, you typically don't define both "image" and "build" (since docker-compose will only use one or the other).

I tried your repro case without the "build" section and it worked a lot better.

I think what's happening is that one part of Tilt is assuming that you want Tilt to own the image build process, and another part of Tilt is assuming you want Docker Compose to own the image build process, and it's leading to weird race conditions

**Comment by rwoll** [comment]
> But there's also something odd going on with your docker-compose file:
> In docker-compose, you typically don't define both "image" and "build" (since docker-compose will only use one or the other).

Perhaps it's odd to do in one file, but it's not uncommon to use multiple overrides that would have these sort of directives combined. Granted, perhaps, with multiple `-f` args to docker-compose it is properly "merging" while this explicit file is confusing either Tilt or DC.

@nicks What happens if you have two files where one has all your services use pre-built image by default, and then you layer on overrides to use local builds for some services? Like this:

`docker-compose.yml`:

```
version: '3.8'
services:
  ui:
    container_name: ui
    build:
      context: .
```

`local-overrides.yml`:

```
version: '3.8'
services:
  ui:
    image: rwoll/tilt-repro:offline
```

and then, in the `Tiltfile`:

```
docker_compose(["docker-compose.yml", "local-overrides.yml"])
```

Will that work properly? (I haven't yet tried the above with the linked repro case to see if it's any better.) I expect that it would to match the following workflow we've been doing with the DC CLI.

```
docker-compose -f  docker-compose.yml -f local/ui.yml -f local/api.yml …
```

While it looks silly in this example, we have 30+ services, so we have a default `docker-compose.yml` file that specifies `image` (pointing to an actual remote repo), and then, depending on what we are working on, will add `local/<service>.yml` like above to get local versions of the build. This saves you from having to build everything locally unless you're working on a particular service.

FWIW, I've seen this pattern in other environments. I haven't yet tested if having this split over multiple files v. in one file changes things.

**Comment by rwoll** [comment]
@nicks i just edited my last comment. In the original version of my last comment, I flipped image and build in the example files.

In the case of build+image, image should simply act like a tag:

> If you specify image as well as build, then Compose names the built image with the webapp and optional tag specified in image

(Source: https://docs.docker.com/compose/compose-file/compose-file-v3/)

So I don't think there is anything "odd" about the checked in compose file.

**Comment by nicks** [comment]
don't worry, Tilt loves all our users, even in the odd ones! :heart: 

definitely didn't intend to suggest you're doing anything wrong! Pointing out this detail because:
- now we know which environments it affects
- there's a short-term workaround for simple cases
- it gives a clue to what the underlying tilt bug is and how we might fix it

**Comment by rwoll** [comment]
Thanks! I didn't think anything of it! but I appreciate the ❤️ and the help! Sorry if my comment came across differently; I should have been less blunt!

I only intended to clarify that I think the file is in spec based on how I've seen docker compose used and what the docs state, so the workaround should be temporary if possible!

Thanks again for helping look into it! ❤️

**Comment by rwoll** [comment]
@nicks Confirmed the workaround works for us! Thanks for narrowing it down!

Opened https://github.com/tilt-dev/tilt.build/pull/987 in case others hit this!

In terms of longer term fix, I think either:

1. Warning the user when Tilt sees this conflicting usage (similar to how the unused image build warning pops up),
2. Have `docker_build` in the Tiltfile take precedence over the Docker Compose file's build.

I personally have a preference for (2) as that's how expected Tilt to work before filing this issue. (It would also save us from having two docker compose files. I "fixed" our setup for now by automatically stripping the `build` section from the docker-compose file on `tilt up` and generate a compose file Tilt is happier with!)

Anyways, thanks for your time and help! Love Tilt and looking forward to having our UI bits back integrated with the rest of our Tilt stack! (Also, the docs repo was super clean to edit and preview! Love that it uses Tilt, too 😄  )

**Comment by rwoll** [comment]
Relates #4094, #3282

**Comment by milas** [comment]
A fix for this will be in the next version of Tilt - internally, the way that Tilt represents Docker Compose image builds has been changed, which should alleviate the race condition seen here.

Thanks for reporting this issue and providing a full repro!

**Comment by rwoll** [comment]
Thanks so much @milas! Appreciate all y'all's help! The workaround has been working well for us, but we will be happy to remove it!!

Cheers! 🎉
