### ISSUE TITLE
--env-file support for docker-compose projects

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#5265]
## Describe the Feature You Want
Docker Compose lets you manually specify the env-file on the CLI
https://docs.docker.com/compose/environment-variables/#using-the---env-file--option

The docker_compose function should support this as well

**Additional context**
Related issue (but very different): https://github.com/tilt-dev/tilt/issues/2643 (this is more about having ways to integrate the .env file with tilt configuration)

**Comment by nicks** [comment]
The workaround is to read the env file yourself with local() and use the result to populate `os.environ` (this could be implemented as a tiltfile extension).
https://docs.tilt.dev/api.html#modules.os.environ

But this would affect all environments, not just the docker-compose project

**Comment by nicksieger** [comment]
This will be easy to add once I merge #5259.
