### ISSUE TITLE
tilt doesn't start on ubuntu with node 14.18.2

### ISSUE THREAD

**Issue by rotten** [tilt-dev/tilt#5317]
### Expected Behavior
After building tilt, for it to "just work", if I have node version 14.18.2 installed.

### Current Behavior
Instead it fails to recognize my node version, which, as near as I can tell, is in the set of allowed ranges.

```

$  tilt up
Tilt started on http://localhost:10350/
v0.23.4-dev, built 2021-12-21

(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
Error: Error installing Tilt webpack deps:
stdout:
yarn install v1.22.17
[1/5] Validating package.json...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

stderr:
error tilt-ui@0.1.0: The engine "node" is incompatible with this module. Expected version ">=14.0.0 <15.0.0, >=16.0.0 <17.0.0". Got "14.18.2"
error Found incompatible module.

error: exit status 1
```

### Steps to Reproduce
1.  Install node 14.18.2 on an Ubuntu 20.04 system:  https://linuxize.com/post/how-to-install-node-js-on-ubuntu-20-04/
2. Build tilt.
3. Try to run it.

#### workaround:
1. edit `web/packages.json` and set it to require the exact version of node that you have installed.
2. build and install tilt
3. then it works.

### Context
...
```Tilt: v0.23.4-dev, built 2021-12-21
System: linux-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.7
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build unknown)
---
Kubernetes
- Env: none
- Context:
- Cluster Name: Unknown
- Namespace: default
- Container Runtime: unknown
- Version: Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: default
- Machine: dbe26443951b43ee5fd52c1fe1dda77b
- Repo: NA7iRe6A6n8EeXIu2lNuWw==
```

#### About Your Use Case
Trying tilt for the first time.  It wouldn't run.

**Comment by hyu** [comment]
Hi @rotten, thanks for the detailed report! I don't have a machine running Ubuntu handy to repro this, but I'll ask one of my colleagues. 

Just to be clear, when you modified the package.json to work with the version of node you had installed, Tilt worked properly, as far as you can tell?

**Comment by rotten** [comment]
As far as I can tell, Tilt is working ok.  I'm still pretty new to it, so I'm probably not hitting any dusty corners or edge cases.

**Comment by nicks** [comment]
can you give some background on why you want to build tilt on Node 14? are you hoping to contribute, or something else?

`make install` will give you a dev build, which will generally be much slower. As you noticed, it needs NodeJS to build an entire web dev toolchain for live-reloading the Tilt UI when the source changes.

If you install tilt with Homebrew or any of the installers (https://docs.tilt.dev/install.html) you don't need Node at all.

Since the Tilt UI isn't really intended to be used as a library, I'm not sure it's a good use of time to support compiling it with arbitrary Node versions.

**Comment by rotten** [comment]
Node 14 is what I'm using for a NodeJS app, so it was already installed on my laptop.  The error message implied it should be within the supported range of Node versions, so I would have expected it to work.

The way I read this:
```
error tilt-ui@0.1.0: The engine "node" is incompatible with this module. Expected version ">=14.0.0 <15.0.0, >=16.0.0 <17.0.0". Got "14.18.2"
```
It seemed like it was between 14.0.0 and 15.0.0.

Since I'm on Ubuntu, I didn't want to use homebrew.

I also didn't want to run arbitrary scripts off the web.  I thought I could simply build and deploy it from source since it isn't supported in the apt package manager or the snap package manager for Ubuntu.

**Comment by milas** [comment]
Apologies for the late follow-up here.

The version range in `package.json` had a syntax mistake, which was causing it to look like it supported 14.x but only accepting 16.x. I've updated it to explicitly only accept 16.x (current LTS) to avoid further confusion in #5788, so I've closed this issue based on the original problem statement.

That said, I realize this issue's scope changed given the build-from-source goal and also understand the hesitation around running arbitrary scripts from the internet! I encourage you to read/audit the [Tilt install script](https://github.com/tilt-dev/tilt/blob/master/scripts/install.sh) or download a binary release from [GitHub releases](https://github.com/tilt-dev/tilt/releases/latest) manually.

You can of course continue to build from source if desirable with the understanding that the Tilt build process can be a bit more complex than some other apps.
