### ISSUE TITLE
upgrade to controller-runtime v0.11 and k8s v0.23

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#5320]
I have a branch to upgrade to controller-runtime v0.11 and Kubernetes v0.23

https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.11.0

Unfortunately, I ran into some issues:
https://github.com/kubernetes-sigs/controller-runtime/issues/1752

I'll resolve this upstream and report back.

**Comment by milas** [comment]
(This was done)
