### ISSUE TITLE
Allow customization of the `tilt_modules` path.

### ISSUE THREAD

**Issue by psigen** [tilt-dev/tilt#5336]
## Describe the Feature You Want
Provide a way to customize the location used for the `tilt_modules` directory that must be committed to VCS.  Ideally this would be a setting in the Tiltfile, but an environment variable or command line flag would be better than no customization at all.

### Current Behavior
As far as I can tell [from the documentation](https://docs.tilt.dev/extensions.html#commit-to-source-control), it is not possible to customize the location of the `tilt_modules` folder.

### Why Do You Want This?
In some cases, especially monorepos, there may be existing directory layouts that make it inconvenient for the `tilt_modules` to be directly contained at the same level as the `Tiltfile`.

There might also be a desired prefix to help designate it as a tool directory (e.g. `.tilt_modules`) for IDEs and other automated tooling.  Allowing the customization of the `tilt_modules` from a `Tiltfile` would allow for users to customize this to their preference.

**Comment by solarmosaic-kflorence** [comment]
We have a monorepo and I'd much rather have all the extensions we use in the root of the repository instead of in every single project (20+ at this point in time).

**Comment by nicks** [comment]
thanks for reporting! my plan on this is to have something like described here:
https://github.com/tilt-dev/tilt/issues/5171#issuecomment-969124590

to version the extensions and store them under ~/.local/share/tilt-dev, rather than in the same directory as your source

**Comment by nicks** [comment]
As of v0.25, we no longer put the extension under tilt_modules next to the Tiltfile. We put them under the XDG data dir as specified here: https://wiki.archlinux.org/title/XDG_Base_Directory

We also provide ways to customize where the extension repo loads from: https://docs.tilt.dev/extensions.html
