### ISSUE TITLE
k8s yaml manipulation docs

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#5368]
When loading k8s yaml in a Tiltfile, one often uses production yaml and needs to make minor tweaks to it for use in dev (e.g., adding a namespace, using a different service name, changing an image name, or reducing cpu limits).

There are a number of options available, including:
1. kustomize
2. helm
3. Tilt extensions (e.g., https://github.com/tilt-dev/tilt-extensions/tree/master/namespace)
4. loading the yaml in the tiltfile and manipulating it via starlark (i.e., what the extensions do, but inline)

For users already familiar with / using kustomize and helm, those make sense. We've had a number of users unaware they could manipulate k8s objects in the Tiltfile itself.

A doc discussing / advertising these options seems valuable.

**Comment by nicks** [comment]
feels like we can adapt this a bit : https://www.dex.dev/dex-videos/templating-solutions
