### ISSUE TITLE
tilt ci never exits when you create both deployments and jobs in a single resource

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#5394]
Repro case:

```
ingress_yaml = 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml'
k8s_custom_deploy(
  'ingress-nginx',
  apply_cmd="kubectl apply -f %s -o yaml" % ingress_yaml,
  delete_cmd='kubectl delete -f %s -o yaml' % ingress_yaml,
  deps=[])
```

Then run:

```
tilt ci
```

Expectation: Tilt should exit as soon as the Deployment pod becomes ready

Actual: Tilt hangs forever

The problem is this manifest contains both deployments and jobs. Tilt gets super confused. Generally, the Tilt UI will use Deployment readiness for visual state, but the CI controller will see the Job and wait for all pods to complete :grimacing: 

## Related Context

I feel like we've made some investment recently into how Tilt handles jobs, in particular:
https://github.com/tilt-dev/tilt/issues/4809
and the stuff around PodReadinessMode (in pkg/model) and around job detection in the Session API

But I'm not quite sure what the right logic should be in this case.

cc @milas @landism what do you think?

**Comment by milas** [comment]
Oh, that's interesting!

I'd say we should wait for all Jobs to be done + all non-job Pods ready.

Longer-term, I could see expanding the readiness options so you could do something like:
```python
k8s_resource(
    "foo",
    readiness={
        "job:ingress-nginx-admission-create": "ignore",   # don't even look at this object
        "deployment:ingress-nginx-controller": "started",  # ignore readiness probe but make sure it launches
    },
)
```

---

Sidenote: If we make any change, I'd also suggest a version bump and call it out as a potentially breaking change - during Session controller impl, there were a couple instances of behavior changes smaller than this that I had to revert to avoid impacting existing projects.
