### ISSUE TITLE
disable_snapshots() is throwing a message saying feature obsolete

### ISSUE THREAD

**Issue by MMartyn** [tilt-dev/tilt#5395]
### Expected Behavior
I would expect that it would disable snapshots

### Current Behavior
Throws message saying that the snapshot flag is obsolete

### Steps to Reproduce

1. Attempt to use disable_snapshots() in Tiltfile

### Context
Tilt: v0.23.6, built 2022-01-14
System: darwin-arm64

**Comment by MMartyn** [comment]
Relevant links:
https://github.com/tilt-dev/tilt/blob/master/internal/tiltfile/features.go#L53
https://github.com/tilt-dev/tilt/blob/master/internal/feature/flags.go#L53
https://github.com/tilt-dev/tilt.build/blob/master/src/_includes/functions.html#L1226

**Comment by milas** [comment]
Thanks for the report! This will be fixed in the next Tilt release (scheduled for tomorrow)

**Comment by milas** [comment]
Tilt [v0.23.7](https://github.com/tilt-dev/tilt/releases/latest) has been released which includes a fix for this. If you still see issues after upgrading, please feel free to either re-open this issue or create a new one 🙂

**Comment by MMartyn** [comment]
Thanks for the quick fix. I'll give it a try on Monday
