### ISSUE TITLE
Wildcard used to detect changes is not working

### ISSUE THREAD

**Issue by maelfosso** [tilt-dev/tilt#5419]
### Expected Behavior

I want to rebuild a Golang application when any changes occur in any *.go files
Here is my `local_resource`
```py
local_resource(
  'build-generator-api',
  compile_cmd,  
  deps=['./**/*.go']
)
```
It's from a Tiltfile at the root of the project.
`./**/*.go` is not working, it's not detecting changes from Go file.

When I click on the re-run button of this resource from `http://localhost:10350/r/build-generator-api/overview` which is supposed to re-build the app and live updating the corresponding image, I have this error on the deployment that is using the docker image
```
Will delete 1 file(s) from container: [generator-api-67fc98558-fgrx9/generator-api]
- '/home/guitou/app/build/main-go-tmp-umask' (matched local path: '/Users/[redacted secret env-secrets:GIT_AUTH_USERNAME]/Documents/Guitou/GitLab/msvc/msvc-generator-api/build/main-go-tmp-umask')
Will copy 1 file(s) to container: [generator-api-67fc98558-fgrx9/generator-api]
- '/Users/[redacted secret env-secrets:GIT_AUTH_USERNAME]/Documents/Guitou/GitLab/msvc/msvc-generator-api/build/main' --> '/home/guitou/app/build/main'
RUNNING: tar -C / -x -f -
Build Failed: Updating pod generator-api-67fc98558-fgrx9: copying files: Exec command exited with status code: 2
LiveUpdate "generator-api:guitou-app_msvc-generator-api" UpdateFailed: Updating pod generator-api-67fc98558-fgrx9: copying files: Exec command exited with status code: 2
```

### Current Behavior

No changes detected 

### Steps to Reproduce

Use wildcard to re-build a docker image

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.23.1, built 2021-11-19
System: darwin-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.8
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
---
Kubernetes
- Env: docker-for-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.21.4
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 35be8577fcb42be788b676fb16072ad3
- Repo:
...
```

**Comment by nicksieger** [comment]
Hi @maelfosso! Thanks for reporting this issue. Unfortunately, `deps` does not support globs or wildcards right now, only directories or paths. My suggestion for a workaround would be to put the name of the top directory containing all your go files for `deps`. And please 👍 or follow #2815 to let us know that you would like to see this improvement made! It helps us gauge interest for planning purposes.

Going to close this as a duplicate.
