### ISSUE TITLE
Manually triggering a resource after a Live Update causes a duplicate Live Update build + full rebuild

### ISSUE THREAD

**Issue by milas** [tilt-dev/tilt#5423]
### Expected Behavior
* Manually triggering a build from the UI invokes a full build

### Current Behavior
* In some cases, a Live Update build AND a full build are both started
* Live Update build fails after a moment (full build succeeds)
* Resource stuck in a perpetual pending state in Tilt UI

### Steps to Reproduce
1. `git clone https://github.com/tilt-dev/tilt-avatars.git`
2. `cd tilt-avatars && tilt up`
3. `touch api/requirements.txt` -> wait for LU to be processed
4. (Optional) Clear logs for `api` resource
5. Click 🔄 next to `api` resource in Tilt UI

Two builds show up in logs (truncated to relevant portions):
**Web Trigger • api**
```
STEP 1/4 — Force update
     Begin force update:
     → api:deployment
     → api:service
     Deleting kubernetes objects:
     → Deployment/api
     → Service/api

STEP 2/4 — Building Dockerfile: [tilt-avatar-api]
...
```

**1 File Changed: [api/requirements.txt] • api**
```
Will copy 1 file(s) to container: [api-84cbf89bcf-q48zk/tilt-avatar-api]
- '/Users/milas/dev/tilt-avatars/api/requirements.txt' --> '/app/api/requirements.txt'

...

RUNNING: pip install -r /app/requirements.txt
OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown
  → Failed to update container api-84cbf89bcf-q48zk/tilt-avatar-api: run step "pip install -r /app/requirements.txt" failed with exit code: 126
```
⬆️  this build should not exist ⬆️ 

### Context
Happens on both v0.23.8 + v0.23.9 (macOS/amd64)

**Comment by adamf** [comment]
We are seeing this often, once it happens tilt is unusable until a restart.

**Comment by landism** [comment]
> once it happens tilt is unusable until a restart

When I try the repro in the original bug report, the extra build is confusing, but things still work. I might be missing something, or that might be a different bug. Could you elaborate a bit on what Tilt is failing to do once this happens?

**Comment by adamf** [comment]
Awesome - I upgraded to 0.25.3 this morning and will report back if I can
repro. You can assume I don't see it again if you don't hear from me in
week (although I'll try to update this issue sooner than that!)

**Comment by nicks** [comment]
assuming this is fixed, we can re-open if we see it again!
