### ISSUE TITLE
`custom_build`: provide EXPECTED_REPOSITORY and EXPECTED_TAG addition to EXPECTED_REF

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [tilt-dev/tilt#5433]
## Describe the Feature You Want

For `custom_build` I would like to have `EXPECTED_REPOSITORY` and `EXPECTED_TAG` in addition to `EXPECTED_REF`. Essentially `EXPECTED_REF` should equal `EXPECTED_REPOSITORY:EXPECTED_TAG`.

### Current Behavior

Currently for `custom_build`, Tilt injects the `EXPECTED_REF` environment variable which contains the full image name + tag reference, like `repository:tilt-build-1643758949`.

### Why Do You Want This?

This is a nice to have. It is common to allow configuring the image repository and tag separately and that is the way our build tooling is currently set up. This means we have to prefix every `custom_build` command with `EXPECTED_REPOSITORY="${EXPECTED_REF%%:*}" EXPECTED_TAG="${EXPECTED_REF#*:}"` to refer to them separately in our build tooling.

**Comment by lizzthabet** [comment]
thanks for opening this feature request! i'd be curious to hear more about how your build tooling is using the repository and tag references. (the extra detail helps us understand your use-case better.)

**Comment by solarmosaic-kflorence** [comment]
hey @lizzthabet -- our custom build process uses a combination of [SBT native packager](https://www.scala-sbt.org/sbt-native-packager/) and a Helm chart (for the `Deployment`, among other things). In our `Deployment`, we have the image repository and image tag defined separately since the repository is generally a static value (defaulting to the name of the Helm release) and the build version generally comes in dynamically from the build environment. So it's just easier to work with those values separately. We could of course define another value in our Helm chart that encompasses both the image repository and tag as a single value, and use that instead if it is supplied, but I just felt like operating on them separately would be a somewhat common scenario.

**Comment by lizzthabet** [comment]
that's helpful context. thanks @solarmosaic-kflorence!
