### ISSUE TITLE
Flaky Test:  podlogstreamcontroller_test.go::TestLogsFailed

### ISSUE THREAD

**Issue by kensipe** [tilt-dev/tilt#5441]
### Expected Behavior
Consistency and deterministic test results

### Current Behavior
with no change in the environment, occasionally this test fails.  It was first noticed by me as the output of https://github.com/tilt-dev/tilt/pull/5440 shown on circleci here:  https://app.circleci.com/pipelines/github/tilt-dev/tilt/10689/workflows/c546b656-d6bb-42e9-ac1e-fabfd5c9efa8/jobs/83675

After a review, it seemed clear the code wasn't the issue.  It was by chance that I ran testing several times locally and eventually saw the same error.

### Steps to Reproduce

Well... that's the hard part... isn't it:)   The steps are to run the tests.   Run, Test Run!  multiple times!   It is unclear what the alignment of the planets must be... or if there was a rampant neutrino passing thru my machine.  or some kind of crazy quantum particle entanglement with circleci.

My experience has been this is usually the result of:
1. eventual consistency / timeout 
2. poor test design with no wait on what should be eventually consistent

I've tried `for i in {1..100}; do go test -run TestLogsFailed ./internal/controllers/core/podlogstream; done` but with no success... err failure.

#### `tilt doctor` Output

Not needed... this is a bug on test not on tilt itself

**Comment by lizzthabet** [comment]
thanks for the detailed report! unfortunately, flaky tests are part of the project's tech debt that we try to tackle on an ongoing basis. this can be frustrating and confusing for a new tilt contributor, when you may spend time chasing an issue that's actually just a flaky test! 

i'll mention (for record keeping) that circleci has a [helpful view](https://app.circleci.com/insights/github/tilt-dev/tilt/workflows/build/tests?branch=master&reporting-window=last-30-days) where it marks tests as "flaky" if they've failed and succeeded on the same test suite. that may be a useful tool for contributors and maintainers to reference.

if you think there are improvements tilt could make to its contribution guidelines and docs around contributing + encountering flaky tests, that's always welcome.
