### ISSUE TITLE
DecideRegistry prefers cluster registry info over default_registry()

### ISSUE THREAD

**Issue by nicksieger** [tilt-dev/tilt#5442]
### Expected Behavior
Using `default_registry()` did not set preferred registry location for `docker push`. Tilt used the information from the cluster instead.

### Current Behavior
`default_registry()` should tell Tilt which registry to use for all situations

#### `tilt doctor` Output
```
Tilt: v0.23.9, built 2022-01-27
System: darwin-arm64
---
Docker
- Host: [default]
- Server Version: 20.10.12
- API Version: 1.41
- Builder: 2
- Compose Version: v2.2.3
---
Kubernetes
- Env: microk8s
- Context: microk8s
- Cluster Name: microk8s-cluster
- Namespace: default
- Container Runtime: containerd
- Version: v1.22.5-3+2cf820a97417ce
- Cluster Local Registry: {Host:localhost:32000 hostFromCluster: SingleName:}
---
```

#### About Your Use Case
See [thread in Kubernetes slack](https://kubernetes.slack.com/archives/CESBL84MV/p1643716822296679) for more information.

**Comment by nicks** [comment]
have you seen this discussion? https://github.com/tilt-dev/tilt/issues/4125

**Comment by nicksieger** [comment]
I regret not searching before filing a duplicate 😦 . Closing this in favor of that.

**Comment by nicks** [comment]
i think a good rule of thumb is that we should err on the side of filing an issue twice rather than not filing it at all!
