### ISSUE TITLE
Misleading error message when an invalid label name is used

### ISSUE THREAD

**Issue by andymartin-sch** [tilt-dev/tilt#5464]
### Expected Behavior
If someone breaks the `A label must start and end with an alphanumeric character, can include _ , - , and . , and must be 63 characters or less` requirement from https://docs.tilt.dev/api.html#api.k8s_resource a clear error message should be shown

### Current Behavior
A misleading error message is shown:
```
You specified some resources that could not be found: ...redacted list of resources...
Is this a typo? Existing resources in Tiltfile: 
```

### Steps to Reproduce
Set `label` to something that includes an invalid character like `&` or `/`

### Context
```
Tilt: v0.24.0, built 2022-02-04
System: darwin-amd64
```

#### About Your Use Case
Very minor bug, but this made adding labels not fun. A developer on our team will probably hit this again in the future while adding new services too.

**Comment by andymartin-sch** [comment]
I think the "misleading error message" part of this is a dupe of https://github.com/tilt-dev/tilt/issues/5467

**Comment by landism** [comment]
Thanks for the report following up!

You should get this error as of [v0.24.1](https://github.com/tilt-dev/tilt/releases/tag/v0.24.1):
```
Error: local_resource: for parameter "labels": Invalid label "-12345": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

I'm closing this, but feel free to reopen if I've misunderstood the scope of the report (not sure if I'm reading too much into the "part of this" bit of your reply).
