### ISSUE TITLE
Using `v1alpha1.extension_repo` with ref pointing to a tag results in error

### ISSUE THREAD

**Issue by sbienkow-ninja** [tilt-dev/tilt#5508]
### Expected Behavior
Tilt extension repo is updated or kept as-is

### Current Behavior
Tilt crashes
```
$ tilt up --stream
Tilt started on http://localhost:10350/
v0.25.0, built 2022-02-11

Initial Build • (Tiltfile)
Loading Tiltfile at: /tmp/tilt/Tiltfile
# cd /home/sbienkow/.local/share/tilt-dev/tilt_modules/github.com/tilt-dev/tilt-extensions; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

ERROR: Traceback (most recent call last):
  /tmp/tilt/Tiltfile:3:1: in <toplevel>
Error: cannot load ext://namespace: loading extension repo default: download error: waiting 5s before retrying. Original error: exit status 1
ERROR: extensionrepo default: download error: waiting 5s before retrying. Original error: exit status 1
```

### Steps to Reproduce

Using following Tiltfile:

```python
# vim: ft=bzl sw=4
v1alpha1.extension_repo(name='default', url='https://github.com/tilt-dev/tilt-extensions', ref='v0.25.0')
load("ext://namespace", "namespace_create", "namespace_inject")
```

1. Make sure to clean downloaded extensions: `rm -rf ~/.local/share/tilt-dev/tilt_modules/github.com/tilt-dev/tilt-extensions/`
2. Run `tilt up --stream` - you will see `ERROR: No resources found.`
3. Close tilt with `Ctrl+C`
4. Run `tilt up --stream` again - you will notice the above error

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.25.0, built 2022-02-11
System: linux-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.12
- API Version: 1.41
- Builder: 2
- Compose Version: v2.2.3
---
Kubernetes
- Env: kind-0.6+
- Context: kind-kind
- Cluster Name: kind-kind
- Namespace: cloud
- Container Runtime: containerd
- Version: v1.22.5
- Cluster Local Registry: none
---
```

#### About Your Use Case

It doesn't let me freeze the version of extensions used - which is a regression, compared to previously available `tilt_modules` that were downloaded to the repository.

**Comment by nicks** [comment]
thanks for the report! ya, that's not right, lemme investigate

**Comment by nicks** [comment]
hopefully should have a fix today, but an easy workaround right now is to for the repo so that it uses the HEAD of your forked version
