### ISSUE TITLE
allow git/ssh extension_repo URLs

### ISSUE THREAD

**Issue by bamorim** [tilt-dev/tilt#5522]
## Describe the Feature You Want
```starlark
v1alpha1.extension_repo(name='my-repo', url='git@github.com:bamorim/my-tilt-extensions.git', ref='HEAD')
```

### Current Behavior
I can only specify `http` or `https` remote repos.

### Why Do You Want This?
We are starting to incorporate Tilt as our main tool for local development at SaltPay and we were looking into having our own repo for our company specific needs.
Our policies discourages public repositories and using SSH would have all the authentication sorted out for us.

If this is something you would be looking to support, maybe I can try to open a PR for that. I'm not a go expert but I could give a shot at it.

**Comment by nicks** [comment]
hi @bamorim ! When you tried to specify your repo as "https://github.com/bamorim/my-tilt-extensions", what happened? did you get an error message? what did it say?

(My understanding was that the underlying library we're using is smart enough to pick the right protocol based on location, similar to how go imports just do the Right Thing when you try to import from github)

**Comment by bamorim** [comment]
Hi @nicks thanks for reaching out. So, the problem in particular is my company's repo that requires SSO:

```
# cd .; git clone -- https://github.com/saltpay/saltpay-tilt-extensions /Users/Bernardo/Library/Application Support/tilt-dev/tilt_modules/github.com/saltpay/saltpay-tilt-extensions
Cloning into '/Users/Bernardo/Library/Application Support/tilt-dev/tilt_modules/github.com/saltpay/saltpay-tilt-extensions'...
remote: The `saltpay' organization has enabled or enforced SAML SSO. To access
remote: this repository, you must re-authorize the OAuth Application `GitHub for VSCode`.
fatal: unable to access 'https://github.com/saltpay/saltpay-tilt-extensions/': The requested URL returned error: 403
```

What I found weird is what it has to do with GitHub for VSCode.

**Comment by bamorim** [comment]
One workaround is to do: `git config --global url."git@github.com:".insteadOf https://github.com/` to use ssh instead of https for github.

Which is the same as putting in `.gitconfig`:

```gitconfig
[url "git@github.com:"]
        insteadOf = https://github.com/
```

But not sure if this is good enough.

**Comment by bamorim** [comment]
Hey @nicks thanks for that. For the time being, I'll instruct my team to set either `.netrc` or the `insteadOf` solutions.

I'll let you decide if the option should be added or not, but in my view explicit is better and I don't see how that would conflict with other options, but I might be too shortsighted.

Nevertheless, thanks a lot already for the explanation and help :heart:

**Comment by bamorim** [comment]
I personally think this approach works well enough and don't require changes to the code and would already be a concern for go modules. So I think I'd be happy with this for now. Do we want to close this?
