### ISSUE TITLE
Unescaped path when loading Tiltfile on macOS

### ISSUE THREAD

**Issue by nvowell** [tilt-dev/tilt#5526]
I get this error when loading my Tiltfile starting in version 0.25.0. Reverting to 0.24.0 fixes the problem. It seems like it's happening because of the space in the path at "Application Support". I'm guessing the problem happened somewhere here:  https://github.com/tilt-dev/tilt/commit/b509b25e306719ce49cdd7d965527e96eb1f758a but I'm not familiar enough with your codebase, or golang for that matter, to pinpoint where the problem is.
```
Loading Tiltfile at: /Users/nick/path/to/my/project/Tiltfile
local: helm repo list --output yaml 2>/dev/null || true
local: helm repo update
local: helm pull bitnami/rabbitmq --untar --destination /Users/nick/Library/Application Support/tilt-dev/.helm/bitnami/8.11.0 --version 8.11.0
Traceback (most recent call last):
  /Users/nick/path/to/my/project/Tiltfile:19:12: in <toplevel>
  /Users/nick/Library/Application Support/tilt-dev/tilt_modules/github.com/tilt-dev/tilt-extensions/helm_remote/Tiltfile:169:14: in helm_remote
  <builtin>: in local
Error: command "helm pull bitnami/rabbitmq --untar --destination /Users/nick/Library/Application Support/tilt-dev/.helm/bitnami/8.11.0 --version 8.11.0" failed.
error: exit status 1
stdout: ""
stderr: "Error: repo Support not found\n"
```

**Comment by nicks** [comment]
hmmmm...when did you see this error?

tilt v0.25 changed the location of where extensions were downloaded, and broke some extensions that weren't properly escaping paths.

but that should be fixed in this PR:
https://github.com/tilt-dev/tilt-extensions/pull/335
and when you run tilt, it should automatically pull in the extension update.

**Comment by nvowell** [comment]
That fixed it, thank you!
