### ISSUE TITLE
Keep log regex filter on a resource when switching resources

### ISSUE THREAD

**Issue by adamf** [tilt-dev/tilt#5567]
## Describe the Feature You Want
I want log filters to persist on a per-resource basis even when switching to and from resources.

### Current Behavior
If I'm looking at resource A, and put in a log filtering regex, then switch to resource B, and switch back to resource A, the log filter is gone.

### Why Do You Want This?
I often run a filter like `/^((?!(kube)).)*$/` to filter out logs from kubernetes probes. It's annoying that when I switch off the resource I'm filtering to check another resource, then flip back, I lose the filter.

**Additional context**

**Comment by lianmakesthings** [comment]
Hi @adamf,
thanks for filing this issue.
The filter string is part of the URL when you apply it. So, if you're really just switching back and forth between two resources, you could navigate back in the browser, which would take you to resource A with the regex filled in.
Would the work for you as a temporary workaround?
