### ISSUE TITLE
Change to a `Dockerfile` sporadically results in erroneous re-use of cached image

### ISSUE THREAD

**Issue by milas** [tilt-dev/tilt#5586]
## Expected Behavior
* A Docker build is triggered whenever the `Dockerfile` changes

## Current Behavior
* Sometimes, despite seeing the `Dockerfile` change, the Docker build will be skipped and the previously cached image will be used

## Steps to Reproduce
1. Create a project with a `docker_build` deployed to K8s
2. Change the `Dockerfile` (add/delete a commented line) <-- intermittent, so might have to try many times 😢 

## Context
I believe I know what's going on:
* The `(Tiltfile)` resource watches the `Dockerfile`s because it reads the file contents into memory to use for the image target (let's call it `image:foo`)
 * The `image:foo` target might _also_ be watching `Dockerfile` if not explicitly ignored by the file watch rules
 * Order these get seen is non-deterministic and can cause problems

### Tiltfile -> image (Happy Path)
1. `(Tiltfile)` is processed first, new Dockerfile contents are read in and it will clear the image build status as part of `ConfigsReloadedAction` reducer since the specs no longer match (as Dockerfile contents have changed)
2. `image:foo` is processed, sees that there is not prior build and executes, using the updated Dockerfile contents from its spec

### Image -> Tiltfile (Broken)
1. `image:foo` is processed, sees that `len(PendingFileChanges) != 0` (because `Dockerfile` is in there), but the re-executed build still has the old Dockerfile contents in its spec, so every layer is cached
2. _While the prior build is still occurring_, `(Tiltfile)` is processed, which clears out the image build status (see happy path) and sets `PendingManifestChange` to now
3. `image:foo` build finishes, storing the build status
4. Another `image:foo` build is kicked off due to `PendingManifestChange`, it sees that it has a prior build and no file changes, so it re-uses the (incorrect) cached result

## Solutions
* Ignore `Dockerfile` from the image target (I think we might want this regardless)
* Avoid adding build statuses for builds that started _before_ the pending manifest change

**Comment by milas** [comment]
@nicks @landism Can either of you think of any potential issues with ignoring the `Dockerfile` on the the `ImageTarget`? (See issue description for more context)

**Comment by nicks** [comment]
can we change the ChangesInvalidateBuild codepath so that it cancels any pending image build and discards the result? that seems like the simplest solution.

There might be cases where you'd want the Dockerfile in the image build, but I'm not 100% sure. But this seems like it would affect all types of DockerImageSpec changes, not just the Dockerfile

**Comment by milas** [comment]
Hmm, I don't think that'll work because the race condition means the image build has already started by the time the Tiltfile side of the house sees things, so there is no pending build.

As for preventing it from being included in the build context...technically, `DockerImage.Spec.ContextIgnores` are distinct from whatever is on the `FileWatch` object for the ImageTarget, so it could be included as an ignore pattern on the FW but NOT in the ContextIgnores. (That said, including the `Dockerfile` in your build is probably a bad idea when using Tilt because it won't _actually_ be the same as the `Dockerfile` being used for the build since the image reference injection and such is all done in memory)

**Comment by nicks** [comment]
Ah, I think you misunderstand - i mean cancel the image build in step (2).

Alternatively (or redundantly), we should probably change step (3) so that it checks if the DockerImageSpec is still the same when it finishes, and ignores the result if it isn't (this is basically what a reconciler would do)

**Comment by milas** [comment]
Gotcha - I don't see a (practical?) way to _cancel_ an arbitrary build using `EngineState` as part of `HandleConfigsReloaded` (the `ChangesInvalidateBuild` codepath), but maybe I'm missing something obvious here

I'm also not totally sure what ignoring the build result would look like impl-wise, and the UX here seems like it'd be extremely confusing as you'd get 2x image builds with the first being an erroneously cached version and then the "real" build.

WDYT about ignoring Dockerfile on the FW but not the Docker context?

**Comment by milas** [comment]
I made a draft PR that only adds it as a FW ignore but not context ignore: #5742

Happy to close it based on how this discussion shakes out - I mostly wanted to get CI to run the integration tests 🙃

**Comment by nicks** [comment]
ya, i think changing the image's filewatch to ignore the dockerfile seems like a good quick fix.
