### ISSUE TITLE
Tilt v0.26.0 does not work on windows

### ISSUE THREAD

**Issue by drano** [tilt-dev/tilt#5593]
With 0.26.0 version, tilt starts and stops immediately without error messages

**Comment by nicksieger** [comment]
Oh no! We added some new dependencies in 0.26 which are most likely the cause of this issue. If you could please use 0.25.3 for the time being until we get a new version released that we verify works on Windows. Thanks for the report!

**Comment by nicksieger** [comment]
I was able to tilt up on a basic k8s project on Windows 10 with 0.26.0 (our [tilt-avatars](/tilt-dev/tilt-avatars) project). Would you be able to provide more info about your setup? Are you able to run `tilt doctor` with 0.26.0? If not, can you run it with 0.25.3 and provide its output here, along with the Windows version you're using?

FYI, my `tilt doctor` output on my Windows 10 system looks like this:
```
Tilt: v0.26.0, built 2022-03-14
System: windows-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.11
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
---
Kubernetes
- Env: docker-for-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.22.4
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
```

**Comment by drano** [comment]
tilt doctor is not working with 0.26.0 but ok with previous version

Tilt: v0.25.3, built 2022-03-04
System: windows-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.11
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: containerd
- Version: v1.21.2
- Cluster Local Registry: {Host:localhost:50954 hostFromCluster: SingleName:}
---

**Comment by nicksieger** [comment]
Sounds like the issue is that we compiled with Mingw but didn't specify static binaries, so tilt.exe is looking for some msys2 .dll's like libgcc_s_seh-1.dll. We'll release a new 0.26.1 version of Tilt shortly.

**Comment by nicksieger** [comment]
This means that another workaround that you can try to fix the issue is to install [msys2](https://www.msys2.org/).

**Comment by drano** [comment]
Actually, I can use locally 0.25.3, and I ask to my team to not upgrade with the latest version (we are using scoop to update)

**Comment by nicksieger** [comment]
Please try 0.26.1 and let us know if you have any problems with it!
