### ISSUE TITLE
Live update - Option to make Sync respect dockerignore (or add ignore param)

### ISSUE THREAD

**Issue by dave-b-code** [tilt-dev/tilt#5651]
## Describe the Feature You Want
It would be very helpful if the docker_build live_update sync had an additional optional parameter of either: folders to ignore within the sync, or the ability to respect the ignore param of the docker_build, or respect the relevant dockerignore file.

### Current Behavior
Sync does not respect the ignore param on docker_build nor the relevant dockerignore (as expected).

### Why Do You Want This?
I have a folder with a significant number of subfolders, but there is only one subfolder I don't want to sync. Manually enumerating the individual subfolders with individual syncs is rather laborious and hard to maintain.

**Additional context**
Happy to help in any way I can, though I don't generally use Go so may not be of much use. Many thanks.

**Comment by nicks** [comment]
re: "Sync does not respect the ignore param on docker_build nor the relevant dockerignore (as expected)."

hmm...are you sure? I just tested it and the sync seemed to ignore things in the dockerignore.

Maybe there's a typo in your dockerignore file? Check out this guide:
https://docs.tilt.dev/file_changes.html#inspecting-file-watches-yourself
which shows how to interactively debug the ignores from the CLI. 

Under the hood, the docker_build() and the liveupdate sync() both share a FileWatch object that handles the .dockerignore, and you can inspect that object from the CLI.

**Comment by dave-b-code** [comment]
Hi, apologies I didn't update this sooner, got sidetracked by other work. To contextualise, imagine I have a folder with the following 3 files 
`C:/Src/SomeRandomFolder/SomeRandomFile.cs`
`C:/Src/SomeRandomFolder/SomeOtherRandomFile.cs`
`C:/Src/SomeRandomFolder/IgnoreThisFile.cs`

Please note that `C:/Src/SomeRandomFolder/IgnoreThisFile.cs` is also in my dockerignore and tiltignore.

 When I originally wrote this post, I had a live_update which had a sync looking like
` sync('C:/Src/SomeRandomFolder', '/app/Src/SomeRandomFolder')`
where I'd like to have ignored C:/Src/SomeRandomFolder/IgnoreThisFile.cs. As live_update updates the entire folder, this sync would cause the ignored file to be sync'd when either of the other files in the folder changed. Thus I changed the sync's to `
 sync('C:/Src/SomeRandomFolder/SomeRandomFile.cs', '/app/Src/SomeRandomFolder/SomeRandomFile.cs')`
 `sync('C:/Src/SomeRandomFolder/SomeRandomFile.cs', '/app/Src/SomeRandomFolder/SomeOtherRandomFile.cs')
`

 I took a look at the links in your previous comment for debugging and noticed in the filewatch yaml that folders were being included in the seenFiles list aswell as the files being updated. I'm on windows 11 fwiw, so would get: 
```
  fileEvents:
  - seenFiles:
    - C:/Src/SomeRandomFolder
    - C:/Src/SomeRandomFolder/SomeRandomFile.cs
    - C:/Src/SomeRandomFolder/SomeOtherRandomFile.cs
```

As I had not included `C:/Src/SomeRandomFolder` in my new sync list, it would force a restart every time any file was changed. Thus I believe the root of my problem in this new setup is the fact folders are showing up in the seenFiles list. This issue could also be solved by using the original ` sync('C:/Src/SomeRandomFolder', '/app/Src/SomeRandomFolder')` and not syncing files which should be dockerignored.

**Comment by nicks** [comment]
Re:
> As live_update updates the entire folder, this sync would cause the ignored file to be sync'd when either of the other files in the folder changed. 

This is definitely not true - live_update doesn't sync whole folders, it should only sync files that changed. If you have a repro case for this, would love to see it, because I haven't been able to repro it. but let me also add an integration test to confirm this.

**Comment by nicks** [comment]
OK, i added an integration test to demonstrate this is working as expected:
https://github.com/tilt-dev/tilt/pull/5721
it creates an example project similar to what you're describing, and confirms that files aren't synced.

what am i missing???

**Comment by dave-b-code** [comment]
I've had this problem on a large project with around 30 .net 6 containers, but am struggling to reproduce on an individual case that I can post here. I'll close this issue, as your integration tests cover this feature, and its entirely possible that the issue I'm seeing is a misconfiguration on my behalf (apologies if so). I'll open an issue again only when I can create a repo that reproduces properly, thanks.
