### ISSUE TITLE
Broken docker_restart in live_update for docker-compose resources in versions >= 0.26.3

### ISSUE THREAD

**Issue by Sorrowwill** [tilt-dev/tilt#5663]
### Expected Behavior
Tilt syncs changed files into a container, restarts it, and continue to watch files.

### Current Behavior
Tilt detects changed files sync them into a container and restarts it. But after that tilt starts to sync files and restarts a container in an infinite loop. This behavior is presented only in versions starting from 0.26.3. Everything works as expected on 0.26.2

![image](https://user-images.githubusercontent.com/20387095/162001679-e5453631-c4f4-49db-953a-19f58f5a6d7c.png)

### Steps to Reproduce
1. Install tilt 
2. Clone docker-compose example https://github.com/tilt-dev/tilt-example-docker-compose
3. tilt up
4. Change server.js

#### `tilt doctor` Output
```
$ tilt doctor
Tilt: v0.27.0, built 2022-04-01
System: linux-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.14
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
```

#### About Your Use Case
We are using Tilt with docker-compose resources and are forced to stick with Tilt 0.26.2

**Comment by hyu** [comment]
Hi @Sorrowwill, thanks for detailing this issue! I was able to repro this by first checking the docker-compose example with v0.25.0, and then with v0.27.0. And I did indeed see this behavior with the infinite loop that starts as soon as you `tilt up`. We'll look into this and see if we can get to the bottom of it.
