### ISSUE TITLE
freeze KUBECONTEXT for `k8s_custom_deploy`

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#5703]
## Describe the Feature You Want
Right now, when tilt shells out in `k8s_custom_deploy`, tilt doesn't do anything to ensure that the script you're invoking is talking to the same kubernetes context that tilt is talking to.

This means that if you change the default context outside of tilt, you could accidentally deploy to a prod cluster :scream: 

## Implementation Notes

We should change the cluster reconciler so that when it "resolves" the context, it:
1) Writes a new "frozen" kubeconfig, similar to `kubectl config view --minify` to a tempdir
2) Publish the path to the frozen kubeconfig on the cluster status field
3) When running `k8s_custom_deploy`, inject the KUBECONTEXT env variable to point to this new file.

**Comment by nicks** [comment]
i'll take a look at this since it came up again today.

**Comment by landism** [comment]
This problem could arise with `local` and `local_resource` as well, though that might be a bit dicier (e.g., I've written a Tiltfile that used `local` to run `kubectl` to copy secrets from one context to another, which could be annoying if Tilt forced the k8s config for all `local`s)

**Comment by landism** [comment]
> This problem could arise with local and local_resource as well
A good argument here is that we've had multiple reports of it with k8s_custom_deploy in the short time since it shipped and haven't heard of it with `local`/`local_resource` in the years they've been around.

**Comment by kalmant** [comment]
> > This problem could arise with local and local_resource as well
> > A good argument here is that we've had multiple reports of it with k8s_custom_deploy in the short time since it shipped and haven't heard of it with `local`/`local_resource` in the years they've been around.

Someone using Tilt v0.27.0 just ran into this issue through `helm_resource` which made me realize `local` and `local_resource` are probably also at risk.
So if possible, I'd like to cast a vote for a "fix" for `local`/`local_resource`. I'm sure I can put together some solution for us but a solution in `tilt` itself would be much better.
