### ISSUE TITLE
Confusing behavior with port forwards when no container port specified

### ISSUE THREAD

**Issue by milas** [tilt-dev/tilt#5728]
### Expected Behavior
* If a container has multiple exposed ports, and there's not an unambiguous mapping, warn or error

### Current Behavior
* Tilt picks one of the exposed ports (at random? first in list?)

### Steps to Reproduce
1. Add `k8s_yaml` for a resource that has multiple exposed ports
2. Add a `k8s_resource` call with `port_forwards=['9000']` (only a singular port)

### Context
My 2c about how to handle this:
* ~If there is exactly one exposed container port, map the local port to it regardless of if they match~
* ~If there are multiple exposed container ports and one of them matches the local port number, forward that one~
* ~If there are multiple exposed container ports and none of them match the local port number, emit a warning~
  * ~In a future version, this could become an error~
~(Note: in all these cases, the assumption is the user has passed a single port number, not a tuple)~

If no container port is specified, map to the same port number as the local port. For example, `port_forwards=8000` would mean `8000:8000` regardless of if `8000` (or any other ports) are exposed by the container spec.

#### About Your Use Case
This was raised in [Slack by Adam](https://kubernetes.slack.com/archives/CESBL84MV/p1650567370910339), who mentioned losing a few hours to debugging this when the wrong container port got picked.

**Comment by nicks** [comment]
ya, i think this was a mistake early on that simply never got fixed. we should change it to match the `kubectl port-forward` behavior (though this would be a breaking change)
