### ISSUE TITLE
"tilt up" from hello-world leads to "libva error"

### ISSUE THREAD

**Issue by yogeek** [tilt-dev/tilt#5732]
### Expected Behavior
the Hello world tutorial has no error

### Current Behavior
Following the instructions here : 
- `tilt up`
- "Create a starter Tiltfile ?" => no
- "space" to open browser => error : 
```
$ tilt up
Starting Tilt...

Tilt started on http://localhost:10350/
v0.27.3, built 2022-04-22

(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
Opening browser: http://localhost:10350/
Opening in existing browser session.
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[42333:42333:0100/000000.072374:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
```

#### `tilt doctor` Output

```
$ tilt doctor

Tilt: v0.27.3, built 2022-04-22
System: linux-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.14
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
---
Kubernetes
- Env: kind
- Context: kind-kind
- Cluster Name: kind-kind
- Namespace: default
- Container Runtime: containerd
- Version: v1.23.4
- Cluster Local Registry: none
```

#### About Your Use Case

Just trying to evaluate Tilt

**Comment by nicks** [comment]
:scream: 

Sorry to hear about that @yogeek .

Can you run

```
xdg-open https://github.com/
```

from the command-line? What happens?

That message usually means you have your default browser badly misconfigured on linux. You can also open the tilt web ui directly at http://localhost:10350/

**Comment by yogeek** [comment]
@nicks thanks for your help.

`xdg-open https://github.com` opens chrome on github page, but in the terminal, it outputs the same error message 
```
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[61003:61003:0100/000000.359207:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
```

the problem, is that, with tilt, the browser also opens automatically event with the error message, but the page http://localhost:10350 displays `This site can’t be reached` error message

**Comment by yogeek** [comment]
@nicks yes I was already using the brower inside the VM, so my localhost is the localhost of the VM

But the `--host 0.0.0.0` solved the problem indeed : now it is working correctly ! 
Thank you for your help ! 

FYI, I checked to try to understand the difference between both command, and it seems to be the URL exposed by tilt by default :

tilt up => expose "localhost"
```
tilt up               
Tilt started on http://localhost:10350/
```

tilt up --host 0.0.0.0 => expose 127.0.0.1
```
tilt up --host 0.0.0.0
Tilt started on http://127.0.0.1:10350/ (listening on 0.0.0.0)
```

**Comment by nicks** [comment]
yay! ya, VM networking is odd. closing...
