### ISSUE TITLE
Support docker compose --project-name option

### ISSUE THREAD

**Issue by studious** [tilt-dev/tilt#5770]
## Describe the Feature You Want
I would like a way for the `-p | --project-name` flag to be passed to the underlying call to `docker compose -p my_proj`

### Current Behavior
I can only find a hard coded internal setting for project name `Name`
https://github.com/tilt-dev/tilt/blob/master/internal/tiltfile/docker_compose.go#L70-L75
```
	project := v1alpha1.DockerComposeProject{
		ConfigPaths: dc.configPaths,
		ProjectPath: dc.Project.ProjectPath,
		Name:        model.NormalizeName(filepath.Base(filepath.Dir(currentTiltfilePath))),
		EnvFile:     envFile.Value,
	}
```

### Why Do You Want This?
We have been heavy users of docker compose and had our own script which would combine our various config files and importantly set the `-p` or `--project-name` flag for the `docker compose` commands.

I have a lot of persisted volumes and built containers using the "project name" but now usingTilt I get everything scoped to our creatively named root folder `monorepo`.

I have spent days digging around looking for a way to squeeze in a project arg or `COMPOSE_PROJECT_NAME` env var and even trying to use `tilt patch dockercomposeservice ...` to no avail. It looks completely internal.

...unless I'm wrong and just can't see how to squeeze that in somehow.

Thanks

**Comment by landism** [comment]
Thanks for filing! This should be in tomorrow's release.
