### ISSUE TITLE
"already registered" when loading same extension from two different Tiltfiles

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#5785]
### Steps to Reproduce
run this: https://github.com/chiefy/tilt-playground

OR

Create two Tiltfiles that load the same extension via v1alpha1.extension_repo / extension
Include both of those Tiltfiles in a third Tiltfile
`tilt up` on that third Tiltfile

### Expected Behavior
Both included Tiltfiles are able to load the extension

### Current Behavior
```
ERROR: Traceback (most recent call last):
  /private/tmp/tilt-playground/Tiltfile:6:8: in <toplevel>
  <builtin>: in include
  /private/tmp/tilt-playground/b/Tiltfile:2:19: in <toplevel>
Error in v1alpha1.extension: extensions "hello" already registered
```

### Notes
v0.28.1-dev, built 2022-05-06

This error occurs [here](https://github.com/tilt-dev/tilt/blob/6fd46e9cf0923940387fb090dbd24707c92ccc27/internal/tiltfile/v1alpha1/plugin.go#L50-L52) when two different api objects are created with the same name. It's surprising that this is erroring, since both Tiltfile calls have the same args.

I logged the existing and new object when this error occurred and got:
```
existing:
(*v1alpha1.Extension)(0x14001760480)(&Extension{ObjectMeta:{hello      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[tilt.dev/managed-by:tiltfile.loader] [] []  []},Spec:ExtensionSpec{RepoName:custom,RepoPath:hello-world,Args:[],},Status:ExtensionStatus{Error:,Path:,},})

new:
(*v1alpha1.Extension)(0x14001326c00)(&Extension{ObjectMeta:{hello      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:ExtensionSpec{RepoName:custom,RepoPath:hello-world,Args:[],},Status:ExtensionStatus{Error:,Path:,},})
```

The difference is the `tilt.dev/managed-by` annotation, which gets [added by Tilt](https://github.com/tilt-dev/tilt/blob/b391f7cb5ea9ce1c2c19243c7b01dc35336bbbaf/internal/tiltfile/tiltextension/plugin.go#L130), not the user.

**Comment by landism** [comment]
We should fix this, but here's a workaround that'd work in https://github.com/chiefy/tilt-playground:

Make a Tiltfile.hello that contains
```
v1alpha1.extension_repo(name='custom', url='https://github.com/chiefy/tilt-extensions', ref='main')
v1alpha1.extension(name='hello', repo_name='custom', repo_path='hello-world')
```

In both a/Tiltfile and b/Tiltfile, replace those two lines with: `load_dynamic('../Tiltfile.hello')`

**Comment by chiefy** [comment]
also if you add the above to the parent Tiltfile it appears to work?
