### ISSUE TITLE
Change in yaml_decode behavior

### ISSUE THREAD

**Issue by kalmant** [tilt-dev/tilt#5793]
### Expected Behavior
In version 0.28.1, calling `print(yaml_decode("port: 5000"))` would return (when printed) `{"port": 5000}`.

### Current Behavior
Now (0.29.0) the same expression returns `{"port": 5000.0}`

### Steps to Reproduce
Simple Tiltfile with one line:
```starlark
print(decode_yaml("port: 5000"))
```
#### `tilt doctor` Output
I can provide these if necessary but I don't think Docker/Kubernetes version/parameters are relevant in this case.
The versions
```
Tilt: v0.28.1, built 2022-05-01
System: darwin-amd64
```
vs. 
```
Tilt: v0.29.0, built 2022-05-06
System: darwin-amd64
```

#### About Your Use Case
I have a yaml file with some configuration (such as ports in this case) that gets parsed and the values eventually are used for `helm` calls' `set` values. So what used to be `--set something.port=5000` would now be `--set something.port=5000.0`.

I can sidestep the "issue" by wrapping such numbers in that file by `"`s.

Since both [YAML](https://symfony.com/doc/current/components/yaml/yaml_format.html#numbers) and [Starlark](https://github.com/bazelbuild/starlark/blob/master/spec.md#integers) have integer concepts one could hope to get back an integer after parsing one but I know parsing is tricky 🙂 .

Could be related to the recent Starlark vendor upgrade but I'm sure you guys will know what has changed.

**Comment by nicksieger** [comment]
Thanks for reporting this! Yeah, my first guess too would be #5755. I'll dig in to see what specifically triggered the change and whether it's something we can fix.

**Comment by nicksieger** [comment]
The new version of starlark-go we upgraded to has [`AllowFloat` set to true by default](https://github.com/google/starlark-go/compare/61b64bc45990..d1966c6b9fcd#diff-6d1c1f9af64023d21a121b9620244a0ece4af724ac780deec2b05fa470350208R109).

Also noting for posterity that the same behavior happens with `decode_json`. Continuing to investigate on the Tilt side how we handle decoding YAML and JSON before handing over to Starlark.

**Comment by nicksieger** [comment]
The rest of the story is that [Go unmarshals all JSON numbers into floats](https://pkg.go.dev/encoding/json@go1.18.2#Unmarshal) whether or not they had a decimal point in the source JSON. And since Starlark now handles floats, they stay floats on the Starlark side rather than getting coerced to an integer in the previous version of starlark-go.

**Comment by nicks** [comment]
Feels like there are a few separate issues here:
- Whether we really want tiltfiles to support floats
- Whether our json/yaml decoders should deserialize to floats
- Whether `str(float(5000))` should really serialize to `5000.0`

I feel like most modern languages (Go, JS) will represent `str(float(5000))` as `5000`, and a lot of the issues here are that Starlark has a different opinion, which messes up the interop

**Comment by nicksieger** [comment]
Floats are enabled by default and can't be disabled in the latest starlark-go. With that in mind, I made an attempt at decoding ints and floats in #5806. Thoughts appreciated.
