### ISSUE TITLE
Tilt fails to detect Docker Desktop for Linux and attempts to push images

### ISSUE THREAD

**Issue by joel0** [tilt-dev/tilt#5812]
### Expected Behavior
Tilt should realize I'm using a local Docker Desktop skip pushing the image. Such as
```
Skipping push: building on cluster's container runtime
```

### Current Behavior
Tilt attempts to push my image to docker.io and fails.
```
STEP 2/3 — Pushing pigeon:tilt-f7346993891b395b
     Pushing with Docker client
     Authenticating to image repo: docker.io
     Sending image data

Build Failed: docker push: pushing image "docker.io/library/pigeon": denied: requested access to the resource is denied
```

### Steps to Reproduce
While I can't provide steps to an exact repro, it starts off with.
1. Install [Docker Desktop for Linux](https://docs.docker.com/desktop/linux/install/) on Debian 11.
2. For good measure, stop Docker engine.
    ```
    sudo systemctl stop docker docker.socket containerd
    ```
3. Open Docker Desktop from the desktop environment and in the settings enable Kubernetes.
4. `kubectl config use-context docker-desktop`
5. `tilt up ...`.  The project I'm doing this on ends up failing 2 resources by attempting to push images.

### Context

This looks very similar to  #5034 on Windows, but I suspect the root cause could be different.  Having `DOCKER_HOST` unset does _not_ work around the problem for me, like the other issue mentions.

I do not encounter this problem when using Minikube instead of Docker Desktop for Linux.

#### `tilt doctor` Output
```
$ tilt doctor
Tilt: v0.29.0, built 2022-05-06
System: linux-amd64
---
Docker
- Host: unix:///home/jmay/.docker/desktop/docker.sock
- Server Version: 20.10.14
- API Version: 1.41
- Builder: 2
---
Kubernetes
- Env: docker-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.24.0
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: cf920a31c2760bcfd0af8a1d35fb070f
- Repo: GMRpQPMQ7lumf8n4GPEFgg==
```

**Comment by nicks** [comment]
thanks for the report! ya, i think docker desktop linux changed where the docker socket lives... :thinking:

**Comment by joel0** [comment]
Yeah, apparently Docker Desktop runs in a VM completely separate from Docker Engine.  https://docs.docker.com/desktop/linux/install/#differences-between-docker-desktop-for-linux-and-docker-engine

**Comment by nicksieger** [comment]
I was looking at this today. I think Desktop uses a socket located in ~/.docker/desktop/docker.sock (I think?). If you find some .sock file in that directory and set DOCKER_HOST to unix://home/user/.docker/desktop/docker.sock does that work for a workaround?

**Comment by joel0** [comment]
> I think Desktop uses a socket located in ~/.docker/desktop/docker.sock (I think?).

Yes, the output of `tilt doctor` above agrees with that.

> DOCKER_HOST to unix://home/user/.docker/desktop/docker.sock does that work for a workaround?

Nope.  It still tries to fruitlessly push the image.  Without having looked too deeply into the code, it looks like the list of known "local" servers will never recognize that Unix socket in `~`.  https://github.com/tilt-dev/tilt/blob/bc91f220fe235c9e421577b714e6fd76c7cbf780/vendor/github.com/docker/cli/opts/hosts.go#L18-L32

A janky workaround that does work is to symlink the expected path to the real path.  Everything works flawlessly after doing that, so I confirm the file path is my only blocker.
```bash
sudo systemctl stop docker.service docker.socket containerd
sudo mv /var/run/docker.sock{,.bak}
sudo ln -s $HOME/.docker/desktop/docker.sock /var/run/docker.sock
export DOCKER_HOST=unix:///var/run/docker.sock
tilt up
```
