### ISSUE TITLE
UI winds up off center

### ISSUE THREAD

**Issue by jvilhuber** [tilt-dev/tilt#5818]
### Expected Behavior
Sometimes (especially with my current tests!) the UI winds up pushed off to the side. Sometime all the way (no resources to be seen at all) and sometimes only partly (see attached screenshot). Obviously expected behavior is to NOT do that ;-)

### Current Behavior
The sidebar is pushed off the screen on the left, and I see no way to get back to it!

I'm not sure what causes that. I initially though some long output line from the pod would do this, but... other times I see long lines properly wrapped (sometimes I don't).

Maybe it could be this?

```
k8s_resource('otel-collector-lb',
    port_forwards=["55679:55679", "8888:8888", "1777:1777", "4317:4317", "14268:14268", "13133:13133"],
    links=[
      "http://localhost:55679/debug/servicez", "http://localhost:55679/debug/tracez", "http://localhost:55679/debug/pipelinez",
      "http://localhost:8888/metrics", "http://localhost:1777/debug/pprof", "http://localhost:14268/", "http://localhost:13133/"])
```
![Screen Shot 2022-05-16 at 16 13 56](https://user-images.githubusercontent.com/794821/168560087-d3c4219a-6ceb-4e27-b557-c318b5602f2e.png)

### Steps to Reproduce
Not sure I have a good and easy reproduction.

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.29.0, built 2022-05-06
System: darwin-arm64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 20.10.14
- API Version: 1.41
- Builder: 2
- Compose Version: v2.2.3
---
Kubernetes
- Env: rancher-desktop
- Context: rancher-desktop
- Cluster Name: rancher-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.21.12+k3s1
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 691e658399c15d72aff8ae7fa49ec4eb
- Repo: dRB8kBFBfP1t+9tttABY5Q==
```

#### About Your Use Case

Well I can't navigate around the UI with the side-bar missing.

**Comment by lizzthabet** [comment]
yikes! thanks for reporting, @jvilhuber. i'm able to reproduce this locally on firefox by viewing a resource with a longer list of links.

**Comment by lizzthabet** [comment]
the fix for this will go out in this week's release.

**Comment by jvilhuber** [comment]
Awesome!

**Comment by jvilhuber** [comment]
@lizzthabet I also noticed that there's a comma missing between the explicitly configured links and the links from the forwarded ports. I might also recommend splitting the lines so that the explicit links are on one line, and port-forwards (Is there a way to exclude those?) on another line.

**Comment by lizzthabet** [comment]
hm, i haven't been able to reproduce the missing comma issue you've described, and i see commas between every element in the screenshot you shared. is there something i'm missing here?

we do have #5485 open, if you'd like to 👍🏻 the issue! you can also [add names to links and port forwards](https://docs.tilt.dev/accessing_resource_endpoints.html) to help better organize them in the ui.

**Comment by jvilhuber** [comment]
> hm, i haven't been able to reproduce the missing comma issue you've described, and i see commas between every element in the screenshot you shared. is there something i'm missing here?
> 

I think the trick is to launch tilt, open the UI (everything looks good at that point), then edit the k8s_resources links (or ports?) removing some. tilt will reload the Tiltfile and update the UI with the removed links, and (at least in my tests) there's now commas missing. If you still can't reproduce, I'll give it another try, documenting a little more rigorously.
