### ISSUE TITLE
cmd_button should allow to set env variables

### ISSUE THREAD

**Issue by fabriziopandini** [tilt-dev/tilt#5910]
## Describe the Feature You Want
I would like to pass env variables to cmd_button, as I can do with local_resource

### Current Behavior
cmd_button doesn't have an env argument

### Why Do You Want This?
To pass env variables to the command defined in cmd_button without messing up os env variables

**Comment by nicks** [comment]
thanks for the request! shouldn't be too hard to add. the api exists on Cmd, just needs to get passed through the extension code that creates the Cmd:
https://github.com/tilt-dev/tilt-extensions/blob/master/uibutton/Tiltfile#L107
https://api.tilt.dev/core/cmd-v1alpha1.html

**Comment by g3kk0** [comment]
I would also like to very much see this feature.

**Comment by tylermichael** [comment]
I think this can be closed

**Comment by fabriziopandini** [comment]
Thanks team! Looking forward to use this!
