### ISSUE TITLE
What happens to synced files when pod crashes

### ISSUE THREAD

**Issue by padzikm** [tilt-dev/tilt#5911]
Hi, I'm investigating Tilt and wondering about scenario:
- tilt is setup with file sync (let's say nodejs project with nodemon for process restarting)
- container image is deployed to k8s
- pod is running
- changed file is synced to running container
- pod is crashed
- pod is redeployed by k8s automatically

My question is will redeployed pod contain synced file, or I should handle this scenario somehow?

**Comment by nicks** [comment]
Tilt uses a reconciliation loop, similar to Kubernetes https://kubernetes.io/docs/concepts/architecture/controller/

One side will keep track of all the files that need to be synced.

The other side will watch the pods that you deployed.

Tilt will continuously try to sync the files, even after the pod crashes.

Tilt makes a best-effort attempt to try to distinguish if the pod is in a temporary failure state or in a permanent failure state. If it thinks it's a temporary failure, tilt will wait for the pod to come back and resync. If it's in a permanent failure state,Tilt will build a new image and redeploy.

You can query the live update state at any time with `tilt get liveupdate -o yaml`, see the API docs https://api.tilt.dev/

**Comment by padzikm** [comment]
Thanks for explanation :)

**Comment by liskin** [comment]
What @nicks described above seems to only work with `trigger_mode = TRIGGER_MODE_AUTO`.

With `TRIGGER_MODE_MANUAL`, when a container restarts, files aren't synced back into the container, and the Tilt UI doesn't let you trigger the sync—only lets you trigger a "Force update" which rebuilds the container. This seems like a bug to me, shall I open a new issue?
