### ISSUE TITLE
Allow to specify timeout to trigger file watcher

### ISSUE THREAD

**Issue by antonyc** [tilt-dev/tilt#5921]
Hi! A small timeout to trigger filewatch would be great. Cause when one uses rsync by default it creates a temp file in same dir, and even if it can be overridden with -T option, this is not super convenient. So, debouncing triggers on tilt side could be an improvement.

**Comment by nicks** [comment]
thanks for the request! I'm going to mark this as a duplicate of https://github.com/tilt-dev/tilt/issues/3606
