### ISSUE TITLE
Feature: Add a directive to build Earthly Image Targets

### ISSUE THREAD

**Issue by vyas-n** [tilt-dev/tilt#5930]
## Describe the Feature You Want
Earthly (https://earthly.dev/) & Earthfile is a program & file spec  that can be used to build Docker images with very similar syntax to that of a Dockerfile.

I'd like to be able to use Tiltfile to build & load a docker image from an Earthfile like how the current `docker_build` function can build & load a docker image from a Dockerfile https://docs.tilt.dev/api.html#api.docker_build.

Perhaps by using a new function like `earthly_build`?

### Current Behavior

I don't think this functionality exists in Tiltfile. Maybe using the [cmd](https://docs.tilt.dev/api.html#api.v1alpha1.cmd) function, but it's not an elegant solution for this.

### Why Do You Want This?

I'm currently using [Earthly](https://earthly.dev/) to centralize CI & build system functionality.

I'd like to integrate Tilt into it so that local dev environments can be centralized as well.

**Comment by nicksieger** [comment]
Hi, did you see our [Earthly extension](https://github.com/tilt-dev/tilt-extensions/tree/master/earthly)? Please file an issue in the extensions repository if you spot any missing functionality. Thanks!
