### ISSUE TITLE
Tilt fails to load extensions: keyword argument may not follow *args" 

### ISSUE THREAD

**Issue by szaher** [tilt-dev/tilt#5947]
### Expected Behavior
tilt fails to load extensions with error message " keyword argument may not follow *args" 
tilt user should be able to pass argument non-keyword arguments without before keyword arguments like python!
The error happens in coreos_prometheus extension or any other tilt extension loaded from https://github.com/tilt-dev/tilt-extensions

### Current Behavior
v0.30.8, built 2022-09-19
Serving embedded Tilt production web assets

Initial Build
Loading Tiltfile at: /Users/szaher-laptop/go/src/github.com/XXX-XXX/REPO-NAME/Tiltfile
local: pwd
Problem processing change. Subscriber: engine/uiresource.Subscriber. Backing off 1s. Error: Operation cannot be fulfilled on uiresources.tilt.dev "(Tiltfile)": the object has been modified; please apply your changes to the latest version and try again
ERROR: Traceback (most recent call last):
  /Users/szaher-laptop/go/src/github.com/XXX-XXX/REPO-NAME/Tiltfile:13:1: in <toplevel>
  /Users/szaher-laptop/go/src/github.com/XXX-XXX/REPO-NAME/test/tilt/Tiltfile:10:1: in <toplevel>
Error: cannot load ext://coreos_prometheus: /Users/szaher-laptop/go/src/github.com/XXX-XXX/REPO-NAME/tilt_modules/coreos_prometheus/Tiltfile:147:29: keyword argument may not follow *args

#### using public extension repo

v0.30.8, built 2022-09-19
Serving embedded Tilt production web assets

Initial Build
Problem processing change. Subscriber: engine/uiresource.Subscriber. Backing off 1s. Error: Operation cannot be fulfilled on uiresources.tilt.dev "(Tiltfile)": the object has been modified; please apply your changes to the latest version and try again
Loading Tiltfile at: /Users/szaher-laptop/go/src/github.com/XXX-XXX/REPO-NAME/Tiltfile
Problem processing change. Subscriber: engine/uiresource.Subscriber. Backing off 1s. Error: Operation cannot be fulfilled on uiresources.tilt.dev "(Tiltfile)": the object has been modified; please apply your changes to the latest version and try again
ERROR: Traceback (most recent call last):
  /Users/szaher-laptop/go/src/github.com/XXX-XXX/REPO-NAME/Tiltfile:13:1: in <toplevel>
  /Users/szaher-laptop/go/src/github.com/XXX-XXX/REPO-NAME/test/tilt/Tiltfile:10:1: in <toplevel>
Error: cannot load ext://coreos_prometheus: /Users/szaher-laptop/Library/Application Support/tilt-dev/tilt_modules/github.com/tilt-dev/tilt-extensions/coreos_prometheus/Tiltfile:147:29: keyword argument may not follow *args

### Steps to Reproduce

1. load('ext://coreos_prometheus')
2. setup_monitoring()
3.
4.

#### `tilt doctor` Output

```
$ tilt doctor
...
```

Tilt: v0.30.8, built 2022-09-19
System: darwin-arm64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 20.10.17
- API Version: 1.41
- Builder: 2
- Compose Version: v2.10.2
---
Kubernetes
- Env: k3d
- Context: k3d-ci-XXX-XXX-k3s
- Cluster Name: k3d-ci-XXX-XXX-k3s
- Namespace: default
- Container Runtime: containerd
- Version: v1.22.12+k3s1
- Cluster Local Registry: &RegistryHosting{Host:localhost:64098,HostFromClusterNetwork:k3d-default-registry:5000,HostFromContainerRuntime:k3d-default-registry:5000,Help:https://k3d.io/usage/guides/registries/#using-a-local-registry,SingleName:,}
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: 8918c6737a97d5b131abfebc5f83b7f1
- Repo: ob5sKsA4aVopw0TIbAaSrg==

**Comment by nicks** [comment]
thanks for the report! the next time you tilt up, it should pull a newer version of the extension that fixes the issue.
