### ISSUE TITLE
How do I get error logs from my application to show in the error tab? 

### ISSUE THREAD

**Issue by benlei** [tilt-dev/tilt#5951]
I don't see a lot of information explaining now to get logs to show in the error/warning tab of the tilt web ui.

I tried echo-ing to stderr in my entry point script of my container but that didn't show up in either tabs either.

**Comment by nicks** [comment]
Viewing logs for your app is usually very self explanatory. Maybe I'm misunderstanding the question? Were you able to run the example projects ok? Eg https://docs.tilt.dev/example_static_html.html

**Comment by stevecooperorg** [comment]
If OP is having the same issue as me, it's understanding how to supply a filter to the logs to indicate that it's an error or a warning. For example, I've got JSON logs where lines like

```
{ logLevel: "ERROR", ...}
{ logLevel: "WARN", ...}
```

do not show up when you click the 'Errors (0)' or 'Warnings (0)' buttons.

**Comment by benlei** [comment]
> If OP is having the same issue as me, it's understanding how to supply a filter to the logs to indicate that it's an error or a warning. For example, I've got JSON logs where lines like
> 
> ```
> { logLevel: "ERROR", ...}
> { logLevel: "WARN", ...}
> ```
> 
> do not show up when you click the 'Errors (0)' or 'Warnings (0)' buttons.

Yes exactly this.

**Comment by nicks** [comment]
ah, thank you, i misunderstood! I'm going to mark this as a duplicate of https://github.com/tilt-dev/tilt/issues/4762 to centralize discussion.
