### ISSUE TITLE
Ability to merge multiple logs in the UI

### ISSUE THREAD

**Issue by dfeyer** [tilt-dev/tilt#5955]
First, thanks for this awesome tool. I have a feature request, when I have a few starred resources, it can be useful to select more than one (double clic, shift clic, or just toggle clic), to be able to have a merged log stream from the selected resources. 

In micro service architures it's nice to be able to watch stream accros a selected resources group, but most of the time "All resources" are too chatty.

**Comment by gamerson** [comment]
I've tried myself to do this (select multiple resources in UI and was hoping for the logs to be multiplexed).  Would be pretty useful it seems.

**Comment by eliyabar** [comment]
I'm using the CLI to get this exact functionality using `tilt logs service_a service_b -f`.
It would be awesome to get this from the UI.
