### ISSUE TITLE
Kustomize does not work with helm charts

### ISSUE THREAD

**Issue by Blinkuu** [tilt-dev/tilt#5956]
### Expected Behavior
When specifying helm charts in `kustomization.yaml`, I expect Tilt to apply those, similarly to applying simple resources. Perhaps Tilt should call customize with `--enable-helm` option enabled by default.

### Current Behavior

Error (anonymized directories):
```
Error in kustomize: command "kubectl kustomize operations/kubernetes/development/tilt" failed.
error: exit status 1
stdout: ""
stderr: "error: accumulating resources: accumulation err='accumulating resources from 'fancy-project': '/Users/Dev/fancy-project/operations/kubernetes/development/tilt/fancy-project' must resolve to a file': recursed accumulation of path '/Users/Dev/fancy-project/operations/kubernetes/development/tilt/fancy-project': accumulating resources: accumulation err='accumulating resources from '../../../base/timescaledb': '/Users/Dev/fancy-project/operations/kubernetes/base/timescaledb' must resolve to a file': recursed accumulation of path '/Users/Dev/fancy-project/operations/kubernetes/base/timescaledb': trouble configuring builtin HelmChartInflationGenerator with config: `\nname: charts/timescaledb-single\nreleaseName: timescaledb\nrepo: [https://charts.timescale.com\n`:](https://charts.timescale.com/n%60:) must specify --enable-helm\n"
```

### Steps to Reproduce

1. Setup `kustomization.yaml` that references a helm chart using `helmCharts` field.
2. Run `tilt up`

**Comment by nicks** [comment]
Thanks for reporting!

You can workaround this now by using a `local()`

```
local('kustomize build --enable-helm')
```

I'm not convinced that `kustomze()` should be a built-in anymore...we wrote it before we had a real extensions system, and increasingly feels like it should be an extension. But maybe there's a kustomize(flags=...) hack we can add in the meantime.

related issue: https://github.com/tilt-dev/tilt/issues/5007

**Comment by nicks** [comment]
we just released a new version of tilt that allows you to add flags to `kustomize()`, see: https://docs.tilt.dev/api.html#api.kustomize

**Comment by Blinkuu** [comment]
Sweet, thanks @nicks!
