### ISSUE TITLE
Broken on Docker Desktop 4.13.0

### ISSUE THREAD

**Issue by Meemaw** [tilt-dev/tilt#5963]
### Expected Behavior
Tilt works correctly on Docker Desktop 4.13.0

### Current Behavior
It seems tilt fails to recognise local k8s context (Docker Dekstop), and tries to push images to a remote cluster.

I have a feeling this was already fixed in https://github.com/tilt-dev/tilt/commit/a1be613b02109e4db7c667796067b3ed72b8dcb4, and just has to be released?

If so, could we release that, as we have a lot of engineers hitting this issue.

**Comment by nicks** [comment]
Thanks for reporting! We just did a release that should fix this.

**Comment by milas** [comment]
For anyone else that hits this, you can also upgrade to Docker Desktop v4.13.1 (or newer)
