### ISSUE TITLE
Make it possible to run tilt up offline

### ISSUE THREAD

**Issue by roma-glushko** [tilt-dev/tilt#5970]
## Describe the Feature You Want
Currently it doesn't seem to be possible to run tilt up offline if you have extensions used in your Tiltfile, e.g.

```
load('ext://dotenv', 'dotenv')

dotenv()
```

### Current Behavior
Tilt constantly tries to pull github repo with extensions on `tilt up` command. There is no way (afaik) to cache that requests to be able to run tilt locally offline.

### Why Do You Want This?
- To make it possible to work under bad internet/connection circumstances (when you are in a long flight, outside of the good connection)
- Local cluster is kind of imply that it would may be run locally e.g. without external dependencies. 

**Additional context**
N/A

**Comment by nicks** [comment]
thanks for the report! i think this is just a bug, the repo fetcher is supposed to cache things in the global xdg-base cache.
