### ISSUE TITLE
match_in_env_vars doesn't get env vars updated on updates

### ISSUE THREAD

**Issue by roma-glushko** [tilt-dev/tilt#5978]
### Expected Behavior
Environment variables that contain image names registered in Tilt (with `match_in_env_vars=True`) doesn't get updated when those images are rebuilt on changes.

### Current Behavior
The env variable with image reference gets updated once during initially during executing `tilt up`. Then if I update the image afterwards, the initial value is kept using.

### Steps to Reproduce

1. Define a new docker_build in Tilt file with `live_updates` and `match_in_env_vars`
2. Define a k8s deployment that is using that image and that has a env var with that image name
3. Deployment should take the value of the env var and create a new deployment dynamically using k8s API/client where that value corresponds to deployment container 
4. Run `tilt up` 
5. Try to trigger a dynamic deployment creation. Notice the final image name/reference
6. Update the source code of the service to reload/update the image
7. Try to trigger a dynamic deployment creation. Notice the final image name/reference. Should be the same as in step 5 which is the issue

#### `tilt doctor` Output
```
❯ tilt doctor
Tilt: v0.30.3, built 2022-06-10
System: darwin-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 20.10.13
- API Version: 1.41
- Builder: 2
- Compose Version: v2.3.3
---
Kubernetes
- Env: k3d
- Context: k3d-nbx
- Cluster Name: k3d-nbx
- Namespace: default
- Container Runtime: containerd
- Version: v1.23.6+k3s1
- Cluster Local Registry: &RegistryHosting{Host:localhost:8300,HostFromClusterNetwork:nbx-registry:5000,HostFromContainerRuntime:nbx-registry:5000,Help:https://k3d.io/usage/guides/registries/#using-a-local-registry,SingleName:,}
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 6f606651adb8e83a4215b4efc55404e3
- Repo: DcR4T0okRlzh2nXUP7EFXw==
...
```

#### About Your Use Case

I'm trying to develop a component that is being created dynamically. So if I change its source code, I would like to get that component reloaded somehow. I'm okay if the env vars get updated and the next time I run the component it contains a new version of the code.

**Comment by roma-glushko** [comment]
Let me know if you need some sample codes for reproducing.

**Comment by nicks** [comment]
I wasn't able to reproduce this. here's the repro case I tried: https://github.com/tilt-dev/tilt-example-html/commit/b29d15d5e80c5dea270d31891bea8b49585b942d

**Comment by roma-glushko** [comment]
@nicks Thank you for checking! Let me create some minimalistic repo to show what I mean. 
Maybe there are some other details that are important and worth mentioning which I don't yet realize.

**Comment by roma-glushko** [comment]
@nicks coming back to you, Nick!

I have created the following project: https://github.com/roma-glushko/tilt-issues/tree/main/5978 to show you what I'm experiencing.

While working on it, I came to the conclusion that most likely it's not a `match_in_env_vars ` fault really, but rather something goes wrong with the way Tilt does live reloads.

The project I have shared consists of two components:

- The Scheduler. It exposes API to create/delete workers. It pays attention to env vars where we pass WORKER_IMAGE that should be used during worker deployment creation. In the Tilt context, that image should be controlled and autoreloads by Tilt. The scheduler is a static component. It exists at the time Tilt deploy the project and its deployment explicitly being fed into Tilt.
- The Worker. This is a dynamically create component, hence, it doesn't exist at the moment Tilt does the project deployment.

Both scheduler and worker share the same image. Other than that, to reduce reload latency, I have configured Tilt live reloads for the image and I think this is where the problem comes.

Before enabling the live reloads, the reload behaves this way:

- On any change that is related to the image, Tilt is building a new version of the image and update the scheduler component along with the `WORKER_IMAGE` env variable.
- If there was any worker that had created before the change, their source code remained unchanged until I recreated them.
- Once I recreated the worker after Tilt had updated the image and the scheduler, the change got into the worker deployment.

Now when I enabled the live reloads, I was able to reproduce the issue I was originally talking about. Tilt stopped updating the image version, now it does some "patch updates" to the image/deployment. However, it does them to the scheduler only, leaving the worker image effectively outdated. That's the problem.

This is how I exactly reproduce that:

- Run `make cluster-start` (make sure you have k3d installed)
- Run `tilt up` to deploy the environment. Wait until the scheduler pod is ready
<img width="1775" alt="Screen Shot 2022-12-04 at 14 20 44" src="https://user-images.githubusercontent.com/9402690/205491279-a88a340e-1a8d-4146-b7ed-64df1c894eb3.png">

- Run `curl --location --request POST 'localhost:8801/worker/5478/'` to create a new worker deployment
- Edit any of `service/worker/*` files. I was adding a dummy comment to `services/worker/config.py`
<img width="833" alt="Screen Shot 2022-12-04 at 14 20 30" src="https://user-images.githubusercontent.com/9402690/205491310-b3cebb5c-2d6a-49a4-ab13-02a0b13c8668.png">

- Inspect the content of scheduler's copy of the file you have edited (via k9s, for example). The edition should be applied immediately.
<img width="603" alt="Screen Shot 2022-12-04 at 14 48 55" src="https://user-images.githubusercontent.com/9402690/205491404-02bf8e78-62ca-40f2-98af-18a2c497eb60.png">

- Now do the same with the worker pod. You will see that the change was not applied there. This is how you can miss an update

<img width="592" alt="Screen Shot 2022-12-04 at 14 48 33" src="https://user-images.githubusercontent.com/9402690/205491411-4fe06aeb-d683-408a-93e5-128a5c975442.png">

The worker deployment won't help you as well. You can do it via:
- `curl --location --request DELETE 'localhost:8801/worker/5478/'`
- `curl --location --request POST 'localhost:8801/worker/5478/'`

Now, I'm curious:
- how to make the update to worker deployment more automatic?
- how to enable Tilt to show these sort of dynamically created components in the UI to read its logs in a convenient manner?

**Comment by nicks** [comment]
ya, i think you need to tell tilt how to find the new pods. we usually see people do this with extra_pod_selectors as in this example:  https://docs.tilt.dev/custom_resource.html#does-it-create-pods

you can inspect what pods tilt is attaching live update to with `tilt get liveupdate -o yaml`

**Comment by roma-glushko** [comment]
https://github.com/roma-glushko/tilt-issues/commit/b7efdfe02adfe5facfa8a35d19a446b64ded832e - specifying the `extra_pod_selectors` does helped. Thank you!

**Comment by nicks** [comment]
extra_pod_selectors should also affect logs. You can inspect what pods tilt is streaming logs from with `tilt get podlogstream -o yaml`

**Comment by roma-glushko** [comment]
@nicks yeah, it's kind of group worker logs together with scheduler ones. Is there a way to represent worker as a separate component in the Tilt UI?

**Comment by nicks** [comment]
we usually see people set up a local_resource that streams the logs, here's an example: https://docs.tilt.dev/local_resource.html#serve_cmd
