### ISSUE TITLE
support input prompt on git bash

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#5989]
When you open tilt in a normal terminal, you get a prompt:

```
(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
```

When you open tilt in a git bash shell, you get a streaming log.

That's because git bash isn't a normal terminal, and doesn't process input in the same way. We would have to write special handling in tilt to make the input prompt support git bash.

**Comment by bshore** [comment]
Thanks @nicks !

**Comment by bshore** [comment]
Hey @nicks, I'd like to make some time to contribute and get this implemented. I'm looking [here](https://github.com/tilt-dev/tilt/blob/v0.30.13/internal/cli/up.go#L117) and wondering if maybe the solution belongs in the `mattn/go-isatty` repo?

In the meantime, in case anyone else encounters this:
```bash
# in the ~/.bashrc file for git bash
alias tilt="winpty tilt"

# or prefix tilt command with 'winpty' each invocation
winpty tilt up
```
[Winpty](https://github.com/rprichard/winpty) seems to be included in Git Bash, and this is working for me
> winpty is a Windows software package providing an interface similar to a Unix pty-master for communicating with Windows console programs.

**Comment by bshore** [comment]
Hey @nicks

I went to look through and possibly start on this, and it seems like things are working just fine now with Git Bash on Windows?

This issue can probably be closed

**Comment by nicks** [comment]
@bshore thank you for the update!

**Comment by bshore** [comment]
😅 🤦‍♂️ 

I forgot that I had aliased `tilt=winpty tilt` in my `.bashrc` so this is actually not resolved. Realizing this I'll give it another shot 😄
