### ISSUE TITLE
Tilt doesn't automatically detect code changes if source-code is mounted the machine running the k8s cluster

### ISSUE THREAD

**Issue by GuyBalmas** [tilt-dev/tilt#5991]
### Background info:
I have a `minikube` cluster running on WSL `ubuntu` machine on a Windows 10 host.
The source code repo is found locally on Windows host under path `C:\Users\<username>\IdeaProjects\tilt-demo`.
The `C:` driver is mounted to the `ubuntu` machine under `/mnt/c/` which means the source code repo is accessable to the `ubuntu` machine under `/mnt/c/Users/<username>/IdeaProjects/tilt-demo`.

Tilt builds and deploys the source code on 'tilt up' command, but will not detect any code changes done to the source-code after that.
I tried looking into the `filewatch` resource that monitors my `src/` folder, and I can see it monitors the correct path:
```
$ tilt get filewatch 
NAME                                                                                            CREATED AT
configs:(Tiltfile)                                                                             2022-12-15T07:09:32Z
image:tilt-example-image-tilt_docker_build_with_restart_base   2022-12-15T07:09:32Z
image:tilt-example-image                                                            2022-12-15T07:09:32Z
local:example-app-jar                                                                   2022-12-15T07:09:32Z
```
```
$ tilt get filewatch local:example-app-jar -o yaml
apiVersion: tilt.dev/v1alpha1
kind: FileWatch
metadata:
  annotations:
    tilt.dev/resource: example-app-jar       
    tilt.dev/target-id: local:example-app-jar
  creationTimestamp: "2022-12-15T07:09:32Z"  
  name: local:example-app-jar
  ownerReferences:
  - apiVersion: tilt.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Tiltfile
    name: (Tiltfile)
    uid: 4bc24806-5fbb-48cb-9120-911b42141333
  resourceVersion: "75"
  uid: 37a9200a-040d-4b38-8b6c-ded938714d73  
spec:
  disableSource:
    configMap:
      key: isDisabled
      name: example-app-jar-disable
  watchedPaths:
  - /mnt/c/Users/GuyBalmas/IdeaProjects/tilt-demo/pom.xml
  - /mnt/c/Users/GuyBalmas/IdeaProjects/tilt-demo/src
status:
  disableStatus:
    disabled: false
    lastUpdateTime: "2022-12-15T07:09:32Z"
    reason: ConfigMap/key "example-app-jar-disable"/"isDisabled" is false
    state: Enabled
  lastEventTime: null
  monitorStartTime: "2022-12-15T07:09:33.036036Z"
```
Still, Tilt won't pick-up the code changes automatically, but needs to be triggered manually for that to happen.

I tried cloning my `tilt-demo` repo to the `ubuntu` machine under `~/tilt-demo` directory, and after I run `tilt up`, Tilt works perfectly fine, picking up changes automatically.

It's not a Windows permissions issue, since the initial build and deploy triggers fine (as well as manual triggering).
A possible reason could be an issue with the `filewatch` locking the files on windows file system?
 
### Source Code Repo
- https://github.com/GuyBalmas/tilt-demo

### Expected Behavior
Code changes should be picked up automatically.

### Current Behavior
Tilt builds and deploys the source code on 'tilt up' command, but will not automatically detect any code changes done to the source-code after that.

### Steps to Reproduce

prerequisites:
1. Running `minikube` cluster on WSL `ubuntu` machine.
2. Install dependencies for running the `Tiltfile` correctly:
  -  Tilt (`v0.30.13`): 
  ```
curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
  ```
- Maven (`Apache Maven 3.6.3`):
```
sudo apt update && sudo apt install maven
```
- JDK (`openjdk 11.0.17`):
```
sudo apt-get install openjdk-11-jdk
```
- Unzip (`UnZip 6.00`)
```
sudo apt install unzip
```

#### Steps:
1. `git clone https://github.com/GuyBalmas/tilt-demo`
2. `tilt up`
3. Change `/src/main/java/org/example/app/controllers/HelloController.java` file.
4. Watch Tilt UI doesn't get automatically triggered.

#### `tilt doctor` Output

```
Tilt: v0.30.13, built 2022-12-05
System: linux-amd64
---
Docker (cluster)
- Host: tcp://127.0.0.1:61473
- Server Version: 20.10.20
- API Version: 1.41
- Builder: 2
---
Docker (local)
- Host: unix:///var/run/docker.sock
- Server Version: 20.10.21
- Version: 1.41
- Builder: 2
- Compose Version: v2.13.0
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.25.3
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: d41d8cd98f00b204e9800998ecf8427e
- Repo: QySegwHs/jsa50xY3V5UHQ==
...
```

#### About Your Use Case

I am trying to develop locally using tilt to build and deploy changes on an `ubuntu` machine running on WSL on windows.
Further info is mentioned above in the '**background info**' section.

Any help will be much appriciated.
Thank you!

**Comment by nicks** [comment]
ahhhh sadly this is a known bug, you can read more about it here:
https://github.com/microsoft/WSL/issues/4739

The basic problem is that if you mount a Windows directory on the Linux filesystem, we don't get inotify / file change events at all. WSL2 doesn't implement them.

I think the WSL team recommends that you put your source code on the Linux filesystem. It's going to be a lot faster and more robust than doing the cross-OS mount approach.
