### ISSUE TITLE
Issue with certificate after a tilt up

### ISSUE THREAD

**Issue by dfeyer** [tilt-dev/tilt#5998]
```
❯ tilt up --stream
Error: unable to create controller manager: Get "https://127.0.0.1:35303/api?timeout=32s": x509: certificate has expired or is not yet valid: current time 2022-12-21T13:14:22-08:00 is after 2022-12-21T18:51:35Z
```
Look like tilt contains in expired certs, I think this API call is to internal tilt API, right ?

Bests

**Comment by dfeyer** [comment]
Upgrading tilt solve this issue. Sorry.

**Comment by nicks** [comment]
yep, dupe of https://github.com/tilt-dev/tilt/issues/5865

you can also delete `~/.cache/tilt-dev/certs`
