### ISSUE TITLE
Support for CDK, CDK8S etc

### ISSUE THREAD

**Issue by oleghind** [tilt-dev/tilt#6012]
Maybe I am wrong but I can't find any way to build CDK\CDK8S deployment yaml file before loading it. It seems like tilt runs k8s_yaml right away. Any suggestions?

**Comment by nicks** [comment]
you're probably looking for this doc - https://docs.tilt.dev/templating.html#how-to-connect-existing-yaml-tools

usually you would use a `local()` call to do this.

**Comment by oleghind** [comment]
yes I used this but was hoping tilt can take care of watching for changes, running synth and updating deployment

**Comment by nicks** [comment]
the tiltfile config language should be powerful enough to handle all of these things. 

the typical pattern we see: teams do a little tiltfile scripting to connect their yaml tools. then, if the tool is general enough, they package it up as an extension https://github.com/tilt-dev/tilt-extensions. We would probably accept an extension for this if you wanted to contribute one.
