### ISSUE TITLE
Tilt uses randomly generated tag for images for configured tag

### ISSUE THREAD

**Issue by o-shevchenko** [tilt-dev/tilt#6021]
### Expected Behavior

We set a tag for `custom_build` and tilt uses this tag to pull images.

### Current Behavior

Tilt uses randomly generated tag for images for configured tag.
We set a tag for `custom_build` but tilt continues to use randomly generated tags for pods.

### Steps to Reproduce
```
default_registry('k3d-registry.localhost')
# Build Docker image
custom_build(
    'k3d-registry.localhost:5000/myservice',
    './gradlew dockerPushImage',
    deps=['src'],
    tag='dev',
    disable_push=True
)

```

We use Java plugin for [dockerPushImage](https://github.com/bmuschko/gradle-docker-plugin)

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.31.1, built 2023-01-09
System: darwin-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 20.10.21
- API Version: 1.41
- Builder: 2
- Compose Version: v2.13.0
---
Kubernetes
- Env: k3d
- Context: k3d-devinfra
- Cluster Name: k3d-devinfra
- Namespace: default
- Container Runtime: containerd
- Version: v1.20.11+k3s2
- Cluster Local Registry: &RegistryHosting{Host:localhost:5000,HostFromClusterNetwork:k3d-registry.localhost:5000,HostFromContainerRuntime:k3d-registry.localhost:5000,Help:https://k3d.io/usage/guides/registries/#using-a-local-registry,SingleName:,}
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: 1fb1bef9bb69b25165841f5f290e2049
- Repo: Zdl9mfyaWpRLshdcXBAUmQ==
```

**Comment by o-shevchenko** [comment]
>If your custom_build doesn't use Docker, you might need to use skips_local_docker=True

Our custom_build uses Docker but such a flag helped.
```
custom_build(
    'k3d-registry.localhost:5000/myservice',
    './gradlew dockerPushImage',
    deps=['api/src/main'],
    skips_local_docker=True
)
```

**Comment by o-shevchenko** [comment]
https://github.com/tilt-dev/tilt-example-java/issues/31

**Comment by nicks** [comment]
this is working as intended.

by design, Tilt sets $EXPECTED_REF, and assumes your build script tags an image with that ref. if your build script doesn't do this, it will fail.

The `skips_local_docker` argument means "i know what i'm doing, so you don't need to validate my build script is doing the right thing." so it doesn't help, it just makes the error more cryptic when it fails downstream.
