### ISSUE TITLE
In app link for Tilt News is 404ing - https://tilt.dev/subscribe

### ISSUE THREAD

**Issue by bwalding** [tilt-dev/tilt#6030]
### Expected Behavior
App should link to a working subscribe page / page should be fixed

Link target is https://tilt.dev/subscribe

Link text is "Already on the recommended version!
If you're impatient for more,
subscribe to [Tilt News](https://tilt.dev/subscribe)."

### Current Behavior

https://tilt.dev/subscribe is 404ing

### Steps to Reproduce
1. Run tilt
2. Click on version number in top right of app page
3. Click on "Tilt News"

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.31.1, built 2023-01-09
System: darwin-arm64
...
```

#### About Your Use Case

Could not subscribe to tilt news! (I am already subscribed of course - just raising a defect).

Not sure on the proper fix for this - so didn't raise a PR.

**Comment by nicks** [comment]
hmmm i'm just going to remove this link

**Comment by nicks** [comment]
thanks for reporting!
