### ISSUE TITLE
Replace httpbin with something up to date

### ISSUE THREAD

**Issue by rafrafek** [tilt-dev/tilt#6035]
httpbin is no longer maintained and does not support arm64 architecture.

**Comment by nicks** [comment]
Where do you see tilt using httpbin? Can you provide a link?

**Comment by rafrafek** [comment]
I'm starting it with `tilt up -- --argo=1`. Is it because argo?

**Comment by rafrafek** [comment]
I think it is because of Argo. Sorry for the confusion.
