### ISSUE TITLE
Argo is broken

### ISSUE THREAD

**Issue by rafrafek** [tilt-dev/tilt#6036]
Originally posted here https://github.com/argoproj/argo-workflows/issues/10405

### Expected Behavior
Argo can start simple workflow without errors

### Current Behavior
Argo fails with error `undefined is not an object (evaluating 't.status.nodes[n]')`

### Steps to Reproduce

1. Install Docker Desktop
2. Enable Kubernetes
3. Install latest tilt
4. Run `tilt up -- --argo=1`
5. Run `kubectl -n argo port-forward deployment/argo-server 2746:2746`
6. Go to 127.0.0.1:2746
7. Run simple Argo workflow
8. Click Logs in Argo workflow

#### `tilt doctor` Output

```
MacOS Ventura 13.2
M1 Pro Macbook 16

$ tilt doctor
Tilt: v0.31.1, built 2023-01-09
System: darwin-arm64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 22.06.0-beta.0-917-gf888bd4531.m
- API Version: 1.43
- Builder: 2
- Compose Version: v2.15.1
---
Kubernetes
- Env: docker-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.25.4
- Cluster Local Registry: none
```

#### About Your Use Case

I can't use Argo

**Comment by nicks** [comment]
Can you elaborate on why you think this is a tilt bug?

**Comment by rafrafek** [comment]
When I run Argo without tilt it works. Maybe it is because tilt uses `quay.io/argoproj/argocli:latest` (untagged) instead of `https://github.com/argoproj/argo-workflows/releases/download/v3.4.4/install.yaml` (v3.4.4). 

How can I specify Argo version when running `tilt up -- --argo=1`? I want latest stable version, not the untagged one.

**Comment by rafrafek** [comment]
I'm really sorry for the confusion I've made here. For some reason I was using wrong Tiltfile.

Bad config included:
```
    argo_vers = '4bd78890ea666888e0c291600110dd6a2dac5bc8'
    argo_yaml_orig = local(
        'curl -fsSL https://raw.githubusercontent.com/argoproj/argo-workflows/%s/manifests/quick-start-minimal.yaml'
        % argo_vers
    )
```

Correct config should include:
```
    argo_vers = 'v3.4.4'
    argo_yaml_orig = local(
        'curl -fsSL https://github.com/argoproj/argo-workflows/releases/download/%s/quick-start-minimal.yaml'
        % argo_vers
    )
```
