### ISSUE TITLE
Readiness Probes with Docker Compose

### ISSUE THREAD

**Issue by saulshanabrook** [tilt-dev/tilt#6037]
## Describe the Feature You Want

I am curious if Docker Compose can support some form of a readiness probe, either from the Docker HEALTHCHECK or a the probe you have defined.

### Current Behavior
I don't believe currently there is a probe for docker compose.

### Why Do You Want This?
I am trying to see if my HTTP server is up, and it would be great in the GUI if there was a way to show that.

**Comment by nicks** [comment]
are you aware of compose's built-in healthcheck? https://docs.docker.com/compose/compose-file/#healthcheck

i don't think we currently display this in the tilt UI, but if we did, we'd probably have tilt hook into that (rather than have people specify it in the tiltfile)

**Comment by saulshanabrook** [comment]
@nicks Yep that makes sense to me! I wasn't sure if this was currently displayed in the UI.

**Comment by apaniel** [comment]
Any plans to show it in the UI? I'd be interested too

**Comment by remi00** [comment]
Having this would be a great addition. Today in the setup based on docker compose we can get 🟢 **all green** and ready on Tilt dashboard whereas the service may be crashing miserably on run-time.
