### ISSUE TITLE
Full update does not re create PVCs

### ISSUE THREAD

**Issue by huangzou70** [tilt-dev/tilt#6048]
### Expected Behavior
Force refreshing a tilt resource should recreate everything in the tilt resource

### Current Behavior
Force refreshing a tilt resource with a PVC does not recreate the PVC, resulting in my app to wait indefinitely for the PVC to be recreated. A second force refresh fixes this.

### Steps to Reproduce
1. Set up a k8s deployment that mounts a PVC
2. Define, in the Tilt file something like this: `k8s_resource('myapp', objects=['myapp-pvc:persistentvolumeclaim'])`
3. tilt up
4. Perform a force refresh in the Tilt UI

#### `tilt doctor` Output

```
Huangs-MacBook-Pro-2:seurat zou$ tilt doctor
Tilt: v0.31.1, built 2023-01-09
System: darwin-amd64
---
Docker
- Host: [default]
- Server Version: 
- API Version: 
- Builder: 
- Compose Version: v2.3.3
---
Kubernetes
- Env: gke
- Context: gke_livedesign-development-31333_us-central1_shared-dev-cluster-11
- Cluster Name: gke_livedesign-development-31333_us-central1_shared-dev-cluster-11
- Namespace: dev-zou-darwin-04d442fb
- Container Runtime: containerd
- Version: v1.24.8-gke.2000
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: bbfb9c78f9450f4c6ace15cd5c20613d
- Repo: GuRVNB7cdKeumnQBjLUROQ==
...
```

#### About Your Use Case
This is made worse by https://github.com/tilt-dev/tilt/issues/5492, since if you want MANUAL_UPDATE resources, they can only be updated via full refreshes.

I suspect the issue here is when tilt refreshes the resource and deletes everything tracked by the tilt resource, the PVCs are deleted but will not go away until the pod referencing the PVC gets deleted. And if the pod takes too long to terminate (it takes about 30 seconds for my pod to terminate), then tilt would try to recreate the PVC while the pod is still going down, and fail at the recreate

I suspect this also affects other k8s objects that are not PVCs

**Comment by nicks** [comment]
thanks for the report! I wasn't able to reproduce this. Here's the repro case I tried:
https://github.com/tilt-dev/tilt-example-html/blob/nicks/pvc/0-base/Tiltfile

Some clarification questions:

1) Can you provide more details on what you're using to provision the storage? your tilt doctor says you're using gce, is it a gcePersistentDisk?

2) Why do you think this is a bug in tilt? from your issue description, in particular:
- "the PVC into a TERMINATING state, but it won't terminate"
- "myapp" won't start up because the PVC, again, does not get recreated
these seem more like bugs in the volume controller you're using. have you checked the logs on your volume controller to see where it's getting stuck?

**Comment by huangzou70** [comment]
@nicks thanks for looking into this!
Here is a full yaml that I'm using to reproduce this if it helps:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app.kubernetes.io/name: my-app

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-app
    spec:
      volumes:
        - name: my-app
          persistentVolumeClaim:
            claimName: my-app-pvc
      containers:
        - name: main
          image: busybox:1.28
          args: [ /bin/sh, -c, 'while true; do sleep 10; done' ]
          volumeMounts:
            - name: my-app
              mountPath: /livedesign/my-app/
```

> Can you provide more details on what you're using to provision the storage? your tilt doctor says you're using gce, is it a gcePersistentDisk?

Yeah, I have tried a few provisioners and all of them runs into this problem. The ones I tried are:
```
15:03:52 desk-lu116:seurat > kubectl get storageclass
NAME                                PROVISIONER                                  RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
nfs                                 cluster.local/chart-nfs-server-provisioner   Retain          Immediate              true                   12m
standard (default)                  kubernetes.io/gce-pd                         Delete          Immediate              true                   149d
standard-rwo                        pd.csi.storage.gke.io                        Delete          WaitForFirstConsumer   true                   149d
```

>Why do you think this is a bug in tilt? from your issue description, in particular:
"the PVC into a TERMINATING state, but it won't terminate"
"myapp" won't start up because the PVC, again, does not get recreated
these seem more like bugs in the volume controller you're using. have you checked the logs on your volume controller to see where it's getting stuck? or checked a kubectl describe pvc [your-pvc] to see if there are any events that say what's happening?

So I think the reason the PVC is "stuck" is because the pvc-protection finalizer is preventing the PVC from being terminated until the pod  ("my-app" in this case) using the PVC has been terminated first. The PVC _does_ get deleted when the pod gets deleted, but that can take a few seconds.

There is nothing in the events, the only relevant pieces is the pod not being able to start up due to missing PVCs. Here is how they look like
```
62s         Warning   FailedScheduling          pod/my-app-566b74b5c6-5pjv8                                                        0/59 nodes are available: 59 persistentvolumeclaim "my-app-pvc" is being deleted. preemption: 0/59 nodes are available: 59 Preemption is not helpful for scheduling.
59s         Normal    NotTriggerScaleUp         pod/my-app-566b74b5c6-5pjv8                                                        pod didn't trigger scale-up (it wouldn't fit if a new node is added): 8 persistentvolumeclaim "my-app-pvc" not found
29s         Warning   FailedScheduling          pod/my-app-566b74b5c6-5pjv8                                                        0/59 nodes are available: 59 persistentvolumeclaim "my-app-pvc" not found. preemption: 0/59 nodes are available: 59 Preemption is not helpful for scheduling.
```

And `kubectl get pvc | grep my-app` is not returning any hits. So I don't think the problem lies in the provisioner failing to provision PVs, but rather than PVC object is completely missing.

If it helps, below is the yaml of the PVC while it's at TERMINATING:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
    volume.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
  creationTimestamp: "2023-02-24T20:02:23Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2023-02-24T20:02:46Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: my-app-pvc
  namespace: dev-zou-linux-8f34c3e9
  resourceVersion: "333999643"
  uid: e2b9d0a5-f8fe-43d0-b32e-cd61a91725bb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-e2b9d0a5-f8fe-43d0-b32e-cd61a91725bb
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
```

>Why do you think this is a bug in tilt? 

I'm not exactly sure how Tilt is recreating the PVC affected here, but my naive assumption is, Tilt issues a `kubectl delete` on the PVC, then later runs `kubectl apply` with the PVC yaml. Whether or not the PVC gets applied is dependent on the timing of the `kubectl apply` run.  My expectation is Tilt would wait for the PVC to be deleted before applying the PVC, and not doing so is a bug in Tilt.

Let me know if more information is needed. Thanks again!

**Comment by huangzou70** [comment]
@nicks 
I took a closer look at this and I'm fairly certain Tilt is not issuing the POST command to create the PVC

On the force refresh where the PVC doesn't get recreated. The following commands are logged in tilt logs:

```
I0403 09:55:18.887815 1200781 round_trippers.go:553] DELETE https://34.68.247.5/apis/apps/v1/namespaces/dev-zou-linux-f9ba3614/deployments/my-app 200 OK in 74 milliseconds
I0403 09:55:18.960022 1200781 round_trippers.go:553] DELETE https://34.68.247.5/api/v1/namespaces/dev-zou-linux-f9ba3614/persistentvolumeclaims/my-app-pvc 200 OK in 71 milliseconds
I0403 09:55:18.976906 1200781 round_trippers.go:553] DELETE https://34.68.247.5/apis/apps/v1/namespaces/dev-zou-linux-f9ba3614/deployments/my-app 404 Not Found in 45 milliseconds
I0403 09:55:19.007761 1200781 round_trippers.go:553] GET https://34.68.247.5/apis/apps/v1/namespaces/dev-zou-linux-f9ba3614/deployments/my-app 404 Not Found in 47 milliseconds
I0403 09:55:19.008219 1200781 round_trippers.go:553] GET https://34.68.247.5/api/v1/namespaces/dev-zou-linux-f9ba3614/persistentvolumeclaims/my-app-pvc 200 OK in 47 milliseconds
I0403 09:55:19.025213 1200781 round_trippers.go:553] DELETE https://34.68.247.5/api/v1/namespaces/dev-zou-linux-f9ba3614/persistentvolumeclaims/my-app-pvc 200 OK in 47 milliseconds
...
I0403 09:55:49.109639 1200781 round_trippers.go:553] GET https://34.68.247.5/api/v1/namespaces/dev-zou-linux-f9ba3614/persistentvolumeclaims/my-app-pvc 200 OK in 97 milliseconds
I0403 09:55:49.182860 1200781 round_trippers.go:553] GET https://34.68.247.5/apis/apps/v1/namespaces/dev-zou-linux-f9ba3614/deployments/my-app 404 Not Found in 67 milliseconds
I0403 09:55:49.248710 1200781 round_trippers.go:553] GET https://34.68.247.5/api/v1/namespaces/dev-zou-linux-f9ba3614 200 OK in 65 milliseconds
I0403 09:55:49.326553 1200781 round_trippers.go:553] POST https://34.68.247.5/apis/apps/v1/namespaces/dev-zou-linux-f9ba3614/deployments 201 Created in 77 milliseconds
...
       my-app │      Objects applied to cluster:
       my-app │        → my-app-pvc:persistentvolumeclaim
       my-app │        → my-app:deployment
```
Notice the last GETs returns a 404 for the deployment, and a 200 for the PVC. And only one POST is issued for the deployment.

It looks like is Tilt isn't handling pods needing a bit of time to be deleted, which prevents the PVC from being deleted. And when tilt sees the PVC still exists, it just proceeds to ignore the recreation.

**Comment by andymartin-sch** [comment]
This is something we're still seeing internally when people use the "force refresh" button, so I was curious why it wouldn't be being seen/reported more widely.

After discussing a bit with Huang, here are some possible reasons:
1. most people are not frequently triggering "force refreshes"
2. most people are not using `k8s_resource` to include PVCs (or other resources) in with the deployment for the resources they're "force refreshing"
3. (for the original issue, not the repro case submitted) it's a race condition that is less likely to be triggered when the pod is able to be quickly deleted
4. despite it being reproducible with the three storageclasses mentioned in the earlier comment, it may not be reproducible with all storage classes (particularly the original scenario's race condition)

My guess is that 2 might be the most significant factor in what makes us different. We had originally done this because if you just have `k8s_resource('$DEPLOYMENT_NAME')`, then the PVC goes into the "uncategorized" resource. The "uncategorized" resource section had grown so large for us that it would take several minutes to deploy all the objects, which was painful (lots of different things can cause it to be rerun + nothing else can start running until it finishes).

It seems like 3 possible ways forward are:
1. underlying issue is fixed/mitigated
2. we put these PVCs back into "uncategorized"
3. we add an additional `k8s_resource`s to separate the resources where we typically see this from the deployments which get force reloaded

Can anyone think of anything else?

It's not really clear to me what 1 would look like :( re:
> It looks like Tilt isn't handling pods needing a bit of time to be deleted, which prevents the PVC from being deleted. And when tilt sees the PVC still exists, it just proceeds to ignore the recreation.

Possibly the check here:
```
I0403 09:55:49.109639 1200781 round_trippers.go:553] GET https://34.68.247.5/api/v1/namespaces/dev-zou-linux-f9ba3614/persistentvolumeclaims/my-app-pvc 200 OK in 97 milliseconds
```
could be expanded to check the status and to NOT consider a 200 as something that indicates the resource is present if the status is also "Terminating"?

**Comment by nicks** [comment]
i did a little research on this. i can repro it. i think the fundamental problem is that there are cases where a k8s apply can quietly fail, there's some discussion about it here - https://github.com/kubernetes/kubernetes/pull/95544. 

other tools that i looked at (e.g. helm) don't seem to handle this great either...

i think the right fix is to detect when this is happening and either mark the apply as failed, or retry it until some timeout.
