### ISSUE TITLE
silence live_update run() commands

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#6054]
## Describe the Feature You Want
Michael writes in the tilt channel:

> when using the run option with LiveUpdates to run a command in a container after files are synced, is there a way to not have the command being run printed into the logs? We're running a fairly long curl command and we don't need it printed out in the logs if there's an easy way to suppress that.

i don't think there's a way to do this right now but might not be too hard to add.

**Comment by muripic** [comment]
I'm also interested in this 🙏 
We need to run a command with a secret we have locally but the way it is now, it's printed out every time

**Comment by nicks** [comment]
fixed in https://github.com/tilt-dev/tilt/pull/6351
