### ISSUE TITLE
`tilt up` and `helm dependency build`

### ISSUE THREAD

**Issue by KarlHakanNordgren** [tilt-dev/tilt#6056]
I see from [here](https://github.com/tilt-dev/tilt/issues/1913) that is should no longer be required to run `helm dependency build`. How does it work? I can't find any documentation

**Comment by nicks** [comment]
tilt's `helm()` build-in just invokes `helm template`, and delegates to helm to decide what to do. There are docs on this here: https://docs.tilt.dev/helm.html

I don't remember off the top of my head how `helm template` handles dependencies, but i believe that the guide also provides examples on how to script more complex behavior.
