### ISSUE TITLE
Semantic versioning not respected in the latest release

### ISSUE THREAD

**Issue by rodonal** [tilt-dev/tilt#6063]
In the release v0.31.2  you have introduced a new feature to infer resource deps from compose project (https://github.com/tilt-dev/tilt/pull/6014). But this feature changes the behaviour of Tilt compared to previous versions. 

The following scenario happened to me today. I do "tilt up" for lets say for service 'x', 'y' and 'z'. In my docker-compose unintentionally someone had written that service 'z' depends on service 'k'. Before this feature my setup would just spin up services x,y,z but now it spins up x,y,z and k. This behavior was not intended or simply saying the behavior has changed and causes confusion. Since the versioning you have used for the release gives the impression that it is only a patch I would highly recommend to point out this (breaking) change to the users. My recommendation would be to have it as version 0.32.0. Thanks in advance.

**Comment by nicks** [comment]
Hmmm...I'm not sure I consider this a breaking change, any more than any bug fix would be considered a breaking change. 

However, even if we did consider it a breaking change, I'm not sure what the fix would be? It's the first thing in the release notes: https://github.com/tilt-dev/tilt/releases/tag/v0.31.2. We're not able to rollback the release at this point.
