### ISSUE TITLE
links have host 0.0.0.0

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#6080]
### Steps to Reproduce
1. Use any tilt project with port forwards
2. Start tilt with `tilt up --host=0.0.0.0`

### Expected result
Link in the web UI should point to a portable URL

### Actual result
Link in the web UI points to 0.0.0.0, which does not work on Windows

#### About Your Use Case
I thought we already had a shim around this, i wonder if it broke at some point or if i'm misremembering

The "naive" solution would correct 0.0.0.0 to 127.0.0.1.

The "good" solution would be to correct 0.0.0.0 to the current HOST, since the whole point of 0.0.0.0 is you can access from a remote IP.

Related issue: https://github.com/tilt-dev/tilt/issues/5403

**Comment by nicksieger** [comment]
I might have touched/altered some of the logic in #5245, though I'm not sure this is something that was already broken or broke due to that PR.
