### ISSUE TITLE
Tilt cannot handle remote build path in docker-compose

### ISSUE THREAD

**Issue by Aryess** [tilt-dev/tilt#6097]
### Expected Behavior
When linking a git repository in the `build` argument of a `docker-compose.yml` service, git would normally download the repo and build the image locally. Cf related doc: https://docs.docker.com/engine/reference/commandline/build/#git-repositories

### Current Behavior
Tilt fails to load with the following error:
```
Loading Tiltfile at: /home/{me}/workspace/Scratch/tilt-bug/Tiltfile
Docker Compose service "backend" has a relative build path: "[https://github.com/Aryess/tilt-docker-bug.git#main"](https://github.com/Aryess/tilt-docker-bug.git#main%22)
```

### Steps to Reproduce
Using [this](https://github.com/docker/awesome-compose/tree/master/nginx-golang) project as a demo for the bug.

Backend part of it has been isolated in this public repo, as it doesn't look like docker can handle subdirs (yet): https://github.com/Aryess/tilt-docker-bug

Setup:

Copy `nginx.conf` from [here](https://github.com/docker/awesome-compose/blob/master/nginx-golang/proxy/nginx.conf)
```nginx
server {
  listen 80;
  location / {
    proxy_pass http://backend:80;
  }
}
```

Create on `docker-compose.yml`. This version is adapted from the orignal repo to build from a git URL instead of locally
```yml
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build: https://github.com/Aryess/tilt-docker-bug.git#main
```

Run `docker-compose up` and see that it builds/runs successfully:
![image](https://user-images.githubusercontent.com/3518172/231062496-20d3a561-9503-4b2f-aeb2-56e0445f2c4e.png)

Now add a simple `Tiltfile` that tries to do the same thing:
```starlark
docker_compose('docker-compose.yml')
```

When doing `tilt up` we get the following error:
```
Loading Tiltfile at: /home/{me}/workspace/Scratch/tilt-bug/Tiltfile
Docker Compose service "backend" has a relative build path: "[https://github.com/Aryess/tilt-docker-bug.git#main"](https://github.com/Aryess/tilt-docker-bug.git#main%22)
```

#### `tilt doctor` Output

```
tilt-bug|⇒ t doctor
Tilt: v0.32.0, built 2023-03-13
System: linux-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 20.10.17
- API Version: 1.41
- Builder: 2
- Compose Version: v2.4.1
---
...
```

#### About Your Use Case

Trying to set up Tilt to improve our developer experience working on a service that requires a specific mock to run properly locally, hosted on a separate repository (as it is shared by multiple services). 
Because it is a dev only mock (and because our local workflow was very manual anyway), it is not available in our registry and has to be cloned/ran locally. It has a Dockerfile in it tho, so by doing this I can directly run it without having to clone anything. 

If this issue is not solvable in Tilt it's not the end of the world, I could also just build and push to our registry, but I'm assuming it's just some oversight on an obscure/lesser known feature of docker.
Thanks <3

**Comment by nicks** [comment]
thanks for the report!
