### ISSUE TITLE
Adopt resources not created via tiltfile

### ISSUE THREAD

**Issue by paccolamano** [tilt-dev/tilt#6107]
This is a question as I could not find an example in the documentation.

I have a scenario where a deployment has to create a series of jobs within the cluster. Each job has different tasks but they all have the same image and I would like to see if there is a possibility to use the tilt feature "image reload" to be able to edit the image locally and build it via tilt.
The goal is to have updated images also for resources (jobs) that are not created directly in the tiltfile but from the deployment

This is my tiltfile
```
update_settings(suppress_unused_image_warnings=["worker"])
docker_build('worker', context='../go-executor/', dockerfile='../go-executor/Dockerfile')

docker_build('task-manager', context='../task-manager/', dockerfile='../task-manager/Dockerfile')

k8s_yaml(kustomize('./k8s'))
```
the task manager is the component that takes care of creating jobs within the cluster with the 'worker' image, but live reload of the worker image does not work as the jobs are not created by tilt
any suggestions are welcome!

**Comment by nicks** [comment]
have you seen this guide? https://docs.tilt.dev/custom_resource.html

**Comment by paccolamano** [comment]
yes I have seen it but I have not found use cases similar to mine. I tried using k8s_resources without success. Tilt goes into error telling me that the only resources it knows about is deployment. The point is that the deployment in turn creates a series of jobs within the cluster with runtime-generated names but Tilt does not see them and cannot do the image reload.
if it can be useful as information to give more context to the question I add that I am trying to replicate this [jobs pattern](https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/).

**Comment by paccolamano** [comment]
I found [this](https://github.com/tilt-dev/tilt-extensions/tree/master/k8s_attach) plugin that suits me although it would be useful to be able to specify labels instead of the name

**Comment by nicks** [comment]
i'm going to close this issue, since i think `k8s_attach` works for this. it shouldn't be too hard to adopt k8s_attach for other selectors if you need to, since it's a fairly simple extension
