### ISSUE TITLE
Is there any way to sync ignored file?

### ISSUE THREAD

**Issue by nxy7** [tilt-dev/tilt#6118]
Hello, as far as I can tell Tilt docker_build 'ignore' and 'only' options apply to both - build context and synced files. I'm building multiservice app, some of my services are made using Rust. My idea for keeping one dockerfile for dev and prod was building service with prod image and then using `liveUpdate` and `sync('./target/debug/app', '/buildArtifact')` so whenever dev image is built locally it would just be swapped with release version inside container. Sadly /target folder gets quiet big and probably should be included in .dockerignore. Is there any way (or plans) on supporting that functionality?
Also adding whole app to 'sync' context just to stop docker container from rebuilding feels 'hacky'. Right now I need to add whole source code even if I'm not really using any of it inside the container. Having option to stop containers from rebuilding after initial build would also be nice.
I really like how flexible tilt is and I don't think this project tries to avoid additional configuration complexity and instead it aims for the best UX not DX so having sync context separate from build context doesn't feel out of place to me.

**Comment by nicks** [comment]
have you looked at `k8s_attach`? it will let you sync arbitrary files. https://github.com/tilt-dev/tilt-extensions/tree/master/k8s_attach

it's built on tilt's `k8s_custom_deploy` function, which is lower-level api for more complex use-cases like this one.

**Comment by nxy7** [comment]
k8s_attach indeed does work, thanks :-)
