### ISSUE TITLE
Port forwarding k8s resources don't work with websocket servers

### ISSUE THREAD

**Issue by anilanar** [tilt-dev/tilt#6119]
### Expected Behavior
Given a websocket server running in k8s, exposing it with tilt using `k8s_resource` and `port_forwards` should work as expected.

### Current Behavior
When a websocket client connects, socket between client <-> tilt proxy stays open and the client thinks ws connection is still open.
However the socket between ws server <-> tilt is immediately closed after connection. 

### Steps to Reproduce
1. Run a ws server with your preferred lang/framework. Log something in open and close handlers.
2. Expose it with `k8s_resource` `port_forwards`.
3. Try to connect to it with your preferred lang/runtime/framework from outside the k8s cluster.

WS server will report a connection immediately followed up with an abnormal closure (i.e. code `1006`)
WS client will think it's still connected.

#### `tilt doctor` Output

```
$ tilt doctor

Tilt: v0.32.3, built 
System: linux-amd64
---
Docker (cluster)
- Host: tcp://192.168.49.2:2376
- Server Version: 20.10.23
- API Version: 1.41
- Builder: 2
---
Docker (local)
- Host: unix:///var/run/docker.sock
- Server Version: 20.10.21
- Version: 1.41
- Builder: 2
- Compose Version: v2.12.2
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: engine-cluster
- Container Runtime: docker
- Version: v1.26.1
- Cluster Local Registry: none
---
...
```

### Workaround

My workaround is using kubectl/k9s to port forward instead of tilt's port forwarding and everything works fine.

More declarative/tilt-esque workaround: 

```
local_resource('example', serve_cmd='kubectl port-forward deployments/example 8080:8080')
```

**Comment by nicks** [comment]
Thanks for the report! I was not able to reproduce this problem. Here's the repro case i tried:

https://github.com/tilt-dev/tilt-example-html/commit/4477e2c9bda988baa810605a82f9d7ed3d9857dd

In this example, I used tilt to run tilt inside a kubernetes cluster and exposed it with a portforward. (tilt uses websockets to serve the UI). when i inspected using the chrome network debugger, i saw messaging coming over the websocket connection just fine.

maybe there's something specific about your websocket server that triggers the issue? the websocket spec is pretty complicated and has a lot of oddball features.

**Comment by anilanar** [comment]
You have a point, I couldn't produce in isolation. I'll give it a try next time I'm back on the project that uses Tilt and will try to come up with a reproduction again. If I succeed, I'll reopen this.
