### ISSUE TITLE
Docker Build Utility Doesn't Have --add-host Option

### ISSUE THREAD

**Issue by oguzhanuninsider** [tilt-dev/tilt#6139]
## Describe the Feature You Want
I want the docker build command's --add-host option to be applicable

### Current Behavior
According to [this link](https://docs.tilt.dev/api.html#api.docker_build) there is no such option.

### Why Do You Want This?
Because there are some software packages that I pull from a private registry.

**Additional context**

**Comment by nicks** [comment]
thanks! shouldn't be too hard to add if you want to put together a PR. you basically need to wire a docker_build argument up to ImageBuildOptions's ExtraHosts (https://pkg.go.dev/github.com/docker/docker/api/types#ImageBuildOptions)

Here's an example PR:
https://github.com/tilt-dev/tilt/pull/4934

**Comment by Azanul** [comment]
May I resolve this?

**Comment by smaaland** [comment]
Nice addition :+1:  Would be nice to have it reflected in the documentation as well!
