### ISSUE TITLE
Simplify the development when the remote cluster  has all elements

### ISSUE THREAD

**Issue by fengyeall111** [tilt-dev/tilt#6172]
## Describe the Feature You Want
Now we must do like this:
```
// 1. csutom build image
// 2. custom k8s deploy
```
Why not go through the ci/cd process if  we already have a ready-made cluster with all the elements, instead of just developing them in containers.

**Comment by fengyeall111** [comment]
This looks like work done by [Nocalhost](https://nocalhost.dev/) or [okteto](https://www.okteto.com/).For developer,thet can focus  business logic  and do not need care about ci/cd.

**Comment by nicks** [comment]
we have a solution for this! The k8s_attach extension lets you attach to an existing kubernetes cluster, see https://github.com/tilt-dev/tilt-extensions/tree/master/k8s_attach

**Comment by fengyeall111** [comment]
> we have a solution for this! The k8s_attach extension lets you attach to an existing kubernetes cluster, see https://github.com/tilt-dev/tilt-extensions/tree/master/k8s_attach

Thanks
