### ISSUE TITLE
Configuration to send SIGINT before replacing containers

### ISSUE THREAD

**Issue by ftqo** [tilt-dev/tilt#6188]
## Describe the Feature You Want
Some of my applications require deferred functions to run, which include tasks such as closing files (removing file locks), closing database connections, and other cleanup. I ensure to handle graceful shutdowns, but it doesn't seem that Tilt has any functionality to help with this.

### Current Behavior
Not sure.

### Why Do You Want This?
To handle graceful shutdowns. These can be important, even while developing.

**Additional context**
N/A

**Comment by nicks** [comment]
tilt usually inherits the graceful termination of the underlying container runner you're using.

If you're using kubernetes, you want https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination
if you're using docker compose, you want https://docs.docker.com/compose/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop

is that what you're looking for?

**Comment by ftqo** [comment]
Yes, it is! Thank you.
