### ISSUE TITLE
Is it possible to launch resources serially?

### ISSUE THREAD

**Issue by danielkalen** [tilt-dev/tilt#6190]
I have a microservices stack which has ~40 services launched independently as separate pods via k8s in addition to 4 databases and a few database monitoring pods. I tried to use the `resource_deps` directive, as well as set the parallelism setting to 1 (`update_settings(max_parallel_updates=1)`), but it seems like when I run `tilt up` tilt is eager to deploy everything at once which has everything competing for resources and my machine gets stuck trying to do that... It can take up to 15-20mins to launch the stack this way compared to if I were to launch things serially where it takes me roughly 1-3 mins. The way I currently achieve serial deploys is extremely ad-hoc - basically I comment out my 40-or-so microservice pods/resources, have my databases and other pods launch, and then uncomment ~5 microservices at a time to let them launch in a pseudo-serial fashion. This is my [Tiltfile](https://gist.github.com/danielkalen/9f3d68cbaaeb19187c8367005bb4530e).

It looks like what clogs up my machine is the attempt to fetch/prepare too many containers/pods at once, and even if I leverage the `resource_deps` arg of k8s resource it seems like even though the dependent resources are still not reporting healthy the depending resource is not completely offline and awaiting the dependency to launch, i.e. it looks like some processing/computation occurs (such as pulling of the container image) even if the dependency is not fully online. Am I misunderstanding the documentation/API of tilt?

Any help will be much appreciated, thank you 🙏.

**Comment by nicks** [comment]
`update_settings(max_parallel_updates=1)` will launch resources serially. 

Serially means "one resource at a time", so yes, I would expect this to be slower than running many resources in parallel.

Does that answer your question?
