### ISSUE TITLE
Accept env vars to `custom_build`

### ISSUE THREAD

**Issue by dnephin** [tilt-dev/tilt#6192]
### Problem description

Hello! I work on a tilt setup that uses `custom_build` and is used across many teams. We've noticed that when the `custom_build` fails and someone reaches out for help they may share the wrong part of the output. I'd like to make it easier for users to debug custom build failures themselves, and also make it easier for them to identify and share the relevant part of the output when they do need help. 

### Current Behavior

Today, the output from our `custom_build` looks something like this when it fails:

>  ... many lines of build output from `docker buildx` ...
> ... one or more lines from `docker buildx` that identify the failure ...  
>
> error: failed to solve: executor failed running [/bin/sh ... *some build step here that may end at the line break*]: exit code: 1
> /Users/username/src/project/scripts/custom-build.zsh --flag-1 /Users/username/src/project2/file3 --dockerfile /tmp/asdf0001/Dockerfile --dest-image-repo registry.internal.net/project/imagename --flag2 more-long-values-here --flag-3 /Users/username/src/project3/.config/imagerefs/service2 --flag-4 yet-more-configuration --flag-5 true --flag-6 false exited with exit code 1
>
> Build Failed: Custom build "/Users/username/src/project/scripts/custom-build.zsh --flag-1 /Users/username/src/project2/file3 --dockerfile /tmp/asdf0001/Dockerfile --dest-image-repo registry.internal.net/project/imagename --flag2 more-long-values-here --flag-3 /Users/username/src/project3/.config/imagerefs/service2 --flag-4 yet-more-configuration --flag-5 true --flag-6 false" failed: exit status 1

It is common for Go programs to print the context about an error following an `error:` line. In the output above the error line from `docker buildx` is immediately followed by a log line from `tilt` that prints the command line. The custom build script includes many command line arguments with long values. Together this block of text can look more significant than the failure details above the error. In practice the values we pass to this script are rarely relevant to the failure.

### Proposed solution

I'm hoping to address the problem with two changes.

I'd like to use environment variables instead of command line flags to pass values to the custom build script. I have found that in general environment variables are easier when the command is being run by code (where as command line flags are easier for humans). The env vars are easier to consume in shell scripts, removing the need to parse command line flags. The environment variables are not printed in the failure message today, so `tilt` could continue to print the full command, but the output would be simply `custom-build.zsh exited with exit code 1`. Those variables can be printed at the start of the script for debugging.

I attempted to use https://docs.tilt.dev/api.html#api.os.putenv to set these env vars, but I realized that `os.putenv` sets the values globally for the whole process, so any time multiple resources are running the custom-build script is unlikely to receive the correct values.

**Proposal 1**:  I would like to add an `env = {}` argument to https://docs.tilt.dev/api.html#api.custom_build, so that we can pass settings to our script via environment variables.

----

To address the duplicate message, I'd like to prevent one of the messages from being printed. I believe the first of the two messages comes from https://github.com/tilt-dev/tilt/blob/f487da92f4f25bab0d8f1cd71227a3c81ef63a08/internal/controllers/core/cmd/execer.go#L228

**Proposal 2**:  Could that log output be changed to `Debugf` since the exit code and reason are being returned to the `statusCh` ?

Would it be more appropriate to try and hide the second message? I believe if we implement proposal 1 this becomes less critical (because it's significant less output in general), but it would still be an improvement to remove the duplicate message.

Thank you!

**Comment by nicks** [comment]
ya, both of those seem reasonable to me.

Adding `env` to `custom_build` should be straightforward (i'm honestly surprised there's not a feature request for it already)

De-duplicating the error message from the cmd might be a little bit more tricky, because a couple things use that codepath, and i'm not 100% confident they all print the error. but i'm fine with trying it and seeing what breaks.

**Comment by nicks** [comment]
closing this, as i think this has been implemented
