### ISSUE TITLE
Image push fails when using an orbstack cluster

### ISSUE THREAD

**Issue by m1guelpf** [tilt-dev/tilt#6218]
When using orbstack with the built-in kubernetes cluster, tilt will attempt to push images to docker.io.

## Expected Behavior
Tilt should skip image push with the message "building on cluster's container runtime".

## Current Behavior
Tilt attempts to push image to docker.io and fails with "requested access to the resource is denied".

## Steps to Reproduce
- Install [Orbstack](https://orbstack.dev) and enable Kubernetes.
- Run `tilt up` for any Tiltfile that contains build image steps.

## Context

```
Tilt: v0.33.4, built 2023-08-10
System: darwin-arm64
---
Docker
- Host: unix:///Users/m1guelpf/.orbstack/run/docker.sock
- Server Version: 24.0.5
- API Version: 1.43
- Builder: 2
- Compose Version: v2.21.0
---
Kubernetes
- Env: unknown
- Context: orbstack
- Cluster Name: orbstack
- Namespace: default
- Container Runtime: docker
- Version: v1.27.4+orb1
- Cluster Local Registry: none
---
```

**Comment by chibuzoro-salesfloor** [comment]
any known workarounds for this issue?

**Comment by nilcolor** [comment]
Are there any plans to release a fix? Or workaround?

**Comment by nilcolor** [comment]
👍  Tilt-on-OrbStack now works as expected! Thank you folks!
