### ISSUE TITLE
Is there a way to run local command serially

### ISSUE THREAD

**Issue by prat1kbhujbal** [tilt-dev/tilt#6224]
## Describe the Feature You Want
Is there a way to run the local command serially after it executes the above functions?

### Current Behavior
As soon as I run tilt up the function gets executed before the function above is executed.

For reference
```
# Function to start services
def start_services():

# Function to upload various CSV files where local commands are running and depend on the above start_services
def upload_tasks():
 
# Main execution
start_services()
upload_tasks()

```
### Why Do You Want This?
As the function in which the local command is running depends on the above function or else it throws errors and I can't find a way to make it serialize.

**Additional context**
I am calling `local_output('curl -isf http://0.0.0.0:8003/health/ | grep "200 OK"', quiet=True, echo_off=True)` and it returns some output. And before that, I ran some services that this command depends on or else it will give this error `ERROR: Build Failed: Command "curl -isf http://0.0.0.0:8003/health/ | grep \"200 OK\"" failed: exit status 1
`, but as all things run parallelly, I couldn't run services first and then this command. Therefore it gives me the error as it takes time to start services.

**Comment by nicks** [comment]
you can accomplish this with Resource dependencies - https://docs.tilt.dev/resource_dependencies.html
