### ISSUE TITLE
More details in timeout error from `tilt ci`

### ISSUE THREAD

**Issue by dnephin** [tilt-dev/tilt#6231]
## Describe the Feature You Want

When `tilt ci` reaches the `ci_settings.timeout` the error it returns is not very informative (ex: "Error: Timeout after 30m0s"). Generally when our builds reach the timeout there are one or more pods that are in crash loop backoff.

I'd like to augment the timeout error and include something like the detail we get for non-timeout builds.

> Error: Timeout after 30m0s: Pod "podname-mb2cb" is in state CrashLoopBackOff

I guess in this case there may be more than one pod that is not ready. I'm not sure if that complicates things or not.

### Current Behavior

> Error: Timeout after 30m0s

### Why Do You Want This?

We're working on making it easier to quickly find the common flakes in our CI builds. When we get an error that includes the pod name it's easier to aggregate the errors. When we get errors like `Timeout after x` it's more difficult because we don't know which pods caused the timeout. There could be many different causes for those timeouts.

**Comment by nicks** [comment]
i like this idea! i'm not sure how you'd thread the info through though.

**Comment by nicks** [comment]
maybe a good place to start would be to check for some common cases :thinking: need to think on it though.

**Comment by dnephin** [comment]
#6262 has been working great for this, so I'd be fine to close this issue now. I think there is still potential to include more details about why something is not ready when the timeout is reached, but I'm not sure if it's worth the effort.

**Comment by nicks** [comment]
🎉
