### ISSUE TITLE
Launch new dev environment from Internal Developer Portal

### ISSUE THREAD

**Issue by regicsolutions** [tilt-dev/tilt#6239]
## Backstage Plugin
For enterprises using internal developer portals using frameworks like [https://backstage.io](Backstage) it would be nice to be able to orchestrate the launch of a new tilt session locally by a click of a button ... could see a front end backstage plugin that introduces a  "Launch Local Development Environment" button similar to the launch GitHub Codespaces button in GitHub, only difference would be the runtime would be the developers local machine, the developer that clicked the button.

### Current Behavior

Developers needs to install the tilt cli, initiate git to a remote repository that has the required tilt file and other manifests and run tilt up

### Why Do You Want This?

**Additional context**

**Comment by nicks** [comment]
thanks for the request!

clarification question: is there something you think the tilt project should do to enable this?

this honestly sounds more like a feature request for backstage...but i don't know the backstage security model well enough to know whether it's even allowed to invoke local development environments.

**Comment by nicks** [comment]
closing this, as i don't see any action to take here within the scope of tilt
