### ISSUE TITLE
Bad address issue while installing Tilt

### ISSUE THREAD

**Issue by santoshrjagtap** [tilt-dev/tilt#6245]
### Expected Behavior
Installing tilt on Ubuntu 20.04 WSL.

### Current Behavior
After executing command "curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash"
It gives below error at the end 

"Note: it looks like it is not the first program named 'tilt' in your path. `tilt version` (running from /home/linuxbrew/.linuxbrew/bin/tilt) did not return a tilt.dev version string.
It output this instead:
main: line 94: /home/linuxbrew/.linuxbrew/bin/tilt: Bad address
Perhaps you have a different program named tilt in your $PATH?"

#### `tilt doctor` Output
-bash: /home/linuxbrew/.linuxbrew/bin/tilt: Bad address

**Comment by nicks** [comment]
:thinking: i've never heard of this before. does it work if you download the binary directly from the releases page?

**Comment by nicks** [comment]
what version of wsl are you using? i poked around in the WSL repo and there were a bunch of complaints about it, mostly related to old WSL versions or WSL corruption

**Comment by santoshrjagtap** [comment]
My version of WSL is  Ubuntu-20.04

**Comment by nicks** [comment]
closing this as a WSL problem, not a tilt problem
