### ISSUE TITLE
0.33.6 breaks Docker Compose with profiles

### ISSUE THREAD

**Issue by Tadimsky** [tilt-dev/tilt#6250]
### Expected Behavior
We have a docker compose file that disables one of our services by default using docker compose profiles.

```yaml
libpostal-http:
    profiles:
      - "include_libpostal"
```

Using `COMPOSE_PROFILES=include_libpostal docker compose up ...` will let you start the service if desired (outside of Tilt).

In our Tiltfile we have this:
```
dc_resource("libpostal-http", auto_init=False, labels=["dependencies"])
```

Before upgrade to 0.33.6 all of this worked totally fine. The service didn't start by default, but could be started in the Tilt UI.

### Current Behavior

Tilt 0.33.6 now has the following error when starting up:

```
Traceback (most recent call last):
  /Users/jonno/Source/rainbow/Tiltfile:16:12: in <toplevel>
Error in dc_resource: no Docker Compose service found with name "libpostal-http". Found these instead:
	db-dev-service; muskie-http; temporal-postgresql; temporal; temporal-ui
```

I'd guess this is related to the upgrade of the compose-go library: https://github.com/tilt-dev/tilt/pull/6225

### Steps to Reproduce
1. Have a docker compose stack with one service using a profile to disable starting up by default
2. Reference the docker compose service in the Tiltfile

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.33.6, built 2023-09-29
System: darwin-arm64
---
Docker
- Host: unix:///Users/jonno/.docker/run/docker.sock
- Server Version: 24.0.6
- API Version: 1.43
- Builder: 2
- Compose Version: v2.22.0-desktop.2
---
Kubernetes
- Env: eks
- Context: arn:aws:eks:us-west-2:535092081012:cluster/temporal
- Cluster Name: arn:aws:eks:us-west-2:535092081012:cluster/temporal
- Namespace: default
- Container Runtime: read-failure
- Version: Error: Get "https://B36932AA0B6F7BDA656BE82B6B587448.yl4.us-west-2.eks.amazonaws.com/version": dial tcp: lookup B36932AA0B6F7BDA656BE82B6B587448.yl4.us-west-2.eks.amazonaws.com: no such host
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: cdf40d782d075d23bf94926753d363e2
- Repo: iD/YjYrm1RtgMGRkMQyhpg==
```

**Comment by nicks** [comment]
thanks for the report!

hmmm...i'm not sure if we ever put much thought into how tilt interacts with docker compose profiles, so i'm actually not sure which behavior is right. @milas @nicksieger do either of you remember?

**Comment by prat1kbhujbal** [comment]
I am facing the same issue can anyone help with this?

**Comment by nicksieger** [comment]
Can you try setting `COMPOSE_PROFILES` inside the Tiltfile?

```tiltfile
os.putenv('COMPOSE_PROFILES', 'include_libpostal')

docker_compose(...)
dc_resource(...)
```

**Comment by prat1kbhujbal** [comment]
> Can you try setting `COMPOSE_PROFILES` inside the Tiltfile?
> 
> ```
> os.putenv('COMPOSE_PROFILES', 'include_libpostal')
> 
> docker_compose(...)
> dc_resource(...)
> ```

Thank you for getting back to me but this doesn't work.

**Comment by prat1kbhujbal** [comment]
> Can you try setting `COMPOSE_PROFILES` inside the Tiltfile?
> 
> ```
> os.putenv('COMPOSE_PROFILES', 'include_libpostal')
> 
> docker_compose(...)
> dc_resource(...)
> ```

It didnt work for me but what I observed whereever I used profiles, for that services it gave me no Docker Compose service found with name "wms_interface_worker"
Eg:  For "wms_interface_worker"
```
 wms_interface_web:
    profiles:
    - wms_interface
    - integration_tests
    - ui_tests
```
