### ISSUE TITLE
Can't run `tilt up` in prod mode

### ISSUE THREAD

**Issue by vindard** [tilt-dev/tilt#6253]
### Expected Behavior
Running `tilt up` should work

### Current Behavior
I get the error message:
```
Tilt started on http://localhost:10350/
v0.33.6, built 
Error: running in prod mode, but JS/CSS files are not available.
Please report this: https://github.com/tilt-dev/tilt/issues
```

### Context
This works in `v0.32.3` but breaks in `v0.33.6` with the same tilt configs

**Comment by nicks** [comment]
Thanks for the report! Where did you get your tilt binary from? This error means it was compiled with the wrong flags.

**Comment by vindard** [comment]
Ah it's from nix and it seems like it's a known issue across there
https://github.com/NixOS/nixpkgs/pull/260712

Closing here for now, will follow across there
