### ISSUE TITLE
Be able to declare a folder structure to ignore rebuilding a full image even if they are not part of a live update sync.

### ISSUE THREAD

**Issue by Corey-J** [tilt-dev/tilt#6257]
## Describe the Feature You Want
Be able to declare a folder structure to ignore rebuilding a full image even if they are not part of a live update 'sync'.

### Current Behavior
Currently when a live update sync path is declared, if a file changes outside of the sync path the full image will rebuild.

### Why Do You Want This?
Currently we run a ASP.NET MVC website that uses a typescript Vue3 'SPA' that renders with each razor page. This is all compiled by webpack.
When making changes to the vue application, to get a 'hot reload' without having to wait for the full container to come alive we add a sync from the external webpack output into the internal webpack output of the pod. We then run a webpack --watch to build as we make html/scss/typescript changes. This lets our dev team have <200ms turn around time for changes rather than ~2-3 minutes for the full container to build.

Unfortunately to achieve this we have also have to add a sync to a web assets folder (html/css/typescript) to prevent the new changes rebuilding the image - this copies alot of unnecessary and unused files into the container.

**Additional context**

**Comment by nicks** [comment]
have you seen this doc? https://docs.tilt.dev/file_changes

usually people use `.tiltignore` or `watch_settings` for this

**Comment by nicks** [comment]
closing this as already implemented
