### ISSUE TITLE
Support `--namespace` flag for `tilt ci`

### ISSUE THREAD

**Issue by greenlynx** [tilt-dev/tilt#6258]
## Describe the Feature You Want
I am using the `--namespace` flag with `tilt up` and I would also like to use it with `tilt ci`

### Current Behavior
The `--namespace` flag is not supported for `tilt ci`

### Why Do You Want This?
I'm using Tilt to spin up an ephemeral environment in Azure DevOps pipelines, and run tests against it before merging PRs. I would like multiple pipelines to be able to run tests at the same time, and am using namespaces to help with segregating the environments.

**Additional context**
N/A

**Comment by nicks** [comment]
this is probably just an oversight; i believe the `--namespace` flag already exists for `tilt up`
