### ISSUE TITLE
Help using Tilt up command

### ISSUE THREAD

**Issue by Orokusaki90** [tilt-dev/tilt#6284]
Hi all,

I need a little help using tilt. We have resources defined in tiltfile on remote machine. When we start tilt, after some time or when machine restarts we need to run tilt up again to use tilt gui.
Is there a way that when we run Tilt up it wont start rebuild all resources again(All containers are all ready running, services are working). We need tilt gui for devs to restart the build  for specific resource when they have a new code they are developing locally.
Thanks so much for you help.

**Comment by nicks** [comment]
i'm not totally sure what's being asked here, but basically:
- when tilt starts, it builds all images. it needs to build all images to know if any of the inputs have changed.
- if the inputs haven't changed, the image builds should all be cached.
- if the images builds are cached, the image tags will be the same.
- if the image tags are the same, `kubectl apply` will not make any changes to the deployments
- if the deployments haven't changed, then tilt will attach to the existing deployments
