### ISSUE TITLE
Tilt thinks 0.33.9 is greater than 0.33.10

### ISSUE THREAD

**Issue by amanibhavam** [tilt-dev/tilt#6289]
### Expected Behavior

Tilt v0.33.10 should not suggest an upgrade to v0.33.9

### Current Behavior

Tilt v0.33.10 says there's an upgrade, which tuns out to be v0.33.9

<img width="535" alt="image" src="https://github.com/tilt-dev/tilt/assets/62630472/40e36914-2a3b-41f1-97fc-aff214e01345">

### Steps to Reproduce

1. Use tilt v0.33.10
2. Run tilt up
3. Open the web UI
4. See upgrade indicator in upper right corner next to v0.33.10 text

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.33.10, built 2023-12-15
System: linux-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 24.0.5
- API Version: 1.43
- Builder: 2
- Compose Version: v2.18.1
---
Kubernetes
- Env: unknown
- Context: coder-amanibhavam-district0-cluster
- Cluster Name: coder-amanibhavam-district0-cluster
- Namespace: coder-amanibhavam-district0
- Container Runtime: containerd
- Version: v1.28.2+k3s1
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: d41d8cd98f00b204e9800998ecf8427e
- Repo: VooP3ze4nbj24sGO34QruQ==
...
```

**Comment by nicks** [comment]
Hmm do you still see this? I think we just had the cache ttl on the update server set too high, but should be good now

**Comment by amanibhavam** [comment]
I don't see the notification anymore.  Thanks for the explanation.  Tilt is one of my favorite software to get updates for, I have something that auto upgrades my dev env :)
