### ISSUE TITLE
sync step of live update never completes

### ISSUE THREAD

**Issue by VictorW96** [tilt-dev/tilt#6296]
### Expected Behavior
The main.py file should be synced 

### Current Behavior
When I do a `tilt up` on this repository https://github.com/VictorW96/tilt-demo/tree/main and change the https://github.com/VictorW96/tilt-demo/blob/main/python-service/main.py I would expect it to live reload inside the container. But this doesn't happen on my machine. It is stuck on the command `tar -C / -x -f -`. 

![never_ending_sync](https://github.com/tilt-dev/tilt/assets/40980071/ddf23a0e-49ba-49f0-90d8-f0876b0bc768)

I am on Windows 10 with Rancher Desktop and Kubernetes 1.25.11

### Steps to Reproduce
1. Clone https://github.com/VictorW96/tilt-demo/tree/main
2. `tilt up`
3. After everything is green change `./python-service/main.py`

**Comment by nicks** [comment]
thanks for the report! ya, this is a known bug in Rancher Desktop:
https://github.com/rancher-sandbox/rancher-desktop/issues/2094

There are workarounds described here:
https://github.com/tilt-dev/tilt/issues/5730
