### ISSUE TITLE
Accelerating Tilt's Build Time

### ISSUE THREAD

**Issue by kahirokunn** [tilt-dev/tilt#6299]
## Describe the Feature You Want
I would like to increase the speed of Tilt's building process. Ideally, I would like the build and push to take place within a pod in the k8s cluster, similar to how the buildx's Kubernetes driver does.

### Current Behavior
Currently, the build process takes longer than desired.

### Why Do You Want This?
By conducting the build and push process in a pod within the k8s cluster, we can make use of a pod that's prepared with a plethora of CPU and memory resources, as well as a container registry that has a fast connection and is network-nearby. This would significantly speed up the process. Ultimately, improving the speed of the build process would enhance the overall efficiency and user experience.

**Additional context**
Not applicable at this moment.

**Comment by nicks** [comment]
this exists! it's a tilt extension
https://github.com/tilt-dev/tilt-extensions/tree/master/kubectl_build

i believe the downstream tool it depends on (`kubectl build`) is currently archived due to lack of interest, but it will still work AFAIK

**Comment by kahirokunn** [comment]
Okay. Thanks!

**Comment by kahirokunn** [comment]
@nicks Unfortunately, kubectl build does not seem to work with the k8s 1.29. 😢 
Therefore, please re-open this issue.

```
kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

```
error: unknown command "build" for "kubectl"

Build Failed: Custom build "kubectl build --context xxxxxx -f ./Dockerfile.tilt --registry-secret docker-registry --platform linux/amd64 -t $EXPECTED_REF ." failed: exit status 1
```

**Comment by nicks** [comment]
you have to install the command plugin, it doesn't ship with stock kubectl - https://github.com/vmware-archive/buildkit-cli-for-kubectl?tab=readme-ov-file#getting-started

**Comment by kahirokunn** [comment]
Okay, Thanks!

**Comment by kahirokunn** [comment]
@nicks I am looking to expand the kubectl_build readme.
But I read the code and I could not decipher it well. 😢 

1. I have confirmed that the buildkit pod is up and build is done in the buildkit, but do you know how to pass cpu memory? 2.
2. do you know how to specify the ServiceAccount?

Thank you. 🙏
