### ISSUE TITLE
k8s_resource Function Unable to Recognize All Objects from YAML

### ISSUE THREAD

**Issue by Andrey1337** [tilt-dev/tilt#6300]
### Expected Behavior
The k8s_resource function should correctly identify and process all specified Kubernetes resources, including Service and Deployment, and any other objects provided in the YAML file during upload.

### Current Behavior
It only identifies the "kafka-update-script:ConfigMap:default" object and don't recognize the Service and Deployment objects.

### Steps to Reproduce
just run `tilt up` and it will crush cuz it recognize only one resource.

I attached 2 files:
* `kafka.yaml` which has 3 kubernetes resources.
* `Tilftile` which use `k8s_yaml` and `k8s_resource` functions.

[tilt-bug.zip](https://github.com/tilt-dev/tilt/files/14115534/tilt-bug.zip)

#### `tilt doctor` Output
```
$ tilt doctor
Tilt: v0.33.10, built 2023-12-15
System: darwin-arm64
---
Docker
- Host: unix:///Users/andrewzolotaryov/.rd/docker.sock
- Server Version: 23.0.6
- API Version: 1.42
- Builder: 2
- Compose Version: v2.23.3
---
Kubernetes
- Env: rancher-desktop
- Context: rancher-desktop
- Cluster Name: rancher-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.28.4+k3s2
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: a8b91ab1d520604d01ec28185bc83bdb
- Repo: lw3FfPFiSwf3VZG70T36RA==
```

#### About Your Use Case
Trying to deploy kafka (confluent) with 3 kubernetes resources, deployment, configmap, service

**Comment by nicks** [comment]
this is working as designed.

by default, Tilt puts the Deployment and Service in a resource. The `objects=` parameter can only select objects in uncategorized.

The snippet you want is something like:

```
# rename the default resource
k8s_resource('kafka-broker', new_name='kafka', labels=['Infra'],  pod_readiness='wait')
# Add the configmap to the resource
k8s_resource('kafka', objects=['kafka-update-script:ConfigMap:default'])
```

https://docs.tilt.dev/tiltfile_concepts#configuring-kubernetes-resources

**Comment by Andrey1337** [comment]
Thank you! Sorry for my misunderstanding @nicks
