### ISSUE TITLE
Tilt tries to push to docker registry when used with rootless docker + minikube

### ISSUE THREAD

**Issue by faergeek** [tilt-dev/tilt#6346]
### Expected Behavior

`tilt up` shouldn't try to push to docker.io. Avoiding pushes at all would be perfect. Or having a way to tell it to use a custom local registry instead.

### Current Behavior

Cloning `tilt-example-html` locally and running `tilt up` from `0-base` directory results in the following error:

```
Build Failed: docker push: pushing image "docker.io/library/example-html-image": denied: requested access to the resource is denied
```

### Steps to Reproduce

1. Set up rootless docker as described in [Docker Docs](https://docs.docker.com/engine/security/rootless/)
2. `minikube start --driver=docker --container-runtime=containerd`
3. `git clone git@github.com:tilt-dev/tilt-example-html.git`
4. `cd tilt-example-html/0-base`
5. `tilt up`
6. Hit `<Space>` to see tilt dashboard in a browser, click "example-html" and observe the error. 

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.33.11, built 2024-02-15
System: linux-amd64
---
Docker
- Host: unix:///run/user/1000/docker.sock
- Server Version: 25.0.4
- API Version: 1.44
- Builder: 2
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: containerd
- Version: v1.28.3
- Cluster Local Registry: none
```

#### About Your Use Case

I'm trying to use tilt on a rootless docker with minikube on Arch Linux.

**Comment by nicks** [comment]
Hmmm...Tilt is trying to tell you that you haven't set up any way to get images into the Minikube cluster. So pushing to a remote registry is the only way to do get an image into the cluster. Here are some guides on this:

https://docs.tilt.dev/choosing_clusters

Honestly, I would be supportive of just making tilt stop with an error when it's in this case.

**Comment by faergeek** [comment]
>Hmmm...Tilt is trying to tell you that you haven't set up any way to get images into the Minikube cluster. So pushing to a remote registry is the only way to do get an image into the cluster. Here are some guides on this:
>
>https://docs.tilt.dev/choosing_clusters

I did try using `ctlptl` before and it fails for me, can't quite remember why exactly. I did set up a registry at `localhost:5000` though, which is accessible by both minikube and docker, so I can push `localhost:5000/image` from docker and create a deployment with image set as `localhost:5000/image`. Is there any way to tell tilt to just use that?

**Comment by nicks** [comment]
Yes, read the section in
https://docs.tilt.dev/choosing_clusters#discovering-the-registry under
"Kubernetes Standard Registry Discovery"

**Comment by faergeek** [comment]
That's exactly what I was looking for and somehow I missed that section. It works great. Thank you very much! :+1:
