### ISSUE TITLE
Override auto_init for `tilt ci`

### ISSUE THREAD

**Issue by c-harding** [tilt-dev/tilt#6350]
## Describe the Feature You Want
I have some Playwright tests that I have set up with auto_init=False, TRIGGER_MODE_MANUAL. I would like to execute them when executing `tilt ci`, although they should not be run automatically on `tilt up`.

### Current Behavior
If the resource does not run on startup, it will not run on `tilt ci`.

### Why Do You Want This?
I want to run the tests with the cluster in my CI pipeline.

**Additional context**
```python
    local_resource(service_label+'-e2e',
        cmd='pnpm exec playwright test',
        dir='src/main/web',
        labels=[service_label],
        auto_init=auto_init,
        trigger_mode=TRIGGER_MODE_MANUAL,
        resource_deps=[service_label, service_label+'-frontend', 'hoverfly'],
    )
```

**Comment by nicks** [comment]
have you considered using:

```
if config.tilt_subcommand == 'ci':
  ...
```

?

https://docs.tilt.dev/api#api.config.tilt_subcommand

**Comment by c-harding** [comment]
@nicks perfect, thank you! I couldn’t spot that in the docs
