### ISSUE TITLE
Make it Scoopable

### ISSUE THREAD

**Issue by zachbugay** [tilt-dev/tilt#6361]
## Describe the Feature You Want

I would love to be able to install this via scoop. `scoop install tilt`
https://scoop.sh/#/

### Current Behavior

I have to manually download it.

### Why Do You Want This?

I want this because it would make life so much better installing software. 

**Additional context**

Scoop is a command line tool for Windows, similar to Homebrew for OSX that allows you to install software via a command line interface.

**Comment by nicks** [comment]
😁

https://docs.tilt.dev/install.html#scoop-windows

```
scoop bucket add tilt-dev https://github.com/tilt-dev/scoop-bucket
scoop install tilt
```
