### ISSUE TITLE
Graceful shutdown is ignored by Tilt

### ISSUE THREAD

**Issue by o-shevchenko** [tilt-dev/tilt#6377]
### Expected Behavior

Our service should support graceful shutdown. We configured service itself to handle SIGNTERM and configured `terminationGracePeriodSeconds` to wait for terminating and it works fine on K8s clusters.

We expect the same behavior from Tilt.

### Current Behavior

Tilt sends SIGNKILL and doesn't waite for termination. I don't see configurations to change that behavior.

### Steps to Reproduce
```
1. We have simple deployment

k8s_yaml(helm(
'bin/k8s/helm/charts',
name='service',
namespace='namespace',
values=['bin/k8s/helm/charts/values.yaml', 'bin/k8s/helm/environment/values-local.yaml'])
)
2. We use Tilt UI to `Trigger update`

3. Pod is killed even if it configured for graceful shutdown 

```

#### `tilt doctor` Output

```
tilt doctor
Tilt: v0.33.5, built 2023-08-30
System: darwin-arm64
---
Docker
- Host: unix:///Users/oleksandr.shevchenko/.docker/run/docker.sock
- Server Version: 24.0.6
- API Version: 1.43
- Builder: 2
- Compose Version: v2.23.0-desktop.1
---
Kubernetes
- Env: k3d
- Context: k3d-devinfra
- Cluster Name: k3d-devinfra
- Namespace: default
- Container Runtime: containerd
- Version: v1.26.14+k3s1
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: edad00184951d8c35aafe1abab31cbdb
- Repo: uzuunRN/159ZTPW03JRFdQ==
...
```

**Comment by nicks** [comment]
thanks for the report! But i was unable to reproduce this problem, given the steps provided.

Here's what I tried:
- i modified the example project to use graceful termination - https://github.com/tilt-dev/tilt-example-html/commit/1bf5c3b4b3a53aaec97cb1b647be7e14583cd257
- ran `tilt up`
- triggered a reload of the resource
- used `stern example-html` to confirm that the old pod received a TERM signal, then stayed up for a while until kubernetes killed it.

what makes you think it's not respecting graceful termination?

**Comment by nicks** [comment]
side note -- under the hood, tilt just calls `kubectl delete`, and lets kubernetes handle shutdown, tilt doesn't send signals to the process directly -- so i'm not sure even how this bug _could_ happen

**Comment by o-shevchenko** [comment]
Thanks for the answer and details @nicks !
What I see is that pod is killed right after trigger upgrade. Let me dig dipper and check if I see the same behavior for  `kubectl delete` for pods created by Tilt. However, `helm upgrade` for the same Helm charts works fine, and pods are waiting for graceful termination.
