### ISSUE TITLE
Docker host as registry

### ISSUE THREAD

**Issue by PumpkinSeed** [tilt-dev/tilt#6396]
## Describe the Feature You Want

I'm currently using k3d as Tilt's backend and it would be nice to somehow the k3d will be able to reuse the images what the docker_build creates and saves into the local docker host.

### Current Behavior

The docker_build creates the image and uploads it into the k3d's local registry. At this point we have the image stored locally and also in the k3d's local registry. After that the k3d pulls the image to start it. 

### Why Do You Want This?

Saving space and time, because some of the NodeJS images are +2GB in size.

**Additional context**

I have read a lot about this topic. Tried with Kind as well, but I did not succeed. I also read through [this issue](https://github.com/k3d-io/k3d/issues/19), but I didn't find what I have looked for.

I know that's a hard task to address, but if that would work it would be outstanding.

**Comment by nicks** [comment]
k3d and your local docker host have separate image stores, stored in different formats, with different ways of managing those images (think: garbage collection). This would require fundamental changes to how OCI container runtimes / image stores work, which is not really in scope for the Tilt project.
