### ISSUE TITLE
issue with ENV build command in 0.33.18

### ISSUE THREAD

**Issue by olivierchatry** [tilt-dev/tilt#6421]
### Expected Behavior
ENV build command should set the environment variable.

### Current Behavior

using `ENV key=value` end up with wrong value set. so if you use `ENV key=`  for example, value become ` =` for some reason. Reverted to 0.33.17 and everything work fine, or  if a value is set `ENV key=value` then, value become `value =`

### Steps to Reproduce
```
ARG APP_NAME=TheAppName

ENV APP_NAME=$APP_NAME
```

APP_NAME is now `TheAppName =`

**Comment by olivierchatry** [comment]
It's probably a WSL / windows only issues

**Comment by rafaelavd** [comment]
Defining the ENV variables in the old way still works:

`ENV APP_NAME TheAppName`

APP_NAME is `TheAppName`

But this syntax is deprecated by Docker.

**Comment by rafaelavd** [comment]
Its likely to be because of the upgrade of `moby/buildkit v0.11.6` => `v0.14.1`
I confirmed this is happening in both WSL and MacOS.

**Comment by nicks** [comment]
thanks for the report! :thinking:
