### ISSUE TITLE
context deadline exceeded: rpc error

### ISSUE THREAD

**Issue by patelronakp** [tilt-dev/tilt#6432]
### Expected Behavior
Im try to simulate fastapi project with minikube + tilt. 
Here is the my TiltFIle.

docker_build("product-service", "./product-service")
docker_build("payment-service", "./payment-service")
docker_build("api-gateway", "./api-gateway")

k8s_yaml("k8s.yaml")

I execute below cmds
- minikube start
- tilt up

### Current Behavior
minikube start successfully and even I can access the minikube dashboard then I run the 2nd cmd which tilt up.  and get below result.

Tilt started on http://localhost:10350/
v0.33.19, built 2024-08-05

(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
**2024/09/03 17:32:14 traces export: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /Users/<username>/AppData/Local/Docker/run/userAnalyticsOtlpHttp.sock: connect: A socket operation encountered a dead network."**

but when I open the http://localhost:10350/ it open the tilt dashboard where I can see all the servicies and also display the endpoints as http://192.168.49.2:31886/ but when i open it nothing happened. 

then I do check minikube service --all and my services are running fine and able to access it. but it won't work with the tilt ip.

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.33.19, built 2024-08-05
System: windows-amd64
---
Docker (cluster)
- Host: tcp://127.0.0.1:53887
- Server Version: 26.1.1
- API Version: 1.45
- Builder: 2
---
Docker (local)
- Host: npipe:////./pipe/dockerDesktopLinuxEngine
- Server Version: 27.2.0
- Version: 1.47
- Builder: 2
- Compose Version: v2.29.2-desktop.2
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.30.0
- Cluster Local Registry: none

**Comment by nicks** [comment]
it's nothing to be too concerned about -- there was a regression in docker/cli where it's trying to send analytics to docker desktop - https://github.com/docker/cli/pull/5188

it's already fixed at tilt HEAD

**Comment by nicks** [comment]
should be fixed in the tilt release we just cut
