### ISSUE TITLE
Documentation has a dead link to oficial node.js website

### ISSUE THREAD

**Issue by gggfox** [tilt-dev/tilt#6436]
### Steps to Reproduce

1. GOTO [https://docs.tilt.dev/example_nodejs](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/#creating-a-dockerfile)
2. CLICK [check out this guide](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/#creating-a-dockerfile)

https://github.com/user-attachments/assets/76d171d2-1a57-4324-b52d-f67115c775fe

**Comment by nicks** [comment]
thanks for the report! (and video!)
