### ISSUE TITLE
Add support/documentation  for k0s?

### ISSUE THREAD

**Issue by plandem** [tilt-dev/tilt#6437]
## Describe the Feature You Want
[k0s](https://k0sproject.io/) is production ready and probably lightest kubernates, production ready as well

### Current Behavior
no info how to run with tilt at all

### Why Do You Want This?
official docs are always better

**Comment by nicks** [comment]
sure, we can add a note about in the docs. it's basically going to fall into the same category as GKE / EKS / AKS

K0s is a kubernetes distro that's designed for edge/IoT use-cases. By design, it doesn't have any tooling for creating local dev envs.

**Comment by plandem** [comment]
@nicks yeah, I know...tbh I'm not looking for kubernates at all, need something that would could replace docker-compose for development and at the same time minimal changes for production. With all these hypes, small-mid size companies are kinda out of the scope these days - kubrnates this, kubernates that, while for small-mid size companies what you need - containerasation with minimal management via something like `systemd` that would work on win, mac, unix dev machines.

And while these shrinked kubernates let devs to work locally, but its still kubernates with all that complexity that comes together.
