### ISSUE TITLE
Add Option to Configure kubectl Timeout Length

### ISSUE THREAD

**Issue by jlehman9** [tilt-dev/tilt#6442]
## Describe the Feature You Want
The ability to modify the timeout length for `kubectl` commands before Tilt thinks something is wrong and reports an error, such as `kubectl get services -n <NAMESPACE>`.

### Current Behavior
There is currently no configuration option for this, so the only behavior is whatever default timeout Tilt is configured for internally. 

### Why Do You Want This?
The default timeout settings are not a problem for the majority of popular use cases, but some clusters users may want to connect to may be behind a lot of different "layers".

For example, I was trying to test Tilt connected to a [vCluster](https://www.vcluster.com/) (which for the intents of this issue shouldn't matter as it's essentially just K3S) hosted inside of a host cluster, which is hosted in AWS behind a VPN. This means that `kubectl` commands often take a bit longer to complete compared to running the same commands against a local cluster. Tilt is able to connect to the vCluster fine and deploy my image, but when running idle (not sure what the proper Tilt term for this is) and Tilt runs what I assume are health checks etc. the commands can take longer than Tilt expects and returns an error:
```
`Try running \`kubectl get services -n "test"\`: WatchServices: makeInformer: the server was unable to return a response in the time allotted, but may still be processing the request, Reason: Timeout, Code: 504`
``` 

If streaming logs in the terminal after running `tilt up` and one of these checks fails, the Tilt terminal app exits which causes the Web server to exit as well. If you only run `tilt up` and only view the error logs from within the web monitor then the Tilt terminal app stays up.

**Comment by nicks** [comment]
ahhh...i think you're misunderstanding the error -- 504 doesn't mean that `tilt` or `kubectl` is timing out. 

504 means that the server itself timed out. i.e., that the server timed out talking to vcluster.

Increasing the timeout on the tilt / kubectl side won't fix this problem; you'll need to fix this on the server side.

Also, for the record -- `tilt` doesn't invoke `kubectl` on the command-line, it uses the Kubernetes APIs directly. In this case, the API that's failing is that it's trying to start a long-lived watch against the cluster so it can stream changes as pods deploy. (this _roughly_ corresponds to what `kubectl get services -n test --watch` does under the hood)
