### ISSUE TITLE
`k8s_custom_deploy` can sometimes be executed without a pinned `KUBECONFIG`

### ISSUE THREAD

**Issue by dougbarth** [tilt-dev/tilt#6453]
### Expected Behavior

Tilt should not run any `k8s_custom_deploy` resources without a working cluster connection, and all executions should have a pinned `KUBECONFIG`.

### Current Behavior

If Tilt executes a `k8s_custom_deploy` step without a pinned `KUBECONFIG`, the custom deploy may execute against the current context. This unpinned execution can result in Tilt deploying resources to the wrong cluster.

### Steps to Reproduce

1. Create two kind clusters: `kind create cluster --name "wrong"` and `kind create cluster --name "expected"`
2. Stop the `expected` cluster (simulating it being unavailable): `docker stop expected-control-plane`
3. Set the current context to `kind-wrong`
4. Create a `Tiltfile` with the following contents:

```
load('ext://helm_resource', 'helm_resource', 'helm_repo')

num_helm_resources = 5
num_docker_services = 5

# This function is like allow_k8s_context but only the listed supplied contexts
# are allowed (allow_k8s_context adds to a default allow list)
def expect_k8s_contexts(contexts):
  if k8s_context() not in contexts:
    fail_msg = "Unexpected k8s context: {} Expected contexts: {}".format(k8s_context(), contexts)
    fail(fail_msg)
  allow_k8s_contexts(k8s_context())

expect_k8s_contexts([
    'kind-expected',
])

services = {}
for i in range(0, num_docker_services):
    services['dynamodb-admin{}'.format(i)] = {
        'image': 'aaronshaf/dynamodb-admin:4.5.1',
    }

docker_compose([encode_yaml({
    'services': services,
})])

helm_repo('examples-repo', 'https://helm.github.io/examples')

for i in range(0, num_helm_resources):
    helm_resource('ahoy{}'.format(i), 'examples-repo/hello-world')
    local('sleep 0.1')
```

5. Repeatedly attempt to recreate the issue by running `tilt up --context kind-expected` until one or more of the `ahoy*` helm installs runs against the wrong cluster

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/61ac55bf-b3c4-467b-8422-fbfb269df3d1">

<img width="1203" alt="image" src="https://github.com/user-attachments/assets/b12d4408-f40c-4a67-bf56-54a35935bab0">

6. Confirm that the Helm install was issued against the current context, not the specified context provided to Tilt.

```
➜  tilt-wrong-cluster helm list --kube-context kind-wrong
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ahoy0   default         1               2024-10-29 16:51:29.547009 -0400 EDT    deployed        hello-world-0.1.0       1.16.0     
➜  tilt-wrong-cluster helm list --kube-context kind-wrong
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ahoy0   default         2               2024-10-29 16:52:12.275137 -0400 EDT    deployed        hello-world-0.1.0       1.16.0     
```

#### `tilt doctor` Output

```
➜  tilt-wrong-cluster tilt doctor                    
Tilt: v0.33.20, built 2024-09-03
System: darwin-arm64
---
Docker
- Host: unix:///Users/dougbarth/.orbstack/run/docker.sock
- Server Version: 27.3.1
- API Version: 1.47
- Builder: 2
- Compose Version: v2.29.7
---
Kubernetes
- Env: kind
- Context: kind-wrong
- Cluster Name: kind-wrong
- Namespace: default
- Container Runtime: containerd
- Version: v1.27.3
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 23edfae12d8628956ea28e9135e28748
- Repo: 
➜  tilt-wrong-cluster tilt doctor --context kind-expected
Tilt: v0.33.20, built 2024-09-03
System: darwin-arm64
---
Docker
- Host: unix:///Users/dougbarth/.orbstack/run/docker.sock
- Server Version: 27.3.1
- API Version: 1.47
- Builder: 2
- Compose Version: v2.29.7
---
Kubernetes
- Env: kind
- Context: kind-expected
- Cluster Name: kind-expected
- Namespace: default
- Container Runtime: read-failure
- Version: Error: Get "https://127.0.0.1:51009/version": dial tcp 127.0.0.1:51009: connect: connection refused
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 23edfae12d8628956ea28e9135e28748
- Repo: 
```

#### About Your Use Case

We discovered that some Helm releases that are only used in our local Tilt environment were installed on remote clusters. We tracked the issue back to Tilt using the current context instead of the pinned `KUBECONFIG`.

For completeness, when we first reproduced this issue using `v0.33.10, built`, we found we could trigger a reload of the failed resource after changing the current context. When attempting to reproduce that behavior with this simplified reproducer, I was unable to get the exact same behavior. It's unclear to me what the difference is, but our usual Tiltfile is significantly more complex.

**Comment by nicks** [comment]
thanks for the report! i can repro

**Comment by dougbarth** [comment]
Thanks @nicks.

Is it an invariant that `k8s_custom_deploy` should always have a pinned `KUBECONFIG`? If yes, would it make sense to teach [`(r *Reconciler) maybeInjectKubeconfig`](https://github.com/tilt-dev/tilt/blob/6278d2cc18a48b70ec46892d73b2dafaacf7bc25/internal/controllers/core/kubernetesapply/reconciler.go#L364-L375) to return an error if a pinned `KUBECONFIG` cannot be created?

**Comment by nicks** [comment]
ya, added an error in https://github.com/tilt-dev/tilt/pull/6458, there were just some other things we had to fix up first
