### ISSUE TITLE
`v1alpha1.extension_repo` should pull latest from specific git references

### ISSUE THREAD

**Issue by brunoluiz** [tilt-dev/tilt#6468]
## Describe the Feature You Want

If a team wants to pin it the `v1alpha1.extension_repo` reference to a rolling tag (eg: `v1` or `main`), it would be interesting if Tilt could pull latest changes on `tilt up` or similar.

### Current Behavior

In a few cases, teams might want to pin the `v1alpha1.extension_repo` to a specific version and this can already be done through a specific tag or commit sha. But we observed that many want to set it to a rolling release, which currently is not possible: if set to a reference, it will pull it once and never refresh it, til a manual `git pull` is done.

This `git pull` is not documented and requires the user to navigate to the XDG folder and do pull:

```shell
cd '/Users/brunoluiz/Library/Application Support/tilt-dev/tilt_modules/github.com/brunoluiz/tilt-extensions'
git pull
```

### Why Do You Want This?

- It would give teams choice to use rolling releases and/or tagged releases
- Less friction or debugging due to "pull once" behaviour (is not documented)

### Alternatives

If nothing can be done, probably might be worth to document it and give a run-book to users on how to update references rolling references.

**Comment by nicks** [comment]
ya, i think the way we originally designed this was -
- if no tag is given, it should pull the latest branch
- if a tag is given, we assume the tag is immutable and only pull once

https://github.com/tilt-dev/tilt/blob/ea06944f7d8296dc3a74fb1992d474d037be2a4c/internal/controllers/core/extensionrepo/reconciler.go#L233

i guess the right way to do it is to make it more like `pull = 'auto' | 'always' | 'never'` sort of like how kubernetes works

**Comment by brunoluiz** [comment]
Makes sense! We decided to pin to a `ref` at the end to not cause any breaking changes when making changes in the company's extensions repository.
